### ISSUE TITLE
Error downloading subs from urskola.se

### ISSUE THREAD

**Issue by wirretheman** [spaam/svtplay-dl#1000]
This one: https://urskola.se/Produkter/158020-Hej-litteraturen-Medeltiden
gives me errors when I try to download it WITH subs (works without subs):

INFO: Outfile: hej.litteraturen.medeltiden-ur.skola-urplay.srt
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 58, in get_media
    get_one_media(stream)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 176, in get_one_media
    options_subs_dl(subfixes)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 171, in options_subs_dl
    subs[0].download()
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/subtitle/__init__.py", line 73, in download
    self.save_file(data, "srt")
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/subtitle/__init__.py", line 79, in save_file
    file_d = output(self.output, self.config, subtype, mode="wt")
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/output.py", line 199, in output
    if findexpisode(output, os.path.dirname(os.path.realpath(name)), os.path.basename(name)):
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/output.py", line 225, in findexpisode
    name.find(output["id"]) > 0 and lsname.find(output["id"]) > 0 and \
TypeError: must be str, not NoneType

This is strange because the first show of the series:
https://urskola.se/Produkter/158019-Hej-litteraturen-Antiken
works just fine.

I use v2.1 on OS X.

**Comment by spaam** [comment]
thanks for the bugreport. this will be fixed in 2.2 and it will be released tomorrow monday.
