### ISSUE TITLE
Viafree.se - OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1004]
I got this error when trying to download latest Efterlyst:
$ svtplay-dl https://www.viafree.se/program/samhalle/efterlyst/sasong-52/985132

```
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==2.1+11.g1c302d4', 'svtplay-dl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+11.g1c302d4-py3.5.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+11.g1c302d4-py3.5.egg/svtplay_dl/__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+11.g1c302d4-py3.5.egg/svtplay_dl/utils/getmedia.py", line 56, in get_media
    get_all_episodes(stream, url)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+11.g1c302d4-py3.5.egg/svtplay_dl/utils/getmedia.py", line 87, in get_all_episodes
    get_one_media(substream)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+11.g1c302d4-py3.5.egg/svtplay_dl/utils/getmedia.py", line 201, in get_one_media
    fstream.download()
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+11.g1c302d4-py3.5.egg/svtplay_dl/fetcher/hls.py", line 121, in download
    self._download(self.url, file_name=(self.output, "ts"))
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+11.g1c302d4-py3.5.egg/svtplay_dl/fetcher/hls.py", line 138, in _download
    file_d = output(file_name[0], self.config, file_name[1])
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+11.g1c302d4-py3.5.egg/svtplay_dl/utils/output.py", line 210, in output
    file_d = open(name, mode, **kwargs)
OSError: [Errno 36] File name too long: 'efterlyst.s52.efterlyst.special.ar.en.fordjupning.av.efterlyst.dar.den.erfarna.och.kunniga.redaktionen.bakom.efterlyst.tar.upp.bekanta.och.sarskilt.intressanta.fall.i.reportageform..fallen.analyseras.och.gas.igenom.pa.satt.som.visar.att.sanningen.kanske.inte.ar.sa.enkel.som.den.forst.tycktes.vara-985135-viaplay.ts'
```
svtplay-dl 2.1+11.g1c302d4

**Comment by spaam** [comment]
wow. impressive :D

**Comment by Sopor-** [comment]
I get the same error message on Efterlyst Special, 317 chars and ext4 can only handle 255.
```
efterlyst.s52.efterlyst.special.ar.en.fordjupning.av.efterlyst.dar.den.erfarna.och.kunniga.redaktionen.bakom.efterlyst.tar.upp.bekanta.och.sarskilt.intressanta.fall.i.reportageform..fallen.analyseras.och.gas.igenom.pa.satt.som.visar.att.sanningen.kanske.inte.ar.sa.enkel.som.den.forst.tycktes.vara-985135-viaplay.ts'

```

**Comment by Sopor-** [comment]
Same error again :(
```
OSError: [Errno 36] File name too long: 'efterlyst.s53.en.stoldliga.specialiserad.pa.aldre.harjar.i.hela.sodra.sverige..efterlyst.har.tydliga.bilder.pa.de.misstankta.garningsmannen..efterlyst.tar.ocksa.upp.det.misstankta.mordet.pa.velmira.i.avesta.med.fler.fall..nu.behover.polisen.allmanhetens.hjalp.i.veckans.efterlyst-990585-viaplay.ts'
```

**Comment by Sopor** [comment]
I don't know if this is the same issue but it is the same TV series
```
svtplay-dl.exe -S -P hls https://www.viafree.se/program/samhalle/efterlyst/sasong-54/1005339 --verbose
DEBUG [1569528627.9064014] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.4-20-g0826b8f
DEBUG [1569528627.9064014] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: viaplay
DEBUG [1569528627.9064014] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.viafree.se/program/samhalle/efterlyst/sasong-54/1005339'
DEBUG [1569528627.9064014] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.viafree.se:443
DEBUG [1569528628.1225843] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.viafree.se:443 "GET /program/samhalle/efterlyst/sasong-54/1005339 HTTP/1.1" 200 None
DEBUG [1569528628.1382008] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://playapi.mtgx.tv/v3/videos/1005339'
DEBUG [1569528628.1382008] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): playapi.mtgx.tv:80
DEBUG [1569528628.9089427] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://playapi.mtgx.tv:80 "GET /v3/videos/1005339 HTTP/1.1" 200 2517
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
    except (yaml.YAMLError, yaml.MarkedYAMLError) as e:
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media

  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
    if stream.config.get("preferred").lower() == i.name:
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\viaplay.py", line 161, in get
    else:
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\viaplay.py", line 288, in _autoname
    parent_id = dataj["derived_from_id"]
IndexError: string index out of range
```

svtplay-dl 2.4-20-g0826b8f
