### ISSUE TITLE
Trouble downloading subtitles from SVT Play

### ISSUE THREAD

**Issue by PastorZ** [spaam/svtplay-dl#1026]
### svtplay-dl versions:

**2.1**

### Operating system and Python version:

**Windows 10 Home
Python-version, whatever comes with Svtplay-dl version 2.1**

### What is the issue:

When I try to download the latest World Cup chronicle (vm-krönika) from SVT Play I get an error message when I try to download the subtitle that comes with it (downloading without subtitle works fine).

The error message is the following:
```
> C:\temp\rip>svtplay-dl -S --verbose https://www.svt.se/sport/fotboll/vm-kronika-2018-aterupplev-sveriges-fantastiska-sommar
> DEBUG [1546172953.6636188] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.1
> DEBUG [1546172953.6701233] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svt
> DEBUG [1546172953.6701233] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svt.se/sport/fotboll/vm-kronika-2018-aterupplev-sveriges-fantastiska-sommar'
> DEBUG [1546172953.6701233] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svt.se:443
> DEBUG [1546172955.172653] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svt.se:443 "GET /sport/fotboll/vm-kronika-2018-aterupplev-sveriges-fantastiska-sommar HTTP/1.1" 200 27279
> DEBUG [1546172955.2417836] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1391602-001A'
> DEBUG [1546172955.2573576] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
> DEBUG [1546172955.4424806] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1391602-001A HTTP/1.1" 200 938
> DEBUG [1546172955.4424806] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/1391602-001A_6a7a6b4e.mpd'
> DEBUG [1546172955.4581034] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
> DEBUG [1546172955.52711] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /1391602-001A_6a7a6b4e.mpd HTTP/1.1" 302 0
> DEBUG [1546172955.52711] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): balancer.cdn.svt.se:80
> DEBUG [1546172955.5583744] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /vod/_definst_/amlst:20181224/1391602-001A/d2cbe3ac-d7c5-4455-bfdc-3ff3b6752e83/PG-1391602-001A-FOTBOLLVMKRON-02/manifest.mpd HTTP/1.1" 302 0
> DEBUG [1546172955.5583744] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): ed5.cdn.svt.se:80
> DEBUG [1546172955.7054741] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed5.cdn.svt.se:80 "GET /vod/_definst_/amlst:20181224/1391602-001A/d2cbe3ac-d7c5-4455-bfdc-3ff3b6752e83/PG-1391602-001A-FOTBOLLVMKRON-02/manifest.mpd HTTP/1.1" 200 2824
> DEBUG [1546172955.7054741] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://svtplay12d-f.akamaihd.net/d/se/open/delivery/20181224/1391602-001A/dash-live/PG-1391602-001A-FOTBOLLVMKRON-02-b0d0864d-1f63-43a8-9584-4f35b32f8119-6f0049ca-a0cf-336d-d7b5-83794cbc6f53-live.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1391602-001A_6a7a6b4e.mpd'
> DEBUG [1546172955.7210915] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): svtplay12d-f.akamaihd.net:80
> DEBUG [1546172955.8749201] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svtplay12d-f.akamaihd.net:80 "GET /d/se/open/delivery/20181224/1391602-001A/dash-live/PG-1391602-001A-FOTBOLLVMKRON-02-b0d0864d-1f63-43a8-9584-4f35b32f8119-6f0049ca-a0cf-336d-d7b5-83794cbc6f53-live.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1391602-001A_6a7a6b4e.mpd HTTP/1.1" 200 924
> DEBUG [1546172956.0754254] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://ed5.cdn.svt.se/vod/_definst_/amlst:20181224/1391602-001A/d2cbe3ac-d7c5-4455-bfdc-3ff3b6752e83/PG-1391602-001A-FOTBOLLVMKRON-02/manifest.mpd'
> DEBUG [1546172956.196016] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed5.cdn.svt.se:80 "GET /vod/_definst_/amlst:20181224/1391602-001A/d2cbe3ac-d7c5-4455-bfdc-3ff3b6752e83/PG-1391602-001A-FOTBOLLVMKRON-02/manifest.mpd HTTP/1.1" 200 2824
> DEBUG [1546172956.3073888] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/1391602-001A_6a7a6b4e.m3u8'
> DEBUG [1546172956.345234] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /1391602-001A_6a7a6b4e.m3u8 HTTP/1.1" 302 0
> DEBUG [1546172956.345234] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /vod/_definst_/amlst:20181224/1391602-001A/d2cbe3ac-d7c5-4455-bfdc-3ff3b6752e83/PG-1391602-001A-FOTBOLLVMKRON-02/playlist.m3u8 HTTP/1.1" 302 0
> DEBUG [1546172956.7621148] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed5.cdn.svt.se:80 "GET /vod/_definst_/amlst:20181224/1391602-001A/d2cbe3ac-d7c5-4455-bfdc-3ff3b6752e83/PG-1391602-001A-FOTBOLLVMKRON-02/playlist.m3u8 HTTP/1.1" 200 1887
> DEBUG [1546172956.7621148] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://svtplay12h-f.akamaihd.net/i/se/open/20181224/1391602-001A/PG-1391602-001A-FOTBOLLVMKRON-02_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1391602-001A_6a7a6b4e.m3u8&defaultSubLang=sv'
> DEBUG [1546172956.7621148] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): svtplay12h-f.akamaihd.net:80
> DEBUG [1546172956.94715] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svtplay12h-f.akamaihd.net:80 "GET /i/se/open/20181224/1391602-001A/PG-1391602-001A-FOTBOLLVMKRON-02_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1391602-001A_6a7a6b4e.m3u8&defaultSubLang=sv HTTP/1.1" 200 1840
> DEBUG [1546172956.94715] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://ed5.cdn.svt.se/vod/_definst_/amlst:20181224/1391602-001A/d2cbe3ac-d7c5-4455-bfdc-3ff3b6752e83/PG-1391602-001A-FOTBOLLVMKRON-02/playlist.m3u8'
> DEBUG [1546172957.226019] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed5.cdn.svt.se:80 "GET /vod/_definst_/amlst:20181224/1391602-001A/d2cbe3ac-d7c5-4455-bfdc-3ff3b6752e83/PG-1391602-001A-FOTBOLLVMKRON-02/playlist.m3u8 HTTP/1.1" 200 1887
> DEBUG [1546172957.23253] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/1391602-001A_6a7a6b4e.m3u8'
> DEBUG [1546172957.2794714] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /1391602-001A_6a7a6b4e.m3u8 HTTP/1.1" 302 0
> DEBUG [1546172957.3106673] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /vod/_definst_/amlst:20181224/1391602-001A/d2cbe3ac-d7c5-4455-bfdc-3ff3b6752e83/PG-1391602-001A-FOTBOLLVMKRON-02/playlist.m3u8 HTTP/1.1" 302 0
> DEBUG [1546172957.5649533] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed5.cdn.svt.se:80 "GET /vod/_definst_/amlst:20181224/1391602-001A/d2cbe3ac-d7c5-4455-bfdc-3ff3b6752e83/PG-1391602-001A-FOTBOLLVMKRON-02/playlist.m3u8 HTTP/1.1" 200 1887
> DEBUG [1546172957.5649533] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://subtitles.static.svt.se/sub-1391602-001a-vmkronikaryssland/SUB-1391602-001A-VMKRONIKARYSSLAND.wsrt'
> DEBUG [1546172957.5805278] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): subtitles.static.svt.se:443
> DEBUG [1546172957.6495411] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://subtitles.static.svt.se:443 "GET /sub-1391602-001a-vmkronikaryssland/SUB-1391602-001A-VMKRONIKARYSSLAND.wsrt HTTP/1.1" 200 58310
> DEBUG [1546172958.012892] C:\Python35\lib\site-packages\chardet\sbcharsetprober.py/feed: windows-1255 confidence = 0.0, below negative shortcut threshhold 0.05
> DEBUG [1546172958.012892] C:\Python35\lib\site-packages\chardet\sbcharsetprober.py/feed: windows-1255 confidence = 0.0, below negative shortcut threshhold 0.05
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: utf-8  confidence = 0.99
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: SHIFT_JIS Japanese confidence = 0.01
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: EUC-JP Japanese confidence = 0.01
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: GB2312 Chinese confidence = 0.01
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: EUC-KR Korean confidence = 0.01
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: CP949 Korean confidence = 0.01
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: Big5 Chinese confidence = 0.01
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: EUC-TW Taiwan confidence = 0.01
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: windows-1251 Russian confidence = 0.01
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: KOI8-R Russian confidence = 0.01
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: ISO-8859-5 Russian confidence = 0.0
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: MacCyrillic Russian confidence = 0.0
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: IBM866 Russian confidence = 0.0
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: IBM855 Russian confidence = 0.01
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: ISO-8859-7 Greek confidence = 0.0
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: windows-1253 Greek confidence = 0.0
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: ISO-8859-5 Bulgairan confidence = 0.0
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: windows-1251 Bulgarian confidence = 0.0
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: TIS-620 Thai confidence = 0.0994343502222403
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: ISO-8859-9 Turkish confidence = 0.5994857973830701
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: windows-1255 Hebrew confidence = 0.0
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: windows-1255 not active
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: windows-1255 not active
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: utf-8  confidence = 0.99
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: SHIFT_JIS Japanese confidence = 0.01
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: EUC-JP Japanese confidence = 0.01
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: GB2312 Chinese confidence = 0.01
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: EUC-KR Korean confidence = 0.01
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: CP949 Korean confidence = 0.01
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: Big5 Chinese confidence = 0.01
> DEBUG [1546172958.0975606] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: EUC-TW Taiwan confidence = 0.01
> INFO [1546172958.135296] c:\projects\svtplay-dl\lib\svtplay_dl\utils\output.py/output: Outfile: vm-kronika.2018.aterupplev.sveriges.fantastiska.sommar.svt.sport-svt.srt
> Traceback (most recent call last):
>   File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
>   File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
>   File "bin/svtplay-dl", line 7, in <module>
>   File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 64, in main
>   File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 58, in get_media
>   File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 176, in get_one_media
>   File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 171, in options_subs_dl
>   File "c:\projects\svtplay-dl\lib\svtplay_dl\subtitle\__init__.py", line 73, in download
>   File "c:\projects\svtplay-dl\lib\svtplay_dl\subtitle\__init__.py", line 77, in save_file
>   File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\output.py", line 199, in output
>   File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\output.py", line 225, in findexpisode
> TypeError: Can't convert 'NoneType' object to str implicitly
```

URL: **svtplay-dl -S --verbose https://www.svt.se/sport/fotboll/vm-kronika-2018-aterupplev-sveriges-fantastiska-sommar**

**Comment by granbom** [comment]
Try to download from this URL instead:
https://www.svtplay.se/video/20463032/vm-kronika-ryssland-2018

**Comment by PastorZ** [comment]
> 
> 
> Try to download from this URL instead:
> https://www.svtplay.se/video/20463032/vm-kronika-ryssland-2018

Seems to work :) thanks!
