### ISSUE TITLE
urplay support doesn't work without TLS1.0 support

### ISSUE THREAD

**Issue by olof** [spaam/svtplay-dl#1034]
### svtplay-dl versions

*any* (but seen on 2.1 and 1.9.11 and current master, dcbf6a)

### Operating system and Python version:

*any that disables support for tlsv1.0* (but seen on Debian Buster (soon to be stable))

### What is the issue:

URPlay uses some load balancer (`streaming-loadbalancer.ur.se`) that doesn't have modern ssl support (only tlsv1.0). In Buster, support for TLSv1.0 is disabled for security reasons, and this leads to errors with the requests library throws an SSLError exception because of unsupported protocol.

This was reported to Debian in https://bugs.debian.org/914126, by Cristian Ionescu-Idbohrn who did the analysis. He also concluded that if you somehow bypass the loadbalancer (or workaround the tls support issue), the assigned server (e.g `streaming4.ur.se`) does support tls1.2.

```
$ ./svtplay-dl --verbose https://urplay.se/program/208359-min-rosa-mamma
DEBUG [1547171405.420088] ./svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 2.1-41-gdcbf6a8
DEBUG [1547171405.422329] ./svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: urplay
DEBUG [1547171405.422428] ./svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://urplay.se/program/208359-min-rosa-mamma'
DEBUG [1547171405.5003562] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): urplay.se
DEBUG [1547171405.6258826] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://urplay.se:443 "GET /program/208359-min-rosa-mamma HTTP/1.1" 200 16138
DEBUG [1547171405.631184] ./svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming-loadbalancer.ur.se/loadbalancer.json'
DEBUG [1547171405.6339307] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): streaming-loadbalancer.ur.se
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 837, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 323, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:841)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 624, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:841)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./svtplay-dl/__main__.py", line 13, in <module>
  File "./svtplay-dl/svtplay_dl/__init__.py", line 64, in main
  File "./svtplay-dl/svtplay_dl/utils/getmedia.py", line 56, in get_media
  File "./svtplay-dl/svtplay_dl/utils/getmedia.py", line 105, in get_one_media
  File "./svtplay-dl/svtplay_dl/service/urplay.py", line 48, in get
  File "./svtplay-dl/svtplay_dl/utils/http.py", line 45, in request
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:841)
```

**Comment by qnorsten** [comment]
The question is if svtplay-dl should bother trying to bypass the load-balancer,or if someone should try contacting ur and see if they can update the load balancer?

**Comment by granbom** [comment]
@qnorsten exactly my thought.

**Comment by Jacalz** [comment]
Seems like the best idea due to TLS1.0 could be considered a security issue...

**Comment by granbom** [comment]
Wrote an example email on IRC #svtplay-dl

**Comment by NoNameForMee** [comment]
Their server appears to run with only SSLv3.0 and TLSv1.0 enabled (or supported). As such the issue is primarily with UR and their outdated servers. I do not think it is worth spending too much time here to write a workaround. It is better to contact UR directly and let them know/fix the root cause. Particularly since TLS v1.0 (as well as TLS v1.1) is soon (March 2020) to be deprecated by all the major browsers (Firefox, Chrome, Edge, Safari).

Src:
https://datatracker.ietf.org/doc/draft-ietf-tls-oldversions-deprecate/
https://blog.mozilla.org/security/2018/10/15/removing-old-versions-of-tls/
https://www.ssllabs.com/ssltest/analyze.html?d=streaming-loadbalancer.ur.se

**Comment by olof** [comment]
Fyi: The Debian bug reporter has contacted UR about the issue, but has not yet received anything substantial in response.

**Comment by olof** [comment]
Seems to be working now, without any changes. I guess they upgraded their loadbalancers. I verified with ssllabs.com's analyzer as linked above. I've asked the original reporter of the Debian bug to confirm before closing just to be sure I'm not missing anything. Anybody else seeing any issues?

**Comment by olof** [comment]
Confirmed solved. The reporter was affected by another issue in 1.9.1, but works in 2.1.
