### ISSUE TITLE
svtplay-dl crashes

### ISSUE THREAD

**Issue by matstnilsson** [spaam/svtplay-dl#1036]
### svtplay-dl versions:

Run `svtplay-dl --version`
0.30.2016.02.08-debian1

### Operating system and Python version:

Name and version of the operating system and python version (run `python --version`)

Linux nusseture 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Python 2.7.12

### What is the issue:

$ svtplay-dl --verbose 'https://www.svtplay.se/video/9887998/det-svenska-dataundret'
DEBUG [1547378391.75] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/video/9887998/det-svenska-dataundret'
DEBUG [1547378391.77] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.svt.se/videoplayer-api/video/1370855-001A'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 352, in main
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 177, in get_media
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 190, in get_one_media
  File "/usr/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 56, in get
  File "/usr/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 152, in outputfilename
KeyError: 'episodeTitle'

**Comment by granbom** [comment]
@matstnilsson if you follow the instuctions here https://svtplay-dl.se/install/linux/ you should have a working svtplay-dl again. Python3 is also needed.

**Comment by matstnilsson** [comment]
Great! Thx very much

Best regards/Hälsningar,
/Mats Nilsson
+46 70 4330801
Sent from my iPhone.


13 jan. 2019 kl. 12:52 skrev granbom <notifications@github.com>:

@matstnilsson if you follow the instuctions here https://svtplay-dl.se/install/linux/ you should have a working svtplay-dl again. Python3 is also needed.
