### ISSUE TITLE
TV4Play - IndexError: list index out of range

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1038]
### svtplay-dl versions:

svtplay-dl 2.1+41.gdcbf6a8

### Operating system and Python version:

Python 3.5.3

### What is the issue:
It seems to crash when trying to download subtitle. I have it in my `.svtplay-dl.yaml` so i was forced to edit that first to not download subtitles. Not a very user-friendly way to exclude options.

```
$ svtplay-dl -S https://www.tv4play.se/program/vem-d%C3%B6dade-birgitte/11957570
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==2.1+41.gdcbf6a8', 'svtplay-dl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+41.gdcbf6a8-py3.5.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+41.gdcbf6a8-py3.5.egg/svtplay_dl/__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+41.gdcbf6a8-py3.5.egg/svtplay_dl/utils/getmedia.py", line 56, in get_media
    get_one_media(stream)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+41.gdcbf6a8-py3.5.egg/svtplay_dl/utils/getmedia.py", line 174, in get_one_media
    options_subs_dl(subfixes)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+41.gdcbf6a8-py3.5.egg/svtplay_dl/utils/getmedia.py", line 169, in options_subs_dl
    subs[0].download()
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+41.gdcbf6a8-py3.5.egg/svtplay_dl/subtitle/__init__.py", line 58, in download
    data = self.wrstsegment(subdata)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+41.gdcbf6a8-py3.5.egg/svtplay_dl/subtitle/__init__.py", line 301, in wrstsegment
    if len(subs) > 0 and itmes[1] == subs[-1][1]:
IndexError: list index out of range
````

**Comment by spaam** [comment]
hmm interesting

**Comment by OldSchool297** [comment]
I have the same problem with tv4.

**Comment by OldSchool297** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. All rights reserved.

C:\Users>cd..

C:\Users>cd..

C:>C:\svtplay-dl\svtplay-dl.exe -o C:\svtplay-dl -S -M --remux -f https://www.t
v4play.se/program/hem-till-g%C3%A5rden/11832356
Traceback (most recent call last):
File "C:\Python35\lib\site-packages\cx_Freeze\initscripts_startup_.py", lin
e 14, in run
File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26
, in run
File "bin/svtplay-dl", line 7, in
File "c:\projects\svtplay-dl\lib\svtplay_dl_init_.py", line 63, in main
File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 56, in ge
t_media
File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 157, in g
et_one_media
File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 152, in o
ptions_subs_dl
File "c:\projects\svtplay-dl\lib\svtplay_dl\subtitle_init_.py", line 58, in
download
File "c:\projects\svtplay-dl\lib\svtplay_dl\subtitle_init_.py", line 291, i
n wrstsegment
IndexError: list index out of range

C:>

**Comment by OldSchool297** [comment]
Tv4 had webvtt subtitles before and now they are streaming, maybe that's the problem?

**Comment by hpsu** [comment]
@spaam  
Using the source file https://www.tv4play.se/program/hem-till-g%C3%A5rden?video_id=11832461
The very first wrtsegment looks like this:
`['00:00:01.600 --> 00:00:04.000', '', 'HEM TILL GÅRDEN']`

Note the empty string before the first text entry.

Removing the `len(subs) > 1` part of the following row:
```python
if len(subs) > 1 and len(itmes) < 2:  # Ignore empty lines in unexpected places
```
in subtitle/__init__.py seems to fix the problem for me although I don't know if it causes problems on other subs.

**Comment by Sopor** [comment]
Yes, i have tested it on a few subtitles and it seems to work, but as you are saying. Will it causes problems on other subs?

**Comment by spaam** [comment]
this is fixed in master. will releasing 2.2 tomorrow or the day after.
