### ISSUE TITLE
svtplay-dl crashed

### ISSUE THREAD

**Issue by bitbytare** [spaam/svtplay-dl#1040]
### svtplay-dl versions:

$ svtplay-dl --version
1.9.11

### Operating system and Python version:
$ python --version
Python 2.7.12

### What is the issue:

Can't download from tv4:

johnny@johnny-pc ~ $ svtplay-dl -S -A -o /media/dreampi/temp/https://www.tv4play.se/program/dirigenten/11792107
INFO: Episode 1 of 4
INFO: Url: http://www.tv4play.se/program/dirigenten?video_id=11792107
ERROR: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues
ERROR: Include the URL used, the stack trace and the output of svtplay-dl --version in the issue
johnny@johnny-pc ~ $  svtplay-dl -S -A -o --verbose /media/dreampi/temp/https://www.tv4play.se/program/dirigenten/11792107
DEBUG [1547850967.49] /usr/bin/svtplay-dl/svtplay_dl/__init__.py/get_media: version: 1.9.11
DEBUG [1547850967.49] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://webapi.tv4play.se/play/video_assets?type=episode&is_live=false&platform=web&node_nids=dirigenten&per_page=99999'
INFO [1547850967.69] /usr/bin/svtplay-dl/svtplay_dl/__init__.py/get_all_episodes: Episode 1 of 4
INFO [1547850967.69] /usr/bin/svtplay-dl/svtplay_dl/__init__.py/get_all_episodes: Url: http://www.tv4play.se/program/dirigenten?video_id=11792107
DEBUG [1547850967.69] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.tv4play.se/program/dirigenten?video_id=11792107'
DEBUG [1547850968.03] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://prima.tv4play.se/api/web/asset/11792107/play'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 511, in main
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 215, in get_media
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 244, in get_all_episodes
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 265, in get_one_media
  File "/usr/bin/svtplay-dl/svtplay_dl/service/tv4play.py", line 52, in get
  File "/usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py", line 68, in request
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 480, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 588, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='prima.tv4play.se', port=80): Max retries exceeded with url: /api/web/asset/11792107/play (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f7532f76050>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))

**Comment by Sopor-** [comment]
You need to update. 1.9.11 is very old.

**Comment by spaam** [comment]
please try a newer version ( https://svtplay-dl.se/install/ ) and see if you still have the issue
