### ISSUE TITLE
dr.dk not working

### ISSUE THREAD

**Issue by tivolimeister** [spaam/svtplay-dl#1047]
### svtplay-dl versions:

**2.1** (homebrew)

### Operating system and Python version:

macOS **10.13.6**
python **3.7**

### What is the issue:

All requests to dr.dk seems to generate the same error. Site probably changed?! Other sites are working which would suggest that my installation is otherwise working.

`requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?`

#### Example of URL not working

`svtplay-dl https://www.dr.dk/tv/se/bedrag/bedrag-i/bedrag-1-10 -v`

#### Output

```
DEBUG [1548699931.2400908] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1548699931.240572] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/__init__.py/__init__: service: dr
DEBUG [1548699931.240651] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.dr.dk/tv/se/bedrag/bedrag-i/bedrag-1-10'
DEBUG [1548699931.301365] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.dr.dk:443
DEBUG [1548699931.556802] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.dr.dk:443 "GET /tv/se/bedrag/bedrag-i/bedrag-1-10 HTTP/1.1" 200 16957
DEBUG [1548699931.559422] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.dr.dk/mu-online/api/1.4/bar/5bfa3ed8a11fa00c28699322'
DEBUG [1548699931.653445] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.dr.dk:443 "GET /mu-online/api/1.4/bar/5bfa3ed8a11fa00c28699322 HTTP/1.1" 302 0
DEBUG [1548699931.945855] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.dr.dk:443 "GET /mu-online/api/1.4/manifest/urn:dr:mu:manifest:5bfa0525a11fa00c28699125 HTTP/1.1" 200 1252
DEBUG [1548699931.9473011] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting None
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 58, in get_media
    get_one_media(stream)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 107, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/dr.py", line 58, in get
    self.http.request("get", stream["Uri"], params={"hdcore": "3.7.0"}),
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py", line 45, in request
    res = Session.request(self, method, url, verify=self.verify, proxies=self.proxy, *args, **kwargs)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/requests/sessions.py", line 510, in request
    prep = self.prepare_request(req)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/requests/sessions.py", line 453, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
```

**Comment by nem0rder** [comment]
The problem i due to dr now only using encrypted uri: this work: 

https://github.com/rg3/youtube-dl/blob/a2d821d7112fb1423f99ddf309a843c80cc3be2d/youtube_dl/extractor/drtv.py
