### ISSUE TITLE
Can't download from dplay

### ISSUE THREAD

**Issue by yabbah** [spaam/svtplay-dl#1052]
When I try downloading the latest episode of 'Sommaren med släkten' from dplay.se (not premium content) I get the following errors:

`svtplay-dl -o Sommaren.Med.Slakten.S03E05 https://www.dplay.se/videos/sommaren-med-slakten/sommaren-med-slakten-25

INFO: Selected to download hls, bitrate: 6549
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 64, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 58, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 201, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/hls.py", line 117, in download
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/hls.py", line 130, in _download
ModuleNotFoundError: No module named 'Crypto'
`

Any ideas?

**Comment by Sopor-** [comment]
Follow the issue template and provide the requested information and it will be much easier to help. It seems that you are missing `Crypto`. You seems to have already got the answer in another issue `pip3 install pycryptodome`

**Comment by yabbah** [comment]
Sorry, here is the template:



### svtplay-dl versions:
svtplay-dl 2.1

### Operating system and Python version:
Ubuntu 18.04.1 LTS
Python 2.7.15rc1
Also have Python 3.6.5, but just `puthon` gives 2.7.15rc1

### What is the issue:

I try download using this command:
`svtplay-dl -o Sommaren.Med.Slakten.S03E05 https://www.dplay.se/videos/sommaren-med-slakten/sommaren-med-slakten-25`

Get this error: 
`INFO: Selected to download hls, bitrate: 6549
Traceback (most recent call last):
File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"**main**", mod_spec)
File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/usr/local/bin/svtplay-dl/**main**.py", line 13, in 
File "/usr/local/bin/svtplay-dl/svtplay_dl/**init**.py", line 64, in main
File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 58, in get_media
File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 201, in get_one_media
File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/hls.py", line 117, in download
File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/hls.py", line 130, in _download
ModuleNotFoundError: No module named 'Crypto'`

I dont have any command like pip3 so I cant install pycryptodome using that. And apt dont find it.

**Comment by yabbah** [comment]
Tried 'alias python=python3' but it give the same error message.

**Comment by yabbah** [comment]
`sudo apt-get install python3-crypto` solved it.

**Comment by Sopor-** [comment]
Yeah, it can sometimes be hard to find the right packages for Linux. Nice that you found the solution :+1:
