### ISSUE TITLE
svtplay error

### ISSUE THREAD

**Issue by JoelHallklint** [spaam/svtplay-dl#1053]
### svtplay-dl versions:

Run `svtplay-dl --version`
0.30.2016.01.10-debian1

### Operating system and Python version:
Linux mint 17

Name and version of the operating system and python version (run `python --version`)

### What is the issue:

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

    svtplay-dl --verbose https://www.example.com

svtplay-dl --verbose https://www.svtplay.se/video/18883422/spion-i-extremhogern
DEBUG [1551792791.69] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/video/18883422/spion-i-extremhogern'
DEBUG [1551792791.74] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.svt.se/videoplayer-api/video/1386081-001A'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 352, in main
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 177, in get_media
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 203, in get_one_media
KeyError: 'episodeTitle'

**Comment by Sopor** [comment]
That is a very old version. Latest version is 2.1 so you need to update.

**Comment by pamm01** [comment]
The program isnt available. https://www.svtplay.se/video/18883422/spion-i-extremhogern

**Comment by Sopor** [comment]
@pamm01 that is because it isn't there

![image](https://user-images.githubusercontent.com/5789283/53987723-1a73c900-4122-11e9-931e-109d126207d6.png)

**Comment by pamm01** [comment]
Thats what i tried to tell.

**Comment by Sopor** [comment]
But in his case it has to be with the old version he is using. Version 0.30 is 3 years old.
