### ISSUE TITLE
Dplay.se - No module named '_cffi_backend'

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1057]
### svtplay-dl versions:

svtplay-dl 2.1-46-g05c322a

### Operating system and Python version:

Windows 10

### What is the issue:

```
svtplay-dl.exe -S -P hls https://www.dplay.se/videos/sofias-anglar/sofias-anglar-1210
INFO: Outfile: sofias-anglar.s12e10.klassen.stottade.cancersjuka.ida-nu.tackar.hon.vannerna-72495-dplay.srt
INFO: Selected to download hls, bitrate: 6499
INFO: Outfile: sofias-anglar.s12e10.klassen.stottade.cancersjuka.ida-nu.tackar.hon.vannerna-72495-dplay.audio.ts
[001/253][................................................................................] ETA: 0:00:00Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 64, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 56, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 207, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 117, in download
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 180, in _download
  File "C:\Python35\lib\site-packages\cryptography\hazmat\backends\__init__.py", line 15, in default_backend
  File "C:\Python35\lib\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 7, in <module>
  File "C:\Python35\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 18, in <module>
  File "C:\Python35\lib\site-packages\cryptography\x509\__init__.py", line 8, in <module>
  File "C:\Python35\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
  File "C:\Python35\lib\site-packages\cryptography\x509\extensions.py", line 18, in <module>
  File "C:\Python35\lib\site-packages\cryptography\hazmat\primitives\constant_time.py", line 11, in <module>
ImportError: No module named '_cffi_backend'
```

It seems that if i'm running an older version it works svtplay-dl 2.1-41-gdcbf6a8

**Comment by spaam** [comment]
i changed the crypto dependency from pycryptodome to cryptography. just because cryptography is available in ubuntu 16.04 and debian stable. 

i hate this kind of errors.. :(

**Comment by spaam** [comment]
can you test this https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23351039/artifacts and see if it works?

**Comment by Sopor** [comment]
```
svtplay-dl.exe -S -P hls https://www.dplay.se/videos/sofias-anglar/sofias-anglar-1210
INFO: Outfile: sofias-anglar.s12e10.klassen.stottade.cancersjuka.ida-nu.tackar.hon.vannerna-72495-dplay.srt
INFO: Selected to download hls, bitrate: 6499
INFO: Outfile: sofias-anglar.s12e10.klassen.stottade.cancersjuka.ida-nu.tackar.hon.vannerna-72495-dplay.audio.ts
[253/253][================================================================================] ETA: 0:00:00
INFO: Outfile: sofias-anglar.s12e10.klassen.stottade.cancersjuka.ida-nu.tackar.hon.vannerna-72495-dplay.ts
[253/253][================================================================================] ETA: 0:00:00
INFO: Merge audio and video into sofias-anglar.s12e10.klassen.stottade.cancersjuka.ida-nu.tackar.hon.vannerna-72495-dplay.ts
INFO: Merging done, removing old files.
INFO: Muxing sofias-anglar.s12e10.klassen.stottade.cancersjuka.ida-nu.tackar.hon.vannerna-72495-dplay.ts into sofias-anglar.s12e10.klassen.stottade.cancersjuka.ida-nu.tackar.hon.vannerna-72495-dplay.mp4
INFO: Muxing done, removing the old file.

svtplay-dl 2.1-49-ga63d33c
```

**Comment by Sopor** [comment]
And now i can't run svtplay-dl any more :(
`ImportError: No module named 'cryptography'`

**Comment by Sopor** [comment]
There was a few dependencies missing, so now i'm back :)
