### ISSUE TITLE
Twitch: add support for /<user>/b/<id> videos

### ISSUE THREAD

**Issue by Rovanion** [spaam/svtplay-dl#106]
I've built svtplay-dl from git master on Ubuntu 14.04. Trying to download a previous broadcast from twitch:

```
svtplay-dl http://www.twitch.tv/dreamleague/b/538832276
```

The following stacktrace is the result: 

``` python
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 5, in <module>
    pkg_resources.run_script('svtplay-dl==0.9.2014.04.27', 'svtplay-dl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.9.2014.04.27-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.9.2014.04.27-py2.7.egg/svtplay_dl/__init__.py", line 218, in main
    get_media(url, options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.9.2014.04.27-py2.7.egg/svtplay_dl/__init__.py", line 88, in get_media
    get_one_media(stream, options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.9.2014.04.27-py2.7.egg/svtplay_dl/__init__.py", line 110, in get_one_media
    for i in streams:
TypeError: 'NoneType' object is not iterable
```

**Comment by olof** [comment]
This has been "fixed" for some time, in that it doesn't crash, but reports the url as unsupported. I'll rephrase the issue as a feature request for extended twitch support.

    $ ./svtplay-dl http://www.twitch.tv/dreamleague/b/538832276
    ERROR: This twitch video type is unsupported
