### ISSUE TITLE
svtplay-dl crashed

### ISSUE THREAD

**Issue by farna1** [spaam/svtplay-dl#1061]
### svtplay-dl versions:
svtplay-dl 2.1
### Operating system and Python version:
Windows 10 Pro 1809 17763.379
### What is the issue:
svtplay-dl crashed 
same on all url in svtplay.se
cant find video on viafree.se, tv4play.se
Error occurred since yesterday at none

C:\svtplay-dl>svtplay-dl.exe --verbose https://www.svtplay.se/video/21162059/the-tunnel/the-tunnel-sabotage-sasong-2-avsnitt-1?start=auto
DEBUG [1554440441.1733682] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.1
DEBUG [1554440441.1733682] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1554440441.1733682] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/21162059/the-tunnel/the-tunnel-sabotage-sasong-2-avsnitt-1?start=auto'
DEBUG [1554440441.1733682] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1554440446.5635614] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/21162059/the-tunnel/the-tunnel-sabotage-sasong-2-avsnitt-1?start=auto HTTP/1.1" 200 38784
DEBUG [1554440446.6135924] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1373274-001A'
DEBUG [1554440446.6135924] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
DEBUG [1554440446.7136476] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1373274-001A HTTP/1.1" 200 785
DEBUG [1554440446.7231545] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/1373274-001A_ab2473e0.m3u8'
DEBUG [1554440446.7336056] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
DEBUG [1554440446.9042463] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /1373274-001A_ab2473e0.m3u8 HTTP/1.1" 302 0
DEBUG [1554440446.9134989] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): svtplay5n-f.akamaihd.net:80
DEBUG [1554440447.2133622] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svtplay5n-f.akamaihd.net:80 "GET /i/se/open/20190221/1373274-001A/PG-1373274-001A-TUNNELTHE2S-01_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8 HTTP/1.1" 200 0
DEBUG [1554440447.2183828] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/1373274-001A_ab2473e0.m3u8'
DEBUG [1554440447.2735014] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /1373274-001A_ab2473e0.m3u8 HTTP/1.1" 302 0
DEBUG [1554440447.4134293] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svtplay5n-f.akamaihd.net:80 "GET /i/se/open/20190221/1373274-001A/PG-1373274-001A-TUNNELTHE2S-01_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8 HTTP/1.1" 200 0
DEBUG [1554440447.4184394] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://svtplay5n-f.akamaihd.net/i/se/open/20190221/1373274-001A/PG-1373274-001A-TUNNELTHE2S-01_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1373274-001A_ab2473e0.m3u8'
DEBUG [1554440447.5834055] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svtplay5n-f.akamaihd.net:80 "GET /i/se/open/20190221/1373274-001A/PG-1373274-001A-TUNNELTHE2S-01_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1373274-001A_ab2473e0.m3u8 HTTP/1.1" 200 0
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 64, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 58, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 107, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 86, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 109, in _get_video
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 41, in hlsparse
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 253, in __init__
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 261, in parse_m3u
ValueError: Does not appear to be an 'EXTM3U' file.

**Comment by Sopor** [comment]
I have no issues when i download from SVTPlay with `svtplay-dl 2.1-49-ga63d33c`
```
svtplay-dl.exe https://www.svtplay.se/video/21162059/the-tunnel/the-tunnel-sabotage-sasong-2-avsnitt-1
INFO: Selected to download dash, bitrate: 3223
INFO: Outfile: the.tunnel.s02e01.avsnitt.1-306a914-svtplay.m4a
[492/492][================================================================================] ETA: 0:00:00
INFO: Outfile: the.tunnel.s02e01.avsnitt.1-306a914-svtplay.mp4
[020/493][===.............................................................................] ETA: 0:00:52
``` 

Viafree.se is also working but TV4Play.se is not working but reported here #1058 

Have you tried latest master? You can download it [here](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23351676/artifacts).
