### ISSUE TITLE
dr.dk crashes trying to dl bonderoeven

### ISSUE THREAD

**Issue by jjabba** [spaam/svtplay-dl#1064]
### Operating system and Python version: OS X 10.13.6, Python 2.7.10 (most likely the python version used is 3 by judging from the error message)

Name and version of the operating system and python version (run `python --version`)

### What is the issue:

     svtplay-dl https://www.dr.dk/tv/se/bonderoeven-tv/bonderoeven-tv-bonderoeven-2008/ --verbose

results in
```
DEBUG [1554957321.57212] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1554957321.573066] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/__init__.py/__init__: service: dr
DEBUG [1554957321.57321] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.dr.dk/tv/se/bonderoeven-tv/bonderoeven-tv-bonderoeven-2008/bonderoeven-1-8-2'
DEBUG [1554957321.63826] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.dr.dk:443
DEBUG [1554957321.904044] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.dr.dk:443 "GET /tv/se/bonderoeven-tv/bonderoeven-tv-bonderoeven-2008/bonderoeven-1-8-2 HTTP/1.1" 200 15003
DEBUG [1554957321.9113522] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.dr.dk/mu-online/api/1.4/bar/5a8a1bd6a11f9f1a7c6c9825'
DEBUG [1554957321.924479] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.dr.dk:443 "GET /mu-online/api/1.4/bar/5a8a1bd6a11f9f1a7c6c9825 HTTP/1.1" 302 0
DEBUG [1554957322.4316502] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.dr.dk:443 "GET /mu-online/api/1.4/manifest/urn:dr:mu:manifest:5a8a173b6187a415a0de2219 HTTP/1.1" 200 1772
DEBUG [1554957322.434288] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting None
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 58, in get_media
    get_one_media(stream)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 107, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/dr.py", line 58, in get
    self.http.request("get", stream["Uri"], params={"hdcore": "3.7.0"}),
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py", line 45, in request
    res = Session.request(self, method, url, verify=self.verify, proxies=self.proxy, *args, **kwargs)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/requests/sessions.py", line 510, in request
    prep = self.prepare_request(req)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/requests/sessions.py", line 453, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
```

**Comment by Sopor** [comment]
Working in latest master `svtplay-dl 2.1-52-gbe21f7d`
```
svtplay-dl https://www.dr.dk/tv/se/bonderoeven-tv/bonderoeven-tv-bonderoeven-2008
INFO: Selected to download hls, bitrate: 2383
INFO: Outfile: bonderven.18.drtv-dr.ts
[023/170][==========......................................................................] ETA: 0:00:24
`````

**Comment by forthrin** [comment]
Had the same problem for another video with latest Homebrew version. Works with said Git version.

I assume the problem arose from the introduction of `EncryptedUri` on the site. Out of curiosity, the code used to decrypt this, is this just something arbitrary they rolled on the site that you just translated step-by-step from JavaScript to Python, or is it a common encryption method found on other sites too?
