### ISSUE TITLE
SVT Play error when downloading "Hemma igen"

### ISSUE THREAD

**Issue by JohnnyJorgensen** [spaam/svtplay-dl#1068]
### svtplay-dl versions:

svtplay-dl version 2.1

### Operating system and Python version:

Windows 10

### What is the issue:

I have downloaded all episodes of "Hemma igen" up to and including season 6, episode 6.

After that (season 6, episodes 7-9), svtplay-dl crashes with the following error:

C:\Users\jojo\Documents\Software\SVTPlay-DL\_new - special ffmpeg>svtplay-dl https://www.svtplay.se/video/21924798/hemma-igen/hemma-igen-sasong-6-nya-aventyr --verbose
DEBUG [1556486511.3259776] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.1
DEBUG [1556486511.3269436] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1556486511.3269436] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/21924798/hemma-igen/hemma-igen-sasong-6-nya-aventyr'
DEBUG [1556486511.330942] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1556486512.2478244] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/21924798/hemma-igen/hemma-igen-sasong-6-nya-aventyr HTTP/1.1" 200 None
DEBUG [1556486512.2776072] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1390227-007A'
DEBUG [1556486512.2794502] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
DEBUG [1556486512.4529552] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1390227-007A HTTP/1.1" 200 784
DEBUG [1556486512.4546473] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/7807176a-6023-49c6-9213-79529c9c1716/manifest.mpd'
DEBUG [1556486512.4566014] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
DEBUG [1556486512.4846058] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /7807176a-6023-49c6-9213-79529c9c1716/manifest.mpd HTTP/1.1" 302 0
DEBUG [1556486512.4856098] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-4j.akamaized.net:80
DEBUG [1556486512.506055] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svt-vod-4j.akamaized.net:80 "GET /d0/se/20190425/7807176a-6023-49c6-9213-79529c9c1716/manifest.mpd HTTP/1.1" 200 2462
DEBUG [1556486512.5069985] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://svt-vod-4j.akamaized.net/d0/se/20190425/7807176a-6023-49c6-9213-79529c9c1716/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F7807176a-6023-49c6-9213-79529c9c1716%2Fmanifest.mpd'
DEBUG [1556486512.5230024] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svt-vod-4j.akamaized.net:80 "GET /d0/se/20190425/7807176a-6023-49c6-9213-79529c9c1716/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F7807176a-6023-49c6-9213-79529c9c1716%2Fmanifest.mpd HTTP/1.1" 200 2462
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 64, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 58, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 107, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 86, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 122, in _get_video
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 143, in dashparse
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 171, in _dashparse
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 102, in adaptionset
IndexError: list index out of range

**Comment by Sopor** [comment]
If you use latest master i'm almost sure this will fix the issue.

**Comment by Sopor** [comment]
I will give you a tip @JohnnyJorgensen . Never ever use space in paths. Even if it is possible to use it, it can also create many weird issues.

**Comment by JohnnyJorgensen** [comment]
Thanks a lot Sopor.

Sorry about the dupe, I hadn't noticed that.

However, I've got a problem. My computer doesn't belong to me, it belongs to my employer, so I can't just go and install everything I'd need to compile the code (even if I knew how, which I don't. I'm a .Net programmer with absolutely NO knowledge of Python). I have to rely on compiled code. :-(

As for space in paths, you are of course right. Even as a programmer, you sometimes do stuff that is not optimal (mostly out of laziness). But surely, that can't be the root of the problem? If so, it would not be able to download ANYHTING at all???

**Comment by Sopor** [comment]
@JohnnyJorgensen You can download it [here](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23825288/artifacts)

**Comment by JohnnyJorgensen** [comment]
Great, thanks a lot Sopor! Trevlig 1:a maj! (y)

**Comment by JohnnyJorgensen** [comment]
BTW: That version seems to have solved the problem! :-)
