### ISSUE TITLE
MacOS svtplay-dl crash

### ISSUE THREAD

**Issue by niclasnj** [spaam/svtplay-dl#1070]
is there also a new master for svtplay-dl  for mac users? 
Got the same problem as the previous users with the "IndexError: list index out of range" i have version 2.1 Tried to uninstalled it but didn´t find any upgrades for the mac users!

**Comment by Sopor** [comment]
You need to compile it by yourself and it isn't so hard to do it. Follow the instructions [here](https://svtplay-dl.se/install/source/).

**Comment by niclasnj** [comment]
thanx @Sopor I have homebrew and just found the source for windows, is there a source for Mac?
Shouldnt I first "brew uninstall svtplay-dl" and then "brew install qemu" and i put the source in macbookuser/library/caches/Homebrew? But where is the file I should clone to the directory? I need to download it but i can´t find it?

**Comment by Sopor** [comment]
The source is the same for all OS. This is what i did if i remember it correctly.

- Open a terminal window

- install brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

- clone to a folder
git clone https://github.com/spaam/svtplay-dl.git

- cd to the folder svtplay-dl was cloned to

- brew install python3
python3 should already be installed with brew, but try to run python to see if it is added to the path

- pip3 install requests

- RTMPDump 2.4 is already installed with brew
if not: brew install rtmpdump

- pip3 install cryptography

- pip3 install pyyaml

- pip3 install pysocks

- brew install ffmpeg

- sudo make install

- make

- svtplay-dl --version

**Comment by petder** [comment]
Hi i get the same thing. And i don't understand how to fixit, get stuck on the clone part. says it already is a folder and so on. How to fix this problem so you don't get the index error?

**Comment by niclasnj** [comment]
thx @Sopor

**Comment by niclasnj** [comment]
@Sopor what do you mean i should do with this step "cd to the folder svtplay-dl was cloned to" 
I have an folder Mac Hd/Users/My Name/svtplay-dl -- in that folder i have all files!
So should i copy anythimng to that folder or I´m not sure what to do?

**Comment by Sopor** [comment]
@niclasnj To run `make` and `sudo make install` you need to have svtplay-dl as the current directory. The command `cd` (change directory) will make you change directory to svtplay-dl `cd svtplay-dl`.

**Comment by niclasnj** [comment]
@Sopor thank you very much, now it works just fine

**Comment by sm4tfe** [comment]
Excellent info :-)
Thanks Sopor!

**Comment by erikdwg** [comment]
Thanks @niclasnj . Took a while for me to fully understand how to do it, but i guess I learned some  new stuff to get there.

**Comment by fezaland** [comment]
> You need to compile it by yourself and it isn't so hard to do it. Follow the instructions [here](https://svtplay-dl.se/install/source/).

Tried that. This is what I got.

svtplay-dl
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 11, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 7, in <module>
ModuleNotFoundError: No module named 'yaml'

I am not good with the terminal, but I sometimes succeed in following instructions... Now I am stuck.
Hoping for an update for svtplay-dl, that I usually manage..

**Comment by Sopor** [comment]
And you have installed all the required libraries?

- `pip3 install cryptography`

- `pip3 install pyyaml`

- `pip3 install pysocks`

**Comment by fezaland** [comment]
-bash: pip3: command not found

**Comment by sm4tfe** [comment]
I wonder what SVTPlay is doing; Most programs have m4a and mp4 as file extensions, but sometimes it is ts... And if I check the same program a few days later it has changed to m4a/mp4.

**Comment by Sopor** [comment]
@fezaland as i already have mentioned, i'm not a MacOS user. I have been using Mac for about 30 minutes in my whole life. But try google and see if you could find a solution. That is what i do :)
`https://www.google.com/search?q=bash+pip3+command+not+found+macos`

**Comment by Sopor** [comment]
@sm4tfe Add `-P hls` and it should probably use the same, but svtplay-dl will convert ts to mp4.

**Comment by erikdwg** [comment]
@fezaland I followed @Sopor tutorial and i worked out great. It took some time before I totally understood it tho. Start with uninstall svtplay-dl: brew uninstall svtplay-dl 
After that just do as the tutorial. I had trouble with "cd" at first, but finally found out that you just type in: 
cd svtplay-dl ... and after that there was no errors.

**Comment by sm4tfe** [comment]
I didn't Uninstall, I just ran it on top of the old installation, it worked flawlessly.

**Comment by noob403** [comment]
@sm4tfe how did you do that? Please do tell and remember I am a noob

**Comment by sm4tfe** [comment]
I just followed the list above from @sopor, no problems. Just copy and paste into the Terminal, one line at a time, and wait for the prompt before you do the next line.
https://github.com/spaam/svtplay-dl/issues/1070#issuecomment-488087551
Where do you have problems?

**Comment by noob403** [comment]
@sm4tfe 
getting this after following the lines one at that time 
MacBook-Pro:~ pd$ svtplay-dl --version
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 11, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 10, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 8, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py", line 10, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py", line 5, in <module>
ModuleNotFoundError: No module named 'requests'

**Comment by sm4tfe** [comment]
And you didn't got any errors after any of the lines you pasted during the installation?

**Comment by JamesWilde** [comment]
Great stuff, Sopor.  Am now running svtplay-dl 2.1-53-gd33186e.  At the moment I'm downloading an item from tv4play and one from svtplay.  Good work, and thanks.

**Comment by EmmW** [comment]
Fantastic -- I also had the svtplay-dl crashed issue, even though I tried both reinstall and uninstall/install, but after having followed the steps above, it now works fine again (the only thing that was actually updated was ffmpeg, apart from that everything seemed fine as it were). I'm now running 2.1-53-gd33186e, which I understand is the most recent version.
