### ISSUE TITLE
SVTplay.se new titles cause crash

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#1075]
Run `svtplay-dl --version`
svplay-dl version 2.1

### Operating system and Python version:
Windows 8.1 64bit
Python 3.5.3 (v3.5.3:1800cb95a742, Jan 16 2017, 16:02:32)

### What is the issue:
A number of titles available at svtplay.se have recently started to cause svtplay.dl to crash.
Sometimes it has gone away if you wait for day, e.g. when SVT has made an update to the web material.
The crashes have, however, become more and more wide spread and this morning every new title I try crashes while older titles can be downloaded just fine.

An example of older material that can be dowloaded:
https://www.svtplay.se/video/27604/faret-shaun/faret-shaun-13-4-07-30?start=auto&tab=2006

An example of a new material which causes a crash:
https://www.svtplay.se/video/34876/faret-shaun/faret-shaun-17-4-14-35?start=auto&tab=2006

The crash trace I get is:
----------------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\svtplaydll\svtplay-dl_v2.1\__main__.py", line 13, in <module>
    svtplay_dl.main()
  File "c:\svtplaydll\svtplay-dl_v2.1\svtplay_dl\__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "c:\svtplaydll\svtplay-dl_v2.1\svtplay_dl\utils\getmedia.py", line 58, in
 get_media
    get_one_media(stream)
  File "c:\svtplaydll\svtplay-dl_v2.1\svtplay_dl\utils\getmedia.py", line 107, i
n get_one_media
    for i in streams:
  File "c:\svtplaydll\svtplay-dl_v2.1\svtplay_dl\service\svtplay.py", line 86, i
n get
    for i in videos:
  File "c:\svtplaydll\svtplay-dl_v2.1\svtplay_dl\service\svtplay.py", line 122,
in _get_video
    streams = dashparse(self.config, self.http.request("get", i["url"]), i["url"
], output=self.output)
  File "c:\svtplaydll\svtplay-dl_v2.1\svtplay_dl\fetcher\dash.py", line 143, in
dashparse
    return _dashparse(config, res.text, url, output, res.cookies)
  File "c:\svtplaydll\svtplay-dl_v2.1\svtplay_dl\fetcher\dash.py", line 171, in
_dashparse
    audiofiles = adaptionset(temp, url, baseurl, offset_sec, duration_sec)
  File "c:\svtplaydll\svtplay-dl_v2.1\svtplay_dl\fetcher\dash.py", line 102, in
adaptionset
    template = element[0].find("{urn:mpeg:dash:schema:mpd:2011}SegmentTemplate")

IndexError: list index out of range
----------------------------------------------------------------------------

To not get stuck I've made a workaround.
In  \fetcher\dash.py I've just short circuited "adaptationset" to make immediately exit  with "return streams"
The effect is that download works
The only side effect that I've noticed from using the patch is an incorrect representation of the Swedish characters "å,ä,ö,Å,Ä,Ö" in .SRT-files 

Since the crash in dash.py I thought that other streams might work.
However, trying to find out available streams also causes a crash.

Regards,
L-B

**Comment by Sopor** [comment]
Use latest [master ](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23825288/artifacts) and it will work.

**Comment by pythonuser3856** [comment]
It works, thanks !

**Comment by sm4tfe** [comment]
And for Mac users?

**Comment by Sopor** [comment]
@sm4tfe read here https://github.com/spaam/svtplay-dl/issues/1070

**Comment by pythonuser3856** [comment]
After some try-out most of the expected functionality is there but the content of .SRT-files are, at least partially, containing incorrect representations of the Swedish characters "å,ä,ö,Å,Ä,Ö".
One example is the .SRT-file saved with the link:
https://www.svtplay.se/video/22127610/josefsson/josefsson-sasong-1-tunneln?start=auto&tab=2019

I've not checked the full content of the .SRT-file but notice that the first part of the file contain incorrect representations, while the latter part includes correct representations.

Regards,
L-B

**Comment by pythonuser3856** [comment]
The last comment is probably a dup of #1072 

Regards,
L-B

**Comment by pythonuser3856** [comment]
Note:
It's not only Swedish characters.
One additional example is at a use of hyphen ("-") to bind two parts of text together.

Regards,
L-B

**Comment by fezaland** [comment]
Anybody have a solution for the problem with svtplay-dl crashing on newer titles?
For Mac OS.
