### ISSUE TITLE
svtplay-dl crashes for a svtplay.se title

### ISSUE THREAD

**Issue by Ragvald** [spaam/svtplay-dl#1080]
svtplay-dl crashes for a Vetenskapens Värld episode  from svtplay.se.
Earlier episodes can be downloaded.

### svtplay-dl versions:
svtplay-dl 2.1

### Operating system and Python version:
Linux  5.0.13-arch1-1-ARCH #1 SMP PREEMPT
Python 3.7.3

### What is the issue:
svtplay-dl --verbose https://www.svtplay.se/video/22112450/vetenskapens-varld/vetenskapens-varld-farliga-forare
DEBUG [1557338756.2531428] /usr/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1557338756.2540457] /usr/lib/python3.7/site-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1557338756.2540934] /usr/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/22112450/vetenskapens-varld/vetenskapens-varld-farliga-forare'
DEBUG [1557338756.2551198] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1557338756.327278] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/22112450/vetenskapens-varld/vetenskapens-varld-farliga-forare HTTP/1.1" 200 51809
DEBUG [1557338756.3423498] /usr/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1391963-018A'
DEBUG [1557338756.3439445] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
DEBUG [1557338756.3752427] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1391963-018A HTTP/1.1" 200 801
DEBUG [1557338756.3772683] /usr/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/e1c381cc-3360-44fe-86ea-92f7b55ad3cc/manifest.mpd'
DEBUG [1557338756.3783472] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
DEBUG [1557338756.4048734] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /e1c381cc-3360-44fe-86ea-92f7b55ad3cc/manifest.mpd HTTP/1.1" 302 0
DEBUG [1557338756.4068055] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): balancer.cdn.svt.se:80
DEBUG [1557338756.4274426] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/world/20190504/e1c381cc-3360-44fe-86ea-92f7b55ad3cc/manifest.mpd HTTP/1.1" 302 0
DEBUG [1557338756.4296548] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): ed6.cdn.svt.se:80
DEBUG [1557338756.447558] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed6.cdn.svt.se:80 "GET /d0/world/20190504/e1c381cc-3360-44fe-86ea-92f7b55ad3cc/manifest.mpd HTTP/1.1" 200 16245
DEBUG [1557338756.4555502] /usr/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://svt-vod-3a.akamaized.net/d0/world/20190504/e1c381cc-3360-44fe-86ea-92f7b55ad3cc/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2Fe1c381cc-3360-44fe-86ea-92f7b55ad3cc%2Fmanifest.mpd'
DEBUG [1557338756.456699] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-3a.akamaized.net:80
DEBUG [1557338756.4849367] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-3a.akamaized.net:80 "GET /d0/world/20190504/e1c381cc-3360-44fe-86ea-92f7b55ad3cc/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2Fe1c381cc-3360-44fe-86ea-92f7b55ad3cc%2Fmanifest.mpd HTTP/1.1" 200 2123
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3.7/site-packages/svtplay_dl/__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 58, in get_media
    get_one_media(stream)
  File "/usr/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 107, in get_one_media
    for i in streams:
  File "/usr/lib/python3.7/site-packages/svtplay_dl/service/svtplay.py", line 86, in get
    for i in videos:
  File "/usr/lib/python3.7/site-packages/svtplay_dl/service/svtplay.py", line 122, in _get_video
    streams = dashparse(self.config, self.http.request("get", i["url"]), i["url"], output=self.output)
  File "/usr/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 143, in dashparse
    return _dashparse(config, res.text, url, output, res.cookies)
  File "/usr/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 171, in _dashparse
    audiofiles = adaptionset(temp, url, baseurl, offset_sec, duration_sec)
  File "/usr/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 102, in adaptionset
    template = element[0].find("{urn:mpeg:dash:schema:mpd:2011}SegmentTemplate")
IndexError: list index out of range

**Comment by pythonuser3856** [comment]
Hi,
See issue #1075 for a similar description and comments put to that issue report.

**Comment by Sopor** [comment]
If i search for `list index out of range` i get 7 newly open reports. Guys, You need to start to search first before you create a new issue.

Solution: Use latest master

**Comment by Ferbd-Git** [comment]
Can we common users of svtplay-dl use the latest master or only developers have access to it?
When will come a new version of svtplay-dl?

**Comment by qnorsten** [comment]
@Ferbd-Git Only @spaam knows when a new version will be released to use master yourself just follow the instructions under https://github.com/spaam/svtplay-dl#from-source
