### ISSUE TITLE
svt-pal

### ISSUE THREAD

**Issue by metricspace** [spaam/svtplay-dl#1085]
### svtplay-dl versions:

Run `svtplay-dl --version`

### Operating system and Python version:

Name and version of the operating system and python version (run `python --version`)

### What is the issue:

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

    svtplay-dl --verbose https://www.example.com

**Comment by metricspace** [comment]
svtplay-dl version: 2.1

Os: Ubuntu 19:04

svtplay-dl "https://www.svtplay.se/video/22133370/matematikens-magiska-varld/matematikens-magiska-varld-sasong-1-avsnitt-2?start=auto"

$ svtplay-dl "https://www.svtplay.se/video/22133370/matematikens-magiska-varld/matematikens-magiska-varld-sasong-1-avsnitt-2?start=auto" --verbose
DEBUG [1557784618.0041373] /usr/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1557784618.0052528] /usr/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1557784618.0053253] /usr/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/22133370/matematikens-magiska-varld/matematikens-magiska-varld-sasong-1-avsnitt-2?start=auto'
DEBUG [1557784618.0069585] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1557784618.3672655] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/22133370/matematikens-magiska-varld/matematikens-magiska-varld-sasong-1-avsnitt-2?start=auto HTTP/1.1" 200 38140
DEBUG [1557784618.3833787] /usr/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1392598-002A'
DEBUG [1557784618.3855681] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
DEBUG [1557784618.4693685] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1392598-002A HTTP/1.1" 200 758
DEBUG [1557784618.4704144] /usr/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/0b4e904f-4390-4458-a323-8c1655517778/master-fmp4.m3u8'
DEBUG [1557784618.4718094] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
DEBUG [1557784618.4921522] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /0b4e904f-4390-4458-a323-8c1655517778/master-fmp4.m3u8 HTTP/1.1" 302 0
DEBUG [1557784618.494744] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): balancer.cdn.svt.se:80
DEBUG [1557784618.5178149] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190506/0b4e904f-4390-4458-a323-8c1655517778/master-fmp4.m3u8 HTTP/1.1" 302 0
DEBUG [1557784618.521474] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): ed7.cdn.svt.se:80
DEBUG [1557784618.5432947] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://ed7.cdn.svt.se:80 "GET /d0/se/20190506/0b4e904f-4390-4458-a323-8c1655517778/master-fmp4.m3u8 HTTP/1.1" 200 2278
DEBUG [1557784618.5444713] /usr/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/0b4e904f-4390-4458-a323-8c1655517778/lowbw.mpd'
DEBUG [1557784618.5580988] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /0b4e904f-4390-4458-a323-8c1655517778/lowbw.mpd HTTP/1.1" 302 0
DEBUG [1557784618.5744317] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190506/0b4e904f-4390-4458-a323-8c1655517778/lowbw.mpd HTTP/1.1" 302 0
DEBUG [1557784618.5860298] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://ed7.cdn.svt.se:80 "GET /d0/se/20190506/0b4e904f-4390-4458-a323-8c1655517778/lowbw.mpd HTTP/1.1" 200 14332
DEBUG [1557784618.596541] /usr/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/0b4e904f-4390-4458-a323-8c1655517778/master.m3u8'
DEBUG [1557784618.6075735] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /0b4e904f-4390-4458-a323-8c1655517778/master.m3u8 HTTP/1.1" 302 0
DEBUG [1557784618.619664] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190506/0b4e904f-4390-4458-a323-8c1655517778/master.m3u8 HTTP/1.1" 302 0
DEBUG [1557784618.6301045] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://ed7.cdn.svt.se:80 "GET /d0/se/20190506/0b4e904f-4390-4458-a323-8c1655517778/master.m3u8 HTTP/1.1" 200 2258
DEBUG [1557784618.6306267] /usr/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://svt-vod-5j.akamaized.net/d0/se/20190506/0b4e904f-4390-4458-a323-8c1655517778/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F0b4e904f-4390-4458-a323-8c1655517778%2Fmaster.m3u8'
DEBUG [1557784618.631949] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-5j.akamaized.net:80
DEBUG [1557784618.7013662] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-5j.akamaized.net:80 "GET /d0/se/20190506/0b4e904f-4390-4458-a323-8c1655517778/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F0b4e904f-4390-4458-a323-8c1655517778%2Fmaster.m3u8 HTTP/1.1" 200 542
DEBUG [1557784618.7047637] /usr/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://ed7.cdn.svt.se/d0/se/20190506/0b4e904f-4390-4458-a323-8c1655517778/master.m3u8'
DEBUG [1557784618.7190847] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://ed7.cdn.svt.se:80 "GET /d0/se/20190506/0b4e904f-4390-4458-a323-8c1655517778/master.m3u8 HTTP/1.1" 200 2258
DEBUG [1557784618.7245452] /usr/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/0b4e904f-4390-4458-a323-8c1655517778/master-fmp4-lowbw.m3u8'
DEBUG [1557784618.7371244] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /0b4e904f-4390-4458-a323-8c1655517778/master-fmp4-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1557784618.751499] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190506/0b4e904f-4390-4458-a323-8c1655517778/master-fmp4-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1557784618.7710226] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://ed7.cdn.svt.se:80 "GET /d0/se/20190506/0b4e904f-4390-4458-a323-8c1655517778/master-fmp4-lowbw.m3u8 HTTP/1.1" 200 1362
DEBUG [1557784618.7718964] /usr/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/0b4e904f-4390-4458-a323-8c1655517778/manifest.mpd'
DEBUG [1557784618.7838974] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /0b4e904f-4390-4458-a323-8c1655517778/manifest.mpd HTTP/1.1" 302 0
DEBUG [1557784618.7954996] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190506/0b4e904f-4390-4458-a323-8c1655517778/manifest.mpd HTTP/1.1" 302 0
DEBUG [1557784618.8096168] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://ed7.cdn.svt.se:80 "GET /d0/se/20190506/0b4e904f-4390-4458-a323-8c1655517778/manifest.mpd HTTP/1.1" 200 15752
DEBUG [1557784618.8103268] /usr/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://svt-vod-5j.akamaized.net/d0/se/20190506/0b4e904f-4390-4458-a323-8c1655517778/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F0b4e904f-4390-4458-a323-8c1655517778%2Fmanifest.mpd'
DEBUG [1557784618.826568] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-5j.akamaized.net:80 "GET /d0/se/20190506/0b4e904f-4390-4458-a323-8c1655517778/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F0b4e904f-4390-4458-a323-8c1655517778%2Fmanifest.mpd HTTP/1.1" 200 2026
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 64, in main
  File "/usr/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 58, in get_media
  File "/usr/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 107, in get_one_media
  File "/usr/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 86, in get
  File "/usr/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 122, in _get_video
  File "/usr/bin/svtplay-dl/svtplay_dl/fetcher/dash.py", line 143, in dashparse
  File "/usr/bin/svtplay-dl/svtplay_dl/fetcher/dash.py", line 171, in _dashparse
  File "/usr/bin/svtplay-dl/svtplay_dl/fetcher/dash.py", line 102, in adaptionset
IndexError: list index out of range

**Comment by Sopor** [comment]
Dupe of #1065 

Use latest master and it will work. Install instructions [here](https://svtplay-dl.se/install/linux/)

**Comment by wirretheman** [comment]
I installed it manually using the instructions above, but when I try to check the version I get this (macOS 14.4.3):

sh-3.2# svtplay-dl --version
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 11, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 7, in <module>
ModuleNotFoundError: No module named 'yaml'

**Comment by bartdedecker** [comment]
> python --version
3.6.0

> svtplay-dl --version
2.1

I followed all the previous install instructions but it still crashes ...

> svtplay-dl --verbose https://www.svtplay.se/video/21811302/plus/plus-sasong-27-avsnitt-12

DEBUG [1557914926.1158612] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\utils\getmedia.py/get_media: version: 2.1
DEBUG [1557914926.1238563] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1557914926.1238563] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/21811302/plus/plus-sasong-27-avsnitt-12'
DEBUG [1557914926.1268544] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se
DEBUG [1557914926.843442] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/21811302/plus/plus-sasong-27-avsnitt-12 HTTP/1.1" 200 47399
DEBUG [1557914926.9263937] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\utils\http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1391720-012A'
DEBUG [1557914926.9283931] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se
DEBUG [1557914927.062316] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1391720-012A HTTP/1.1" 200 799
DEBUG [1557914927.0643153] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/859e84fe-9379-4e41-9929-d4910518bcb8/master.m3u8'
DEBUG [1557914927.0663145] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se
DEBUG [1557914927.1892426] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /859e84fe-9379-4e41-9929-d4910518bcb8/master.m3u8 HTTP/1.1" 302 0
DEBUG [1557914927.1922414] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-5t.akamaized.net
DEBUG [1557914927.2372153] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_make_request: http://svt-vod-5t.akamaized.net:80 "GET /d0/world/20190507/859e84fe-9379-4e41-9929-d4910518bcb8/master.m3u8 HTTP/1.1" 200 597
DEBUG [1557914927.2382154] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\utils\http.py/request: HTTP getting 'http://svt-vod-5t.akamaized.net/d0/world/20190507/859e84fe-9379-4e41-9929-d4910518bcb8/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F859e84fe-9379-4e41-9929-d4910518bcb8%2Fmaster.m3u8'
DEBUG [1557914927.253206] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_make_request: http://svt-vod-5t.akamaized.net:80 "GET /d0/world/20190507/859e84fe-9379-4e41-9929-d4910518bcb8/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F859e84fe-9379-4e41-9929-d4910518bcb8%2Fmaster.m3u8 HTTP/1.1" 200 597
DEBUG [1557914927.3781338] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\utils\http.py/request: HTTP getting 'http://svt-vod-5t.akamaized.net/d0/world/20190507/859e84fe-9379-4e41-9929-d4910518bcb8/master.m3u8'
DEBUG [1557914927.3901274] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_make_request: http://svt-vod-5t.akamaized.net:80 "GET /d0/world/20190507/859e84fe-9379-4e41-9929-d4910518bcb8/master.m3u8 HTTP/1.1" 200 597
DEBUG [1557914927.4820738] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/859e84fe-9379-4e41-9929-d4910518bcb8/lowbw.mpd'
DEBUG [1557914927.5300467] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /859e84fe-9379-4e41-9929-d4910518bcb8/lowbw.mpd HTTP/1.1" 302 0
DEBUG [1557914927.5450382] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_make_request: http://svt-vod-5t.akamaized.net:80 "GET /d0/world/20190507/859e84fe-9379-4e41-9929-d4910518bcb8/lowbw.mpd HTTP/1.1" 200 1171
DEBUG [1557914927.5460396] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/859e84fe-9379-4e41-9929-d4910518bcb8/master-fmp4.m3u8'
DEBUG [1557914927.5940096] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /859e84fe-9379-4e41-9929-d4910518bcb8/master-fmp4.m3u8 HTTP/1.1" 302 0
DEBUG [1557914927.6100004] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_make_request: http://svt-vod-5t.akamaized.net:80 "GET /d0/world/20190507/859e84fe-9379-4e41-9929-d4910518bcb8/master-fmp4.m3u8 HTTP/1.1" 200 598
DEBUG [1557914927.6110005] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/859e84fe-9379-4e41-9929-d4910518bcb8/master-lowbw.m3u8'
DEBUG [1557914927.6589723] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /859e84fe-9379-4e41-9929-d4910518bcb8/master-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1557914927.6729646] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_make_request: http://svt-vod-5t.akamaized.net:80 "GET /d0/world/20190507/859e84fe-9379-4e41-9929-d4910518bcb8/master-lowbw.m3u8 HTTP/1.1" 200 459
DEBUG [1557914927.6739638] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/859e84fe-9379-4e41-9929-d4910518bcb8/master-fmp4-lowbw.m3u8'
DEBUG [1557914927.7219362] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /859e84fe-9379-4e41-9929-d4910518bcb8/master-fmp4-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1557914927.7389266] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_make_request: http://svt-vod-5t.akamaized.net:80 "GET /d0/world/20190507/859e84fe-9379-4e41-9929-d4910518bcb8/master-fmp4-lowbw.m3u8 HTTP/1.1" 200 453
DEBUG [1557914927.7399263] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/859e84fe-9379-4e41-9929-d4910518bcb8/manifest.mpd'
DEBUG [1557914927.7878985] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /859e84fe-9379-4e41-9929-d4910518bcb8/manifest.mpd HTTP/1.1" 302 0
DEBUG [1557914927.7998917] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_make_request: http://svt-vod-5t.akamaized.net:80 "GET /d0/world/20190507/859e84fe-9379-4e41-9929-d4910518bcb8/manifest.mpd HTTP/1.1" 200 1268
DEBUG [1557914927.800891] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\utils\http.py/request: HTTP getting 'http://svt-vod-5t.akamaized.net/d0/world/20190507/859e84fe-9379-4e41-9929-d4910518bcb8/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F859e84fe-9379-4e41-9929-d4910518bcb8%2Fmanifest.mpd'
DEBUG [1557914927.8128848] C:\Program Files (x86)\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py/_make_request: http://svt-vod-5t.akamaized.net:80 "GET /d0/world/20190507/859e84fe-9379-4e41-9929-d4910518bcb8/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F859e84fe-9379-4e41-9929-d4910518bcb8%2Fmanifest.mpd HTTP/1.1" 200 1268
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\Python36-32\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\Program Files (x86)\Python\Python36-32\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "bin/svtplay-dl", line 7, in <module>
  File "C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\utils\getmedia.py", line 58, in get_media
    get_one_media(stream)
  File "C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\utils\getmedia.py", line 107, in get_one_media
    for i in streams:
  File "C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\service\svtplay.py", line 86, in get
    for i in videos:
  File "C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\service\svtplay.py", line 122, in _get_video
    streams = dashparse(self.config, self.http.request("get", i["url"]), i["url"], output=self.output)
  File "C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\fetcher\dash.py", line 143, in dashparse
    return _dashparse(config, res.text, url, output, res.cookies)
  File "C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\fetcher\dash.py", line 171, in _dashparse
    audiofiles = adaptionset(temp, url, baseurl, offset_sec, duration_sec)
  File "C:\Program Files (x86)\Python\Python36-32\lib\site-packages\svtplay_dl\fetcher\dash.py", line 102, in adaptionset
    template = element[0].find("{urn:mpeg:dash:schema:mpd:2011}SegmentTemplate")
IndexError: list index out of range

**Comment by bartdedecker** [comment]
💨 is actually :dash:

**Comment by bartdedecker** [comment]
💨 is actually : dash :  but without spaces

**Comment by Sopor** [comment]
If you type `svtplay-dl --version` you should see `svtplay-dl 2.1-53-gd33186e`. If not, you are not running latest master.
