### ISSUE TITLE
ERROR: svtplay-dl crashed

### ISSUE THREAD

**Issue by DK28082** [spaam/svtplay-dl#1087]
### svtplay-dl versions: 

svtplay-dl 2.1

### Operating system and Python version: 

Mac OS 10.14

```
Dannys-MBP:~ Danny$ svtplay-dl --version
svtplay-dl 2.1
Dannys-MBP:~ Danny$ python --version
Python 2.7.15
Dannys-MBP:~ Danny$ brew --version
Homebrew 2.1.2
Homebrew/homebrew-core (git revision 4f140; last commit 2019-05-15)
```

### What is the issue:

Trying to download Eurovision and keep getting error: https://www.svtplay.se/video/21925806/eurovision-song-contest-2019/eurovision-song-contest-2019-semifinal-1-14-maj-21-00

```
Dannys-MBP:~ Danny$ svtplay-dl --verbose https://www.svtplay.se/video/21925806/eurovision-song-contest-2019/eurovision-song-contest-2019-semifinal-1-14-maj-21-00
DEBUG [1557982680.899601] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1557982680.900979] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1557982680.9010549] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/21925806/eurovision-song-contest-2019/eurovision-song-contest-2019-semifinal-1-14-maj-21-00'
DEBUG [1557982680.908279] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1557982683.134093] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/21925806/eurovision-song-contest-2019/eurovision-song-contest-2019-semifinal-1-14-maj-21-00 HTTP/1.1" 200 35782
DEBUG [1557982683.175479] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1390749-001A'
DEBUG [1557982683.177443] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
DEBUG [1557982683.8320708] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1390749-001A HTTP/1.1" 200 792
DEBUG [1557982683.833727] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/f949d527-ca0b-4280-b7e5-21a8ccbc6c0c/master-fmp4-lowbw.m3u8'
DEBUG [1557982683.835094] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
DEBUG [1557982684.2636049] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /f949d527-ca0b-4280-b7e5-21a8ccbc6c0c/master-fmp4-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1557982684.265413] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-10t.akamaized.net:80
DEBUG [1557982684.412322] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-10t.akamaized.net:80 "GET /d0/world/20190514/f949d527-ca0b-4280-b7e5-21a8ccbc6c0c/master-fmp4-lowbw.m3u8 HTTP/1.1" 200 466
DEBUG [1557982684.4132018] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/f949d527-ca0b-4280-b7e5-21a8ccbc6c0c/manifest.mpd'
DEBUG [1557982684.60717] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /f949d527-ca0b-4280-b7e5-21a8ccbc6c0c/manifest.mpd HTTP/1.1" 302 0
DEBUG [1557982684.639963] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-10t.akamaized.net:80 "GET /d0/world/20190514/f949d527-ca0b-4280-b7e5-21a8ccbc6c0c/manifest.mpd HTTP/1.1" 200 912
DEBUG [1557982684.640722] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://svt-vod-10t.akamaized.net/d0/world/20190514/f949d527-ca0b-4280-b7e5-21a8ccbc6c0c/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2Ff949d527-ca0b-4280-b7e5-21a8ccbc6c0c%2Fmanifest.mpd'
DEBUG [1557982684.673682] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-10t.akamaized.net:80 "GET /d0/world/20190514/f949d527-ca0b-4280-b7e5-21a8ccbc6c0c/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2Ff949d527-ca0b-4280-b7e5-21a8ccbc6c0c%2Fmanifest.mpd HTTP/1.1" 200 912
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 58, in get_media
    get_one_media(stream)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 107, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/svtplay.py", line 86, in get
    for i in videos:
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/svtplay.py", line 122, in _get_video
    streams = dashparse(self.config, self.http.request("get", i["url"]), i["url"], output=self.output)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 143, in dashparse
    return _dashparse(config, res.text, url, output, res.cookies)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 171, in _dashparse
    audiofiles = adaptionset(temp, url, baseurl, offset_sec, duration_sec)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 102, in adaptionset
    template = element[0].find("{urn:mpeg:dash:schema:mpd:2011}SegmentTemplate")
IndexError: list index out of range
```

**Comment by Sopor** [comment]
Dupe of #1065 

Use latest master and it will work. Install instructions [here](https://svtplay-dl.se/install/source/)

My installation [guide](https://github.com/spaam/svtplay-dl/issues/1070#issuecomment-488087551)for MacOS

**Comment by DK28082** [comment]
Thank you, this worked. Do I have to use this process every time there's an update? I had tried `brew upgrade svtplay-dl` but it said it was already installed.

**Comment by Sopor** [comment]
@DK28082 
Next time you will have to do
- `cd svtplay-dl`
- `git pull`
- `make`
- `sudo make install`

If you compile your own svtplay-dl it will make you use latest master (branch) instead of waiting for a new release.

**Comment by DK28082** [comment]
Okay thank you!
