### ISSUE TITLE
Issues with videos and series on SVTPlay

### ISSUE THREAD

**Issue by MikaThor** [spaam/svtplay-dl#1091]
### svtplay-dl versions:

svtplay-dl 2.1

### Operating system and Python version:

Windows 10 
Added the folder containing svtplay-dl.exe and python35.dll to the computer's PATH
Has been running fine so far

### What is the issue:
Works for some videos but not all -  not for this one

svtplay-dl --verbose https://www.svtplay.se/video/22153785/walk-with-me
DEBUG [1558216723.0221949] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.1
DEBUG [1558216723.0241563] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1558216723.0241563] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/22153785/walk-with-me'
DEBUG [1558216723.027181] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1558216723.3809025] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/22153785/walk-with-me HTTP/1.1" 200 36094
DEBUG [1558216723.414359] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1367768-001A'
DEBUG [1558216723.4153564] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
DEBUG [1558216723.528683] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1367768-001A HTTP/1.1" 200 713
DEBUG [1558216723.5316472] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/8d18d394-11b4-42a2-8519-db9acad9455c/master-lowbw.m3u8'
DEBUG [1558216723.5326443] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
DEBUG [1558216723.5722916] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /8d18d394-11b4-42a2-8519-db9acad9455c/master-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1558216723.5742342] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): balancer.cdn.svt.se:80
DEBUG [1558216723.611249] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190508/8d18d394-11b4-42a2-8519-db9acad9455c/master-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1558216723.614274] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): ed2.cdn.svt.se:80
DEBUG [1558216723.6475592] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed2.cdn.svt.se:80 "GET /d0/se/20190508/8d18d394-11b4-42a2-8519-db9acad9455c/master-lowbw.m3u8 HTTP/1.1" 200 1347
DEBUG [1558216723.6485972] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/8d18d394-11b4-42a2-8519-db9acad9455c/master.m3u8'
DEBUG [1558216723.6678784] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /8d18d394-11b4-42a2-8519-db9acad9455c/master.m3u8 HTTP/1.1" 302 0
DEBUG [1558216723.6860523] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190508/8d18d394-11b4-42a2-8519-db9acad9455c/master.m3u8 HTTP/1.1" 302 0
DEBUG [1558216723.7048068] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed2.cdn.svt.se:80 "GET /d0/se/20190508/8d18d394-11b4-42a2-8519-db9acad9455c/master.m3u8 HTTP/1.1" 200 2256
DEBUG [1558216723.7058046] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://svt-vod-3j.akamaized.net/d0/se/20190508/8d18d394-11b4-42a2-8519-db9acad9455c/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F8d18d394-11b4-42a2-8519-db9acad9455c%2Fmaster.m3u8'
DEBUG [1558216723.7078266] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-3j.akamaized.net:80
DEBUG [1558216723.7428894] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svt-vod-3j.akamaized.net:80 "GET /d0/se/20190508/8d18d394-11b4-42a2-8519-db9acad9455c/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F8d18d394-11b4-42a2-8519-db9acad9455c%2Fmaster.m3u8 HTTP/1.1" 200 541
DEBUG [1558216723.7459092] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://ed2.cdn.svt.se/d0/se/20190508/8d18d394-11b4-42a2-8519-db9acad9455c/master.m3u8'
DEBUG [1558216723.763098] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed2.cdn.svt.se:80 "GET /d0/se/20190508/8d18d394-11b4-42a2-8519-db9acad9455c/master.m3u8 HTTP/1.1" 200 2256
DEBUG [1558216723.7681158] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/8d18d394-11b4-42a2-8519-db9acad9455c/lowbw.mpd'
DEBUG [1558216723.7869158] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /8d18d394-11b4-42a2-8519-db9acad9455c/lowbw.mpd HTTP/1.1" 302 0
DEBUG [1558216723.805051] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190508/8d18d394-11b4-42a2-8519-db9acad9455c/lowbw.mpd HTTP/1.1" 302 0
DEBUG [1558216723.8234532] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed2.cdn.svt.se:80 "GET /d0/se/20190508/8d18d394-11b4-42a2-8519-db9acad9455c/lowbw.mpd HTTP/1.1" 200 16595
DEBUG [1558216723.838589] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/8d18d394-11b4-42a2-8519-db9acad9455c/manifest.mpd'
DEBUG [1558216723.8572938] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /8d18d394-11b4-42a2-8519-db9acad9455c/manifest.mpd HTTP/1.1" 302 0
DEBUG [1558216723.875748] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190508/8d18d394-11b4-42a2-8519-db9acad9455c/manifest.mpd HTTP/1.1" 302 0
DEBUG [1558216723.8957815] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed2.cdn.svt.se:80 "GET /d0/se/20190508/8d18d394-11b4-42a2-8519-db9acad9455c/manifest.mpd HTTP/1.1" 200 18018
DEBUG [1558216723.8977456] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://svt-vod-3j.akamaized.net/d0/se/20190508/8d18d394-11b4-42a2-8519-db9acad9455c/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F8d18d394-11b4-42a2-8519-db9acad9455c%2Fmanifest.mpd'
DEBUG [1558216723.9090793] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svt-vod-3j.akamaized.net:80 "GET /d0/se/20190508/8d18d394-11b4-42a2-8519-db9acad9455c/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F8d18d394-11b4-42a2-8519-db9acad9455c%2Fmanifest.mpd HTTP/1.1" 200 2076
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 64, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 58, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 107, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 86, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 122, in _get_video
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 143, in dashparse
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 171, in _dashparse
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 102, in adaptionset
IndexError: list index out of range

**Comment by Sopor** [comment]
Dupe of #1065 

Use latest [master ](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23825288/artifacts) and it will work.

**Comment by MikaThor** [comment]
Thanks
I am not familiar with python.
Will you build a new version of the windows executable and distribute on www.svtplay-dl.se any time soon?

**Comment by Sopor** [comment]
Follow the link in the above comment and you will find latest master to download.

**Comment by MikaThor** [comment]
Great! Thanks again.
