### ISSUE TITLE
Whats missing? (svtplay-dl on OSX Mojave)

### ISSUE THREAD

**Issue by b0bber** [spaam/svtplay-dl#1093]
svtplay-dl 2.1
Python 3.7.3

`svtplay-dl -S --verbose https://www.svtplay.se/video/11145865/andra-avenyn/andra-avenyn-sasong-1-avsnitt-1
DEBUG [1558860576.9622452] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1558860576.964125] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1558860576.9642189] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/11145865/andra-avenyn/andra-avenyn-sasong-1-avsnitt-1'
DEBUG [1558860576.983594] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1558860577.6453261] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/11145865/andra-avenyn/andra-avenyn-sasong-1-avsnitt-1 HTTP/1.1" 200 None
DEBUG [1558860577.694358] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1124033-001A'
DEBUG [1558860577.697938] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
DEBUG [1558860577.809152] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1124033-001A HTTP/1.1" 200 787
DEBUG [1558860577.8113978] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/ff37fa57-5258-4079-a141-5f4354723f9e/master-lowbw.m3u8'
DEBUG [1558860577.824318] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
DEBUG [1558860577.8661609] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /ff37fa57-5258-4079-a141-5f4354723f9e/master-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1558860577.870544] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): balancer.cdn.svt.se:80
DEBUG [1558860577.913388] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/world/20190502/ff37fa57-5258-4079-a141-5f4354723f9e/master-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1558860577.930764] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-ed7.secure.footprint.net:80
DEBUG [1558860578.119443] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-ed7.secure.footprint.net:80 "GET /d0/world/20190502/ff37fa57-5258-4079-a141-5f4354723f9e/master-lowbw.m3u8 HTTP/1.1" 200 1551
DEBUG [1558860578.120327] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/ff37fa57-5258-4079-a141-5f4354723f9e/master.m3u8'
DEBUG [1558860578.144434] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /ff37fa57-5258-4079-a141-5f4354723f9e/master.m3u8 HTTP/1.1" 302 0
DEBUG [1558860578.171212] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/world/20190502/ff37fa57-5258-4079-a141-5f4354723f9e/master.m3u8 HTTP/1.1" 302 0
DEBUG [1558860578.202516] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-ed7.secure.footprint.net:80 "GET /d0/world/20190502/ff37fa57-5258-4079-a141-5f4354723f9e/master.m3u8 HTTP/1.1" 200 2514
DEBUG [1558860578.203285] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://svt-vod-5t.akamaized.net/d0/world/20190502/ff37fa57-5258-4079-a141-5f4354723f9e/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2Fff37fa57-5258-4079-a141-5f4354723f9e%2Fmaster.m3u8'
DEBUG [1558860578.2527308] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-5t.akamaized.net:80
DEBUG [1558860578.2796822] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-5t.akamaized.net:80 "GET /d0/world/20190502/ff37fa57-5258-4079-a141-5f4354723f9e/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2Fff37fa57-5258-4079-a141-5f4354723f9e%2Fmaster.m3u8 HTTP/1.1" 200 591
DEBUG [1558860578.300305] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/eucjpprober.py/feed: EUC-JP Japanese prober hit error at byte 240
DEBUG [1558860578.307654] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/mbcharsetprober.py/feed: EUC-KR Korean prober hit error at byte 240
DEBUG [1558860578.3210828] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/mbcharsetprober.py/feed: EUC-TW Taiwan prober hit error at byte 239
DEBUG [1558860578.3323588] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: utf-8  confidence = 0.7525
DEBUG [1558860578.332478] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: SHIFT_JIS Japanese confidence = 0.01
DEBUG [1558860578.332532] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: EUC-JP not active
DEBUG [1558860578.332612] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: GB2312 Chinese confidence = 0.01
DEBUG [1558860578.3326788] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: EUC-KR not active
DEBUG [1558860578.332748] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: CP949 Korean confidence = 0.01
DEBUG [1558860578.332832] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: Big5 Chinese confidence = 0.01
DEBUG [1558860578.332897] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: EUC-TW not active
DEBUG [1558860578.33298] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: windows-1251 Russian confidence = 0.01
DEBUG [1558860578.33306] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: KOI8-R Russian confidence = 0.01
DEBUG [1558860578.33314] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: ISO-8859-5 Russian confidence = 0.01
DEBUG [1558860578.333214] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: MacCyrillic Russian confidence = 0.01
DEBUG [1558860578.333291] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: IBM866 Russian confidence = 0.01
DEBUG [1558860578.333365] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: IBM855 Russian confidence = 0.01
DEBUG [1558860578.3334458] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: ISO-8859-7 Greek confidence = 0.0
DEBUG [1558860578.333524] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: windows-1253 Greek confidence = 0.0
DEBUG [1558860578.333602] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: ISO-8859-5 Bulgairan confidence = 0.01
DEBUG [1558860578.333672] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: windows-1251 Bulgarian confidence = 0.01
DEBUG [1558860578.3337522] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: TIS-620 Thai confidence = 0.0
DEBUG [1558860578.3338292] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: ISO-8859-9 Turkish confidence = 0.16848297696268852
DEBUG [1558860578.3339221] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: windows-1255 Hebrew confidence = 0.0
DEBUG [1558860578.334002] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: windows-1255 Hebrew confidence = 0.0
DEBUG [1558860578.334097] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: windows-1255 Hebrew confidence = 0.0
DEBUG [1558860578.33422] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: utf-8  confidence = 0.7525
DEBUG [1558860578.3342998] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: SHIFT_JIS Japanese confidence = 0.01
DEBUG [1558860578.334357] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: EUC-JP not active
DEBUG [1558860578.3344572] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: GB2312 Chinese confidence = 0.01
DEBUG [1558860578.3345768] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: EUC-KR not active
DEBUG [1558860578.334707] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: CP949 Korean confidence = 0.01
DEBUG [1558860578.334829] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: Big5 Chinese confidence = 0.01
DEBUG [1558860578.334954] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: EUC-TW not active
DEBUG [1558860578.341613] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://svt-ed7.secure.footprint.net/d0/world/20190502/ff37fa57-5258-4079-a141-5f4354723f9e/master.m3u8'
DEBUG [1558860578.366124] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-ed7.secure.footprint.net:80 "GET /d0/world/20190502/ff37fa57-5258-4079-a141-5f4354723f9e/master.m3u8 HTTP/1.1" 200 2514
DEBUG [1558860578.388268] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/eucjpprober.py/feed: EUC-JP Japanese prober hit error at byte 240
DEBUG [1558860578.395839] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/mbcharsetprober.py/feed: EUC-KR Korean prober hit error at byte 240
DEBUG [1558860578.4107661] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/mbcharsetprober.py/feed: EUC-TW Taiwan prober hit error at byte 239
DEBUG [1558860578.4223402] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: utf-8  confidence = 0.7525
DEBUG [1558860578.422504] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: SHIFT_JIS Japanese confidence = 0.01
DEBUG [1558860578.422627] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: EUC-JP not active
DEBUG [1558860578.422729] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: GB2312 Chinese confidence = 0.01
DEBUG [1558860578.422818] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: EUC-KR not active
DEBUG [1558860578.4229062] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: CP949 Korean confidence = 0.01
DEBUG [1558860578.422994] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: Big5 Chinese confidence = 0.01
DEBUG [1558860578.423115] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: EUC-TW not active
DEBUG [1558860578.423271] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: windows-1251 Russian confidence = 0.01
DEBUG [1558860578.423347] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: KOI8-R Russian confidence = 0.01
DEBUG [1558860578.423458] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: ISO-8859-5 Russian confidence = 0.01
DEBUG [1558860578.423527] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: MacCyrillic Russian confidence = 0.01
DEBUG [1558860578.4236119] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: IBM866 Russian confidence = 0.01
DEBUG [1558860578.4236832] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: IBM855 Russian confidence = 0.01
DEBUG [1558860578.423771] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: ISO-8859-7 Greek confidence = 0.0
DEBUG [1558860578.423846] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: windows-1253 Greek confidence = 0.0
DEBUG [1558860578.423924] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: ISO-8859-5 Bulgairan confidence = 0.01
DEBUG [1558860578.423996] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: windows-1251 Bulgarian confidence = 0.01
DEBUG [1558860578.4240792] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: TIS-620 Thai confidence = 0.0
DEBUG [1558860578.424155] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: ISO-8859-9 Turkish confidence = 0.16848297696268852
DEBUG [1558860578.4242508] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: windows-1255 Hebrew confidence = 0.0
DEBUG [1558860578.4243279] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: windows-1255 Hebrew confidence = 0.0
DEBUG [1558860578.424416] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: windows-1255 Hebrew confidence = 0.0
DEBUG [1558860578.42451] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: utf-8  confidence = 0.7525
DEBUG [1558860578.424672] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: SHIFT_JIS Japanese confidence = 0.01
DEBUG [1558860578.424771] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: EUC-JP not active
DEBUG [1558860578.424876] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: GB2312 Chinese confidence = 0.01
DEBUG [1558860578.4249642] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: EUC-KR not active
DEBUG [1558860578.425053] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: CP949 Korean confidence = 0.01
DEBUG [1558860578.4251351] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: Big5 Chinese confidence = 0.01
DEBUG [1558860578.425215] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet/charsetgroupprober.py/get_confidence: EUC-TW not active
DEBUG [1558860578.4289339] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/ff37fa57-5258-4079-a141-5f4354723f9e/lowbw.mpd'
DEBUG [1558860578.452218] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /ff37fa57-5258-4079-a141-5f4354723f9e/lowbw.mpd HTTP/1.1" 302 0
DEBUG [1558860578.4789639] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/world/20190502/ff37fa57-5258-4079-a141-5f4354723f9e/lowbw.mpd HTTP/1.1" 302 0
DEBUG [1558860578.670998] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-ed7.secure.footprint.net:80 "GET /d0/world/20190502/ff37fa57-5258-4079-a141-5f4354723f9e/lowbw.mpd HTTP/1.1" 200 8689
DEBUG [1558860578.671993] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/ff37fa57-5258-4079-a141-5f4354723f9e/master-fmp4.m3u8'
DEBUG [1558860578.696231] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /ff37fa57-5258-4079-a141-5f4354723f9e/master-fmp4.m3u8 HTTP/1.1" 302 0
DEBUG [1558860578.7230022] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/world/20190502/ff37fa57-5258-4079-a141-5f4354723f9e/master-fmp4.m3u8 HTTP/1.1" 302 0
DEBUG [1558860578.730526] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): ed7.cdn.svt.se:80
DEBUG [1558860578.773827] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed7.cdn.svt.se:80 "GET /d0/world/20190502/ff37fa57-5258-4079-a141-5f4354723f9e/master-fmp4.m3u8 HTTP/1.1" 200 2533
DEBUG [1558860578.774755] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/ff37fa57-5258-4079-a141-5f4354723f9e/master-fmp4-lowbw.m3u8'
DEBUG [1558860578.798675] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /ff37fa57-5258-4079-a141-5f4354723f9e/master-fmp4-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1558860578.825336] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/world/20190502/ff37fa57-5258-4079-a141-5f4354723f9e/master-fmp4-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1558860578.8542972] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed7.cdn.svt.se:80 "GET /d0/world/20190502/ff37fa57-5258-4079-a141-5f4354723f9e/master-fmp4-lowbw.m3u8 HTTP/1.1" 200 1566
DEBUG [1558860578.855416] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/ff37fa57-5258-4079-a141-5f4354723f9e/manifest.mpd'
DEBUG [1558860578.8801181] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /ff37fa57-5258-4079-a141-5f4354723f9e/manifest.mpd HTTP/1.1" 302 0
DEBUG [1558860578.906712] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/world/20190502/ff37fa57-5258-4079-a141-5f4354723f9e/manifest.mpd HTTP/1.1" 302 0
DEBUG [1558860578.937827] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed7.cdn.svt.se:80 "GET /d0/world/20190502/ff37fa57-5258-4079-a141-5f4354723f9e/manifest.mpd HTTP/1.1" 200 10106
DEBUG [1558860578.938787] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://svt-vod-5t.akamaized.net/d0/world/20190502/ff37fa57-5258-4079-a141-5f4354723f9e/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2Fff37fa57-5258-4079-a141-5f4354723f9e%2Fmanifest.mpd'
DEBUG [1558860578.956865] /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-5t.akamaized.net:80 "GET /d0/world/20190502/ff37fa57-5258-4079-a141-5f4354723f9e/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2Fff37fa57-5258-4079-a141-5f4354723f9e%2Fmanifest.mpd HTTP/1.1" 200 1506
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 64, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 58, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 107, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 86, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 122, in _get_video
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/dash.py", line 143, in dashparse
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/dash.py", line 171, in _dashparse
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/dash.py", line 102, in adaptionset
IndexError: list index out of range
`

**Comment by Sopor** [comment]
Dupe of #1065 

Use latest master and it will work. Install instructions [here](https://svtplay-dl.se/install/source/) or try my [guide](https://github.com/spaam/svtplay-dl/issues/1070) for MacOS.
