### ISSUE TITLE
3 episodes of A Place To call Home not working

### ISSUE THREAD

**Issue by Hedhagen** [spaam/svtplay-dl#1095]
### svtplay-dl versions:
svtplay-dl 2.1

### Operating system and Python version:
Name and version of the operating system and python version (run `python --version`)

### What is the issue:
I have used -a (all command to try download all episodes and seasons)
But 3 episodes is not working, I've also tried them individually

https://www.svtplay.se/video/21924798/hemma-igen/hemma-igen-sasong-6-nya-aventyr?start=auto

https://www.svtplay.se/video/21959342/hemma-igen/hemma-igen-sasong-6-affarer-om-hosten?start=auto

https://www.svtplay.se/video/21963306/hemma-igen/hemma-igen-sasong-6-fyra-manader-senare?start=auto

svtplay-dl --verbose -p hds https://www.svtplay.se/video/21924798/hemma-igen/hemma-igen-sasong-6-nya-aventyr

DEBUG [1559460012.798909] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.1
DEBUG [1559460012.8009117] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1559460012.8009117] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/21924798/hemma-igen/hemma-igen-sasong-6-nya-aventyr'
DEBUG [1559460012.816542] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1559460013.819751] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/21924798/hemma-igen/hemma-igen-sasong-6-nya-aventyr HTTP/1.1" 200 53307
DEBUG [1559460013.941158] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1390227-007A'
DEBUG [1559460013.942159] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
DEBUG [1559460014.1733844] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1390227-007A HTTP/1.1" 200 None
DEBUG [1559460014.1889868] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/7807176a-6023-49c6-9213-79529c9c1716/manifest.mpd'
DEBUG [1559460014.1889868] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
DEBUG [1559460014.2578292] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /7807176a-6023-49c6-9213-79529c9c1716/manifest.mpd HTTP/1.1" 302 0
DEBUG [1559460014.2578292] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): balancer.cdn.svt.se:80
DEBUG [1559460014.3047032] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190425/7807176a-6023-49c6-9213-79529c9c1716/manifest.mpd HTTP/1.1" 302 0
DEBUG [1559460014.3047032] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): ed3.cdn.svt.se:80
DEBUG [1559460014.3203282] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed3.cdn.svt.se:80 "GET /d0/se/20190425/7807176a-6023-49c6-9213-79529c9c1716/manifest.mpd HTTP/1.1" 200 20387
DEBUG [1559460014.342464] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://svt-vod-4j.akamaized.net/d0/se/20190425/7807176a-6023-49c6-9213-79529c9c1716/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F7807176a-6023-49c6-9213-79529c9c1716%2Fmanifest.mpd'
DEBUG [1559460014.342464] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-4j.akamaized.net:80
DEBUG [1559460014.404972] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svt-vod-4j.akamaized.net:80 "GET /d0/se/20190425/7807176a-6023-49c6-9213-79529c9c1716/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F7807176a-6023-49c6-9213-79529c9c1716%2Fmanifest.mpd HTTP/1.1" 200 None
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 64, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 58, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 107, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 86, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 122, in _get_video
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 143, in dashparse
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 171, in _dashparse
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 102, in adaptionset
IndexError: list index out of range

**Comment by Sopor** [comment]
Dupe of #1065 #1068 #1070 #1075 #1080 #1084 #1085 #1091 #1093 #1094

Use latest [master](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23825288/artifacts) and it will work.
