### ISSUE TITLE
Compiling svtplay-dl on Windows - ModuleNotFoundError: No module named 'svtplay_dl'

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1111]
When i try to compile svtplay-dl on Windows i get the same error message everytime i run svtplay.exe.

[Step 5](https://github.com/spaam/svtplay-dl#windows)
`python %PYTHON%\\Scripts\\cxfreeze --include-modules=cffi,queue,idna.idnadata --target-dir=build bin/svtplay-dl`
What do you mean with %PYTHON% and why double `\\`. If i run that it will only be an error that it can't find the file or directory.

If i instead add the path to `cxfreeze` it will compile as it should, but when i run svtplay-dl.exe it will show this error message:
```
svtplay-dl.exe --version
Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python37\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python37\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "bin/svtplay-dl", line 4, in <module>
ModuleNotFoundError: No module named 'svtplay_dl'
```

So are your instructions wrong or is it me doing something wrong or both :)

I use Python 64-bit, maybe i need to use 32-bit instead? At least it seems to work better with the 32-bit version, but i still get the same error :(

Maybe i need to use Python 3.5 instead of 3.7?

I installed it on a totally new installation of Windows 10 and it isn't very easy to get it compiled. Now i get a message about `Microsoft Visual C++ 14.0 is required` for wheel for cx-Freeze and for cx_Freeze.

I also noticed that when i get it compiled there are a few missing folders in the `lib` folder:
asn1crypto
backports
certifi
chardet
cryptography
I have no idea why because everything is installed as it should.

@spaam Maybe you could install a fresh copy of Windows 10 (Vmware or VirtualBox) and see if your instructions really works when nothing is installed and you start from scratch? I can't get it to work when i'm trying :(

**Comment by Sopor** [comment]
Yes, now it worked! 🎆
