### ISSUE TITLE
SVTPlay - UnicodeEncodeError: 'ascii' codec can't encode characters in position 39-40: ordinal not in range(128)

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1119]
### svtplay-dl versions:

svtplay-dl 2.1+53.gd33186e

### Operating system and Python version:

OSMC Python 3.5.3

### What is the issue:

```
$ svtplay-dl -S -P hls https://www.svtplay.se/video/2400319/hjarta-for-djur/avsnitt-7-88
INFO: Outfile: hjarta.for.djur.s01e07.avsnitt.7-78391cb-svtplay.srt
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==2.1+53.gd33186e', 'svtplay-dl')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+53.gd33186e-py3.5.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+53.gd33186e-py3.5.egg/svtplay_dl/__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+53.gd33186e-py3.5.egg/svtplay_dl/utils/getmedia.py", line 56, in get_media
    get_one_media(stream)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+53.gd33186e-py3.5.egg/svtplay_dl/utils/getmedia.py", line 174, in get_one_media
    options_subs_dl(subfixes)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+53.gd33186e-py3.5.egg/svtplay_dl/utils/getmedia.py", line 169, in options_subs_dl
    subs[0].download()
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+53.gd33186e-py3.5.egg/svtplay_dl/subtitle/__init__.py", line 73, in download
    self.save_file(data, "srt")
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+53.gd33186e-py3.5.egg/svtplay_dl/subtitle/__init__.py", line 82, in save_file
    file_d.write(data)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 39-40: ordinal not in range(128)
```

**Comment by spaam** [comment]
man i dont like this stuff.  feels like i should just remove this subtitle stuff. always some stupid unicode errors here and there.
