### ISSUE TITLE
Error with latest snapshot

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [spaam/svtplay-dl#1138]
D:\dl>svtplay-dl.exe https://www.svtplay.se/video/13906548/svensson-svensson/svensson-svensson-sasong-1-god-jul-svensson?start=auto --verbose
DEBUG [1567805032.8755257] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.3-22-g5234f88
DEBUG [1567805032.876523] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1567805032.876523] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/13906548/svensson-svensson/svensson-svensson-sasong-1-god-jul-svensson?start=auto'
DEBUG [1567805032.8785176] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1567805033.919754] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/13906548/svensson-svensson/svensson-svensson-sasong-1-god-jul-svensson?start=auto HTTP/1.1" 200 31376
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 85, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 296, in extrametadata
  File "C:\Python35\lib\_strptime.py", line 510, in _strptime_datetime
  File "C:\Python35\lib\_strptime.py", line 343, in _strptime
ValueError: time data '2013-04-16T00:00:00+02:00' does not match format '%Y-%m-%dT%H:%M:%S%z'

**Comment by Sopor** [comment]
Dupe #1137

**Comment by spaam** [comment]
closing this. follow  #1137 for updates.
