### ISSUE TITLE
svtplay-dl crashed

### ISSUE THREAD

**Issue by leipet** [spaam/svtplay-dl#1140]
### svtplay-dl versions:

svtplay-dl 2.3

### Operating system and Python version:

Windows 10, python 3.5

### What is the issue: svtplay-dl crashed

C:\Kodak\uwtd\svtplay_dl>svtplay-dl --list-quality --verbose https://www.svtplay.se/video/23498406/ss-gb/ss-gb-sasong-1-avsnitt-3
DEBUG [1567813173.3750918] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.3
DEBUG [1567813173.3750918] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1567813173.3750918] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/23498406/ss-gb/ss-gb-sasong-1-avsnitt-3'
DEBUG [1567813173.3750918] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1567813173.6259468] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/23498406/ss-gb/ss-gb-sasong-1-avsnitt-3 HTTP/1.1" 200 31004
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 64, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 56, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 106, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 81, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 254, in outputfilename
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 286, in seasoninfo
ValueError: Unknown format code 'd' for object of type 'str'

**Comment by pythonuser3856** [comment]
I can successfully download from this link after patching two lines of code from master:
1)
svtplay.py, Line 296 new line content:
self.output["publishing_datetime"] = int(dateutil.parser.parse(episode["validFrom"]).strftime("%Y%m%d%H%M%S"))
2)
getmedia.py, Line 139 new line content:
    except (ValueError, TypeError, KeyError, OSError):

py c:\svtplaydll\svtplay-dl_v2.3fix\svtplay-dl-master\lib\svtplay_dl\__main__.py --subtitle https://www.svtplay.se/video/23498406/ss-gb/ss-gb-sasong-1-avsnitt-3
INFO: Selected to download hls, bitrate: 3190
INFO: Outfile: ss-gb.s01e03.avsnitt-3-4925621-svtplay.audio.ts
[350/350][========================================] ETA: 0:00:00
INFO: Outfile: ss-gb.s01e03.avsnitt-3-4925621-svtplay.ts
[350/350][========================================] ETA: 0:00:00
INFO: Merge audio and video into ss-gb.s01e03.avsnitt-3-4925621-svtplay.ts
INFO: Merging done, removing old files.
INFO: Muxing ss-gb.s01e03.avsnitt-3-4925621-svtplay.ts into ss-gb.s01e03.avsnitt
-3-4925621-svtplay.mp4
INFO: Muxing done, removing the old file.


Regards,
L-B

**Comment by spaam** [comment]
i have released 2.4 with the fix for this.  thanks for the bug report :)
