### ISSUE TITLE
The -A option to download all movies from svtplay does not work!

### ISSUE THREAD

**Issue by gotroni** [spaam/svtplay-dl#1141]
### svtplay-dl versions:

svtplay-dl 2.3+23.gbc15c69      (built from github / spaam/svtplay-dl / master)

### Operating system and Python version:

Ubuntu 19.04
Python 3.7.3

### What is the issue:

The -A option to download all files do not work anymore from svtplay.
The site svtplay has recently changed the website, so the json with episode information seems to have been changed as well. Downloading a single episode (not using -A option) works fine though and seems to has been fixed in the latest source from github - master. 

   svtplay-dl -A --verbose https://www.svtplay.se/playa-del-sol

DEBUG [1567849117.0750384] /usr/local/lib/python3.7/dist-packages/svtplay_dl-2.3+23.gbc15c69-py3.7.egg/svtplay_dl/utils/getmedia.py/get_media: version: 2.3+23.gbc15c69
DEBUG [1567849117.0760667] /usr/local/lib/python3.7/dist-packages/svtplay_dl-2.3+23.gbc15c69-py3.7.egg/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1567849117.076395] /usr/local/lib/python3.7/dist-packages/svtplay_dl-2.3+23.gbc15c69-py3.7.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/playa-del-sol'
DEBUG [1567849117.0775588] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1567849117.8469894] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /playa-del-sol HTTP/1.1" 200 36040
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==2.3+23.gbc15c69', 'svtplay-dl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/svtplay_dl-2.3+23.gbc15c69-py3.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.7/dist-packages/svtplay_dl-2.3+23.gbc15c69-py3.7.egg/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.7/dist-packages/svtplay_dl-2.3+23.gbc15c69-py3.7.egg/svtplay_dl/utils/getmedia.py", line 59, in get_media
    get_all_episodes(stream, url, options)
  File "/usr/local/lib/python3.7/dist-packages/svtplay_dl-2.3+23.gbc15c69-py3.7.egg/svtplay_dl/utils/getmedia.py", line 77, in get_all_episodes
    episodes = stream.find_all_episodes(stream.config)
  File "/usr/local/lib/python3.7/dist-packages/svtplay_dl-2.3+23.gbc15c69-py3.7.egg/svtplay_dl/service/svtplay.py", line 182, in find_all_episodes
    self.visibleid = list(janson["visible"].keys())[0]
KeyError: 'visible'

**Comment by spaam** [comment]
thanks for the bug report <3. i have commited a fix for this

**Comment by gotroni** [comment]
Your fix works fine!   Many thanks for fast and great support! :+1:
