### ISSUE TITLE
svtplay-dl crashed for windows 8.1

### ISSUE THREAD

**Issue by Haksej** [spaam/svtplay-dl#1143]
Crash for both latest 2.4 2019-09-07 and 2019-04-13

Tried this link (and others from svtplay): https://www.svtplay.se/shetland
```
DEBUG [1567887356.467827] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.4
DEBUG [1567887356.4698288] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1567887356.470829] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay
.se/shetland'
DEBUG [1567887356.473816] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connecti
on (1): www.svtplay.se:443
DEBUG [1567887357.0212047] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se
:443 "GET /shetland HTTP/1.1" 200 29377
DEBUG [1567887357.0922537] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
INFO [1567887357.0922537] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_all_episodes: Episode 1 of 1
INFO [1567887357.0942545] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_all_episodes: Url: http://www.svtp
lay.se/video/23523210/shetland/shetland-sasong-5-avsnitt-1
DEBUG [1567887357.0942545] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://www.svtplay
.se/video/23523210/shetland/shetland-sasong-5-avsnitt-1'
DEBUG [1567887357.101259] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connectio
n (1): www.svtplay.se:80
DEBUG [1567887357.1432936] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://www.svtplay.se:
80 "GET /video/23523210/shetland/shetland-sasong-5-avsnitt-1 HTTP/1.1" 307 0
DEBUG [1567887357.1492987] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connect
ion (1): www.svtplay.se:443
DEBUG [1567887357.1943293] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se
:443 "GET /video/23523210/shetland/shetland-sasong-5-avsnitt-1 HTTP/1.1" 200 29315
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 59, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 91, in get_all_episodes
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 77, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 306, in extrametadata
ValueError: Invalid format string
```

**Comment by Sopor** [comment]
Why didn't you follow the issue template? It is so muck easier if you show the url and what command line switches you are using.

You can't only try to download `https://www.svtplay.se/shetland`, you need to add -A.

**Comment by spaam** [comment]
This only happen on windows. it works great with macos and linux. maybe time to stop supporting windows 🤔

**Comment by spaam** [comment]
it seems to be related to `cx_freeze` ( the script to create windows binaries )  and `python-dateutil` ..

**Comment by pythonuser3856** [comment]
This may be the error I reported in #1140 
- Using "%s" as time string format qualifier seems to not be sufficient
- Error handling of datetime seems to have changed over time and may throw an "OSError" exception
In my installation I just patched the above to pass the error and I'm aware of that this may cause unwanted cause side effects.

Thanks for your effort and speedy result !

Regards,
L-B

**Comment by spaam** [comment]
@pythonuser3856 yeah. i dont like the exception because we want to use the info..

i have replaced the .zip file on the site for 2.4 with a modified version that works.
you have to download it again.

anyway thanks for the bug report <3
