### ISSUE TITLE
Time format error, not accepting uppercase Z

### ISSUE THREAD

**Issue by psi167** [spaam/svtplay-dl#1144]
### svtplay-dl versions: 

2.4

### Operating system and Python version:

Windows 10
Python 3.7.3

### What is the issue:

There is a time stamp ending with uppercase Z, but the program only accepts lowercase z. I believe the matching should be done against either upper or lower case. See debug output below. This was also reported as a comment on bug #1134, but as this bug was already closed, I file a new ticket specifically for this.

C:\>c:/bin/svtplay-dl/svtplay-dl.exe -v -g http://svtplay.se/video/23549922/det-kinesiska-experimentet
DEBUG [1567944229.255608] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.4-2-g5466853
DEBUG [1567944229.255608] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1567944229.255608] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://svtplay.se/video/23549922/det-kinesiska-experimentet'
DEBUG [1567944229.255608] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): svtplay.se:80
DEBUG [1567944229.3180676] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svtplay.se:80 "GET /video/23549922/det-kinesiska-experimentet HTTP/1.1" 301 0
DEBUG [1567944229.3180676] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): www.svtplay.se:80
DEBUG [1567944229.380548] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://www.svtplay.se:80 "GET /video/23549922/det-kinesiska-experimentet HTTP/1.1" 307 0
DEBUG [1567944229.380548] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1567944229.5523827] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/23549922/det-kinesiska-experimentet HTTP/1.1" 200 27856
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 78, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 315, in extrametadata
  File "C:\Python35\lib\_strptime.py", line 510, in _strptime_datetime
  File "C:\Python35\lib\_strptime.py", line 343, in _strptime
ValueError: time data '2019-09-08T00:00:00Z' does not match format '%Y-%m-%dT%H:%M:%S%z'

**Comment by AliensInc** [comment]
Yep, same here:

svtplay-dl.exe -P hls https://www.svtplay.se/video/23578454/fraga-lund/fraga-lund-sasong-4-avsnitt-2 --verbose
DEBUG [1568135240.0853] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.4-2-g5466853
DEBUG [1568135240.0882578] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1568135240.089256] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/23578454/fraga-lund/fraga-lund-sasong-4-avsnitt-2'
DEBUG [1568135240.0942545] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1568135240.5812535] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/23578454/fraga-lund/fraga-lund-sasong-4-avsnitt-2 HTTP/1.1" 200 30995
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 78, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 315, in extrametadata
  File "C:\Python35\lib\_strptime.py", line 510, in _strptime_datetime
  File "C:\Python35\lib\_strptime.py", line 343, in _strptime
ValueError: time data '2019-09-10T00:00:00Z' does not match format '%Y-%m-%dT%H:%M:%S%z'
