### ISSUE TITLE
No module named dateutil

### ISSUE THREAD

**Issue by rockomannen** [spaam/svtplay-dl#1147]
Version 2.4
Ubuntu 18.04.3 LTS
Python 2.7.15+

poweruser@hp:~$ svtplay-dl --version
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 12, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 11, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/services.py", line 5, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/barnkanalen.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 15, in <module>
ModuleNotFoundError: No module named 'dateutil'

**Comment by dalgr** [comment]
You can install `dateutil` with:
```
pip install python-dateutil
```

**Comment by rockomannen** [comment]
I'm afraid that didn't help:
poweruser@hp:~$ pip install python-dateutil
Collecting python-dateutil
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
    100% |████████████████████████████████| 235kB 1.4MB/s
Collecting six>=1.5 (from python-dateutil)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil
Successfully installed python-dateutil-2.8.0 six-1.12.0
poweruser@hp:~$ svtplay-dl --version
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 12, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 11, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/services.py", line 5, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/barnkanalen.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 15, in <module>
ModuleNotFoundError: No module named 'dateutil'
poweruser@hp:~$

**Comment by spaam** [comment]
You need to write `pip3`  to install it.  `pip` in ubuntu points to python2. svtplay-dl use python3 now.
