### ISSUE TITLE
Muxing fails after download

### ISSUE THREAD

**Issue by tomasgrahn** [spaam/svtplay-dl#1153]
After downloading the audio and video parts of an episode of Octonauterna (and possibly other series as well) svtplay-dl crashes when attempting to multiplex the files:
```
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==2.4+8.geb4f508', 'svtplay-dl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+8.geb4f508-py3.6.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+8.geb4f508-py3.6.egg/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+8.geb4f508-py3.6.egg/svtplay_dl/utils/getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+8.geb4f508-py3.6.egg/svtplay_dl/utils/getmedia.py", line 228, in get_one_media
    post.remux()
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+8.geb4f508-py3.6.egg/svtplay_dl/postprocess/__init__.py", line 122, in remux
    if ext == ".ts" and "aac" in self._getcodec(streams, audiotrack):
TypeError: argument of type 'NoneType' is not iterable
```

(Complete output attached)

Here's the command I was running:
svtplay-dl --verbose https://www.svtplay.se/video/13305964/octonauterna/octonauterna-sasong-1-odjurskartan

I'm running the latest version (as of writing this) on Ubuntu 19.04:
svtplay-dl 2.4+8.geb4f508
[output.txt](https://github.com/spaam/svtplay-dl/files/3612975/output.txt)

**Comment by spaam** [comment]
thank you for the bug report <3  i commited a fix for this

**Comment by tomasgrahn** [comment]
Thanks, but I'm still getting the same error:
```
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==2.4+9.gb428bcc', 'svtplay-dl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+9.gb428bcc-py3.6.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+9.gb428bcc-py3.6.egg/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+9.gb428bcc-py3.6.egg/svtplay_dl/utils/getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+9.gb428bcc-py3.6.egg/svtplay_dl/utils/getmedia.py", line 228, in get_one_media
    post.remux()
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+9.gb428bcc-py3.6.egg/svtplay_dl/postprocess/__init__.py", line 122, in remux
    if ext == ".ts" and "aac" in self._getcodec(streams, audiotrack):
TypeError: argument of type 'NoneType' is not iterable
```
