### ISSUE TITLE
Muxing still fails after download

### ISSUE THREAD

**Issue by tomasgrahn** [spaam/svtplay-dl#1154]
Despite the latest patch, I'm still getting the same error:
```
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==2.4+9.gb428bcc', 'svtplay-dl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+9.gb428bcc-py3.6.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+9.gb428bcc-py3.6.egg/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+9.gb428bcc-py3.6.egg/svtplay_dl/utils/getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+9.gb428bcc-py3.6.egg/svtplay_dl/utils/getmedia.py", line 228, in get_one_media
    post.remux()
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+9.gb428bcc-py3.6.egg/svtplay_dl/postprocess/__init__.py", line 122, in remux
    if ext == ".ts" and "aac" in self._getcodec(streams, audiotrack):
TypeError: argument of type 'NoneType' is not iterable
```

_Originally posted by @tomasgrahn in https://github.com/spaam/svtplay-dl/issues/1153#issuecomment-531503564_

**Comment by tomasgrahn** [comment]
Just tested version svtplay-dl 2.4+20.g0826b8f and muxing seems to be fixed now so I'm closing this issue. Thanks!
