### ISSUE TITLE
TV4 play crash svtplay-dl version 2.4-2-g5466853

### ISSUE THREAD

**Issue by niclasnj** [spaam/svtplay-dl#1155]
Tried to download https://www.tv4play.se/program/mord-utan-lik/11974491
and get: svtplay-dl crashed
i did --verbose get this messege

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 69, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 61, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/tv4play.py", line 70, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py", line 39, in request
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='playback-api.b17g.net', port=443): Max retries exceeded with url: /media/11974491?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine (Caused by ResponseError('too many 500 error responses'))

Any suggestions?

**Comment by felsokning** [comment]
Reproduces in Windows:

```
.\svtplay-dl.exe --subtitle --all-subtitles --convert-subtitle-colors --all-episodes --thumbnail --output '<path>' https://www.tv4play.se/program/sthlm-rekviem/11998351 --verbose
DEBUG [1569675750.7609143] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.4-2-g5466853
DEBUG [1569675750.762915] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: tv4play
DEBUG [1569675750.762915] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/program/sthlm-rekviem/11998351'
DEBUG [1569675750.7659152] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1569675751.2640283] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/sthlm-rekviem/11998351 HTTP/1.1" 200 None
INFO [1569675751.4120622] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_all_episodes: Episode 1 of 4
INFO [1569675751.4130626] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_all_episodes: Url: https://www.tv4play.se/program/sthlm-rekviem/11998351
DEBUG [1569675751.4140625] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://playback-api.b17g.net/media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'
DEBUG [1569675751.416063] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback-api.b17g.net:443
DEBUG [1569675751.8221557] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 116
DEBUG [1569675751.8231552] C:\Python35\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'): Retry(total=4, connect=5, read=5, redirect=None, status=None)
DEBUG [1569675751.8231552] C:\Python35\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine
DEBUG [1569675752.023201] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 116
DEBUG [1569675752.023201] C:\Python35\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'): Retry(total=3, connect=5, read=5, redirect=None, status=None)
DEBUG [1569675752.6233373] C:\Python35\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine
DEBUG [1569675752.9104037] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 116
DEBUG [1569675752.9104037] C:\Python35\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'): Retry(total=2, connect=5, read=5, redirect=None, status=None)
DEBUG [1569675754.110675] C:\Python35\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine
DEBUG [1569675754.3207223] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 116
DEBUG [1569675754.3217227] C:\Python35\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'): Retry(total=1, connect=5, read=5, redirect=None, status=None)
DEBUG [1569675756.7222683] C:\Python35\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine
DEBUG [1569675756.919313] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 116
DEBUG [1569675756.9203346] C:\Python35\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'): Retry(total=0, connect=5, read=5, redirect=None, status=None)
DEBUG [1569675761.7204032] C:\Python35\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine
DEBUG [1569675761.9154477] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 116
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\requests\adapters.py", line 449, in send
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 734, in urlopen
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 734, in urlopen
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 734, in urlopen
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 734, in urlopen
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 734, in urlopen
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
  File "C:\Python35\lib\site-packages\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='playback-api.b17g.net', port=443): Max retries exceeded with url: /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 59, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 91, in get_all_episodes
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\tv4play.py", line 70, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py", line 39, in request
  File "C:\Python35\lib\site-packages\requests\sessions.py", line 533, in request
  File "C:\Python35\lib\site-packages\requests\sessions.py", line 646, in send
  File "C:\Python35\lib\site-packages\requests\adapters.py", line 507, in send
requests.exceptions.RetryError: HTTPSConnectionPool(host='playback-api.b17g.net', port=443): Max retries exceeded with url: /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine (Caused by ResponseError('too many 500 error responses',))
```

It looks like the B17G servers are returning 500 status codes to specific requests, as the videos play in the browser[s] just fine.

**Comment by Sopor** [comment]
It works perfect here

```
e:\Utils\svtplay-dl-test>svtplay-dl.exe --subtitle --all-subtitles --convert-subtitle-colors --all-episodes --thumbnail https://www.tv4play.se/program/sthlm-rekviem/11998351
INFO: Episode 1 of 4
INFO: Url: https://www.tv4play.se/program/sthlm-rekviem/11998351
INFO: Outfile: sthlm-rekviem.s01e01.sthlm.rekviem.del.1-oonskad-sv-11998351-tv4play.srt
INFO: Selected to download hls, bitrate: 4536
INFO: Outfile: sthlm-rekviem.s01e01.sthlm.rekviem.del.1-oonskad-11998351-tv4play.audio.ts
[1025/1301][===============================================================.................] ETA: 0:00:09
```

Try latest master 2.4-24-g1721ca1

**Comment by felsokning** [comment]
@Sopor - It reproduces with the [latest snapshot](https://svtplay-dl.se/download/snapshots/20190929_184814/) (svtplay-dl 2.4-25-g806fc1d).

```
.\svtplay-dl.exe --subtitle --all-subtitles --convert-subtitle-colors --all-episodes --thumbnail --output [PATH] https://www.tv4play.se/program/sthlm-rekviem/11998351 --verbose
DEBUG [1569837920.7528908] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.4-25-g806fc1d
DEBUG [1569837920.7538915] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: tv4play
DEBUG [1569837920.7548916] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/program/sthlm-rekviem/11998351'
DEBUG [1569837920.756892] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1569837921.1059766] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/sthlm-rekviem/11998351 HTTP/1.1" 200 None
INFO [1569837921.1809883] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_all_episodes: Episode 1 of 4
INFO [1569837921.1809883] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_all_episodes: Url: https://www.tv4play.se/program/sthlm-rekviem/11998351
DEBUG [1569837921.1819887] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://playback-api.b17g.net/media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'
DEBUG [1569837921.1839888] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback-api.b17g.net:443
DEBUG [1569837921.7141101] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 116
DEBUG [1569837921.7141101] C:\Python37\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'): Retry(total=4, connect=5, read=5, redirect=None, status=None)
DEBUG [1569837921.7141101] C:\Python37\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine
DEBUG [1569837922.0101771] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 116
DEBUG [1569837922.0101771] C:\Python37\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'): Retry(total=3, connect=5, read=5, redirect=None, status=None)
DEBUG [1569837922.610313] C:\Python37\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine
DEBUG [1569837922.9353864] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 116
DEBUG [1569837922.9353864] C:\Python37\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'): Retry(total=2, connect=5, read=5, redirect=None, status=None)
DEBUG [1569837924.1366951] C:\Python37\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine
DEBUG [1569837924.465734] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 116
DEBUG [1569837924.465734] C:\Python37\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'): Retry(total=1, connect=5, read=5, redirect=None, status=None)
DEBUG [1569837926.8672793] C:\Python37\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine
DEBUG [1569837927.1833513] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 116
DEBUG [1569837927.1843517] C:\Python37\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'): Retry(total=0, connect=5, read=5, redirect=None, status=None)
DEBUG [1569837931.9844415] C:\Python37\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine
DEBUG [1569837932.310516] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 116
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\requests\adapters.py", line 449, in send
  File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 846, in urlopen
  File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 846, in urlopen
  File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 846, in urlopen
  [Previous line repeated 2 more times]
  File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 820, in urlopen
  File "C:\Python37\lib\site-packages\urllib3\util\retry.py", line 436, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='playback-api.b17g.net', port=443): Max retries exceeded with url: /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python37\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 59, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 91, in get_all_episodes
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\tv4play.py", line 70, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py", line 39, in request
  File "C:\Python37\lib\site-packages\requests\sessions.py", line 533, in request
  File "C:\Python37\lib\site-packages\requests\sessions.py", line 646, in send
  File "C:\Python37\lib\site-packages\requests\adapters.py", line 507, in send
requests.exceptions.RetryError: HTTPSConnectionPool(host='playback-api.b17g.net', port=443): Max retries exceeded with url: /media/11998351?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine (Caused by ResponseError('too many 500 error responses'))
```

Do you know which date your specific build was from?

**Comment by Sopor** [comment]
Windows svtplay-dl 2.4-25-g806fc1d
```
svtplay-dl.exe --subtitle --all-subtitles --convert-subtitle-colors --all-episodes --thumbnail https://www.tv4play.se/program/sthlm-rekviem/11998351
INFO: Episode 1 of 4
INFO: Url: https://www.tv4play.se/program/sthlm-rekviem/11998351
INFO: Outfile: sthlm-rekviem.s01e01.sthlm.rekviem.del.1-oonskad-sv-11998351-tv4play.srt
INFO: Selected to download hls, bitrate: 4536
INFO: Outfile: sthlm-rekviem.s01e01.sthlm.rekviem.del.1-oonskad-11998351-tv4play.audio.ts
[0107/1301][======..........................................................................] ETA: 0:00:28
```

Linux svtplay-dl 2.4-25-g806fc1d:
```
$ svtplay-dl --subtitle --all-subtitles --convert-subtitle-colors --all-episodes --thumbnail https://www.tv4play.se/program/sthlm-rekviem/11998351
INFO: Episode 1 of 4
INFO: Url: https://www.tv4play.se/program/sthlm-rekviem/11998351
INFO: Outfile: sthlm-rekviem.s01e01.sthlm.rekviem.del.1-oonskad-sv-11998351-tv4play.srt
INFO: Selected to download hls, bitrate: 4536
INFO: Outfile: sthlm-rekviem.s01e01.sthlm.rekviem.del.1-oonskad-11998351-tv4play.audio.ts
[0173/1301][==============................................................................................................] ETA: 0:00:33
```

If the version is the same our files are identically.

**Comment by einarblaberg** [comment]
For me turning off IPv6 helped.

Before that I tried with both the 2.4 release and latest master on Windows and I tried latest master on Linux, both failed on multiple shows (Blood, The Victim). Once I disabled IPv6 it started working again.

**Comment by einarblaberg** [comment]
> For me turning off IPv6 helped.
It seems to be enough to block IPv6/AAAA DNS-lookups for playback-api.b17g.net
