### ISSUE TITLE
svtplay-dl 2.4 Time format bug - again

### ISSUE THREAD

**Issue by bohelax** [spaam/svtplay-dl#1156]
I posted this before, but it was closed (without action)?
It's still (or again) there!
bin>ver

Microsoft Windows [Version 10.0.17763.615]

bin>svtplay-dl --version
svtplay-dl 2.4-2-g5466853

bin>svtplay-dl https://www.svtplay.se/video/23680902/far-till-sol-och-var --verbose
DEBUG [1568681319.8109555] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.4-2-g5466853
DEBUG [1568681319.8140032] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1568681319.8140032] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/23680902/far-till-sol-och-var'
DEBUG [1568681319.8199985] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1568681320.2158384] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/23680902/far-till-sol-och-var H
TTP/1.1" 200 29718
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 78, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 315, in extrametadata
  File "C:\Python35\lib\_strptime.py", line 510, in _strptime_datetime
  File "C:\Python35\lib\_strptime.py", line 343, in _strptime
ValueError: time data '2019-09-16T13:15:00Z' does not match format '%Y-%m-%dT%H:%M:%S%z'

bin>

**Comment by SYSophie** [comment]
@bohelax latest version of master is 2.4+20.g0826b8f and it runs fine and should be fixed there. Please update <3

**Comment by bohelax** [comment]
Thanks SYSophie for a quick reply.
However the Windows version of svtplay-dl.exe I can download from the site (https://svtplay-dl.se/archive/) is still "2.4-2-g5466853" as used above.
Is there a more recent version at some better URL?

Unfortunately I don't have the resources to build from the master.
I've looked into getting a build capability a couple of times, but have always run into the problem of "to install This you need That" and to "install That you need Something Else" etc.
So far I have given up trying to follow this chain to its end (if there is one).
//BoH

**Comment by Sopor** [comment]
@bohelax You can download it [here](https://ci.appveyor.com/api/buildjobs/3e0cl5579j3j3jp4/artifacts/svtplay-dl.zip)

**Comment by bohelax** [comment]
Excellent - many thanks !!

Question: Is the link persistent to whatever is the latest build, or temporary just for now?
//BoH

**Comment by Sopor** [comment]
@bohelax The link is only valid for 6 month and you need to find a new URL for every new commit that is made but it isn't so hard to get if you look at this [comment](https://github.com/spaam/svtplay-dl/issues/1044#issuecomment-456759821)

**Comment by spaam** [comment]
@bohelax or use the latest snapshot from this https://svtplay-dl.se/download/snapshots/ to test it out until i release a new version tomorrow or thursday.

**Comment by bohelax** [comment]
Thank you both for the info.
I'll stay with the stable (official) version as long as it works.
But when a show-stopper is encountered its good to have a back-door;)
//BoH

**Comment by Sopor** [comment]
I got this in latest master 2.4-20
```
svtplay-dl.exe -S -P hls http://www.svtplay.se/video/23726174/de-drabbade/de-drabbade-avsnitt-9 --verbose
DEBUG [1568928837.6921923] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.4-20-g0826b8f
DEBUG [1568928837.6921923] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1568928837.6921923] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://www.svtplay.se/video/23726174/de-drabbade/de-drabbade-avsnitt-9'
DEBUG [1568928837.6921923] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): www.svtplay.se:80
DEBUG [1568928837.7609048] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://www.svtplay.se:80 "GET /video/23726174/de-drabbade/de-drabbade-avsnitt-9 HTTP/1.1" 307 0
DEBUG [1568928837.7609048] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1568928837.9460711] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/23726174/de-drabbade/de-drabbade-avsnitt-9 HTTP/1.1" 200 32954
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
    except (yaml.YAMLError, yaml.MarkedYAMLError) as e:
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media

  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
    if stream.config.get("preferred").lower() == i.name:
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 78, in get
    vid = janson["video"]["id"]
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 317, in extrametadata
    pass
  File "C:\Python35\lib\_strptime.py", line 510, in _strptime_datetime
  File "C:\Python35\lib\_strptime.py", line 343, in _strptime
ValueError: time data '2013-04-15T22:0000' does not match format '%Y-%m-%dT%H:%M:%S%z'
```

**Comment by spaam** [comment]
@Sopor feels like they have so many different ways to have the date. maybe its time to remove the metadata feature 🤔

**Comment by adron1111** [comment]
svtplay seems to supply dates on these formats
2019-08-04T12:05:00+02:00
2019-09-14T08:25:00Z

Both should be valid in python 3.7 with "%Y-%m-%dT%H:%M:%S%z"

The problem is:
"2019-09-14T08:25:00Z" transforms to "2019-09-14T08:25:00" from the fix to remove Z, then to "2019-09-14T08:2500" from the fix to remove : from inside the timezone specification.

**Comment by spaam** [comment]
@adron1111 its a fix for py37, but the issue is that we have users running py35 (ubuntu 16.04) and py36 (ubuntu 18.04). i think i fix ze issue now. will commit it in a few min and later release a new verison

**Comment by Sopor** [comment]
When i run svtplay-dl 2.4-25-g806fc1d in Windows i get `ValueError: time data '2019-09-29T18:0000' does not match format '%Y-%m-%dT%H:%M:%S%z'` but if i run the exact same version in Linux it works. In Linux i run Python 3.5.3.

So i'm waiting for your commit @spaam :)

**Comment by spaam** [comment]
i pushed a commit that should fix it
