### ISSUE TITLE
Option --silent-semi causes error

### ISSUE THREAD

**Issue by adron1111** [spaam/svtplay-dl#1163]
svtplay-dl --version
svtplay-dl 2.4-2-g5466853

svtplay-dl --silent-semi --verbose http://www.svtplay.se/video/8713341/ronja-rovardotter-animerad/ronja-rovardotter-sasong-1-svt-10

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 230, in get_one_media
AttributeError: 'HLS' object has no attribute 'options'

**Comment by Sopor** [comment]
It seems to download the episode but it will show this error. If i download without `--silent-semi` there will not be any error message when i run it in latest master `2.4-24-g1721ca1`
