### ISSUE TITLE
Problems downloading from cmore.se: account.cmore.se does not exist

### ISSUE THREAD

**Issue by lunderhage** [spaam/svtplay-dl#1174]
§### svtplay-dl versions:
svtplay-dl 2.4-26-g5dcc899

### Operating system and Python version:
Ubuntu 19.04 and Python 3.7.3

### What is the issue:
Tries to connect to account.cmore.se which does not exist, see stacktrace below:

svtplay-dl --verbose -u user@example.com -p secret https://www.cmore.se/serie/72596-gasmamman/sasong-2/episod-7/3666453-gasmamman
DEBUG [1571170283.8534477] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 2.4-26-g5dcc899
DEBUG [1571170283.853907] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: cmore
DEBUG [1571170283.8539677] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.cmore.se/serie/72596-gasmamman/sasong-2/episod-7/3666453-gasmamman'
DEBUG [1571170283.8556206] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.cmore.se:443
DEBUG [1571170283.942425] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.cmore.se:443 "GET /serie/72596-gasmamman/sasong-2/episod-7/3666453-gasmamman HTTP/1.1" 200 None
DEBUG [1571170283.947553] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.cmore.se/login'
DEBUG [1571170283.9547782] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.cmore.se:443 "GET /login HTTP/1.1" 200 None
DEBUG [1571170283.9557457] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://account.cmore.se/session?client=cmore-web-prod'
DEBUG [1571170283.9574425] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): account.cmore.se:443
DEBUG [1571170283.9625323] /usr/lib/python3/dist-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/session?client=cmore-web-prod'): Retry(total=4, connect=4, read=5, redirect=None, status=None)
WARNING [1571170283.962811] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/urlopen: Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb66dd7b9b0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /session?client=cmore-web-prod
DEBUG [1571170283.9629707] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (2): account.cmore.se:443
DEBUG [1571170283.9686832] /usr/lib/python3/dist-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/session?client=cmore-web-prod'): Retry(total=3, connect=3, read=5, redirect=None, status=None)
WARNING [1571170284.5699894] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/urlopen: Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb66dd2db00>: Failed to establish a new connection: [Errno -2] Name or service not known')': /session?client=cmore-web-prod
DEBUG [1571170284.5703955] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (3): account.cmore.se:443
DEBUG [1571170284.582065] /usr/lib/python3/dist-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/session?client=cmore-web-prod'): Retry(total=2, connect=2, read=5, redirect=None, status=None)
WARNING [1571170285.7840185] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/urlopen: Retrying (Retry(total=2, connect=2, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb66dd7b940>: Failed to establish a new connection: [Errno -2] Name or service not known')': /session?client=cmore-web-prod
DEBUG [1571170285.7844265] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (4): account.cmore.se:443
DEBUG [1571170285.7957287] /usr/lib/python3/dist-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/session?client=cmore-web-prod'): Retry(total=1, connect=1, read=5, redirect=None, status=None)
WARNING [1571170288.1990244] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/urlopen: Retrying (Retry(total=1, connect=1, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb66dd7ba20>: Failed to establish a new connection: [Errno -2] Name or service not known')': /session?client=cmore-web-prod
DEBUG [1571170288.1994238] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (5): account.cmore.se:443
DEBUG [1571170288.2676866] /usr/lib/python3/dist-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/session?client=cmore-web-prod'): Retry(total=0, connect=0, read=5, redirect=None, status=None)
WARNING [1571170293.0721135] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/urlopen: Retrying (Retry(total=0, connect=0, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb66dd7bac8>: Failed to establish a new connection: [Errno -2] Name or service not known')': /session?client=cmore-web-prod
DEBUG [1571170293.072454] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (6): account.cmore.se:443
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fb66dd7bc18>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  [Previous line repeated 2 more times]
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='account.cmore.se', port=443): Max retries exceeded with url: /session?client=cmore-web-prod (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb66dd7bc18>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 69, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 61, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/cmore.py", line 22, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/cmore.py", line 99, in _login
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py", line 39, in request
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='account.cmore.se', port=443): Max retries exceeded with url: /session?client=cmore-web-prod (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb66dd7bc18>: Failed to establish a new connection: [Errno -2] Name or service not known'))

user@Computer:~/Videos/Gåsmamman$ host account.cmore.se
Host account.cmore.se not found: 3(NXDOMAIN)

**Comment by calleman** [comment]
Any news on this issue?

**Comment by carlrygart** [comment]
I'm also having this issue. Any news?

**Comment by tivolimeister** [comment]
Seems like login on cmore is made to a new host, `account-delta.b17g.services`. Previously it was `account.cmore.se`

**Comment by tivolimeister** [comment]
Got it to work by making changes to `cmore.py`; using `https://account-delta.b17g.services//api?client=cmore-web` and adjusting to the new json formats (in/out).

But isn't all this unrelevant since all content is DRM on cmore?

**Comment by carlrygart** [comment]
@tivolimeister You're correct. I got it working as well a few days ago, but also realized all content is DRM, so I'm not sure it's worth spending time on getting this into master.

**Comment by xopheus** [comment]
@tivolimeister @carlrygart 
Is there any chance you would be willing to share your solution here?

**Comment by carlrygart** [comment]
@xopheus 
I made a fix for this locally, but it's not worth sharing because of the DRM reason mentioned above.

So to be clear: Even if you get the login working, you'll not be able to download anything anyway, because of the DRM protection. Instead, a proposed solution would be to remove support for Cmore completely, because I doubt that they ever will remove the DRM protection.

**Comment by xopheus** [comment]
I see - thanks.
