### ISSUE TITLE
svtplay-dl crashes when downloading from TV4 play

### ISSUE THREAD

**Issue by diskpart** [spaam/svtplay-dl#1191]
### svtplay-dl versions:

svtplay-dl 2.4-2-g5466853

### Operating system and Python version:

Running the Windows exe on Windows 7 Ultimate 64bit

### What is the issue:

svtplay-dl crashes when downloading from TV4 play. Have tried multiple files. Downloading from SVT play works fine.

c:\svtplay-dl>svtplay-dl --verbose https://www.tv4play.se/program/hela-sverige-b
akar/11979410
DEBUG [1574873338.687095] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.p
y/get_media: version: 2.4-2-g5466853
DEBUG [1574873338.688595] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__
.py/__init__: service: tv4play
DEBUG [1574873338.688595] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/re
quest: HTTP getting 'https://www.tv4play.se/program/hela-sverige-bakar/11979410'

DEBUG [1574873338.6910954] C:\Python35\lib\site-packages\urllib3\connectionpool.
py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1574873338.9816322] C:\Python35\lib\site-packages\urllib3\connectionpool.
py/_make_request: https://www.tv4play.se:443 "GET /program/hela-sverige-bakar/11
979410 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", lin
e 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23
, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in ge
t_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 111, in g
et_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\tv4play.py", line 49, in g
et
KeyError: 'VideoAsset:11979410'

**Comment by diskpart** [comment]
Tried again tonight and it worked. Must have been some temporary error on tv4 yesterday.

Closing the issue.
