### ISSUE TITLE
Unable to download show that requires log in.

### ISSUE THREAD

**Issue by letharion** [spaam/svtplay-dl#1202]
When visiting https://www.tv4play.se/program/farmen/12490244 I get told to log in, so I do.
I then pass the url to svt-play, which of course has difficulty downloading the content since it doesn't run in my web browser.

### svtplay-dl versions:
$ svtplay-dl --version
svtplay-dl 2.4

### Operating system and Python version:
Linux
$ python --version
Python 3.6.9

### What is the issue:

$ svtplay-dl -A -S https://www.tv4play.se/program/farmen/12490244 --verbose
DEBUG [1578824953.6173189] /home/letharion/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 2.4
DEBUG [1578824953.618485] /home/letharion/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1578824953.6187778] /home/letharion/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/farmen/12490244'
DEBUG [1578824953.6207907] /usr/lib64/python3.6/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1578824954.1991162] /usr/lib64/python3.6/site-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/farmen/12490244 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/letharion/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/home/letharion/bin/svtplay-dl/svtplay_dl/__init__.py", line 69, in main
  File "/home/letharion/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 59, in get_media
  File "/home/letharion/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 77, in get_all_episodes
  File "/home/letharion/bin/svtplay-dl/svtplay_dl/service/tv4play.py", line 98, in find_all_episodes
KeyError: 'clip'

From my browser I try to copy the cookie header in, hoping that will help, but I clearly get it wrong since the values cannot be parsed:

$ svtplay-dl -A -S https://www.tv4play.se/program/farmen/12490244 --verbose --http-header Cookie='accepted_terms=true; bbToken=[token]; birth_year=[year]; first_name=[name]; last_name=[name]; last_session_touch=1578824762049; userCompleteStatus=true; user_id=[uid]; user_name=[e-mail]; zip_code=[zip]'
DEBUG [1578827188.2089083] /home/letharion/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 2.4
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/letharion/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/home/letharion/bin/svtplay-dl/svtplay_dl/__init__.py", line 69, in main
  File "/home/letharion/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 47, in get_media
  File "/home/letharion/bin/svtplay-dl/svtplay_dl/service/__init__.py", line 245, in service_handler
  File "/home/letharion/bin/svtplay-dl/svtplay_dl/service/__init__.py", line 44, in __init__
  File "/home/letharion/bin/svtplay-dl/svtplay_dl/utils/http.py", line 27, in __init__
  File "/home/letharion/bin/svtplay-dl/svtplay_dl/utils/http.py", line 43, in split_header
ValueError: dictionary update sequence element #0 has length 3; 2 is required

How can I download TV4 play content that requires log in?

**Comment by SYSophie** [comment]
@letharion you need to use the arguments -u, --username in combination with -p, --password. Not just login thru your browser.

**Comment by letharion** [comment]
Hey, thanks. :)
I tried this as well, and appear to be hitting the same issue:
```
$ svtplay-dl -A -S https://www.tv4play.se/program/farmen/12490244 --verbose -u [e-mail] -p$(pass websites/tv4play)
DEBUG [1578908532.4414656] /home/letharion/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 2.4
DEBUG [1578908532.4427483] /home/letharion/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1578908532.443062] /home/letharion/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/farmen/12490244'
DEBUG [1578908532.4453225] /usr/lib64/python3.6/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1578908532.5789688] /usr/lib64/python3.6/site-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/farmen/12490244 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/letharion/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/home/letharion/bin/svtplay-dl/svtplay_dl/__init__.py", line 69, in main
  File "/home/letharion/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 59, in get_media
  File "/home/letharion/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 77, in get_all_episodes
  File "/home/letharion/bin/svtplay-dl/svtplay_dl/service/tv4play.py", line 98, in find_all_episodes
KeyError: 'clip'
```

**Comment by SYSophie** [comment]
@letharion Farmen shouldn't require login as far as I know make sure that you don't just have the email and password and no other symbols: 

`-u superniceusername -p supersecretpassword`

I don't know if their might be a bug with the -A (all) command for tv4play or not, maybe you could start with a single episode. Tv4play itself don't require you to use login details other then for actual premium content.

**Comment by letharion** [comment]
I tried dropping the -A now, and it seems like I can successfully download one episode at a time.
If you failed to download any episodes it might have been a temporary issue?

**Comment by SYSophie** [comment]
@letharion the issue seems to be that the API has changed which breaks the search for all episodes with the -A argument.

**Comment by letharion** [comment]
@SYSophie I've changed the issue title to something more appropriate then.
