### ISSUE TITLE
[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC]

### ISSUE THREAD

**Issue by lethargicpizza** [spaam/svtplay-dl#1203]
I've downloaded svtplay-dl.zip from the site and extracted it to a folder in Windows 10 and ran:

svtplay-dl https://www.svtplay.se/video/25113006/kalifat/kalifat-sasong-1-avsnitt-1?start=auto

The issue will be (when downloading ts):

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 212, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 141, in download
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 182, in _download
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py", line 39, in request
  File "C:\Python35\lib\site-packages\requests\sessions.py", line 533, in request
  File "C:\Python35\lib\site-packages\requests\sessions.py", line 686, in send
  File "C:\Python35\lib\site-packages\requests\models.py", line 828, in content
  File "C:\Python35\lib\site-packages\requests\models.py", line 750, in generate
  File "C:\Python35\lib\site-packages\urllib3\response.py", line 531, in stream
  File "C:\Python35\lib\site-packages\urllib3\response.py", line 479, in read
  File "C:\Python35\lib\http\client.py", line 448, in read
  File "C:\Python35\lib\http\client.py", line 488, in readinto
  File "C:\Python35\lib\socket.py", line 576, in readinto
  File "C:\Python35\lib\ssl.py", line 937, in recv_into
  File "C:\Python35\lib\ssl.py", line 799, in read
  File "C:\Python35\lib\ssl.py", line 583, in read
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2083)

**Comment by Sopor** [comment]
The issue template is there because is it quite annoying to ask for it every time a new issue is open.. So what is the svtplay-dl and ffmpeg version?

**Comment by Sopor** [comment]
It is working perfect with 2.4-29-gc59a305
```
svtplay-dl.exe https://www.svtplay.se/video/25113006/kalifat/kalifat-sasong-1-avsnitt-1
INFO: Outfile: kalifat.s01e01.avsnitt-1-d1124f1-svtplay.srt
INFO: Selected to download hls, bitrate: 2705
INFO: Outfile: kalifat.s01e01.avsnitt-1-d1124f1-svtplay.audio.ts
[091/683][==========......................................................................] ETA: 0:00:13
```

**Comment by lethargicpizza** [comment]
The recent version from the site, of course!
There's no one else to download.

It's working, but not perfect because the download is interrupted everytime when you download the "ts" (after "audio.ts" ([683/683]) is finished).

**Comment by Sopor** [comment]
What site? Tell me the version instead of letting me guess the version.

Have you tried latest [master](https://svtplay-dl.se/download/snapshots/)?

**Comment by lethargicpizza** [comment]
https://svtplay-dl.se/archive/

"Latest windows .exe (currently 2.4)"

**Comment by SYSophie** [comment]
@lethargicpizza have you tried downloading while using the argument:

`--dont-verify-ssl-cert`

If it works with that it might be right to assume that your system might have some old SSL-cert files that needs to removed or updated.

**Comment by lethargicpizza** [comment]
yes, I have

**Comment by SYSophie** [comment]
And the output for that is? @lethargicpizza
