### ISSUE TITLE
TV4 play issue

### ISSUE THREAD

**Issue by Bofinken** [spaam/svtplay-dl#1204]
### svtplay-dl versions:
svtplay-dl v2.4
Run `svtplay-dl --version`

### Operating system and Python version:
Windows 10
Name and version of the operating system and python version (run `python --version`)

### What is the issue:
svtplay-dl -v -S -o "D:\TV\hamilton 1" https://www.tv4play.se/program/hamilton/12514049

DEBUG [1579510645.14214] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/12514049?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 114
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\requests\adapters.py", line 449, in send
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 734, in urlopen
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 734, in urlopen
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 734, in urlopen
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 734, in urlopen
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 734, in urlopen
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
  File "C:\Python35\lib\site-packages\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='playback-api.b17g.net', port=443): Max retries exceeded with url: /media/12514049?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\tv4play.py", line 70, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py", line 39, in request
  File "C:\Python35\lib\site-packages\requests\sessions.py", line 533, in request
  File "C:\Python35\lib\site-packages\requests\sessions.py", line 646, in send
  File "C:\Python35\lib\site-packages\requests\adapters.py", line 507, in send
requests.exceptions.RetryError: HTTPSConnectionPool(host='playback-api.b17g.net', port=443): Max retries exceeded with url: /media/12514049?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine (Caused by ResponseError('too many 500 error responses',))

**Comment by Sopor** [comment]
Have you tried latest [master](https://svtplay-dl.se/download/snapshots/)?
