### ISSUE TITLE
SVT Play crashing

### ISSUE THREAD

**Issue by tobbefix** [spaam/svtplay-dl#1208]
### svtplay-dl versions:

svtplay-dl 2.4-2-g5466853

### Operating system and Python version:

svtplay-dl.exe

### What is the issue:

Episode 1, 2 and 6 of Kalifat is OK but Episode 3-5 crashes the program

g:\svtplay-dl>svtplay-dl.exe https://www.svtplay.se/video/25117658/kalifat/kalifat-sasong-1-avsnitt-3?start=auto --verbose
DEBUG [1580474704.2270935] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.4-2-g5466853
DEBUG [1580474704.2280836] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1580474704.2280836] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/25117658/kalifat/kalifat-sasong-1-avsnitt-3?start=auto'
DEBUG [1580474704.2300925] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1580474704.5542843] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/25117658/kalifat/kalifat-sasong-1-avsnitt-3?start=auto HTTP/1.1" 200 38606
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 78, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 315, in extrametadata
  File "C:\Python35\lib\_strptime.py", line 510, in _strptime_datetime
  File "C:\Python35\lib\_strptime.py", line 343, in _strptime
ValueError: time data '2020-01-12T01:00:00Z' does not match format '%Y-%m-%dT%H:%M:%S%z'

**Comment by Sopor** [comment]
Try another [snapshot](https://svtplay-dl.se/download/snapshots/20191019_132253/svtplay-dl.zip)
