### ISSUE TITLE
Can't connect to HTTPS URL because the SSL module is not available."

### ISSUE THREAD

**Issue by JonasHKSUSA** [spaam/svtplay-dl#1215]
### svtplay-dl versions:

C:\svtplay-dl>svtplay-dl --version
svtplay-dl 2.4-2-g5466853

### Operating system and Python version:

Windows 7 64 bit
Python 3.4
However I'm running the executable.

### What is the issue:

When I try to download one episode of Saltkråkan from SVT Play, I get following printout:

C:\svtplay-dl>svtplay-dl https://www.svtplay.se/video/14733592/vi-pa-saltkrakan/
vi-pa-saltkrakan-sasong-1-en-dag-i-juni
WARNING: Retrying (Retry(total=4, connect=5, read=5, redirect=None, status=None)
) after connection broken by 'SSLError("Can't connect to HTTPS URL because the S
SL module is not available.",)': /video/14733592/vi-pa-saltkrakan/vi-pa-saltkrak
an-sasong-1-en-dag-i-juni
WARNING: Retrying (Retry(total=3, connect=5, read=5, redirect=None, status=None)
) after connection broken by 'SSLError("Can't connect to HTTPS URL because the S
SL module is not available.",)': /video/14733592/vi-pa-saltkrakan/vi-pa-saltkrak
an-sasong-1-en-dag-i-juni
WARNING: Retrying (Retry(total=2, connect=5, read=5, redirect=None, status=None)
) after connection broken by 'SSLError("Can't connect to HTTPS URL because the S
SL module is not available.",)': /video/14733592/vi-pa-saltkrakan/vi-pa-saltkrak
an-sasong-1-en-dag-i-juni
WARNING: Retrying (Retry(total=1, connect=5, read=5, redirect=None, status=None)
) after connection broken by 'SSLError("Can't connect to HTTPS URL because the S
SL module is not available.",)': /video/14733592/vi-pa-saltkrakan/vi-pa-saltkrak
an-sasong-1-en-dag-i-juni
WARNING: Retrying (Retry(total=0, connect=5, read=5, redirect=None, status=None)
) after connection broken by 'SSLError("Can't connect to HTTPS URL because the S
SL module is not available.",)': /video/14733592/vi-pa-saltkrakan/vi-pa-saltkrak
an-sasong-1-en-dag-i-juni
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 591, in u
rlopen
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 249, in _
get_conn
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 818, in _
new_conn
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module i
s not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\requests\adapters.py", line 449, in send
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 670, in u
rlopen
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 670, in u
rlopen
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 670, in u
rlopen
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 670, in u
rlopen
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 670, in u
rlopen
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 641, in u
rlopen
  File "C:\Python35\lib\site-packages\urllib3\util\retry.py", line 399, in incre
ment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.svtplay.se', por
t=443): Max retries exceeded with url: /video/14733592/vi-pa-saltkrakan/vi-pa-sa
ltkrakan-sasong-1-en-dag-i-juni (Caused by SSLError("Can't connect to HTTPS URL
because the SSL module is not available.",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", lin
e 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23
, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in ge
t_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 96, in ge
t_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\output.py", line 121, in fil
ename
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py", line 63, in
get_urldata
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py", line 39, in reques
t
  File "C:\Python35\lib\site-packages\requests\sessions.py", line 533, in reques
t
  File "C:\Python35\lib\site-packages\requests\sessions.py", line 646, in send
  File "C:\Python35\lib\site-packages\requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.svtplay.se', port=44
3): Max retries exceeded with url: /video/14733592/vi-pa-saltkrakan/vi-pa-saltkr
akan-sasong-1-en-dag-i-juni (Caused by SSLError("Can't connect to HTTPS URL beca
use the SSL module is not available.",))

Sorry for this noob question, I'm very new to Python.

**Comment by ChristofferHolmesland** [comment]
Try installing OpenSSL. If that doesn't work you should try to reinstall python.

**Comment by Sopor** [comment]
Try this version of [svtplay-dl](https://gofile.io/?c=2PfCBx) for Windows

**Comment by JonasHKSUSA** [comment]
Thanks for the other version Sopor, it works!
However, it split the video in one audio stream and one video stream, I cannot find any options to merge while download, am I doing something wrong?
