### ISSUE TITLE
Downloading from TV4 Play does not work.

### ISSUE THREAD

**Issue by erikatl** [spaam/svtplay-dl#1219]
### svtplay-dl --version
``` 
[erik@max]$ svtplay-dl --version
svtplay-dl 2.4-29-gc59a305
``` 

### Operating system and Python version:
Manjaro Linux
Kernel		: Linux 5.3.18-1-MANJARO (x86_64)

``` 
[erik@max]$ python --version
Python 3.8.1
``` 

### What is the issue:
Problem downloading from TV4 Play. SVT Play seems to work ok.
``` 
[erik@max En plats i solen]$ svtplay-dl --verbose https://www.tv4play.se/program/en-plats-i-solen/11791521
DEBUG [1582161344.652057] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 2.4-29-gc59a305
DEBUG [1582161344.6552753] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1582161344.655655] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/en-plats-i-solen/11791521'
DEBUG [1582161344.6573966] /usr/lib/python3.8/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1582161345.0719967] /usr/lib/python3.8/site-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/en-plats-i-solen/11791521 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 69, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 59, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 77, in get_all_episodes
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/tv4play.py", line 98, in find_all_episodes
KeyError: 'clip'
```

**Comment by SYSophie** [comment]
@erikatl see #1202

**Comment by erikatl** [comment]
OK, it was late at night and I edited away the --username/--password arguments without mentioning it. I have tried quoting the username which has the '@' character (both "" and ''), to no avail.

**Comment by SYSophie** [comment]
@erikatl login credentials for tv4play is only needed for content that's premium. For this you don't needed it

I suspect that you had the -A argument specified since you're getting the error same error message as in #1202

**Comment by erikatl** [comment]
@SYSophie No I did not have the -A argument specified. I just tried without any optional argument, it still fails:
```
[erik@max ~]$ svtplay-dl https://www.tv4play.se/program/en-plats-i-solen/11791521
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 69, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 59, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 77, in get_all_episodes
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/tv4play.py", line 98, in find_all_episodes
KeyError: 'clip'
```

**Comment by SYSophie** [comment]
@erikatl line 59 in getmedia.py is only called for if the -A option is called for either by commandline or from config file. 

Do you have any config file?

**Comment by erikatl** [comment]
Oh, sorry! I had been experimenting with the config file and set "all_episodes: true" and I had forgotten about it. Now everything works fine - as long as I din't use the -A argument. Should I close the issue?

**Comment by SYSophie** [comment]
@erikatl it's the same issue as #1202 and I don't think we need two tickets for the same issue :) But that's just my suggestion.

**Comment by erikatl** [comment]
No we don't of course. I'll close it. Thanks for your help!

**Comment by SYSophie** [comment]
@erikatl no problem, good that things got sorted :)
