### ISSUE TITLE
Crash on newer episodes on viafree.se

### ISSUE THREAD

**Issue by magic75** [spaam/svtplay-dl#1222]
### svtplay-dl versions:

svtplay-dl 2.4+29.gc59a305

### Operating system and Python version:

Linux Mint 19.3 Tricia
Python 3.6.9

### What is the issue:
Crashes on newer episodes from viafree.
svtplay-dl --verbose https://www.viafree.se/program/humor/community/sasong-1/avsnitt-20

DEBUG [1582918475.5855362] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+29.gc59a305-py3.6.egg/svtplay_dl/utils/getmedia.py/get_media: version: 2.4+29.gc59a305
DEBUG [1582918475.5876734] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+29.gc59a305-py3.6.egg/svtplay_dl/service/__init__.py/__init__: service: viaplay
DEBUG [1582918475.5878096] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+29.gc59a305-py3.6.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.viafree.se/program/humor/community/sasong-1/avsnitt-20'
DEBUG [1582918475.5907562] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.viafree.se
DEBUG [1582918475.6939056] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.viafree.se:443 "GET /program/humor/community/sasong-1/avsnitt-20 HTTP/1.1" 200 None
DEBUG [1582918475.6980858] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+29.gc59a305-py3.6.egg/svtplay_dl/utils/http.py/request: HTTP getting 'http://playapi.mtgx.tv/v3/videos/1015206'
DEBUG [1582918475.7003422] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): playapi.mtgx.tv
DEBUG [1582918475.7054975] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://playapi.mtgx.tv:80 "GET /v3/videos/1015206 HTTP/1.1" 200 2272
DEBUG [1582918475.7067156] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+29.gc59a305-py3.6.egg/svtplay_dl/utils/http.py/request: HTTP getting 'http://playapi.mtgx.tv/v3/videos/stream/1015206'
DEBUG [1582918475.8111494] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://playapi.mtgx.tv:80 "GET /v3/videos/stream/1015206 HTTP/1.1" 200 317
DEBUG [1582918475.8123033] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+29.gc59a305-py3.6.egg/svtplay_dl/utils/http.py/request: HTTP getting '?cc1=name=Svenska~default=yes~forced=no~lang=sv~uri=https%3A%2F%2Fsubstitch.viafree.tv%2Fsubtitle%2Fconvert%2Fvtt%3Fsource%3Dhttps%3A%2F%2Fcdn-subtitles-mtgx-tv.akamaized.net%2Fpitcher%2FV3xxxx%2FV347xx%2FV34715%2F9370003500%2FV34715_sv.vtt%26output%3Dm3u8'
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==2.4+29.gc59a305', 'svtplay-dl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+29.gc59a305-py3.6.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+29.gc59a305-py3.6.egg/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+29.gc59a305-py3.6.egg/svtplay_dl/utils/getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+29.gc59a305-py3.6.egg/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
    for i in streams:
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+29.gc59a305-py3.6.egg/svtplay_dl/service/viaplay.py", line 199, in get
    streams = hlsparse(self.config, self.http.request("get", streamj["streams"]["hls"]), streamj["streams"]["hls"], output=self.output)
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+29.gc59a305-py3.6.egg/svtplay_dl/utils/http.py", line 39, in request
    res = Session.request(self, method, url, verify=self.verify, proxies=self.proxy, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 506, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 449, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3/dist-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '?cc1=name=Svenska~default=yes~forced=no~lang=sv~uri=https%3A%2F%2Fsubstitch.viafree.tv%2Fsubtitle%2Fconvert%2Fvtt%3Fsource%3Dhttps%3A%2F%2Fcdn-subtitles-mtgx-tv.akamaized.net%2Fpitcher%2FV3xxxx%2FV347xx%2FV34715%2F9370003500%2FV34715_sv.vtt%26output%3Dm3u8': No schema supplied. Perhaps you meant http://?cc1=name=Svenska~default=yes~forced=no~lang=sv~uri=https%3A%2F%2Fsubstitch.viafree.tv%2Fsubtitle%2Fconvert%2Fvtt%3Fsource%3Dhttps%3A%2F%2Fcdn-subtitles-mtgx-tv.akamaized.net%2Fpitcher%2FV3xxxx%2FV347xx%2FV34715%2F9370003500%2FV34715_sv.vtt%26output%3Dm3u8?

**Comment by Sopor** [comment]
Seems to be the same in 2.4+31.g25d3105
