### ISSUE TITLE
ModuleNotFoundError: No module named '_cffi_backend'

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1225]
This is what i get when i run my home compiled version and tried to download from viafree. It crash after the first block as you can see below.

If i go back to svtplay-dl 2.4+31.g25d3105 it seems to work, but not if i'm running latest master that i compiled with that patched cx_Freeze.

```
svtplay-dl.exe https://www.viafree.se/program/drama/navy-ncis/sasong-17/avsnitt-10
INFO: Outfile: navy-ncis.s17e10-1014618-viaplay.srt
INFO: Selected to download hls, bitrate: 1878
INFO: Outfile: navy-ncis.s17e10-1014618-viaplay.ts
[001/251][................................................................................] ETA: 0:00:00
Traceback (most recent call last):
  File "c:\users\<user>\appdata\local\programs\python\python37\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run module.run()
  File "c:\users\<user>\appdata\local\programs\python\python37\lib\site packages\cx_Freeze\initscripts\Console.py", line 37, in run exec(code, {'__name__': '__main__'})
  File "bin/svtplay-dl", line 7, in <module>
  File "d:\on_going_project\svtplay-dl_install\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main get_media(urls[0], config, __version__)
  File "d:\on_going_project\svtplay-dl_install\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media get_one_media(stream)
  File "d:\on_going_project\svtplay-dl_install\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 214, in get_one_media fstream.download()
  File "d:\on_going_project\svtplay-dl_install\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 149, in download self._download(self.url, file_name=(self.output, "ts"))
  File "d:\on_going_project\svtplay-dl_install\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 205, in _download backend = default_backend()
  File "c:\users\<user>\appdata\local\programs\python\python37\lib\site-packages\cryptography\hazmat\backends\__init__.py", line 15, in default_backend from cryptography.hazmat.backends.openssl.backend import backend
  File "c:\users\<user>\appdata\local\programs\python\python37\lib\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 7, in <module> from cryptography.hazmat.backends.openssl.backend import backend
  File "c:\users\<user>\appdata\local\programs\python\python37\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 16, in <module> from cryptography import utils, x509
  File "c:\users\<user>\appdata\local\programs\python\python37\lib\site-packages\cryptography\x509\__init__.py", line 8, in <module> from cryptography.x509.base import (
  File "c:\users\<user>\appdata\local\programs\python\python37\lib\site-packages\cryptography\x509\base.py", line 18, in <module> from cryptography.x509.extensions import Extension, ExtensionType
  File "c:\users\<user>\appdata\local\programs\python\python37\lib\site-packages\cryptography\x509\extensions.py", line 20, in <module> from cryptography.hazmat.primitives import constant_time, serialization
  File "c:\users\<user>\appdata\local\programs\python\python37\lib\site-packages\cryptography\hazmat\primitives\constant_time.py", line 11, in <module> from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named '_cffi_backend'
```

**Comment by spaam** [comment]
can you test latest snapshot and see if it works?

**Comment by Sopor** [comment]
No, still the same `ModuleNotFoundError: No module named '_cffi_backend'` :(

**Comment by Sopor** [comment]
Btw, even if i run `python3 setversion.py` i get a weird version number `2.4-6-gce9bfd3` when i compile it in Windows.

**Comment by spaam** [comment]
did you pull the latest changes from git?  `git pull --rebase`  . it looks like your checkout is behind a bunch of commits.

**Comment by Sopor** [comment]
Do i need to do a `--rebase` too?

**Comment by spaam** [comment]
Did you commit something? If so yes.
If no, no you dont need rebase

**Comment by Sopor** [comment]
If i do a
`git reset --hard` it will show
`HEAD is now at 800d406 Add cx-freeze as deps` and that is the latest commit

**Comment by Sopor** [comment]
The commande `python3 setversion.py`, what file will it write the version to?

**Comment by Sopor** [comment]
If i check my `c:\Users\Sopor\AppData\Local\Programs\Python\Python37\Scripts\` folder i will find a svtplay-dl file with the following text:
```
#!c:\users\sopor\appdata\local\programs\python\python37\python.exe
# EASY-INSTALL-DEV-SCRIPT: 'svtplay-dl==2.4+34.g800d406.dirty','svtplay-dl'
__requires__ = 'svtplay-dl==2.4+34.g800d406.dirty'
__import__('pkg_resources').require('svtplay-dl==2.4+34.g800d406.dirty')
__file__ = 'D:\\On_going_project\\svtplay-dl_install\\svtplay-dl\\bin\\svtplay-dl'
with open(__file__) as f:
    exec(compile(f.read(), __file__, 'exec'))
```

**Comment by Sopor** [comment]
Now it will show `svtplay-dl 0+unknown`

**Comment by Sopor** [comment]
Now i got it to work `svtplay-dl 2.4-34-g800d406` and i found why it didn't worked before. Instead of running `python3 setversion.py`, i need to run `python setversion.py`.

I can't test it on viafree anymore if the `cffi_backend' is fixed because all the video url's will now show the same message `ERROR: No videos found.`

**Comment by Sopor** [comment]
It seems that this message is back when i run svtplay-dl 2.7-3-ga550bd1, but if i run svtplay-dl 2.7 i don't get this error message. I don't know if the issue is my homemade compiled version or if it is the master. I didn't manage to find any snapshot of my build only [this](https://svtplay-dl.se/download/snapshots/20201102_220856) but when i run version i get `svtplay-dl ef557cb` and this version will also work.

`svtplay-dl.exe -A https://www.viafree.se/program/dokumentar/mythbusters/sasong-4`

```
Traceback (most recent call last):
  File "c:\users\abbe\appdata\local\programs\python\python37\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "c:\users\abbe\appdata\local\programs\python\python37\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "bin/svtplay-dl", line 7, in <module>
  File "d:\on_going_project\svtplay-dl_install\svtplay-dl\lib\svtplay_dl\__init__.py", line 66, in main
    get_media(urls[0], config, __version__)
  File "d:\on_going_project\svtplay-dl_install\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 59, in get_media
    get_all_episodes(stream, url, options)
  File "d:\on_going_project\svtplay-dl_install\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 91, in get_all_episodes
    get_one_media(substream)
  File "d:\on_going_project\svtplay-dl_install\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 214, in get_one_media
    fstream.download()
  File "d:\on_going_project\svtplay-dl_install\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 164, in download
    self._download(self.url, file_name=(self.output, "ts"))
  File "d:\on_going_project\svtplay-dl_install\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 220, in _download
    backend = default_backend()
  File "c:\users\xxxx\appdata\local\programs\python\python37\lib\site-packages\cryptography\hazmat\backends\__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "c:\users\xxxx\appdata\local\programs\python\python37\lib\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "c:\users\xxxx\appdata\local\programs\python\python37\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 16, in <module>
    from cryptography import utils, x509
  File "c:\users\xxxx\appdata\local\programs\python\python37\lib\site-packages\cryptography\x509\__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "c:\users\xxxx\appdata\local\programs\python\python37\lib\site-packages\cryptography\x509\base.py", line 18, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "c:\users\xxxx\appdata\local\programs\python\python37\lib\site-packages\cryptography\x509\extensions.py", line 20, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "c:\users\xxxx\appdata\local\programs\python\python37\lib\site-packages\cryptography\hazmat\primitives\constant_time.py", line 11, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named '_cffi_backend'
```

**Comment by spaam** [comment]
what version of cx_freeze do you have?

**Comment by Sopor** [comment]
It seems to be 6.2 and i have now updated to 6.3. I will try again and see if it is working now.

**Comment by spaam** [comment]
i guess you are using `python setup.py build_exe` to geneate the .exe?

**Comment by Sopor** [comment]
5 ⭐ to @spaam. It is working now ...

I'm running:
```
pip install -e .
python setversion.py
c:\Users\xxxx\AppData\Local\Programs\Python\Python37\Scripts\cxfreeze.exe --include-modules=queue,idna.idnadata --target-dir=build bin/svtplay-dl
```

Btw, how do i compile a 32-bits version?

**Comment by spaam** [comment]
you need to use a 32bit version of python to do it

**Comment by Sopor** [comment]
It was so easy, thanks!

> i guess you are using `python setup.py build_exe` to generate the .exe?

Do i compile it wrong?

**Comment by spaam** [comment]
No. its just another way to do it. that is how i do it now  :)

**Comment by Sopor** [comment]
So if i use `python setup.py build_exe` i don't need to run the other commands first?

**Comment by spaam** [comment]
`python setversion.py` im not sure. i have not yet tried it yet. i hopefully do that later today.

**Comment by Sopor** [comment]
Maybe that is why the snapshot has a weird version number because you are not running `python setversion.py`?

**Comment by spaam** [comment]
the weird version number is the git hash it was built because `gitlab actions` that i use to built the stuff nowdays, is doing a shallow clone by default. it means basically that it use latest commit and dont fetch any tags at all. so the `git describe` command dont know what version it is so it will use the git hash instead.  i have fix for that and will commit it later today :)

**Comment by Sopor** [comment]
Sounds great 👍
