### ISSUE TITLE
Error downloading from CMore

### ISSUE THREAD

**Issue by jby** [spaam/svtplay-dl#1232]
### svtplay-dl versions:

svtplay-dl --version
svtplay-dl 2.4

### Operating system and Python version:

Name and version of the operating system and python version (run `python --version`)
macOS 10.15.4 Python 2.7.16 & Synology Linux Python 2.7.12 (same issue in both systems)
### What is the issue:
svtplay-dl --verbose --cmore-operator cmore -u USERNAME -p PASSWORD https://www.cmore.se/film/12502524-hamilton-men-inte-om-det-galler-din-dotter   11.1s  Fri Apr 24 22:03:55 2020
DEBUG [1587758649.474665] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.4
DEBUG [1587758649.475358] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/svtplay_dl/service/__init__.py/__init__: service: cmore
DEBUG [1587758649.475449] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.cmore.se/film/12502524-hamilton-men-inte-om-det-galler-din-dotter'
DEBUG [1587758649.481879] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.cmore.se:443
DEBUG [1587758649.549963] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_make_request: https://www.cmore.se:443 "GET /film/12502524-hamilton-men-inte-om-det-galler-din-dotter HTTP/1.1" 200 None
DEBUG [1587758649.55377] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.cmore.se/login'
DEBUG [1587758649.6546261] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_make_request: https://www.cmore.se:443 "GET /login HTTP/1.1" 200 None
DEBUG [1587758649.655274] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://account.cmore.se/session?client=cmore-web-prod'
DEBUG [1587758649.6568692] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): account.cmore.se:443
DEBUG [1587758649.658113] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/session?client=cmore-web-prod'): Retry(total=4, connect=4, read=5, redirect=None, status=None)
WARNING [1587758649.658276] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/urlopen: Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109dba9d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session?client=cmore-web-prod
DEBUG [1587758649.65847] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (2): account.cmore.se:443
DEBUG [1587758649.659542] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/session?client=cmore-web-prod'): Retry(total=3, connect=3, read=5, redirect=None, status=None)
WARNING [1587758650.2606862] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/urlopen: Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109dbae80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session?client=cmore-web-prod
DEBUG [1587758650.2611551] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (3): account.cmore.se:443
DEBUG [1587758650.2645319] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/session?client=cmore-web-prod'): Retry(total=2, connect=2, read=5, redirect=None, status=None)
WARNING [1587758651.468997] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/urlopen: Retrying (Retry(total=2, connect=2, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109de8040>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session?client=cmore-web-prod
DEBUG [1587758651.469456] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (4): account.cmore.se:443
DEBUG [1587758651.471492] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/session?client=cmore-web-prod'): Retry(total=1, connect=1, read=5, redirect=None, status=None)
WARNING [1587758653.872355] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/urlopen: Retrying (Retry(total=1, connect=1, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109de8190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session?client=cmore-web-prod
DEBUG [1587758653.8729658] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (5): account.cmore.se:443
DEBUG [1587758653.875975] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/session?client=cmore-web-prod'): Retry(total=0, connect=0, read=5, redirect=None, status=None)
WARNING [1587758658.6815832] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/urlopen: Retrying (Retry(total=0, connect=0, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109de82b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /session?client=cmore-web-prod
DEBUG [1587758658.682086] /usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (6): account.cmore.se:443
Traceback (most recent call last):
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x109de83d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='account.cmore.se', port=443): Max retries exceeded with url: /session?client=cmore-web-prod (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109de83d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/svtplay_dl/utils/getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/svtplay_dl/service/cmore.py", line 22, in get
    token, message = self._login()
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/svtplay_dl/service/cmore.py", line 99, in _login
    res = self.http.post("https://account.cmore.{}/session?client=cmore-web-prod".format(tld), json=post, cookies=self.cookies)
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/svtplay_dl/utils/http.py", line 39, in request
    res = Session.request(self, method, url, verify=self.verify, proxies=self.proxy, *args, **kwargs)
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/svtplay-dl/2.4_3/libexec/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='account.cmore.se', port=443): Max retries exceeded with url: /session?client=cmore-web-prod (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109de83d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

**Comment by carlrygart** [comment]
Duplicate of https://github.com/spaam/svtplay-dl/issues/1174

Tips: If you want that specific content it's currently available on tv4play.se.

**Comment by jby** [comment]
> Duplicate of #1174
> 
> Tips: If you want that specific content it's currently available on tv4play.se.

Apparently not:

```
INFO: Url: https://www.tv4play.se/program/hamilton-2-men-inte-om-det-gäller-din-dotter/2629839
ERROR: No videos found. We can't download DRM protected content from this site.
```

**Comment by carlrygart** [comment]
I see! It looks like TV4Play has started to DRM protect new content as well.
