### ISSUE TITLE
ValueError: time data '2020-08-23T00:00:00Z' does not match format '%Y-%m-%dT%H:%M:%S%z'

### ISSUE THREAD

**Issue by AliensInc** [spaam/svtplay-dl#1245]
### svtplay-dl versions:
svtplay-dl 2.4-2-g5466853

### Operating system and Python version:
Right now on Win10_x64-2004 - 19041.450)
python35.dll has info:
File version: 3.5.4150.1013
Product version: 3.5.4

### What is the issue:
svtplay-dl.exe --verbose -P hls https://www.svtplay.se/video/27889331/vetenskapens-varld/vetenskapens-varld-sasong-33-resan-till-livets-karna-bilden-av-ett-dodligt-virus
DEBUG [1598300252.2830472] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.4-2-g5466853
DEBUG [1598300252.2850025] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1598300252.2860065] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/27889331/vetenskapens-varld/vetenskapens-varld-sasong-33-resan-till-livets-karna-bilden-av-ett-dodligt-virus'
DEBUG [1598300252.2910578] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1598300253.3242419] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/27889331/vetenskapens-varld/vetenskapens-varld-sasong-33-resan-till-livets-karna-bilden-av-ett-dodligt-virus HTTP/1.1" 200 42794
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 78, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 315, in extrametadata
  File "C:\Python35\lib\_strptime.py", line 510, in _strptime_datetime
  File "C:\Python35\lib\_strptime.py", line 343, in _strptime
ValueError: time data '2020-08-23T00:00:00Z' does not match format '%Y-%m-%dT%H:%M:%S%z'

**Comment by spaam** [comment]
can you try latest snapshot to see if it works https://svtplay-dl.se/download/snapshots/20200602_154130/ ?

**Comment by AliensInc** [comment]
Well the issue is that after about 15 minutes I _could_ download it as the all other same error I had with this version.
So it's not an error per say as the download worked 15 mins later.
I think it's weird and I can put my finger on what it can be.

Ooooh, I see. My information about this is gone in here :( I'm sure I wrote about it though.
Ah well as I said above, it worked after about 15 mins later.

**Comment by spaam** [comment]
closing this. open a new if it crash with latest version
