### ISSUE TITLE
Crash on dplay.se

### ISSUE THREAD

**Issue by casper** [spaam/svtplay-dl#1256]
### svtplay-dl versions:
svtplay-dl 2.5+7.g7db9f7e

### Operating system and Python version:
Linux CentOS 7
Python 3.6.8

### What is the issue:
Using the instructions for dplay.se from #1069 I run the following command line:

svtplay-dl --verbose --cookies st=$COOKIE https://www.dplay.se/program/sodertaljepolisen/97917

### Result
```
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==2.5+7.g7db9f7e', 'svtplay-dl')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1434, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/svtplay_dl-2.5+7.g7db9f7e-py3.6.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.6/site-packages/svtplay_dl-2.5+7.g7db9f7e-py3.6.egg/svtplay_dl/__init__.py", line 66, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.6/site-packages/svtplay_dl-2.5+7.g7db9f7e-py3.6.egg/svtplay_dl/utils/getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "/usr/local/lib/python3.6/site-packages/svtplay_dl-2.5+7.g7db9f7e-py3.6.egg/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
    for i in streams:
  File "/usr/local/lib/python3.6/site-packages/svtplay_dl-2.5+7.g7db9f7e-py3.6.egg/svtplay_dl/service/dplay.py", line 41, in get
    path = "/shows/{}".format(match.group(2))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by casper** [comment]
Never mind. The URL needed to be changed to videos instead of programs. It works now!
