### ISSUE TITLE
svtplay download all episodes broken (-A)

### ISSUE THREAD

**Issue by tubalainen** [spaam/svtplay-dl#1257]
Hi!

Tried under Windows 10 and under Debian Linux with the same result and issue.

Cannot get -A to work any longer.

Rolled back to 2.4-29-gc59a305 and that did not work either - I guess SVT done something.... :/

```
root@docker04:/mnt/usbdisk01/share/media/barn/Annat/Andys forhistoriska aventyr# svtplay-dl --version
svtplay-dl 2.5
root@docker04:/mnt/usbdisk01/share/media/barn/Annat/Andys forhistoriska aventyr# python3 --version
Python 3.5.3
root@docker04:/mnt/usbdisk01/share/media/barn/Annat/Andys forhistoriska aventyr# svtplay-dl -A -v https://www.svtplay.se/andys-forhistoriska-aventyr
DEBUG [1601490057.889138] /usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.5
DEBUG [1601490057.8905528] /usr/lib/python3/dist-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1601490057.8909993] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/andys-forhistoriska-aventyr'
DEBUG [1601490057.8993852] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se
DEBUG [1601490058.5504923] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /andys-forhistoriska-aventyr HTTP/1.1" 200 32010
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3/dist-packages/svtplay_dl/__init__.py", line 66, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 59, in get_media
    get_all_episodes(stream, url, options)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 77, in get_all_episodes
    episodes = stream.find_all_episodes(stream.config)
  File "/usr/lib/python3/dist-packages/svtplay_dl/service/svtplay.py", line 220, in find_all_episodes
    for n in janson[i]["items"]:
KeyError: 'items'
```

**Comment by spaam** [comment]
yep it crashed on other videos too :D

**Comment by tubalainen** [comment]
> yep it crashed on other videos too :D

Bummer :/
Have your identified the issue/bug? Is there anything more I can do to help?

**Comment by spaam** [comment]
i have found the issue and fixed it on my computer.  will check a bunch of videos if its correct or not :)

**Comment by spaam** [comment]
i pused a fix . will release 2.6 with the fix in ~1h
