### ISSUE TITLE
All episodes switch (-A) doesn't work for Dplay

### ISSUE THREAD

**Issue by RandAlThor82** [spaam/svtplay-dl#1258]
I am unable to download all episodes using the following command line:
svtplay-dl -A --cookies st=mycookie https://www.dplay.se/program/estonia-fyndet-som-andrar-allt
Of course, substitute the "mycookie" with the value for your st cookie.

I get errors as follows:

Traceback (most recent call last):                                                                                      
  File "C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in
 run                                                                                                                    
  File "C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 33, in run
  File "bin/svtplay-dl", line 7, in <module>                                                                            
  File "D:\a\svtplay-dl\svtplay-dl\lib/svtplay_dl\__init__.py", line 66, in main                                        
  File "D:\a\svtplay-dl\svtplay-dl\lib/svtplay_dl\utils\getmedia.py", line 59, in get_media                             
  File "D:\a\svtplay-dl\svtplay-dl\lib/svtplay_dl\utils\getmedia.py", line 77, in get_all_episodes                      
  File "D:\a\svtplay-dl\svtplay-dl\lib/svtplay_dl\service\dplay.py", line 154, in find_all_episodes                     
KeyError: 'data'                                                                                                         

What can I try? I haven't found a way to determine the URLs for the individual episodes. And, if I run without the -A command, I get only episode 3 (not 1?).

**Comment by granbom** [comment]
Check out this issue #1069 

(In short; get video ID from XHR data, and change "program" to "videos")
So URL for Episode one will be:
https://www.dplay.se/videos/estonia-fyndet-som-andrar-allt/165853
The IDs for the other episodes are:
E02: 165851
E03: 165855
E04: 165852
E05: 165854
