### ISSUE TITLE
Problem with svtplay-dl on urplay.se

### ISSUE THREAD

**Issue by EmmW** [spaam/svtplay-dl#1259]
### svtplay-dl versions:

svtplay-dl 2.4-26-g5dcc899

### Operating system and Python version:

Mac OS 10.14.6 and Python 2.7.17

### What is the issue:

I get the following error when I try to download from urplay.se:

svtplay-dl https://urplay.se/program/214606-kanaler-batar-och-karlek-brittiska-och-irlandska-strapatser -S --remux --verbose
DEBUG [1602032062.400931] /Library/Frameworks/Python.framework/Versions/3.5/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 2.4-26-g5dcc899
DEBUG [1602032062.403197] /Library/Frameworks/Python.framework/Versions/3.5/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: urplay
DEBUG [1602032062.403308] /Library/Frameworks/Python.framework/Versions/3.5/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://urplay.se/program/214606-kanaler-batar-och-karlek-brittiska-och-irlandska-strapatser'
DEBUG [1602032062.418593] /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): urplay.se
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 376, in wrap_socket
    _context=self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 747, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 630, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/svtplay-dl/svtplay_dl/__init__.py", line 69, in main
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 61, in get_media
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 96, in get_one_media
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/svtplay-dl/svtplay_dl/utils/output.py", line 121, in filename
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/svtplay-dl/svtplay_dl/service/__init__.py", line 63, in get_urldata
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/svtplay-dl/svtplay_dl/utils/http.py", line 39, in request
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:645)

Please let me know if this is something I can remedy myself, or if there is an upgrade coming that will fix this issue -- thanks,
Mark

**Comment by pythonuser3856** [comment]
I get the same failure using the new version 2.6 and when trying the same URplay-link.

What I notice as a change in the URplay-website is that FireFox does not load its internal video player unless you allow JavaScript from jwpcdn.com to execute. A use of jwpcdn.com is a new behavior by URplay.se.
( I just point it out as a website-change and don't know if it's related to the issue )

**Comment by bohelax** [comment]
Here is another variation.
It does not work even for cases that worked a few days ago.
Luckily UR Play's programs tend to be available for a long time.
//BoH
bin>timer
Timer 4.0 - Command Line Timer - www.Gammadyne.com
Copyright (C) 2007-2017 by Greg Wittmeyer - All Rights Reserved
Timer started: 2020-10-7 15:52:32

bin>ver

Microsoft Windows [Version 10.0.18363.1110]

bin>svtplay-dl.exe --version
svtplay-dl 2.4-42-g916e199

bin>svtplay-dl.exe -S -M https://urplay.se/program/214631-nixon-och-skandalerna-
nixons-fall
ERROR: No videos found. Can't find json info
1.8 seconds

bin>svtplay-dl.exe -S -M https://urplay.se/program/214631-nixon-och-skandalerna-
nixons-fall --verbose
DEBUG [1602078754.7561374] C:\projects\svtplay-dl\lib/svtplay_dl\utils\getmedia.
py/get_media: version: 2.4-42-g916e199
DEBUG [1602078754.7561374] C:\projects\svtplay-dl\lib/svtplay_dl\service\__init_
_.py/__init__: service: urplay
DEBUG [1602078754.7561374] C:\projects\svtplay-dl\lib/svtplay_dl\utils\http.py/r
equest: HTTP getting 'https://urplay.se/program/214631-nixon-och-skandalerna-nix
ons-fall'
DEBUG [1602078754.7717643] C:\Python37\lib\site-packages\urllib3\connectionpool.
py/_new_conn: Starting new HTTPS connection (1): urplay.se:443
DEBUG [1602078754.8811302] C:\Python37\lib\site-packages\urllib3\connectionpool.
py/_make_request: https://urplay.se:443 "GET /program/214631-nixon-och-skandaler
na-nixons-fall HTTP/1.1" 200 40533
ERROR [1602078754.896757] C:\projects\svtplay-dl\lib/svtplay_dl\utils\getmedia.p
y/get_one_media: No videos found. Can't find json info
859 milliseconds
bin>

**Comment by pythonuser3856** [comment]
Tip:
Until a fix becomes available; see issue #1246 about obtaining a stream-copy of a wanted title that's broadcast by SVTplay channels such as "Kunskapskanalen".

**Comment by spaam** [comment]
i have commited a fix for this, it will be in 2.6 release tomorrow sunday.

**Comment by bohelax** [comment]
Thanks a lot spaam, works fine for me now!
//BoH

**Comment by EmmW** [comment]
Would either of you guys be so kind as to look into #1236 and see if you can help me sort out how to get the latest version 2.7 (seemingly properly installed via brew) activated instead of the old 2.4, which somehow still is the active version? Thanks :-)

**Comment by bohelax** [comment]
Hi spaam!

I'm writing this to you, rather than posting it on GitHub, since it may be a bit peculiar.

Now that you've got UR Play working again, I notice a difference:

Before the transport stream (.ts -> .mp4) apparently did not contain 'hard-coded' subtitles (i.e. not 'burned' into the video).
I therefore used svtplay-dl options -S -M, allowing me to choose when to display subtitles when playing.
This I considered a nice feature.

Now the videos are 'hard-coded' with subtitles.

Maybe it is unavoidable in the new scheme of things, and if so I just have to live with it.

As someone not capable of contributing actively in projects such as this one, I just want to thank you so much for your the effort you put into svtplay-dl (which by now have gone far beyond SVT Play and UR Play).

//BoH
     On Saturday, October 10, 2020, 01:21:53 PM GMT+2, Johan Andersson <notifications@github.com> wrote:  
 
 


i have commited a fix for this, it will be in 2.6 release tomorrow sunday.

**Comment by EmmW** [comment]
I notice that this thread was closed, but I couldn't find another thread that dealt with the same issue, so I thought I would try to follow up and let the developers know that even the most recent version of svtplay-dl (2.7+3.ga550bd1) -- which I just managed to install with kind help from Sopor -- still doesn't resolve the problem with downloading from urplay.se. I just wrote the following (after having made sure I was up to date on everything through "brew update && brew upgrade"):

"svtplay-dl https://urplay.se/program/214583-kanaler-batar-och-karlek-aventyr-over-hela-varlden -S --remux"

...and got the following error message:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 376, in wrap_socket
    _context=self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 747, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 630, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==2.7+3.ga550bd1', 'svtplay-dl')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/svtplay_dl-2.7+3.ga550bd1-py3.5.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/svtplay_dl-2.7+3.ga550bd1-py3.5.egg/svtplay_dl/__init__.py", line 66, in main
    get_media(urls[0], config, __version__)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/svtplay_dl-2.7+3.ga550bd1-py3.5.egg/svtplay_dl/utils/getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/svtplay_dl-2.7+3.ga550bd1-py3.5.egg/svtplay_dl/utils/getmedia.py", line 96, in get_one_media
    if not filename(stream):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/svtplay_dl-2.7+3.ga550bd1-py3.5.egg/svtplay_dl/utils/output.py", line 119, in filename
    data = ensure_unicode(stream.get_urldata())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/svtplay_dl-2.7+3.ga550bd1-py3.5.egg/svtplay_dl/service/__init__.py", line 61, in get_urldata
    self._urldata = self.http.request("get", self.url).text
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/svtplay_dl-2.7+3.ga550bd1-py3.5.egg/svtplay_dl/utils/http.py", line 41, in request
    res = Session.request(self, method, url, verify=self.verify, proxies=self.proxy, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:645)

On a side-note, using youtube-dl (version ) doesn't work either:

"youtube-dl https://urplay.se/program/214583-kanaler-batar-och-karlek-aventyr-over-hela-varlden --all-subs"

...gives:

[URPlay] 214583: Downloading webpage
ERROR: Unable to extract urplayer data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

(I'll report the youtube-dl problem on the youtube-dl site, just thought I'd mention it as it seems there is something fundamentally different with the urplay-dl site -- which worked fine about a week ago.)

**Comment by pythonuser3856** [comment]
Hi,

A comment to the statement "Now the videos are 'hard-coded' with subtitles." from BoH:
It works for me, i.e. I get external .srt files and no sub hard-coding.

I'm using an installation of python 3.7.4 in MS Windows 8.1 to execute snapshot-version 201010_113044 of svtplay-dl. To this I'm using ffmpeg 4.1.3.
I've not tested later versions av svtplay-dl since this snapshot-version does the trick for me.

/L-B

**Comment by pythonuser3856** [comment]
Hi,
I installed and ran v2.7 and now I get hardcoded subs and no .srt-file.
/L-B

**Comment by pythonuser3856** [comment]
A later snapshot version 20201012_173206 equally fails to produce a separate.srt file.
My conclusion:
Something was altered between the two snapshot-version which inhibit generation of external subtitles.
/L-B

**Comment by spaam** [comment]
@pythonuser3856 this is a closed issue. please open a new ticket if you feels its an issue with latest snapshot. please include the right info for it. what arguments you use, what video it was. what you expected to happen.
