### ISSUE TITLE
svtplay problem

### ISSUE THREAD

**Issue by dentarg** [spaam/svtplay-dl#126]
```sh
$ svtplay-dl http://www.svtplay.se/video/2278473/val-2014-utfragningen-stefan-lofven-s                                                                                         dentarg@proalu ~/Downloads
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 231, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 91, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 134, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/hls.py", line 63, in download
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/hls.py", line 130, in parsem3u
ValueError: dictionary update sequence element #0 has length 1; 2 is required

$ svtplay-dl -P hds http://www.svtplay.se/video/2278473/val-2014-utfragningen-stefan-lofven-s                                                                                  dentarg@proalu ~/Downloads
INFO: Outfile: val-2014-val-2014-utfragningen-stefan-lofven-s-2278473-svtplay.flv
[0256/1049][========================================...............................................................................................................................] ETA: 0:06:08ERROR: So
mething wrong with that url
ERROR: Error code: 404

$ svtplay-dl --version                                                                                                                                                         dentarg@proalu ~/Downloads
0.9.2014.08.28
```

**Comment by dentarg** [comment]
So old, I hope this has been fixed... :)
