### ISSUE TITLE
svtplay-dl crashed

### ISSUE THREAD

**Issue by liquidbydesign** [spaam/svtplay-dl#1260]
### svtplay-dl versions:

svtplay-dl 2.6

### Operating system and Python version:

Windows 10

### What is the issue:

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

svtplay-dl.exe --verbose -S --cookies st=#MY_COOKIE# https://www.dplay.se/videos/the-big-bang-theory/big-bang-theory-the
DEBUG [1602265491.2716908] D:\a\svtplay-dl\svtplay-dl\lib/svtplay_dl\utils\getmedia.py/get_media: version: 2.6
DEBUG [1602265491.2716908] D:\a\svtplay-dl\svtplay-dl\lib/svtplay_dl\service\__init__.py/__init__: service: dplay
DEBUG [1602265491.2716908] D:\a\svtplay-dl\svtplay-dl\lib/svtplay_dl\utils\http.py/request: HTTP getting 'https://www.dplay.se/videos/the-big-bang-theory/big-bang-theory-the'
DEBUG [1602265491.2716908] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.dplay.se:443
DEBUG [1602265491.4279003] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.dplay.se:443 "GET /videos/the-big-bang-theory/big-bang-theory-the HTTP/1.1" 200 None
DEBUG [1602265491.4279003] D:\a\svtplay-dl\svtplay-dl\lib/svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-api.dplay.se/token?realm=dplayse&deviceId=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855&shortlived=true'
DEBUG [1602265491.4279003] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): disco-api.dplay.se:443
DEBUG [1602265491.6779308] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.dplay.se:443 "GET /token?realm=dplayse&deviceId=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855&shortlived=true HTTP/1.1" 200 None
DEBUG [1602265491.6779308] D:\a\svtplay-dl\svtplay-dl\lib/svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-api.dplay.se/users/me'
DEBUG [1602265491.7403295] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.dplay.se:443 "GET /users/me HTTP/1.1" 200 None
DEBUG [1602265491.7403295] D:\a\svtplay-dl\svtplay-dl\lib/svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-api.dplay.se/content/videos/the-big-bang-theory/big-bang-theory-the'
DEBUG [1602265491.8028784] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.dplay.se:443 "GET /content/videos/the-big-bang-theory/big-bang-theory-the HTTP/1.1" 200 None
DEBUG [1602265491.8028784] D:\a\svtplay-dl\svtplay-dl\lib/svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-api.dplay.se/playback/videoPlaybackInfo/34513'
DEBUG [1602265492.493381] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.dplay.se:443 "GET /playback/videoPlaybackInfo/34513 HTTP/1.1" 500 None
DEBUG [1602265492.493381] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/playback/videoPlaybackInfo/34513'): Retry(total=4, connect=5, read=5, redirect=None, status=None)
DEBUG [1602265492.493381] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /playback/videoPlaybackInfo/34513
DEBUG [1602265492.931259] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.dplay.se:443 "GET /playback/videoPlaybackInfo/34513 HTTP/1.1" 500 None
DEBUG [1602265492.931259] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/playback/videoPlaybackInfo/34513'): Retry(total=3, connect=5, read=5, redirect=None, status=None)
DEBUG [1602265493.5313637] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /playback/videoPlaybackInfo/34513
DEBUG [1602265493.8991237] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.dplay.se:443 "GET /playback/videoPlaybackInfo/34513 HTTP/1.1" 500 None
DEBUG [1602265493.9005332] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/playback/videoPlaybackInfo/34513'): Retry(total=2, connect=5, read=5, redirect=None, status=None)
DEBUG [1602265495.1074996] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /playback/videoPlaybackInfo/34513
DEBUG [1602265495.5128758] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.dplay.se:443 "GET /playback/videoPlaybackInfo/34513 HTTP/1.1" 500 None
DEBUG [1602265495.5128758] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/playback/videoPlaybackInfo/34513'): Retry(total=1, connect=5, read=5, redirect=None, status=None)
DEBUG [1602265497.918688] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /playback/videoPlaybackInfo/34513
DEBUG [1602265498.2741754] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.dplay.se:443 "GET /playback/videoPlaybackInfo/34513 HTTP/1.1" 500 None
DEBUG [1602265498.2741754] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/playback/videoPlaybackInfo/34513'): Retry(total=0, connect=5, read=5, redirect=None, status=None)
DEBUG [1602265503.0906854] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /playback/videoPlaybackInfo/34513
DEBUG [1602265503.5000968] C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.dplay.se:443 "GET /playback/videoPlaybackInfo/34513 HTTP/1.1" 500 None
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\requests\adapters.py", line 439, in send
  File "C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py", line 817, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py", line 817, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py", line 817, in urlopen
  [Previous line repeated 2 more times]
  File "C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\connectionpool.py", line 807, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\urllib3\util\retry.py", line 439, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='disco-api.dplay.se', port=443): Max retries exceeded with url: /playback/videoPlaybackInfo/34513 (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 33, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib/svtplay_dl\__init__.py", line 66, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib/svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib/svtplay_dl\utils\getmedia.py", line 111, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib/svtplay_dl\service\dplay.py", line 88, in get
  File "C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\requests\sessions.py", line 543, in get
  File "D:\a\svtplay-dl\svtplay-dl\lib/svtplay_dl\utils\http.py", line 41, in request
  File "C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\requests\sessions.py", line 530, in request
  File "C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\requests\sessions.py", line 643, in send
  File "C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\site-packages\requests\adapters.py", line 507, in send
requests.exceptions.RetryError: HTTPSConnectionPool(host='disco-api.dplay.se', port=443): Max retries exceeded with url: /playback/videoPlaybackInfo/34513 (Caused by ResponseError('too many 500 error responses'))

**Comment by spaam** [comment]
i see the error. missing something in the URL to get the actual video info.

but i have some bad news for you. after the fix, it will show you a message that video have DRM and fail to download the video.

**Comment by liquidbydesign** [comment]
Thank you for the answer. It seems like d-play has DRM on some of the episodes of season 11 and 12.
