### ISSUE TITLE
Öppet arkiv --all-episodes stopped working

### ISSUE THREAD

**Issue by augustjanse** [spaam/svtplay-dl#1271]
### svtplay-dl versions:
```
august@august-ThinkPad-T420:~/Downloads$ svtplay-dl --version
svtplay-dl 2.7
```

### Operating system and Python version:

```
august@august-ThinkPad-T420:~/Downloads$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
august@august-ThinkPad-T420:~/Downloads$ python --version
Python 3.8.5
```

### What is the issue:

Downloading videos from Öppet arkiv worked for me the other day, but not any longer. Not sure what changed.

```
august@august-ThinkPad-T420:~/Downloads$ svtplay-dl --all-episodes --verbose https://www.svtplay.se/bamse
DEBUG [1604340175.3378484] /usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.7
DEBUG [1604340175.3390446] /usr/lib/python3/dist-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1604340175.3394089] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/bamse'
DEBUG [1604340175.3408985] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1604340175.5390644] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /bamse HTTP/1.1" 200 33852
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3/dist-packages/svtplay_dl/__init__.py", line 66, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 59, in get_media
    get_all_episodes(stream, url, options)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 77, in get_all_episodes
    episodes = stream.find_all_episodes(stream.config)
  File "/usr/lib/python3/dist-packages/svtplay_dl/service/svtplay.py", line 220, in find_all_episodes
    for n in janson[i]['items({"filter":{"includeFullOppetArkiv":false}})']:
KeyError: 'items({"filter":{"includeFullOppetArkiv":false}})
'```

**Comment by spaam** [comment]
thanks for the bug report. i commited a fix for this. will release 2.8 tomorrow evening :)

**Comment by augustjanse** [comment]
That's quick, thanks!
