### ISSUE TITLE
The option "--all-episodes" fails at SVTplay.se

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#1272]
### What is the issue:
The option --all-episodes do no longer work with web-site svtplay.se
Here is an example trace from use of the python code version of svtplay-dl:

py "c:\svtplaydll\svtplay-dl_v2.7_2020-11-02_official" --verbose --all-episodes --subtitle 
https://www.svtplay.se/video/18556810/psl/guleed-tillbaka-med-under-tiden-2-avsnitt-52

DEBUG [1604418141.075487] c:\svtplaydll\svtplay-dl_v2.7_2020-11-02_official\svtplay_dl\utils\getmedia.py/get_media: version: -unknown
DEBUG [1604418141.0804877] c:\svtplaydll\svtplay-dl_v2.7_2020-11-02_official\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1604418141.0804877] c:\svtplaydll\svtplay-dl_v2.7_2020-11-02_official\svtplay_dl\util\http.py/request: HTTP getting 

'https://www.svtplay.se/video/18556810/psl/guleed-tillbaka-med-under-tiden-2-avsnitt-52'
DEBUG [1604418141.0804877] C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS 

connection (1): www.svtplay.se:443
DEBUG [1604418141.150516] C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: 

https://www.svtplay.se:443 "GET /video/18556810/psl/guleed-tillbaka-med-under-tiden-2-avsnitt-52 HTTP/1.1" 200 53618
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\svtplaydll\svtplay-dl_v2.7_2020-11-02_official\__main__.py", line 15, in <module>
  File "c:\svtplaydll\svtplay-dl_v2.7_2020-11-02_official\svtplay_dl\__init__.py", line 66, in main
  File "c:\svtplaydll\svtplay-dl_v2.7_2020-11-02_official\svtplay_dl\utils\getmedia.py", line 59, in get_media
  File "c:\svtplaydll\svtplay-dl_v2.7_2020-11-02_official\svtplay_dl\utils\getmedia.py", line 77, in get_all_episodes
  File "c:\svtplaydll\svtplay-dl_v2.7_2020-11-02_official\svtplay_dl\service\svtplay.py", line 220, in find_all_episodes
KeyError: 'items({"filter":{"includeFullOppetArkiv":false}})'

--------------------------------------------------------
The failing behaviour suddenly appeared a couple of days ago.
I waited to see if it was a temporary issue but for me the issue remains.

/L-B

**Comment by spaam** [comment]
this is fixed already in #1267  and will be fixed later today :)

**Comment by pythonuser3856** [comment]
Great to know, thanks !
/L-B
