### ISSUE TITLE
Unable to download "All Episode" from SVT play

### ISSUE THREAD

**Issue by gonzzor** [spaam/svtplay-dl#1274]
### svtplay-dl versions:
$ svtplay-dl --version
svtplay-dl 2.7

### Operating system and Python version:

Fedora 32, x86_64, python 3.8.6

### What is the issue:
```
$ svtplay-dl -v -A https://www.svtplay.se/alfons-aberg
DEBUG [1604515413.1962543] /home/jonas/.local/lib/python3.8/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.7
DEBUG [1604515413.1977608] /home/jonas/.local/lib/python3.8/site-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1604515413.198249] /home/jonas/.local/lib/python3.8/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/alfons-aberg'
DEBUG [1604515413.2002056] /home/jonas/.local/lib/python3.8/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1604515414.0620255] /home/jonas/.local/lib/python3.8/site-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /alfons-aberg HTTP/1.1" 200 40047
Traceback (most recent call last):
  File "/home/jonas/.local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/home/jonas/.local/lib/python3.8/site-packages/svtplay_dl/__init__.py", line 66, in main
    get_media(urls[0], config, __version__)
  File "/home/jonas/.local/lib/python3.8/site-packages/svtplay_dl/utils/getmedia.py", line 59, in get_media
    get_all_episodes(stream, url, options)
  File "/home/jonas/.local/lib/python3.8/site-packages/svtplay_dl/utils/getmedia.py", line 77, in get_all_episodes
    episodes = stream.find_all_episodes(stream.config)
  File "/home/jonas/.local/lib/python3.8/site-packages/svtplay_dl/service/svtplay.py", line 220, in find_all_episodes
    for n in janson[i]['items({"filter":{"includeFullOppetArkiv":false}})']:
KeyError: 'items({"filter":{"includeFullOppetArkiv":false}})'
```

**Comment by gonzzor** [comment]
It seems that the rss feed <link> has gotten an extra data-react-helmet="true" but that doesn't seem to be enough.
```diff
diff --git a/lib/svtplay_dl/service/svtplay.py b/lib/svtplay_dl/service/svtplay.py
index 7599bf7..4f86555 100644
--- a/lib/svtplay_dl/service/svtplay.py
+++ b/lib/svtplay_dl/service/svtplay.py
@@ -171,7 +171,7 @@ class Svtplay(Service, OpenGraphThumbMixin):
         if len(parse.path) > 7 and parse.path[-7:] == "rss.xml":
             rss_url = self.url
         else:
-            rss_url = re.search(r'<link rel="alternate" type="application/rss\+xml" [^>]*href="([^"]+)"', self.get_urldata())
+            rss_url = re.search(r'<link data-react-helmet="true" rel="alternate" type="application/rss\+xml" [^>]*href="([^"]+)"', self.get_urldata())
             if rss_url: 
                 rss_url = rss_url.group(1)
 
```

**Comment by pythonuser3856** [comment]
See issue #1272.
It's been addressed and is available as part of the latest snapshot version; I'm using it and it works for me.

**Comment by gonzzor** [comment]
@pythonuser3856 Thanks. It works for me now.
