### ISSUE TITLE
svtplay-dl==2.4+35.g81cb18f error message

### ISSUE THREAD

**Issue by fabfer** [spaam/svtplay-dl#1292]
Hello,

I'm having the following issue with svtplay-dl since I upgraded my Untuntu to 20.04.
Any help would be appreciated!

Thank you in advance,
Fabrizio

### svtplay-dl versions:

2.8

### Operating system and Python version:

Python 2.7.18

### What is the issue:

When I run svtplay-dl is now get the following error message:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (svtplay-dl 2.8 (/usr/lib/python3/dist-packages), Requirement.parse('svtplay-dl==2.4+35.g81cb18f'))
```

During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==2.4+35.g81cb18f', 'svtplay-dl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'svtplay-dl==2.4+35.g81cb18f' distribution was not found and is required by the application
```

**Comment by spaam** [comment]
it seems like you have two versions of the script installed for some reason.
How did you install it? what binary do you use?

**Comment by fabfer** [comment]
Hello,

I installed the script following your instructions for Ubuntu, through:

    sudo apt-get update
    sudo apt-get install svtplay-dl

**Comment by spaam** [comment]
it seems like you have another version installed too in `/usr/local/bin/svtplay-dl`  for example.  how did you install that?

**Comment by fabfer** [comment]
I didn't do anything else than using apt-get. Since I got the error above, I did apt-get purge and installed the script again from scratch. Apparently the purge didn't remove the old installation for some reason

**Comment by fabfer** [comment]
Hello,

I did some cleaning, and now it's working again. Thank you very much for explaining the problem!

**Comment by spaam** [comment]
woho, sound fantastic that the problem is fixed. good job <3
