### ISSUE TITLE
svt: broken audio with format h264-51 

### ISSUE THREAD

**Issue by ottob** [spaam/svtplay-dl#1301]
### svtplay-dl versions:

2.8

### Operating system and Python version:

macOS 11. Python 2.7.16

### What is the issue:
```
./svtplay-dl --format-preferred h264-51 https://www.svtplay.se/video/29402400/mud
INFO: Selected to download hls, bitrate: 3632 format: h264-51
INFO: Outfile: mud-250eb91-svtplay.audio.ts
[1946/1946][========================================] ETA: 0:00:00
INFO: Outfile: mud-250eb91-svtplay.ts
[1946/1946][========================================] ETA: 0:00:00
INFO: Merge audio and video into mud-250eb91-svtplay.ts
ERROR: Something went wrong: ffmpeg version N-97606-gaa6d32ae43-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 43.100 / 56. 43.100
  libavcodec     58. 82.100 / 58. 82.100
  libavformat    58. 42.102 / 58. 42.102
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 80.100 /  7. 80.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, mpegts, from 'mud-250eb91-svtplay.ts':
  Duration: 02:04:32.00, start: 0.100000, bitrate: 3184 kb/s
    Stream #0:0[0x50]: Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
mud-250eb91-svtplay.audio.ts: Invalid data found when processing input
INFO: Muxing mud-250eb91-svtplay.ts into mud-250eb91-svtplay.mp4
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "./svtplay-dl/__main__.py", line 15, in <module>
  File "./svtplay-dl/svtplay_dl/__init__.py", line 66, in main
  File "./svtplay-dl/svtplay_dl/utils/getmedia.py", line 61, in get_media
  File "./svtplay-dl/svtplay_dl/utils/getmedia.py", line 230, in get_one_media
  File "./svtplay-dl/svtplay_dl/postprocess/__init__.py", line 57, in remux
TypeError: argument of type 'NoneType' is not iterable
```
If I run ffprobe on the downloaded audio ts file it says `mud-250eb91-svtplay.audio.ts: Invalid data found when processing input`.

**Comment by spaam** [comment]
interesting. for some reason the playlist say the files is encrypted but they aren't, because of that we try to decrypt the files and it ends up as junk and ffmpeg complain about invalid data. 🤔

**Comment by spaam** [comment]
the latest snapshot that from today will have a fix for this. i will make a release 2.9 tomorrow or the day after.

**Comment by ottob** [comment]
tack för snabb fix och gott nytt år!
