### ISSUE TITLE
Failed download of sound from svtplay.se

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#1307]
**svtplay-dl versions:**
svtplay-dl v2.8 python code
snap-shot 201231_141922 python code

**Operating system and Python version:**
python 3.7.4
windows 8.1 64-bit

**What is the issue:**

https://www.svtplay.se/video/3057276/ryska-huset

Despite the notice from SVT on the web page:
"På grund av ett tekniskt problem går filmen endast att se på vissa enheter"
the movie can be watched using FireFox with sound available during the full movie.

However, when using svtplay-dl the resulting audio in the .mp4-file stop is silent after a couple minutes.

the switches used with svtplay-dl are: 
--subtitle
--quality
--verbose
-o

**The failing cases all show the same crash dump:**
ERROR [1610546462.3622544] e:\svtplaydll\svtplay-dl_sshot_20201231_141922py\svtp
lay_dl\utils\proc.py/run_program: Something went wrong: ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200726
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
ryska_huset_vSS1231_hls_q3284.ts: Invalid data found when processing input
INFO [1610546462.4472706] e:\svtplaydll\svtplay-dl_sshot_20201231_141922py\svtplay_dl\postprocess\__init__.py/remux: Muxing ryska_huset_vSS1231_hls_q3284.ts into ryska_huset_vSS1231_hls_q3284.mp4
Traceback (most recent call last):
  File "e:\svtplaydll\svtplay-dl_sshot_20201231_141922py\__main__.py", line 15,
in <module>
    svtplay_dl.main()
  File "e:\svtplaydll\svtplay-dl_sshot_20201231_141922py\svtplay_dl\__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "e:\svtplaydll\svtplay-dl_sshot_20201231_141922py\svtplay_dl\utils\getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "e:\svtplaydll\svtplay-dl_sshot_20201231_141922py\svtplay_dl\utils\getmedia.py", line 234, in get_one_media
    post.remux()
  File "e:\svtplaydll\svtplay-dl_sshot_20201231_141922py\svtplay_dl\postprocess\__init__.py", line 57, in remux
    if ext == ".ts" and "aac" in _getcodec(streams, audiotrack):
TypeError: argument of type 'NoneType' is not iterable

**Some observations:**
The available qualities with the web-link are:
hls 3376    <- no crash and an .mp4-file is created but sound stops after 3 min 26 sec
hls 3284    <- crash at exection of ffmpeg
hls 2332
hls 2262
hls 1558
hls 1505
hls 1041
hls 999
hls 551   <- no crash but sound stops after approx 10 min
hls 519   <- no crash and an .mp4-file is created but sound stops after 

What I notice at attempting to download using different value of "quality" is that the .audio.ts file varies in size such that it's smaller for lower qualities for the cases where download succeeds.
However, for the cases where ffmpeg fails the size of the .audio.ts file is close to the large size with quality=3376.
Every other quality value (3284, 2262, etc) results in a crash at use of ffmpeg.
The quality values which results in an .mp4-file includes sound only at start of the movie.

**Comment by pythonuser3856** [comment]
And now, without and changes in the disclaimer notification on the web page, it suddenly works.
