### ISSUE TITLE
Crash on https://www.tv4play.se/program/sverige-mot-norge avsnitt 4.

### ISSUE THREAD

**Issue by SweDennis** [spaam/svtplay-dl#1311]
### svtplay-dl versions:
```
dennis@Lenovo:~$ svtplay-dl --version
svtplay-dl 2.8+11.gd193679
dennis@Lenovo:~$ 

```
### Operating system and Python version:
```
dennis@Lenovo:~$ uname -a
Linux Lenovo 5.8.0-41-generic #46~20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
dennis@Lenovo:~$ 

dennis@Lenovo:~$ python --version
Python 3.8.5
dennis@Lenovo:~$ 
```
### What is the issue: svtplay-dl crashes
```

dennis@Lenovo:~$ svtplay-dl https://www.tv4play.se/program/sverige-mot-norge/del-4-s%C3%A4song-2/13286084 --verbose 
DEBUG [1612267025.9551997] /usr/local/lib/python3.8/dist-packages/svtplay_dl-2.8+11.gd193679-py3.8.egg/svtplay_dl/utils/getmedia.py/get_media: version: 2.8+11.gd193679
DEBUG [1612267025.956382] /usr/local/lib/python3.8/dist-packages/svtplay_dl-2.8+11.gd193679-py3.8.egg/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1612267025.9564426] /usr/local/lib/python3.8/dist-packages/svtplay_dl-2.8+11.gd193679-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/sverige-mot-norge/del-4-s%C3%A4song-2/13286084'
DEBUG [1612267025.9578416] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1612267026.7469256] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/sverige-mot-norge/del-4-s%C3%A4song-2/13286084 HTTP/1.1" 200 None
DEBUG [1612267026.7571566] /usr/local/lib/python3.8/dist-packages/svtplay_dl-2.8+11.gd193679-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://playback-api.b17g.net/media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'
DEBUG [1612267026.7588162] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback-api.b17g.net:443
DEBUG [1612267027.0691907] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 115
DEBUG [1612267027.069643] /usr/lib/python3/dist-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'): Retry(total=4, connect=5, read=5, redirect=None, status=None)
DEBUG [1612267027.0699594] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/urlopen: Retry: /media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine
DEBUG [1612267027.1725082] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 115
DEBUG [1612267027.1729448] /usr/lib/python3/dist-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'): Retry(total=3, connect=5, read=5, redirect=None, status=None)
DEBUG [1612267027.7739286] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/urlopen: Retry: /media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine
DEBUG [1612267027.9021747] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 115
DEBUG [1612267027.9026656] /usr/lib/python3/dist-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'): Retry(total=2, connect=5, read=5, redirect=None, status=None)
DEBUG [1612267029.1042292] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/urlopen: Retry: /media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine
DEBUG [1612267029.270764] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 115
DEBUG [1612267029.271196] /usr/lib/python3/dist-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'): Retry(total=1, connect=5, read=5, redirect=None, status=None)
DEBUG [1612267031.6739607] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/urlopen: Retry: /media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine
DEBUG [1612267031.8387756] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 115
DEBUG [1612267031.8391912] /usr/lib/python3/dist-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'): Retry(total=0, connect=5, read=5, redirect=None, status=None)
DEBUG [1612267036.6422691] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/urlopen: Retry: /media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine
DEBUG [1612267036.7853098] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 500 115
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 833, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 833, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 833, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 819, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='playback-api.b17g.net', port=443): Max retries exceeded with url: /media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==2.8+11.gd193679', 'svtplay-dl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-2.8+11.gd193679-py3.8.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-2.8+11.gd193679-py3.8.egg/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-2.8+11.gd193679-py3.8.egg/svtplay_dl/utils/getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-2.8+11.gd193679-py3.8.egg/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
    for i in streams:
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-2.8+11.gd193679-py3.8.egg/svtplay_dl/service/tv4play.py", line 69, in get
    res = self.http.request("get", url, cookies=self.cookies)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-2.8+11.gd193679-py3.8.egg/svtplay_dl/utils/http.py", line 41, in request
    res = Session.request(self, method, url, verify=self.verify, proxies=self.proxy, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='playback-api.b17g.net', port=443): Max retries exceeded with url: /media/13286084?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine (Caused by ResponseError('too many 500 error responses'))

```

**Comment by SweDennis** [comment]
Just as an added comment, I have successfully downloaded episodes 1-3 before, but none of those work anymore.
So either tv4 has changed something, or it's something with an update with svtplay-dl.
Episode 3 was successfully downloaded on jan 26'th, with the then current svtplay-dl. I update svtplay-dl, daily, and automatically, if there is an update, so I'm always current.
Don't know if that info helps. but there it is. :-D

/Dennis

**Comment by spaam** [comment]
i cant reproduce this with 1 to 4.   it works great here 🤔

**Comment by spaam** [comment]
hmm.. its failing now for me  🤔

**Comment by spaam** [comment]
and now its working again.. seems pretty unstable :(

**Comment by SweDennis** [comment]
Wow, didn't see this coming. I tried all 4 again, without a VPN using my Com-Hem provided IP, and ALL 4 WORKS, without VPN, and none, with a VPN ... what would life be without a mystery ...

**Comment by SweDennis** [comment]
Does it fail for you, when it fails, with the same errors?

**Comment by granbom** [comment]
Works for me:
  ~  svtplay-dl https://www.tv4play.se/program/sverige-mot-norge/del-4-s%C3%A4song-2/13286084
INFO: Selected to download hls, bitrate: 4473 format: h264
INFO: Outfile: sverige-mot-norge.s02e04.sverige.mot.norge.del.4-13286084-tv4play.audio.ts
[665/665][================================================================================] ETA: 0:00:00
INFO: Outfile: sverige-mot-norge.s02e04.sverige.mot.norge.del.4-13286084-tv4play.ts
[095/665][===========.....................................................................] ETA: 0:04:37

I would say, that I have noticed before that tv4play is fairly unstable, especially with files recently released.
Since @SweDennis error is an (Caused by ResponseError('too many 500 error responses') that also indicates errors at the tv4play server and not that the connection it self have any issues.

**Comment by SweDennis** [comment]
Leave it be, now it works again for me with VPN going. tv4play is messing around, or something is in between, but fact remains, a crash is a crash, is a crash, and a crash is never ok. An error message is ok, but a crash, not so much. :-D
(All said with the greatest of respect, we both know what I mean. At least I do being 49, and having programmed since I was 25:-D )
All the best with this, but it is as you say, very unstable, I've just never seen it before.

**Comment by SweDennis** [comment]
Just as a formal thingy, case can be closed, as far as I'm concerned, as the case starter.

**Comment by granbom** [comment]
As far as I know @SweDennis  you have the right to close your own case =)

**Comment by SweDennis** [comment]
Oh I know, but wasn't sure if SPAAM thought it reasonable to keep it open as something to work on, and what might be an issue for others.
All I meant as well, with my talk above with crash is a crash and so on ... perhaps an error message saying something like ..."Temporary trouble with <insert site here>, please try again later ..." :-D

I'll leave it open until tomorrow when back from work, and leave it to spaam to decide whether to close it before that, or not. :-D

Good night,
/Dennis

**Comment by SweDennis** [comment]
Oh I know, but wasn't sure if SPAAM thought it reasonable to keep it open as something to work on, and what might be an issue for others.
All I meant as well, with my talk above with crash is a crash and so on ... perhaps an error message saying something like ..."Temporary trouble with "site name", please try again later ..." :-D

I'll leave it open until tomorrow when back from work, and leave it to spaam to decide whether to close it before that, or not. :-D

Good night,
/Dennis

**Comment by SweDennis** [comment]
Closing the case, due to it being a temporary error on tv4play.se, so I as a case starter am very comfortable with closing. If it's of general interest as a reference to keep it open, then I'll leave it to someone else to either re-open, or reference in a new case.

/Dennis
