### ISSUE TITLE
cookies dont work with config

### ISSUE THREAD

**Issue by spaam** [spaam/svtplay-dl#1316]
### svtplay-dl versions:

2.9

### Operating system and Python version:

macos python 3.9

### What is the issue:

cookies in config dont work.

**Comment by Sopor** [comment]
@spaam How do i add the cookie to the config file?

**Comment by spaam** [comment]
@Sopor https://svtplay-dl.se/config/ `cookies`

**Comment by Sopor** [comment]
Hmm, could you show me an example?

Btw, do i need to change the dplay to discovery+ or what?

**Comment by Sopor** [comment]
I only get `ERROR: Need the 'st' cookie to work` :(

**Comment by spaam** [comment]
i did not change the internal name from `dplay` to `discoveryplus`

```
service:
  dplay:
    cookies: st=KalleAnka;
```

**Comment by Sopor** [comment]
If i end the cookie with `;` i get this:

```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.7\x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 74, in run
  File "C:\hostedtoolcache\windows\Python\3.8.7\x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 47, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py", line 220, in service_handler
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py", line 52, in __init__
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py", line 29, in __init__
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py", line 45, in split_header
ValueError: dictionary update sequence element #1 has length 1; 2 is required
```

**Comment by Sopor** [comment]
It seems to work if i remove the `;` :)

**Comment by spaam** [comment]
> If i end the cookie with `;` i get this:
> 
> ```
> Traceback (most recent call last):
>   File "C:\hostedtoolcache\windows\Python\3.8.7\x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 74, in run
>   File "C:\hostedtoolcache\windows\Python\3.8.7\x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
>   File "bin/svtplay-dl", line 7, in <module>
>   File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
>   File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 47, in get_media
>   File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py", line 220, in service_handler
>   File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py", line 52, in __init__
>   File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py", line 29, in __init__
>   File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py", line 45, in split_header
> ValueError: dictionary update sequence element #1 has length 1; 2 is required
> ```

that will be fixed in next version. forgot to check if the value was valid
