### ISSUE TITLE
svtplay-dl funkar inte för närvarande

### ISSUE THREAD

**Issue by Thoxxx** [spaam/svtplay-dl#1328]
### svtplay-dl versions:

Run `svtplay-dl --version`

### Operating system and Python version:

Name and version of the operating system and python version (run `python --version`)

### What is the issue:

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

    svtplay-dl --verbose https://www.example.com

**Comment by Thoxxx** [comment]
Uppdaterat till 3.0

Får detta meddelande i Terminalen (Mac OS):

svtplay-dl https://www.svtplay.se/video/29852578/hjarter-dam?start=auto
WARNING: Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103773220>: Failed to establish a new connection: [Errno 64] Host is down')': /video/29852578/hjarter-dam?start=auto
WARNING: Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103773460>: Failed to establish a new connection: [Errno 64] Host is down')': /video/29852578/hjarter-dam?start=auto
WARNING: Retrying (Retry(total=2, connect=2, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103773610>: Failed to establish a new connection: [Errno 64] Host is down')': /video/29852578/hjarter-dam?start=auto
WARNING: Retrying (Retry(total=1, connect=1, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1037737c0>: Failed to establish a new connection: [Errno 64] Host is down')': /video/29852578/hjarter-dam?start=auto
WARNING: Retrying (Retry(total=0, connect=0, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103773970>: Failed to establish a new connection: [Errno 64] Host is down')': /video/29852578/hjarter-dam?start=auto
Traceback (most recent call last):
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 64] Host is down

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x103773b20>: Failed to establish a new connection: [Errno 64] Host is down

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.svtplay.se', port=443): Max retries exceeded with url: /video/29852578/hjarter-dam?start=auto (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103773b20>: Failed to establish a new connection: [Errno 64] Host is down'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 96, in get_one_media
    if not filename(stream):
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/svtplay_dl/utils/output.py", line 119, in filename
    data = ensure_unicode(stream.get_urldata())
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/svtplay_dl/service/__init__.py", line 64, in get_urldata
    self._urldata = self.http.request("get", self.url).text
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/svtplay_dl/utils/http.py", line 41, in request
    res = Session.request(self, method, url, verify=self.verify, proxies=self.proxy, *args, **kwargs)
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/svtplay-dl/3.0/libexec/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.svtplay.se', port=443): Max retries exceeded with url: /video/29852578/hjarter-dam?start=auto (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103773b20>: Failed to establish a new connection: [Errno 64] Host is down'))
