### ISSUE TITLE
KeyError: 'data' when trying to download from svtplay.se

### ISSUE THREAD

**Issue by marcg-75** [spaam/svtplay-dl#1352]
### svtplay-dl versions: 
svtplay-dl 3.3+2.gcdf394e

### Operating system and Python version:
macOS Big Sur (11.2.1)
Python 3.9.4

### What is the issue:
KeyError: 'data' when trying to download from svtplay.se

svtplay-dl --verbose https://www.svtplay.se/video/13888272/trazan-apansson-och-banarne/trazan-apansson-och-banarne-avsnitt-7?modalId=KGYGnge

Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==3.3+2.gcdf394e', 'svtplay-dl')
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.9/site-packages/svtplay_dl-3.3+2.gcdf394e-py3.9.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.9/site-packages/svtplay_dl-3.3+2.gcdf394e-py3.9.egg/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.9/site-packages/svtplay_dl-3.3+2.gcdf394e-py3.9.egg/svtplay_dl/utils/getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "/usr/local/lib/python3.9/site-packages/svtplay_dl-3.3+2.gcdf394e-py3.9.egg/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
    for i in streams:
  File "/usr/local/lib/python3.9/site-packages/svtplay_dl-3.3+2.gcdf394e-py3.9.egg/svtplay_dl/service/svtplay.py", line 73, in get
    entry = json.loads(data_entry["data"])
KeyError: 'data'

**Comment by spaam** [comment]
thanks for the bug ticket, i will look into this after work today. :)

**Comment by beneix** [comment]
Thanks @spaam for incorporating my ticket. Perhaps there have been some changes made on the SVT side this morning – I ran a successful download earlier today (~08:30 CEST), then the next episode failed at 09:45.

To check, I re-ran the download that was successful earlier, and it failed the same way as the one I reported. So – it seems not to be about different episodes, but something that has either changed on the SVT side (or is temporarily broken).

**Comment by JohnnyJorgensen** [comment]
I second beneix's observations. I also ran successful downloads earlier today. Think that something has changed on SVT Play around 9-9.30.

**Comment by pythonuser3856** [comment]
Snapshot version 20210413_151844 works just fine.
Many thanks !

**Comment by beneix** [comment]
> Snapshot version 20210413_151844 works just fine.

I concur. Tack!

**Comment by spaam** [comment]
3.4 is out with ze fix.  Did a PR to brew and it will hit that in a few hours.
thanks for the report <3
