### ISSUE TITLE
Error starting SVTPlay download

### ISSUE THREAD

**Issue by beneix** [spaam/svtplay-dl#1353]
Running svtplay-dl 3.3, I get an error when trying certain episodes of a series. Others work. Here is an example of a failure:

C:\>svtplay-dl -S --verbose https://www.svtplay.se/video/13814920/glappet/glappet-avsnitt-5
DEBUG [1618300591.5337853] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 3.3
DEBUG [1618300591.534785] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1618300591.534785] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/13814920/glappet/glappet-avsnitt-5'
DEBUG [1618300591.5410614] C:\hostedtoolcache\windows\Python\3.8.8\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1618300591.9293528] C:\hostedtoolcache\windows\Python\3.8.8\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/13814920/glappet/glappet-avsnitt-5 HTTP/1.1" 200 28414
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.8\x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 74, in run
  File "C:\hostedtoolcache\windows\Python\3.8.8\x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 73, in get
KeyError: 'data'

Any suggestions?

**Comment by spaam** [comment]
i will look at this after work today. in the mean time, we already got a issue with this #1352 , it was created few min before this.  please follow that one for updates :)
