### ISSUE TITLE
SVT Play cannot download a short clip

### ISSUE THREAD

**Issue by WheelCool** [spaam/svtplay-dl#1363]
### svtplay-dl versions:

svtplay-dl 3.6

### Operating system and Python version:

Ubuntu 21.04 and Python 2.7.18

### What is the issue:

When trying to download a clip about children/youths being put into institutions svtplay-dl fails to download even though I compiled and installed svtplay-dl instead of using the installed one from the svtplay-dl repo I end up with this:

svtplay-dl https://www.svtplay.se/klipp/30926142/sa-ser-det-ut-pa-sis-hemmen-i-sverige--vanligare-att-flickor-isoleras?id=j4VqWXp --verbose

DEBUG [1618862075.5277247] /usr/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 3.6
DEBUG [1618862075.5310032] /usr/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1618862075.5312011] /usr/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/klipp/30926142/sa-ser-det-ut-pa-sis-hemmen-i-sverige--vanligare-att-flickor-isoleras?id=j4VqWXp'
DEBUG [1618862075.535737] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1618862075.629402] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /klipp/30926142/sa-ser-det-ut-pa-sis-hemmen-i-sverige--vanligare-att-flickor-isoleras?id=j4VqWXp HTTP/1.1" 200 75601
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 69, in main
  File "/usr/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 61, in get_media
  File "/usr/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
  File "/usr/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 85, in get
  File "/usr/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 220, in outputfilename
  File "/usr/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 241, in seasoninfo
  File "/usr/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 265, in _find_season
KeyError: 'positionInSeason'

I even tried removing ?id=j4VqWXp, but that did not work.

**Comment by spaam** [comment]
thanks for the bug issue <3. i committed a fix for this and it will be available in a release later this week.

**Comment by WheelCool** [comment]
Problem fixed when building with latest commits. Thank you.
