### ISSUE TITLE
Crash on discoveryplus.se using -A.

### ISSUE THREAD

**Issue by SweDennis** [spaam/svtplay-dl#1368]
### svtplay-dl versions:

```
dennis@Lenovo:~$ svtplay-dl --version
svtplay-dl 3.6+2.g0dcb01f
dennis@Lenovo:~$ 
```

### Operating system and Python version:

```
dennis@Lenovo:~$ uname -a
Linux Lenovo 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
dennis@Lenovo:~$ python --version
Python 3.8.5
dennis@Lenovo:~$ 
```

### What is the issue:

svtplay-dl crash when using -A on discoveryplus.se

```
dennis@Lenovo:~$ svtplay-dl -v -A -g --cookies st=`cat ~/dplaycookie.txt` https://www.discoveryplus.se/program/alla-mot-alla-med-filip-och-fredrik
DEBUG [1619105413.3225043] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.6+2.g0dcb01f-py3.8.egg/svtplay_dl/utils/getmedia.py/get_media: version: 3.6+2.g0dcb01f
DEBUG [1619105413.3230178] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.6+2.g0dcb01f-py3.8.egg/svtplay_dl/service/__init__.py/__init__: service: dplay
DEBUG [1619105413.323599] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.6+2.g0dcb01f-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/users/me'
DEBUG [1619105413.325147] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): disco-api.discoveryplus.se:443
DEBUG [1619105413.6305966] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /users/me HTTP/1.1" 200 None
DEBUG [1619105413.631641] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.6+2.g0dcb01f-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/token?realm=dplayse&deviceId=a7353125e0ac7337b89cb4f8262996fcd954398805f81572b7856bbc2f9c998d&shortlived=true'
DEBUG [1619105413.7112951] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /token?realm=dplayse&deviceId=a7353125e0ac7337b89cb4f8262996fcd954398805f81572b7856bbc2f9c998d&shortlived=true HTTP/1.1" 200 None
DEBUG [1619105413.7127163] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.6+2.g0dcb01f-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/users/me'
DEBUG [1619105413.7852392] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /users/me HTTP/1.1" 200 None
DEBUG [1619105413.7862475] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.6+2.g0dcb01f-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'http://disco-api.discoveryplus.se/cms/routes/program/alla-mot-alla-med-filip-och-fredrik?decorators=viewingHistory&include=default'
DEBUG [1619105413.788906] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): disco-api.discoveryplus.se:80
DEBUG [1619105413.949801] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://disco-api.discoveryplus.se:80 "GET /cms/routes/program/alla-mot-alla-med-filip-och-fredrik?decorators=viewingHistory&include=default HTTP/1.1" 301 134
DEBUG [1619105414.0921557] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/routes/program/alla-mot-alla-med-filip-och-fredrik?decorators=viewingHistory&include=default HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==3.6+2.g0dcb01f', 'svtplay-dl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-3.6+2.g0dcb01f-py3.8.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-3.6+2.g0dcb01f-py3.8.egg/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-3.6+2.g0dcb01f-py3.8.egg/svtplay_dl/utils/getmedia.py", line 59, in get_media
    get_all_episodes(stream, url, options)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-3.6+2.g0dcb01f-py3.8.egg/svtplay_dl/utils/getmedia.py", line 77, in get_all_episodes
    episodes = stream.find_all_episodes(stream.config)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-3.6+2.g0dcb01f-py3.8.egg/svtplay_dl/service/dplay.py", line 159, in find_all_episodes
    for ses in what["attributes"]["component"]["filters"]:
KeyError: 'filters'
dennis@Lenovo:~$ 
```

**Comment by SweDennis** [comment]
Sorry, found this to be a duplicate of #1366 , my bad. Not quite same errors though, so will leave it open in case it is of use.

**Comment by spaam** [comment]
i committed a fix for this. it should work better :)

**Comment by SweDennis** [comment]
Indeed it does. Works fine now. Great job, many thanks.

/Dennis
