### ISSUE TITLE
Still a crash at using switch "--live" with SVTplay

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#1381]
svtplay-dl python code snapshot version 20210510_221658
windows 81., python 3.8.10

At capturing live from an svt channel svtplay-dl crashes

**1) at no use of switch "--stream-priority hls" the crash trace is**
```
Traceback (most recent call last):
  File "c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\__main__.py", line 15,in <module>
    svtplay_dl.main()
  File "c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\svtplay_dl\__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\svtplay_dl\utils\getmedia.py", line 62, in get_media
    get_one_media(stream)
  File "c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\svtplay_dl\utils\getmedia.py", line 227, in get_one_media
    raise e
  File "c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\svtplay_dl\utils\getmedia.py", line 224, in get_one_media
    fstream.download()
  File "c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\svtplay_dl\fetcher\dash.py", line 322, in download
    raise LiveDASHException(self.url)
svtplay_dl.fetcher.dash.LiveDASHException: This is a live DASH stream, and they are not supported.
```
**I'm fine with including the switch but it's a change in behavior.**

**2) at use of switch "--stream-priority hls" there is a crash at ending a time-limited stream (using "--capture_time ##). Opening the downloaded .ts-file with vlc reveals that it's a video download only.**

```
Traceback (most recent call last):
  File "c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\__main__.py", line 15,in <module>
    svtplay_dl.main()
  File "c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\svtplay_dl\__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\svtplay_dl\utils\getmedia.py", line 62, in get_media
    get_one_media(stream)
  File "c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\svtplay_dl\utils\getmedia.py", line 240, in get_one_media
    post.remux()
  File "c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\svtplay_dl\postprocess\__init__.py", line 57, in remux
    if orig_filename.suffix == ".ts" and streams and "aac" in _getcodec(streams, audiotrack):
TypeError: argument of type 'NoneType' is not iterable
```

**3) New behavior: at a use of specified output file name the designated file name is cut of**
py svtplay-dl --live --verbose --capture_time 2 --stream-priority hls --output "**2021-05-11_10.36_2_min_#1**" https://www.svtplay.se/kanaler/svt2
File name of file created (before the crash at use of --stream-priority hls):
**2021-05-11_10.ts**

**Comment by spaam** [comment]
where is the urls for the first one and second one? can't fix it without it.

the first one is not really a crash. it just say that it does not support live stream then its dash , sure it does not show that error message when you specify HLS.

**Comment by pythonuser3856** [comment]
Sorry, it was the same url in all cases:  https://www.svtplay.se/kanaler/svt2

1) it's a change in behavior and I included it for that reason only.
Previous behavior was that svtplay-dl automatically selected hls and started downloading. That was kind of neat, I think.

**Comment by spaam** [comment]
i cant reproduce 1 and 2.

3)  the dots is the issue using python's function to detect file extensions. stop using it? 
```
In [2]: os.path.splitext("2021-05-11_10.36_2_min_#1")
Out[2]: ('2021-05-11_10', '.36_2_min_#1')
```
 
the issue  is that people do `-o kalle.win` and we put the correct file extension to it. 
i guess one fix could be that we trust the user to do the right thing  and if they do something wrong, then they can blame themself for it.

**Comment by pythonuser3856** [comment]
Neither can I using the same version of svtplay-dl.
Let's hope SVT keep it that way.

About file naming; it's a nuissance to not be able to use the punctuation character in file names.
I'm using it in a script to auto-name captures by starting date, time and length of recording where I'm using the "." as part of it, typically for time-delayed start of recordings from TV-channels (i.e. like VCR-recording and applied to material which is not made available via play).
