### ISSUE TITLE
New Crash on Discovery+

### ISSUE THREAD

**Issue by SweDennis** [spaam/svtplay-dl#1384]
### svtplay-dl versions:

dennis@Lenovo:~$ svtplay-dl --version
svtplay-dl 3.8+10.gc9a606d
dennis@Lenovo:~$ 

### Operating system and Python version:

dennis@Lenovo:~$ uname -a
Linux Lenovo 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
dennis@Lenovo:~$ python --version
Python 3.8.5
dennis@Lenovo:~$ 

### What is the issue: svtplay-dl crashes on Discovery+ using -A 

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)
 ```
svtplay-dl -A -g --cookies st=`cat ~/dplaycookie.txt` https://www.discoveryplus.se/program/alla-mot-alla-med-filip-och-fredrik -v
DEBUG [1621354241.8964217] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/getmedia.py/get_media: version: 3.8+10.gc9a606d
DEBUG [1621354241.8969183] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/service/__init__.py/__init__: service: discoveryplus
DEBUG [1621354241.8978813] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/users/me'
DEBUG [1621354241.8997679] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): disco-api.discoveryplus.se:443
DEBUG [1621354242.2112613] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /users/me HTTP/1.1" 200 None
DEBUG [1621354242.2123778] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/token?realm=dplayse&deviceId=0ed9e26c3f1435e498beb2369bdf5a04a7fe4f0e302068ef2c308e1ff872b5f7&shortlived=true'
DEBUG [1621354242.290917] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /token?realm=dplayse&deviceId=0ed9e26c3f1435e498beb2369bdf5a04a7fe4f0e302068ef2c308e1ff872b5f7&shortlived=true HTTP/1.1" 200 None
DEBUG [1621354242.2922232] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/users/me'
DEBUG [1621354242.3655217] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /users/me HTTP/1.1" 200 None
DEBUG [1621354242.3664997] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'http://disco-api.discoveryplus.se/cms/routes/program/alla-mot-alla-med-filip-och-fredrik?decorators=viewingHistory&include=default'
DEBUG [1621354242.3690488] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): disco-api.discoveryplus.se:80
DEBUG [1621354242.5190382] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://disco-api.discoveryplus.se:80 "GET /cms/routes/program/alla-mot-alla-med-filip-och-fredrik?decorators=viewingHistory&include=default HTTP/1.1" 301 134
DEBUG [1621354242.6652982] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/routes/program/alla-mot-alla-med-filip-och-fredrik?decorators=viewingHistory&include=default HTTP/1.1" 200 None
DEBUG [1621354242.669862] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=1&pf[seasonNumber]=5'
DEBUG [1621354242.7482805] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=1&pf%5BseasonNumber%5D=5 HTTP/1.1" 200 None
DEBUG [1621354242.7546387] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=2&pf[seasonNumber]=5'
DEBUG [1621354242.835959] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=2&pf%5BseasonNumber%5D=5 HTTP/1.1" 200 None
DEBUG [1621354242.839335] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=3&pf[seasonNumber]=5'
DEBUG [1621354242.938027] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=3&pf%5BseasonNumber%5D=5 HTTP/1.1" 200 None
DEBUG [1621354242.9411433] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=4&pf[seasonNumber]=5'
DEBUG [1621354243.0290768] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=4&pf%5BseasonNumber%5D=5 HTTP/1.1" 200 None
DEBUG [1621354243.0321643] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=5&pf[seasonNumber]=5'
DEBUG [1621354243.1223347] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=5&pf%5BseasonNumber%5D=5 HTTP/1.1" 200 None
DEBUG [1621354243.1245184] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=6&pf[seasonNumber]=5'
DEBUG [1621354243.198881] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=6&pf%5BseasonNumber%5D=5 HTTP/1.1" 200 None
DEBUG [1621354243.2009635] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=1&pf[seasonNumber]=4'
DEBUG [1621354243.2785075] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=1&pf%5BseasonNumber%5D=4 HTTP/1.1" 200 None
DEBUG [1621354243.2815638] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=2&pf[seasonNumber]=4'
DEBUG [1621354243.3674786] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=2&pf%5BseasonNumber%5D=4 HTTP/1.1" 200 None
DEBUG [1621354243.371574] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=3&pf[seasonNumber]=4'
DEBUG [1621354243.4590428] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=3&pf%5BseasonNumber%5D=4 HTTP/1.1" 200 None
DEBUG [1621354243.4621608] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=4&pf[seasonNumber]=4'
DEBUG [1621354243.5492811] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=4&pf%5BseasonNumber%5D=4 HTTP/1.1" 200 None
DEBUG [1621354243.552246] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=5&pf[seasonNumber]=4'
DEBUG [1621354243.6328225] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=5&pf%5BseasonNumber%5D=4 HTTP/1.1" 200 None
DEBUG [1621354243.6361406] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=6&pf[seasonNumber]=4'
DEBUG [1621354243.7180984] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=6&pf%5BseasonNumber%5D=4 HTTP/1.1" 200 None
DEBUG [1621354243.7199638] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=1&pf[seasonNumber]=3'
DEBUG [1621354243.8069494] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=1&pf%5BseasonNumber%5D=3 HTTP/1.1" 200 None
DEBUG [1621354243.8090386] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=2&pf[seasonNumber]=3'
DEBUG [1621354243.8888311] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=2&pf%5BseasonNumber%5D=3 HTTP/1.1" 200 None
DEBUG [1621354243.8921216] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=3&pf[seasonNumber]=3'
DEBUG [1621354243.9761987] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=3&pf%5BseasonNumber%5D=3 HTTP/1.1" 200 None
DEBUG [1621354243.979246] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=4&pf[seasonNumber]=3'
DEBUG [1621354244.0948012] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=4&pf%5BseasonNumber%5D=3 HTTP/1.1" 200 None
DEBUG [1621354244.0973997] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=5&pf[seasonNumber]=3'
DEBUG [1621354244.1750567] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=5&pf%5BseasonNumber%5D=3 HTTP/1.1" 200 None
DEBUG [1621354244.1778705] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=1&pf[seasonNumber]=2'
DEBUG [1621354244.2652028] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=1&pf%5BseasonNumber%5D=2 HTTP/1.1" 200 None
DEBUG [1621354244.2672226] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=2&pf[seasonNumber]=2'
DEBUG [1621354244.3616545] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=2&pf%5BseasonNumber%5D=2 HTTP/1.1" 200 None
DEBUG [1621354244.363895] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=3&pf[seasonNumber]=2'
DEBUG [1621354244.4496036] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=3&pf%5BseasonNumber%5D=2 HTTP/1.1" 200 None
DEBUG [1621354244.4517062] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=4&pf[seasonNumber]=2'
DEBUG [1621354244.5372574] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=4&pf%5BseasonNumber%5D=2 HTTP/1.1" 200 None
DEBUG [1621354244.5395837] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=5&pf[seasonNumber]=2'
DEBUG [1621354244.626057] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=5&pf%5BseasonNumber%5D=2 HTTP/1.1" 200 None
DEBUG [1621354244.628364] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=1&pf[seasonNumber]=1'
DEBUG [1621354244.7122633] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=1&pf%5BseasonNumber%5D=1 HTTP/1.1" 200 None
DEBUG [1621354244.7145138] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page[items.number]=2&pf[seasonNumber]=1'
DEBUG [1621354244.7962408] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/250113178068544661220696579997795310376?decorators=viewingHistory&include=default&page%5Bitems.number%5D=2&pf%5BseasonNumber%5D=1 HTTP/1.1" 200 None
DEBUG [1621354244.7990303] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/service/__init__.py/__init__: service: discoveryplus
INFO [1621354244.7991486] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/getmedia.py/get_all_episodes: Episode 1 of 64
INFO [1621354244.7992601] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/getmedia.py/get_all_episodes: Url: https://www.discoveryplus.se/videos/alla-mot-alla-med-filip-och-fredrik/kvartsfinal-1-sang-och-nervositet
DEBUG [1621354244.799388] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.discoveryplus.se/videos/alla-mot-alla-med-filip-och-fredrik/kvartsfinal-1-sang-och-nervositet'
DEBUG [1621354244.8014584] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.discoveryplus.se:443
DEBUG [1621354245.1305063] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.discoveryplus.se:443 "GET /videos/alla-mot-alla-med-filip-och-fredrik/kvartsfinal-1-sang-och-nervositet HTTP/1.1" 200 None
DEBUG [1621354245.1322641] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/token?realm=dplayse&deviceId=f4e5da9aa987fbfc9485237a81368552e4578555f8afb1242a168b3ce3a50e54&shortlived=true'
DEBUG [1621354245.1346123] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): disco-api.discoveryplus.se:443
DEBUG [1621354245.4493666] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /token?realm=dplayse&deviceId=f4e5da9aa987fbfc9485237a81368552e4578555f8afb1242a168b3ce3a50e54&shortlived=true HTTP/1.1" 200 None
DEBUG [1621354245.451012] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/users/me'
DEBUG [1621354245.5271194] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /users/me HTTP/1.1" 200 None
DEBUG [1621354245.5279927] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/content/videos/alla-mot-alla-med-filip-och-fredrik/kvartsfinal-1-sang-och-nervositet'
DEBUG [1621354245.607872] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /content/videos/alla-mot-alla-med-filip-och-fredrik/kvartsfinal-1-sang-och-nervositet HTTP/1.1" 200 None
DEBUG [1621354245.6090894] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/playback/videoPlaybackInfo/193535?usePreAuth=true'
DEBUG [1621354245.6947474] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /playback/videoPlaybackInfo/193535?usePreAuth=true HTTP/1.1" 200 None
DEBUG [1621354245.6957412] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://02-httpcache0-90220-cacheod0.dna.ip-only.net/90220-cacheod0/qticket:010000000060a53885981293d06d6f59c17d1a489facbdca3d/dplaydni/213999/0/hls/10171076004/playlist.m3u8'
DEBUG [1621354245.698479] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): 02-httpcache0-90220-cacheod0.dna.ip-only.net:443
DEBUG [1621354245.8758729] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://02-httpcache0-90220-cacheod0.dna.ip-only.net:443 "GET /90220-cacheod0/qticket:010000000060a53885981293d06d6f59c17d1a489facbdca3d/dplaydni/213999/0/hls/10171076004/playlist.m3u8 HTTP/1.1" 200 3227
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==3.8+10.gc9a606d', 'svtplay-dl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/getmedia.py", line 60, in get_media
    get_all_episodes(stream, url, options)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/getmedia.py", line 92, in get_all_episodes
    get_one_media(substream)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/utils/getmedia.py", line 112, in get_one_media
    for i in streams:
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-3.8+10.gc9a606d-py3.8.egg/svtplay_dl/service/dplay.py", line 102, in get
    for n in list(streams.keys()):
AttributeError: 'generator' object has no attribute 'keys'
```

**Comment by SweDennis** [comment]
Added comment, even if URLs are presented without --versbose and such, single episode downloads don't work either, for me.

**Comment by spaam** [comment]
this should be fixed in master now :)

**Comment by SweDennis** [comment]
Confirmed. Works now.

Many thanks.

/Dennis
