### ISSUE TITLE
Can't parse date format

### ISSUE THREAD

**Issue by mattiasost** [spaam/svtplay-dl#1388]
### svtplay-dl versions: svtplay-dl 3.8

Run `svtplay-dl --version` 

### Operating system and Python version: Python 2.7.16, MacOs BigSur Version 11.2.3

Name and version of the operating system and python version (run `python --version`)

### What is the issue:

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

    svtplay-dl --force --verbose https://www.svtplay.se/video/31050626/rapport/rapport-26-maj-18-00-5?id=KM3vYV5
    
    resulting in: 
    
    Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/3.8/libexec/lib/python3.9/site-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/Cellar/svtplay-dl/3.8/libexec/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 62, in get_media
    get_one_media(stream)
  File "/usr/local/Cellar/svtplay-dl/3.8/libexec/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 112, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/3.8/libexec/lib/python3.9/site-packages/svtplay_dl/service/svtplay.py", line 95, in get
    yield from videos
  File "/usr/local/Cellar/svtplay-dl/3.8/libexec/lib/python3.9/site-packages/svtplay_dl/service/svtplay.py", line 120, in _get_video
    streams = dashparse(self.config, self.http.request("get", i["url"]), i["url"], output=self.output)
  File "/usr/local/Cellar/svtplay-dl/3.8/libexec/lib/python3.9/site-packages/svtplay_dl/fetcher/dash.py", line 210, in dashparse
    return _dashparse(config, res.text, url, output, cookies=res.cookies, **kwargs)
  File "/usr/local/Cellar/svtplay-dl/3.8/libexec/lib/python3.9/site-packages/svtplay_dl/fetcher/dash.py", line 227, in _dashparse
    attributes.set("publishTime", parse_dates(xml.attrib["publishTime"]))
  File "/usr/local/Cellar/svtplay-dl/3.8/libexec/lib/python3.9/site-packages/svtplay_dl/fetcher/dash.py", line 309, in parse_dates
    raise ValueError(f"Can't parse date format: {date_str}")
ValueError: Can't parse date format: 2021-05-26T16:15:04.61105105Z

**Comment by spaam** [comment]
This is fixed in master. I will release a new version 3.9 tomorrow with the fix

**Comment by spaam** [comment]
3.9.1 have the fix :)
