### ISSUE TITLE
svtplay-dl -S fails with "list index out of range"

### ISSUE THREAD

**Issue by ecowitness** [spaam/svtplay-dl#1391]
### svtplay-dl versions:

from the code download button, downloaded zip file 2021-05-29 and running directly from the unzip image which doesn't have a valid version since I didn't actually do the setup to install

### Operating system and Python version:

ubutu desktop 20.04.2 LTS
Python 3.8.5

### What is the issue:

I am in the US
no  VPN involved
this title is available to users outside of Sweden

download of program without -S is successful
download of program with -S fails
download of program with -S --force-subtitle fails (documented below)

note that the very, very long path to svtplay-dl has been replaced by <vlpath> below

I normally run svtplay-dl in docker in silent mode and haven't paid much attention to where the content originates. I don't know if the source = svt-vod-3b.akamaized.net is new, but I don't remember seeing it before.

Note the vtt file (see below) instead of srt that I expected. 

I was able to manually obtain just the vtt file and go on to machine translation of the closed captions/subtitles, so I do have a workaround.

Thanks for your help.

```
user@pc:<vlpath>$ python3 __main__.py -v -S --force-subtitle  https://www.svtplay.se/video/21165363/de-forsta-svenskarna/de-forsta-svenskarna-sasong-1-avsnitt-1
DEBUG [1622334023.985923] <vlpath>/utils/getmedia.py/get_media: version: 0+unknown
DEBUG [1622334023.9870934] <vlpath>/service/__init__.py/__init__: service: svtplay
DEBUG [1622334023.987155] <vlpath>/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/21165363/de-forsta-svenskarna/de-forsta-svenskarna-sasong-1-avsnitt-1'
DEBUG [1622334023.9886987] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1622334025.4947236] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/21165363/de-forsta-svenskarna/de-forsta-svenskarna-sasong-1-avsnitt-1 HTTP/1.1" 200 30088
DEBUG [1622334025.511851] <vlpath>/utils/http.py/request: HTTP getting 'https://api.svt.se/video/KXYZkNr'
DEBUG [1622334025.5128825] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): api.svt.se:443
DEBUG [1622334026.3486762] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://api.svt.se:443 "GET /video/KXYZkNr HTTP/1.1" 200 870
DEBUG [1622334026.3498604] <vlpath>/utils/http.py/request: HTTP getting 'https://svt-vod-3b.akamaized.net/d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/manifest.mpd?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F7efdfec6-8fec-4d3b-af95-c4873f5f4ab5%2Fmanifest.mpd'
DEBUG [1622334026.3509512] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-3b.akamaized.net:443
DEBUG [1622334026.54219] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-3b.akamaized.net:443 "GET /d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/manifest.mpd?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F7efdfec6-8fec-4d3b-af95-c4873f5f4ab5%2Fmanifest.mpd HTTP/1.1" 200 875
DEBUG [1622334026.6599166] <vlpath>/utils/http.py/request: HTTP getting 'https://svt-vod-3b.akamaized.net/d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/manifest.mpd?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F7efdfec6-8fec-4d3b-af95-c4873f5f4ab5%2Fmanifest.mpd'
DEBUG [1622334026.674352] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-3b.akamaized.net:443 "GET /d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/manifest.mpd?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F7efdfec6-8fec-4d3b-af95-c4873f5f4ab5%2Fmanifest.mpd HTTP/1.1" 200 875
DEBUG [1622334026.7906036] <vlpath>/utils/http.py/request: HTTP getting 'https://svt-vod-3b.akamaized.net/d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/master.m3u8?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F7efdfec6-8fec-4d3b-af95-c4873f5f4ab5%2Fmaster.m3u8'
DEBUG [1622334026.809458] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-3b.akamaized.net:443 "GET /d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/master.m3u8?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F7efdfec6-8fec-4d3b-af95-c4873f5f4ab5%2Fmaster.m3u8 HTTP/1.1" 200 603
DEBUG [1622334026.8124053] <vlpath>/utils/http.py/request: HTTP getting 'https://svt-vod-3b.akamaized.net/d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/text/closed.m3u8'
DEBUG [1622334026.8135521] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-3b.akamaized.net:443
DEBUG [1622334026.8965845] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-3b.akamaized.net:443 "GET /d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/text/closed.m3u8 HTTP/1.1" 200 109
DEBUG [1622334026.8980818] <vlpath>/utils/http.py/request: HTTP getting 'https://svt-vod-3b.akamaized.net/d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/master-lowbw.m3u8?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F7efdfec6-8fec-4d3b-af95-c4873f5f4ab5%2Fmaster-lowbw.m3u8'
DEBUG [1622334027.0521364] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-3b.akamaized.net:443 "GET /d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/master-lowbw.m3u8?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F7efdfec6-8fec-4d3b-af95-c4873f5f4ab5%2Fmaster-lowbw.m3u8 HTTP/1.1" 200 397
DEBUG [1622334027.0534856] <vlpath>/utils/http.py/request: HTTP getting 'https://svt-vod-3b.akamaized.net/d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/text/closed.m3u8'
DEBUG [1622334027.054487] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-3b.akamaized.net:443
DEBUG [1622334027.1382482] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-3b.akamaized.net:443 "GET /d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/text/closed.m3u8 HTTP/1.1" 200 109
DEBUG [1622334027.1398468] <vlpath>/utils/http.py/request: HTTP getting 'https://svt-vod-3b.akamaized.net/d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/hbbtv.mpd'
DEBUG [1622334027.1893733] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-3b.akamaized.net:443 "GET /d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/hbbtv.mpd HTTP/1.1" 200 728
DEBUG [1622334027.2469711] <vlpath>/utils/http.py/request: HTTP getting 'https://svt-vod-3b.akamaized.net/d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/master-fmp4-lowbw.m3u8?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F7efdfec6-8fec-4d3b-af95-c4873f5f4ab5%2Fmaster-fmp4-lowbw.m3u8'
DEBUG [1622334027.2755415] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-3b.akamaized.net:443 "GET /d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/master-fmp4-lowbw.m3u8?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F7efdfec6-8fec-4d3b-af95-c4873f5f4ab5%2Fmaster-fmp4-lowbw.m3u8 HTTP/1.1" 200 399
DEBUG [1622334027.2767146] <vlpath>/utils/http.py/request: HTTP getting 'https://svt-vod-3b.akamaized.net/d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/text/closed.m3u8'
DEBUG [1622334027.2778304] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-3b.akamaized.net:443
DEBUG [1622334027.3634148] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-3b.akamaized.net:443 "GET /d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/text/closed.m3u8 HTTP/1.1" 200 109
DEBUG [1622334027.3648894] <vlpath>/utils/http.py/request: HTTP getting 'https://svt-vod-3b.akamaized.net/d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/lowbw.mpd?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F7efdfec6-8fec-4d3b-af95-c4873f5f4ab5%2Flowbw.mpd'
DEBUG [1622334027.410283] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-3b.akamaized.net:443 "GET /d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/lowbw.mpd?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F7efdfec6-8fec-4d3b-af95-c4873f5f4ab5%2Flowbw.mpd HTTP/1.1" 200 733
DEBUG [1622334027.4489923] <vlpath>/utils/http.py/request: HTTP getting 'https://svt-vod-3b.akamaized.net/d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/master-fmp4.m3u8?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F7efdfec6-8fec-4d3b-af95-c4873f5f4ab5%2Fmaster-fmp4.m3u8'
DEBUG [1622334027.4780035] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-3b.akamaized.net:443 "GET /d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/master-fmp4.m3u8?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F7efdfec6-8fec-4d3b-af95-c4873f5f4ab5%2Fmaster-fmp4.m3u8 HTTP/1.1" 200 605
DEBUG [1622334027.4805274] <vlpath>/utils/http.py/request: HTTP getting 'https://svt-vod-3b.akamaized.net/d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/text/closed.m3u8'
DEBUG [1622334027.4814944] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-3b.akamaized.net:443
DEBUG [1622334027.564189] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-3b.akamaized.net:443 "GET /d0/world/20200305/7efdfec6-8fec-4d3b-af95-c4873f5f4ab5/text/closed.m3u8 HTTP/1.1" 200 109
Traceback (most recent call last):
  File "__main__.py", line 15, in <module>
    svtplay_dl.main()
  File "<vlpath>/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "<vlpath>/utils/getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "<vlpath>/utils/getmedia.py", line 160, in get_one_media
    subtitle_decider(stream, subtitles)
  File "<vlpath>/utils/stream.py", line 110, in subtitle_decider
    subtitles[0].download()
IndexError: list index out of range
```
the contents of closed.m3u8 might be useful:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:3527
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:3526.24,
closed.vtt
#EXT-X-ENDLIST
```

**Comment by Sopor** [comment]
I can confirm it with svtplay-dl 3.8-22-g45fceaa

**Comment by SweDennis** [comment]
Confirned here as well, with the below:

```
dennis@Lenovo:~$ uname -a
Linux Lenovo 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
dennis@Lenovo:~$ python --version
Python 3.8.5
dennis@Lenovo:~$ 
```

**Comment by SweDennis** [comment]
Forgot version, but same thing ...

```
dennis@Lenovo:~$ svtplay-dl --version
svtplay-dl 3.8+23.g89284c9
dennis@Lenovo:~$ 
```
