### ISSUE TITLE
Issues with live recording

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#1398]
svtplay-dl v4.0,   snapshot 20210625_075225,   and snapshot 20210516_200220
MS WIndows 8.1
Python 3.8.10
ffmpeg 4.4

**There is no audio stream included in the resulting .mp4-file**
command used: svtplay-dl --live --capture_time 2 --stream-priority hls https://www.svtplay.se/kanaler/svt1
INFO: Outfile: svt.1.svt.play-svtplay.ts
INFO: Selected to download hls, bitrate: 3744 format: h264
[38/40][======================================..] DU: 0:02:01
INFO: Merge audio and video into svt.1.svt.play-svtplay.mp4
INFO: Merging done, removing old files.
The resulting .mp4-file does not include any audio stream.

Another example
command used: svtplay-dl --verbose --live --capture_time 2 --stream-priority hls https://www.svtplay.se/kanaler/svt24
...
[38/38][========================================] DU: 0:02:01DEBUG [1625008760.2
044294] c:\svtplaydll\svtplay-dl_sshot_20210625_075225py\svtplay_dl\utils\http.py/request: HTTP getting 'https://svtb-c.akamaized.net/se/svtb/fe02730f-7e28-4f34-b9bc-b0ce023e9909/hls-v4/v4-552124.ts'
DEBUG [1625008760.2194324] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://svtb-c.akamaized.net:443 "GET /se/svtb/fe02730f-7e28-4f34-b9bc-b0ce023e9909/hls-v4/v4-552124.ts HTTP/1.1" 200 1495352
INFO [1625008760.6695194] c:\svtplaydll\svtplay-dl_sshot_20210625_075225py\svtplay_dl\postprocess\__init__.py/merge: Merge audio and video into svt.24.svt.play-svtplay.mp4
INFO [1625008760.9345708] c:\svtplaydll\svtplay-dl_sshot_20210625_075225py\svtplay_dl\postprocess\__init__.py/merge: Merging done, removing old files.
The resulting .mp4-file does not include any audio stream.

**Consistent crash at attempting to capture from https://www.svtplay.se/kanaler/svt2**
command used: svtplay-dl --verbose --live --stream-priority hls https://www.svtplay.se/kanaler/svt2
Traceback (most recent call last):
  File "c:\svtplaydll\svtplay-dl_sshot_20210625_075225py\__main__.py", line 15,in <module>
    svtplay_dl.main()
  File "c:\svtplaydll\svtplay-dl_sshot_20210625_075225py\svtplay_dl\__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "c:\svtplaydll\svtplay-dl_sshot_20210625_075225py\svtplay_dl\utils\getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "c:\svtplaydll\svtplay-dl_sshot_20210625_075225py\svtplay_dl\utils\getmedia.py", line 112, in get_one_media
    for i in streams:
  File "c:\svtplaydll\svtplay-dl_sshot_20210625_075225py\svtplay_dl\service\svtplay.py", line 61, in get
    yield from videos
  File "c:\svtplaydll\svtplay-dl_sshot_20210625_075225py\svtplay_dl\service\svtplay.py", line 112, in _get_video
    yield from dashparse(self.config, self.http.request("get", i["url"]), i["url"], output=self.output)
  File "c:\svtplaydll\svtplay-dl_sshot_20210625_075225py\svtplay_dl\fetcher\dash.py", line 217, in dashparse
    yield from _dashparse(config, res.text, url, output, cookies=res.cookies, **kwargs)
  File "c:\svtplaydll\svtplay-dl_sshot_20210625_075225py\svtplay_dl\fetcher\dash.py", line 232, in _dashparse
    attributes.set("availabilityStartTime", parse_dates(xml.attrib["availabilityStartTime"]))
  File "c:\svtplaydll\svtplay-dl_sshot_20210625_075225py\svtplay_dl\fetcher\dash.py", line 314, in parse_dates
    raise ValueError(f"Can't parse date format: {date_str}")
ValueError: Can't parse date format: 2021-06-09T12:32:43.51611449Z

**Sometimes a crash at attempting to capture from https://www.svtplay.se/kanaler/svt1**
_In this case I used the old snapshot 20210516_200220. I have not seen this crash with the other two newer versions of svtplay-dl that I've used here but include the observation since it seems to relate to audio stream handling._
command used: svtplay-dl --live --capture_time 2 --stream-priority hls https://www.svtplay.se/kanaler/svt1
INFO: Outfile: svt.1.svt.play-svtplay.ts
INFO: Selected to download hls, bitrate: 3744 format: h264
[38/38][========================================] DU: 0:02:01
INFO: Muxing svt.1.svt.play-svtplay.ts into svt.1.svt.play-svtplay.mp4
Traceback (most recent call last):
  File "c:\svtplaydll\svtplay-dl_sshot_20210516_200220py\__main__.py", line 15,
in <module>
    svtplay_dl.main()
  File "c:\svtplaydll\svtplay-dl_sshot_20210516_200220py\svtplay_dl\__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "c:\svtplaydll\svtplay-dl_sshot_20210516_200220py\svtplay_dl\utils\getmedia.py", line 62, in get_media
    get_one_media(stream)
  File "c:\svtplaydll\svtplay-dl_sshot_20210516_200220py\svtplay_dl\utils\getmedia.py", line 245, in get_one_media
    post.remux()
  File "c:\svtplaydll\svtplay-dl_sshot_20210516_200220py\svtplay_dl\postprocess\__init__.py", line 57, in remux
    if orig_filename.suffix == ".ts" and streams and "aac" in _getcodec(streams,
 audiotrack):
TypeError: argument of type 'NoneType' is not iterable

-------------------

I find live recording convenient to capture items not available via SVTplay.
One example is the feature film "Kill me three times" which is scheduled to be broadcast on svt2 tomorrow evening.

**Comment by spaam** [comment]
the first , it seems like they changed so audio and video is in separate files now,  the fix for #1333 will fix this issue too. 

how many times do they change the dates? first it was like 22.22, then it was 11.451554796,  now its 43.51611449. they really like to change it every now and then. i guess i need to find a better way to fix it 🤔 

the  last postprocess should be fixed already in a newer version and snapshot.

**Comment by pythonuser3856** [comment]
Thanks for the quick comment !

**Comment by pythonuser3856** [comment]
I got a comment from another user of svtplay-dl that an old snapshot-version, version 20190104_235221, actually works such that an .mp4-file with both video and audio is created.
I just tested myself with "https://www.svtplay.se/kanaler/svt2" and can confirm.

**Comment by pythonuser3856** [comment]
Sadly, the workaround using the old snapshot-version of svtplay-dl to capture media from the broadcast channel at svtplay.se no longer works.

This issue was initially reported with version 4.0 of svtplay-dl.
Now I've tested with the new version 4.4 and the issue remains.
The seemingly successful resulting .mp4-file includes a video stream only, no audio.
The issue is at hand both at capturing from svt channel and at capturing from live items available via the svtplay repository.

**By that it's currently no longer possible to capture using svtplay-dl and the switch "--live", as far as I can see.**

I used the snapshot-version from 20190104_235221 as late as yesterday to capture the movie "Brooklyn" since that movie is not made available for watching via the svtplay repository.
But today this snapshot-version of svtplay-dl no longer works, the verbose printout shows that there is now a change in date format:

py c:\svtplaydll\svtplay-dl_sshot_20190104_235221py\_main__.py --live --verbose --subtitle --stream-priority hls -c 3 https://www.stplay.se/kanaler/svt1

Traceback (most recent call last):
  File "c:\svtplaydll\svtplay-dl_sshot_20190104_235221py\__main__.py", line 13, in <module>
    svtplay_dl.main()
  File "c:\svtplaydll\svtplay-dl_sshot_20190104_235221py\svtplay_dl\__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "c:\svtplaydll\svtplay-dl_sshot_20190104_235221py\svtplay_dl\utils\getmedia.py", line 56, in get_media
    get_one_media(stream)
  File "c:\svtplaydll\svtplay-dl_sshot_20190104_235221py\svtplay_dl\utils\getmedia.py", line 105, in get_one_media
    for i in streams:
  File "c:\svtplaydll\svtplay-dl_sshot_20190104_235221py\svtplay_dl\service\svtplay.py", line 47, in get
    for i in videos:
  File "c:\svtplaydll\svtplay-dl_sshot_20190104_235221py\svtplay_dl\service\svtplay.py", line 122, in _get_video
    streams = dashparse(self.config, self.http.request("get", i["url"]), i["url"], output=self.output)
  File "c:\svtplaydll\svtplay-dl_sshot_20190104_235221py\svtplay_dl\fetcher\dash.py", line 143, in dashparse
    return _dashparse(config, res.text, url, output, res.cookies)
  File "c:\svtplaydll\svtplay-dl_sshot_20190104_235221py\svtplay_dl\fetcher\dash.py", line 161, in _dashparse
    datetime_start = parse_dates(availabilityStartTime)
  File "c:\svtplaydll\svtplay-dl_sshot_20190104_235221py\svtplay_dl\fetcher\dash.py", line 199, in parse_dates
    raise ValueError("Can't parse date format: {0}".format(date_str))
ValueError: Can't parse date format: 2021-09-13T09:24:26.616420518Z

**Comment by pythonuser3856** [comment]
Any news / thoughts / insights on this one (and on #1333) ?

**Comment by spaam** [comment]
im going to rewrite the way we download files to be a more generic way. but im a bit stuck how to design it. wrote something and removed it later because im not happy with it. i want to use it with vod, live and with special encrypted subtitles. 

the HLS and DASH are more or less the same while downloading files. the only thing that is different is the playlist stuff to get what files to download.  i had some idea about split things out to its own functions for parsing playlists and a function for encrypted HLS data.  add some thread to the mix.  downside going to be it will eat more space while downloading the files and the two progressbars going away (yay).  for vod it will be faster.  🤔

**Comment by pythonuser3856** [comment]
Thank's for letting me know the intended way forward
