### ISSUE TITLE
Crash when try to download a video from svtplay.se

### ISSUE THREAD

**Issue by whome** [spaam/svtplay-dl#1405]
### svtplay-dl versions: 3.5

Run `svtplay-dl --version`

### Operating system and Python version: Linux Mint 20.1 Cinnamon

Name and version of the operating system and python version (run `python --version`)
Python 3.8.10

### What is the issue:
crash when try to download i program from svtplay.se

svtplay-dl --verbose https://www.svtplay.se/klipp/31109266/vader-sa-paverkas-din-kropp-av-hetta
DEBUG [1627760572.226326] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 3.5
DEBUG [1627760572.22717] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1627760572.2272286] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/klipp/31109266/vader-sa-paverkas-din-kropp-av-hetta'
DEBUG [1627760572.2284045] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1627760572.7164536] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /klipp/31109266/vader-sa-paverkas-din-kropp-av-hetta HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 69, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 61, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 85, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 220, in outputfilename
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 241, in seasoninfo
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 265, in _find_season
KeyError: 'positionInSeason'

and

svtplay-dl --verbose https://www.svtplay.se/klipp/31109266/vader-sa-paverkas-din-kropp-av-hetta?id=eWXkrX9
DEBUG [1627760671.766185] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 3.5
DEBUG [1627760671.7670841] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1627760671.7671418] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/klipp/31109266/vader-sa-paverkas-din-kropp-av-hetta?id=eWXkrX9'
DEBUG [1627760671.7684114] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1627760671.8680544] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /klipp/31109266/vader-sa-paverkas-din-kropp-av-hetta?id=eWXkrX9 HTTP/1.1" 200 114421
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 69, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 61, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 85, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 220, in outputfilename
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 241, in seasoninfo
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 265, in _find_season
KeyError: 'positionInSeason'

**Comment by spaam** [comment]
you are using 3.5 of the script, please update to version 4.2 and see if you have the same issue.

**Comment by whome** [comment]
I have trouble to upgrade to version 4.2.

I have use these commands but can not upgrade to 4.2 and of some reason still have version 3.5.

erik@erik-MACH-WX9:~$ sudo apt-get update
[sudo] password for erik:         
Hit:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://ppa.launchpad.net/opencpn/opencpn/ubuntu focal InRelease          
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease                         
Hit:4 http://repository.spotify.com stable InRelease                           
Hit:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease                 
Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease               
Hit:7 https://apt.svtplay-dl.se svtplay-dl InRelease                           
Hit:8 https://packages.microsoft.com/repos/ms-teams stable InRelease           
Hit:9 http://security.ubuntu.com/ubuntu focal-security InRelease               
Hit:10 http://archive.canonical.com/ubuntu focal InRelease                     
Ign:11 http://packages.linuxmint.com ulyssa InRelease                          
Hit:12 http://packages.linuxmint.com ulyssa Release
Hit:13 https://repo.nordvpn.com/deb/nordvpn/debian stable InRelease
Reading package lists... Done
erik@erik-MACH-WX9:~$ sudo apt-get install svtplay-dl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
svtplay-dl is already the newest version (4.2).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
erik@erik-MACH-WX9:~$ svtplay-dl --version
svtplay-dl 3.5

**Comment by spaam** [comment]
what does `which svtplay-dl` say? i have a strong feeling that it say `/usr/local/bin/svtplay-dl`  and not `/usr/bin/svtplay-dl`.  
if you dont remember how you installed it, try `pip3 list | grep svtplay`  if its there try `sudo pip3 uninstall svtplay-dl`.  if its not in the `pip3 list` output. you can just do `sudo rm /usr/local/bin/svtplay-dl`. then it should say 4.2 when you do `svtplay-dl --version`

**Comment by whome** [comment]
You was absolutely correct. 
Now is it version 4.2 and everything is working fine! 
Thanks
