### ISSUE TITLE
DR.dk crashes

### ISSUE THREAD

**Issue by kamakamadaun** [spaam/svtplay-dl#1407]
### svtplay-dl versions:
svtplay-dl 4.2

### Operating system and Python version:
Windows 10
Python 3.9.6

Tried on two different computers.

### What is the issue:
```
svtplay-dl -A --verbose "https://www.dr.dk/drtv/saeson/gurli-gris_252484"
```
gives the following error. Trying a single episode has the same issue.

```
DEBUG [1628337742.411676] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.2
DEBUG [1628337742.412681] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: dr
DEBUG [1628337742.4146762] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.dr.dk/drtv/saeson/gurli-gris_252484'
DEBUG [1628337742.4196625] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.dr.dk:443
DEBUG [1628337742.7318869] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.dr.dk:443 "GET /drtv/saeson/gurli-gris_252484 HTTP/1.1" 200 None
DEBUG [1628337742.7608013] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.dr.dk/drtv/saeson/gurli-gris_252484'
DEBUG [1628337742.8583179] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.dr.dk:443 "GET /drtv/saeson/gurli-gris_252484 HTTP/1.1" 200 None
DEBUG [1628337742.8912182] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.dr.dk/drtv/saeson/gurli-gris_230018'
DEBUG [1628337743.288043] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.dr.dk:443 "GET /drtv/saeson/gurli-gris_230018 HTTP/1.1" 200 None
DEBUG [1628337743.3359091] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.dr.dk/drtv/saeson/gurli-gris_236226'
DEBUG [1628337743.6676915] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.dr.dk:443 "GET /drtv/saeson/gurli-gris_236226 HTTP/1.1" 200 None
DEBUG [1628337743.7005813] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: dr
INFO [1628337743.7005813] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_all_episodes: Episode 1 of 84
INFO [1628337743.7018516] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_all_episodes: Url: https://www.dr.dk/drtv/se/gurli-gris_-sandslottet_236261
DEBUG [1628337743.702183] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.dr.dk/drtv/se/gurli-gris_-sandslottet_236261'
DEBUG [1628337743.7045524] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.dr.dk:443
DEBUG [1628337744.021704] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.dr.dk:443 "GET /drtv/se/gurli-gris_-sandslottet_236261 HTTP/1.1" 200 None
DEBUG [1628337744.0566094] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://isl.dr-massive.com/api/authorization/anonymous-sso?device=web_browser&ff=idp%2Cldp&lang=da'
DEBUG [1628337744.0605993] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): isl.dr-massive.com:443
DEBUG [1628337744.1923382] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://isl.dr-massive.com:443 "POST /api/authorization/anonymous-sso?device=web_browser&ff=idp%2Cldp&lang=da HTTP/1.1" 200 None
DEBUG [1628337744.1933482] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://isl.dr-massive.com/api/account/items/236261/videos?delivery=stream&device=web_browser&ff=idp%2Cldp&lang=da&resolution=HD-1080&sub=Anonymous'
DEBUG [1628337744.2313402] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://isl.dr-massive.com:443 "GET /api/account/items/236261/videos?delivery=stream&device=web_browser&ff=idp%2Cldp&lang=da&resolution=HD-1080&sub=Anonymous HTTP/1.1" 200 None
DEBUG [1628337744.2333384] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://drod09l-vh.akamaihd.net/i/dk/encrypted/streaming/48/60e6b9cbac5a6109d833a748/Gurli-Gris_f58ab2dfec4d480bb928343035a52dd4_,500,1100,2000,3500,5500,.mp4.csmil/master.m3u8'
DEBUG [1628337744.239319] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): drod09l-vh.akamaihd.net:443
DEBUG [1628337744.535597] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://drod09l-vh.akamaihd.net:443 "GET /i/dk/encrypted/streaming/48/60e6b9cbac5a6109d833a748/Gurli-Gris_f58ab2dfec4d480bb928343035a52dd4_,500,1100,2000,3500,5500,.mp4.csmil/master.m3u8 HTTP/1.1" 200 1994
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 104, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 93, in get_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 112, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\dr.py", line 62, in get
IndexError: list index out of range
```

**Comment by SweDennis** [comment]
```
dennis@lenovo:~$ uname -a
Linux lenovo 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
dennis@lenovo:~$ svtplay-dl --version
svtplay-dl 4.2
dennis@lenovo:~$ python --version
Python 3.8.10
dennis@lenovo:~$ 
```
Nothing much to add, apart from confirming from a different OS, albeit same python version.
Just one thing, though, it says python version 3.9.6 on top, but the log references 3.8.10.
Might not matter but still ...

Using a Swedish IP I get Geoblocked, using a Danish IP, however, I get the below:

```
dennis@lenovo:~$ svtplay-dl -A -v "https://www.dr.dk/drtv/saeson/gurli-gris_252484"
DEBUG [1628582926.0892575] /usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/svtplay_dl/utils/getmedia.py/get_media: version: 4.2
DEBUG [1628582926.089592] /usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/svtplay_dl/service/__init__.py/__init__: service: dr
DEBUG [1628582926.089942] /usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.dr.dk/drtv/saeson/gurli-gris_252484'
DEBUG [1628582926.0912864] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.dr.dk:443
DEBUG [1628582926.2550051] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.dr.dk:443 "GET /drtv/saeson/gurli-gris_252484 HTTP/1.1" 200 None
DEBUG [1628582926.3045409] /usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.dr.dk/drtv/saeson/gurli-gris_252484'
DEBUG [1628582926.376405] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.dr.dk:443 "GET /drtv/saeson/gurli-gris_252484 HTTP/1.1" 200 None
DEBUG [1628582926.408832] /usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.dr.dk/drtv/saeson/gurli-gris_230018'
DEBUG [1628582926.4797852] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.dr.dk:443 "GET /drtv/saeson/gurli-gris_230018 HTTP/1.1" 200 None
DEBUG [1628582926.4964366] /usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.dr.dk/drtv/saeson/gurli-gris_236226'
DEBUG [1628582926.6211278] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.dr.dk:443 "GET /drtv/saeson/gurli-gris_236226 HTTP/1.1" 200 None
DEBUG [1628582926.6507215] /usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/svtplay_dl/service/__init__.py/__init__: service: dr
INFO [1628582926.6508224] /usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/svtplay_dl/utils/getmedia.py/get_all_episodes: Episode 1 of 81
INFO [1628582926.6508663] /usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/svtplay_dl/utils/getmedia.py/get_all_episodes: Url: https://www.dr.dk/drtv/se/gurli-gris_-sandslottet_236261
DEBUG [1628582926.6509142] /usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.dr.dk/drtv/se/gurli-gris_-sandslottet_236261'
DEBUG [1628582926.6519117] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.dr.dk:443
DEBUG [1628582926.777852] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.dr.dk:443 "GET /drtv/se/gurli-gris_-sandslottet_236261 HTTP/1.1" 200 60632
DEBUG [1628582926.809645] /usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://isl.dr-massive.com/api/authorization/anonymous-sso?device=web_browser&ff=idp%2Cldp&lang=da'
DEBUG [1628582926.8120236] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): isl.dr-massive.com:443
DEBUG [1628582926.9947374] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://isl.dr-massive.com:443 "POST /api/authorization/anonymous-sso?device=web_browser&ff=idp%2Cldp&lang=da HTTP/1.1" 200 None
DEBUG [1628582926.9955113] /usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://isl.dr-massive.com/api/account/items/236261/videos?delivery=stream&device=web_browser&ff=idp%2Cldp&lang=da&resolution=HD-1080&sub=Anonymous'
DEBUG [1628582927.047201] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://isl.dr-massive.com:443 "GET /api/account/items/236261/videos?delivery=stream&device=web_browser&ff=idp%2Cldp&lang=da&resolution=HD-1080&sub=Anonymous HTTP/1.1" 200 None
DEBUG [1628582927.04825] /usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://drod09l-vh.akamaihd.net/i/dk/encrypted/streaming/48/60e6b9cbac5a6109d833a748/Gurli-Gris_f58ab2dfec4d480bb928343035a52dd4_,500,1100,2000,3500,5500,.mp4.csmil/master.m3u8'
DEBUG [1628582927.050434] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): drod09l-vh.akamaihd.net:443
DEBUG [1628582927.3399765] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://drod09l-vh.akamaihd.net:443 "GET /i/dk/encrypted/streaming/48/60e6b9cbac5a6109d833a748/Gurli-Gris_f58ab2dfec4d480bb928343035a52dd4_,500,1100,2000,3500,5500,.mp4.csmil/master.m3u8 HTTP/1.1" 200 2014
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==4.2', 'svtplay-dl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/svtplay_dl/utils/getmedia.py", line 61, in get_media
    get_all_episodes(stream, url, options)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/svtplay_dl/utils/getmedia.py", line 93, in get_all_episodes
    get_one_media(substream)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/svtplay_dl/utils/getmedia.py", line 112, in get_one_media
    for i in streams:
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2-py3.8.egg/svtplay_dl/service/dr.py", line 62, in get
    yield subtitle(copy.copy(self.config), "wrst", video["subtitles"][0]["link"], output=self.output)
IndexError: list index out of range
```
