### ISSUE TITLE
TV4 - KeyError: 'audio-aacl-93'

### ISSUE THREAD

**Issue by SYSophie** [spaam/svtplay-dl#1409]
### svtplay-dl versions:

svtplay-dl 4.2

### Operating system and Python version:

MacOS Big Sur, Python 3.9.6

### What is the issue:

```
svtplay-dl --verbose "https://www.tv4play.se/program/kronofogden-knackar-på/del-17-säsong-4/3910568"
DEBUG [1628845074.796855] /usr/local/lib/python3.9/site-packages/svtplay_dl-4.2-py3.9.egg/svtplay_dl/utils/getmedia.py/get_media: version: 4.2
DEBUG [1628845074.797527] /usr/local/lib/python3.9/site-packages/svtplay_dl-4.2-py3.9.egg/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1628845074.797559] /usr/local/lib/python3.9/site-packages/svtplay_dl-4.2-py3.9.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/kronofogden-knackar-på/del-17-säsong-4/3910568'
DEBUG [1628845074.8737102] /usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1628845075.1321301] /usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/kronofogden-knackar-p%C3%A5/del-17-s%C3%A4song-4/3910568 HTTP/1.1" 200 None
DEBUG [1628845075.1386921] /usr/local/lib/python3.9/site-packages/svtplay_dl-4.2-py3.9.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://playback-api.b17g.net/media/3910568?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome'
DEBUG [1628845075.1884239] /usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback-api.b17g.net:443
DEBUG [1628845075.458852] /usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/3910568?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome HTTP/1.1" 200 1016
DEBUG [1628845075.4603121] /usr/local/lib/python3.9/site-packages/svtplay_dl-4.2-py3.9.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/0779b/pid200028961_3910568(3910568_ISMUSP).ism/pid200028961_3910568(3910568_ISMUSP).m3u8?hls_no_audio_only=true'
DEBUG [1628845075.5148869] /usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): lbs-usp-hls-vod.cmore.se:443
DEBUG [1628845075.8050401] /usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/0779b/pid200028961_3910568(3910568_ISMUSP).ism/pid200028961_3910568(3910568_ISMUSP).m3u8?hls_no_audio_only=true HTTP/1.1" 200 625
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==4.2', 'svtplay-dl')
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.9/site-packages/svtplay_dl-4.2-py3.9.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.9/site-packages/svtplay_dl-4.2-py3.9.egg/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.9/site-packages/svtplay_dl-4.2-py3.9.egg/svtplay_dl/utils/getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "/usr/local/lib/python3.9/site-packages/svtplay_dl-4.2-py3.9.egg/svtplay_dl/utils/getmedia.py", line 112, in get_one_media
    for i in streams:
  File "/usr/local/lib/python3.9/site-packages/svtplay_dl-4.2-py3.9.egg/svtplay_dl/service/tv4play.py", line 77, in get
    yield from hlsparse(
  File "/usr/local/lib/python3.9/site-packages/svtplay_dl-4.2-py3.9.egg/svtplay_dl/fetcher/hls.py", line 46, in hlsparse
    yield from _hlsparse(config, res.text, url, output, cookies=res.cookies, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/svtplay_dl-4.2-py3.9.egg/svtplay_dl/fetcher/hls.py", line 125, in _hlsparse
    for group in media[audio_group]:
KeyError: 'audio-aacl-93'

```

URI for audio is missing in m3u8.

**Suggestion**: 
Might be good to be able to fall back on "#variants" if this would be missing. Seems like pretty many of the recent episodes of this particular show is missing this information.

I assume that this might affect other series too, but I have tested a few more and haven't been able to find this issue again.

**Comment by spaam** [comment]
you are somewhat right, the issue was that i forgot to check if the audio group had some values after the URI is empty. i fixed this is master now.

**Comment by spaam** [comment]
it reminds me that i should add some tests for this stuff, just similar as i have for dash stuff 🤔

**Comment by SYSophie** [comment]
> you are somewhat right, the issue was that i forgot to check if the audio group had some values after the URI is empty. i fixed this is master now.

Nice seems to work

Thanks for fast fix 👍

**Comment by spaam** [comment]
4.3 got a fix for this if you dont liketo use snapshots :)
