### ISSUE TITLE
ValueError: check_hostname requires server_hostname

### ISSUE THREAD

**Issue by fyrekrig** [spaam/svtplay-dl#1411]
### svtplay-dl versions: x86 4.2

Run `svtplay-dl --version`

### Operating system and Python version: Windows 10

Name and version of the operating system and python version (run `python --version`)

### What is the issue:

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

    svtplay-dl --verbose https://www.example.com
D:\PortApps\SVT\svtplay-dl>svtplay-dl https://www.svtplay.se/video/24064454/det-svenska-popundret/det-svenska-popundret-sasong-1-ma-basta-lat-vinna
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 104, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 63, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 98, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\output.py", line 120, in filename
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py", line 66, in get_urldata
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py", line 42, in request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\requests\sessions.py", line 542, in request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\requests\sessions.py", line 655, in send
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\requests\adapters.py", line 439, in send
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connection.py", line 359, in connect
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\ssl.py", line 500, in wrap_socket
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\ssl.py", line 997, in _create
ValueError: check_hostname requires server_hostname

What am I doing wrong?

**Comment by spaam** [comment]
i have never seen this error before.
are you using a proxy?
can you try adding `"` around the url like this `"https://www.svtplay.se/video/24064454/det-svenska-popundret/det-svenska-popundret-sasong-1-ma-basta-lat-vinna"`?

**Comment by fyrekrig** [comment]
Thanks your reply!

Yes, I am using a proxy  (psiphon3). As I am in Thailand I have to use a proxy with Swedish IP to get access to all SVT Play videos.
Have now tried with the same URL with no proxy and get following reply:

D:\PortApps\SVT\svtplay-dl>svtplay-dl https://www.svtplay.se/video/24064454/det-svenska-popundret/det-svenska-popundret-sasong-1-ma-basta-lat-vinna
ERROR: No videos found.

D:\PortApps\SVT\svtplay-dl>

Same response with quote marks!

**Comment by spaam** [comment]
How did you write your proxy config? like `https://0.00.0.00:8888` or like `0.00.0.00:8888`? have you tried both ways? 

if that does not work. you can try using `--http-header x-forwarded-for=0.0.0.0`  replace `0.0.0.0` with a swedish ip.

**Comment by fyrekrig** [comment]
Don't know where to put in proxy info into the string

The proxy info is 127.0.0.1  49699  IP:79.142.76.233

D:\PortApps\SVT\svtplay-dl>D:\PortApps\SVT\svtplay-dl>"https://127.0.0.1:49699--www.svtplay.se/video/24064454/det-svenska-popundret/det-svenska-popundret-sasong-1-ma-basta-lat-vinna"

Got this back;

D:\PortApps\SVT\svtplay-dl>D:\PortApps\SVT\svtplay-dl>"https://127.0.0.1:49699--www.svtplay.se/video/24064454/det-svenska-popundret/det-svenska-popundret-sasong-1-ma-basta-lat-vinna"
The filename, directory name, or volume label syntax is incorrect.

D:\PortApps\SVT\svtplay-dl>

**Comment by spaam** [comment]
you said `I have to use a proxy with Swedish IP` ? are you using a proxy or what? i cant really help if you say you do and then later say you dont do it.  you cant use a http url to  download a video like you did in the latest message.

**Comment by fyrekrig** [comment]
Sorry, but don't understand your last message!

I never said I don't use a proxy!

I use proxy! And the details are 127.0.0.1:49699 
I end up with a Swedish IP being: 79.142.76.233 

As I tried to explain in my previous message I don't know where to put in -- proxy proxy  into the main string. 
Apparently I did it wrong.

Can you please give me the full string with proxy info inserted .

**Comment by fyrekrig** [comment]
Tried with something else. Still no luck

D:\PortApps\SVT\svtplay-dl>svtplay-dl --127.0.0.1:49774 https://www.svtplay.se/video/24064454/det-svenska-popundret/det-svenska-popundret-sasong-1-ma-basta-lat-vinna
usage: svtplay-dl [-h] [--version] [-o output] [--subfolder] [--config configfile] [-f] [-r] [-l] [-c capture_time]
                  [-s] [--silent-semi] [-u USERNAME] [-p PASSWORD] [-t] [-g] [--get-only-episode-url]
                  [--dont-verify-ssl-cert] [--http-header header1=value;header2=value2]
                  [--cookies cookie1=value;cookie2=value2] [--exclude WORD1,WORD2,...] [--after-date yyyy-MM-dd]
                  [--proxy proxy] [-v] [--nfo] [--force-nfo] [--only-audio] [--only-video] [-q quality] [-Q amount]
                  [-P preferred] [--list-quality] [--stream-priority dash,hls,http] [--format-preferred h264,h264-51]
                  [--audio-language AUDIO_LANGUAGE] [--audio-role AUDIO_ROLE] [-S] [-M] [--force-subtitle]
                  [--require-subtitle] [--all-subtitles] [--raw-subtitles] [--convert-subtitle-colors] [-A]
                  [--all-last NN] [--include-clips] [--cmore-operatorlist] [--cmore-operator operator] [--no-remux]
                  [--no-merge] [--no-postprocess] [--keep-original] [--output-format {mp4,mkv}]
                  [urls [urls ...]]
svtplay-dl: error: unrecognized arguments: --127.0.0.1:49774

Will appreciate your comment.

**Comment by fyrekrig** [comment]
It looks like you are not going to help me. Please tell me why?

**Comment by spaam** [comment]
why i have not helped you is because i just taking a break from computers after my day job and do other things on my spare time :)

> Sorry, but don't understand your last message!
> 
> I never said I don't use a proxy!
> ...
> I use proxy! And the details are 127.0.0.1:49699
> 

seriously you keep changing your answer and stuff in your response that is in conflict with previous responses, if these keep happening i cant really help you sadly.

If you use a proxy, how do you define it?  is it by system level or just a environment variable?  is it a http based proxy or a socks proxy?
is it a http proxy,  have you tried using `http://127.0.0.1:49699`  instead of  only `127.0.0.1:496999`?   is it a socks5 proxy , have you tried using `socks5://127.0.0.1:49699` ? 

if you dont use it on a system level or environment variable. you need to use `svtplay-dl --proxy VALUE`  change the `VALUE` text with the correct answer above.

**Comment by fyrekrig** [comment]
OK we try again.
When I access SVT Play I ALWAYS have to use a Swedish IP. Never said anything else!
I get that by either use 
psison3 with Swedish based server 127.0.0.1:62095 IP:37.120.153.138
or
AdvOr with Swedish exit node 127.0.0.1:9050 IP:171.25.193.78

"is it by system level or just a environment variable?"
Don't `know
"is it a http based proxy or a socks proxy?``
Don't know

**Comment by Candolah** [comment]
I live in Singapore and having the same problems. 
Using psiphon and Tor.
Are you not going to reply? Or is  the problem impossible to solve?

**Comment by spaam** [comment]
@Candolah  i have never used this `psiphon`  thing.  its hard to help people when i dont get any answer to my questions and they skip half of them.  if you and/or @fyrekrig want help. please start answering my questions if not i cant help you guys.

**Comment by Candolah** [comment]
I don't know what you are complaing about. You should have enought info to make a constructive reply.
If you don't know what Psiphon3 is, it should be easy to find out.  https://www.psiphon3.com/en/index.html
If using Psiphon3 or Tor with Swedish exit nodes result in an environment variable, HTTP or Socks proxy I don't know and
don't know how to find out. Maybe you can help?
Why don't you post a svt-dl string with the info you got so I can try it out

**Comment by fyrekrig** [comment]
Had another go.

Also put proxy at  Environmet variable. See screenshot
![001](https://user-images.githubusercontent.com/29265156/133878484-5cbf7b29-83d4-4b52-b9c3-39657d04aa85.jpg)


set http_proxy=http://194.59.250.67.67:50162

svtplay-dl https://www.svtplay.se/video/26643218/bast-i-test/bast-i-test-sasong-4-bonusavsnitt?id=e5wyxrg

svtplay-dl>set http_proxy=http://194.59.250.67.67:50162

svtplay-dl>svtplay-dl "https://www.svtplay.se/video/26643218/bast-i-test/bast-i-test-sasong-4-bonusavsnitt?id=e5wyxrg"
ERROR: No videos found.

Hope you are not to pissed off to reply!
