### ISSUE TITLE
Svtplay-dl - Barnkanalen no longer works

### ISSUE THREAD

**Issue by gr3p** [spaam/svtplay-dl#1414]
Svtplay-dl version: 4.2

Tested in Win and Ubuntu/WSL.

Python 2.7.17 --> Ubuntu test.
Python 3.9.0 --> Win 10 test.

Example url: 
 svtplay-dl https://www.svt.se/barnkanalen/barnplay/bolibompafamiljen/jdPAmQy/ --verbose

Error same error on both linux or win platform:
svtplay-dl https://www.svt.se/barnkanalen/barnplay/bolibompafamiljen/jdPAmQy/ --verbose
DEBUG [1631199514.4704292] /usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py/get_media: version: 4.2
DEBUG [1631199514.4706922] /usr/lib/python3/dist-packages/svtplay_dl/service/__init__.py/__init__: service: barnkanalen
DEBUG [1631199514.4707525] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svt.se/barnkanalen/barnplay/bolibompafamiljen/jdPAmQy/'
DEBUG [1631199514.4742393] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svt.se
DEBUG [1631199516.0355] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svt.se:443 "GET /barnkanalen/barnplay/bolibompafamiljen/jdPAmQy/ HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3/dist-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 112, in get_one_media
    for i in streams:
  File "/usr/lib/python3/dist-packages/svtplay_dl/service/barnkanalen.py", line 44, in get
    title = janson["props"]["pageProps"]["initialState"]["gridContent"]["featuredContent"]["name"]
KeyError: 'gridContent'

**Comment by SweDennis** [comment]
Absolutely confirmed:

```
dennis@lenovo:~$ svtplay-dl https://www.svt.se/barnkanalen/barnplay/bolibompafamiljen/jdPAmQy/ --verbose
DEBUG [1631204821.3586624] /usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2+5.g404373e-py3.8.egg/svtplay_dl/utils/getmedia.py/get_media: version: 4.2+5.g404373e
DEBUG [1631204821.3593068] /usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2+5.g404373e-py3.8.egg/svtplay_dl/service/__init__.py/__init__: service: barnkanalen
DEBUG [1631204821.3594267] /usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2+5.g404373e-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svt.se/barnkanalen/barnplay/bolibompafamiljen/jdPAmQy/'
DEBUG [1631204821.3621793] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svt.se:443
DEBUG [1631204821.510355] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svt.se:443 "GET /barnkanalen/barnplay/bolibompafamiljen/jdPAmQy/ HTTP/1.1" 200 110304
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==4.2+5.g404373e', 'svtplay-dl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2+5.g404373e-py3.8.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2+5.g404373e-py3.8.egg/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2+5.g404373e-py3.8.egg/svtplay_dl/utils/getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2+5.g404373e-py3.8.egg/svtplay_dl/utils/getmedia.py", line 112, in get_one_media
    for i in streams:
  File "/usr/local/lib/python3.8/dist-packages/svtplay_dl-4.2+5.g404373e-py3.8.egg/svtplay_dl/service/barnkanalen.py", line 44, in get
    title = janson["props"]["pageProps"]["initialState"]["gridContent"]["featuredContent"]["name"]
KeyError: 'gridContent'
dennis@lenovo:~$ 
```
```
dennis@lenovo:~$ uname -a
Linux lenovo 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
dennis@lenovo:~$ svtplay-dl --version
svtplay-dl 4.2+5.g404373e
dennis@lenovo:~$ python --version
Python 3.8.10
dennis@lenovo:~$ 
```

**Comment by spaam** [comment]
4.3 got a fix for this :)
