### ISSUE TITLE
tv4play SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Bofinken** [spaam/svtplay-dl#1421]
### svtplay-dl versions:

Run `svtplay-dl --version`

### Operating system and Python version:

Name and version of the operating system and python version (run `python --version`)

### What is the issue:

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

    svtplay-dl --verbose https://www.example.com
svtplay-dl 4.5-1-gadcaa73
svtplay-dl -S -o "H:\TV/vit sand 1" https://www.tv4play.se/program/vit-sand/del-1-s%C3%A4song-1/13339049

svtplay-dl  --verbose -S -o "H:\TV/vit sand" https://www.tv4play.se/program/vit-sand/del-1-sA4song-1/13339049
DEBUG [1633558573.9955213] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.5-1-gadcaa73
DEBUG [1633558573.9971068] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: tv4play
DEBUG [1633558573.9971068] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/program/vit-sand/del-1-sA4song-1/13339049'
DEBUG [1633558574.0335112] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1633558574.336257] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/program/vit-sand/del-1-sA4song-1/13339049'): Retry(total=4, connect=5, read=5, redirect=None, status=None)
WARNING [1633558574.336257] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/urlopen: Retrying (Retry(total=4, connect=5, read=5, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /program/vit-sand/del-1-sA4song-1/13339049
DEBUG [1633558574.3382552] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (2): www.tv4play.se:443
DEBUG [1633558574.422487] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/program/vit-sand/del-1-sA4song-1/13339049'): Retry(total=3, connect=5, read=5, redirect=None, status=None)
WARNING [1633558575.0383215] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/urlopen: Retrying (Retry(total=3, connect=5, read=5, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /program/vit-sand/del-1-sA4song-1/13339049
DEBUG [1633558575.0392857] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (3): www.tv4play.se:443
DEBUG [1633558575.1581032] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/program/vit-sand/del-1-sA4song-1/13339049'): Retry(total=2, connect=5, read=5, redirect=None, status=None)
WARNING [1633558576.367958] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/urlopen: Retrying (Retry(total=2, connect=5, read=5, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /program/vit-sand/del-1-sA4song-1/13339049
DEBUG [1633558576.3687959] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (4): www.tv4play.se:443
DEBUG [1633558576.4866886] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/program/vit-sand/del-1-sA4song-1/13339049'): Retry(total=1, connect=5, read=5, redirect=None, status=None)
WARNING [1633558578.8892703] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/urlopen: Retrying (Retry(total=1, connect=5, read=5, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /program/vit-sand/del-1-sA4song-1/13339049
DEBUG [1633558578.8901327] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (5): www.tv4play.se:443
DEBUG [1633558579.0135489] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/program/vit-sand/del-1-sA4song-1/13339049'): Retry(total=0, connect=5, read=5, redirect=None, status=None)
WARNING [1633558583.8289902] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/urlopen: Retrying (Retry(total=0, connect=5, read=5, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /program/vit-sand/del-1-sA4song-1/13339049
DEBUG [1633558583.8289902] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (6): www.tv4play.se:443
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connection.py", line 416, in connect
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\ssl.py", line 500, in wrap_socket
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\ssl.py", line 1040, in _create
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\requests\adapters.py", line 439, in send
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
  [Previous line repeated 2 more times]
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.tv4play.se', port=443): Max retries exceeded with url: /program/vit-sand/del-1-sA4song-1/13339049 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 63, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 98, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\output.py", line 120, in filename
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py", line 66, in get_urldata
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py", line 42, in request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\requests\sessions.py", line 542, in request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\requests\sessions.py", line 655, in send
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.tv4play.se', port=443): Max retries exceeded with url: /program/vit-sand/del-1-sA4song-1/13339049 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

**Comment by spaam** [comment]
you are missing some stuff here.  what version of svtplay-dl do you use? what OS and version do you use?  the full traceback where i can see the issue.
