### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1433]
### svtplay-dl versions:

svtplay-dl 4.8-5-gd44a838

### Operating system and Python version:

Windows 10

### What is the issue:

I was downloading to my network drive and when i added a `\` at the end i got this crash:

```
svtplay-dl.exe https://www.svtplay.se/video/32947142/vendettan/vendettan-sasong-1-avsnitt-5 -o "\\compu\TV Shows\vendettan-svtplay\"
INFO: Outfile: vendettan-svtplay".mp4
INFO: Selected to download dash, bitrate: 5743 format: h264-51
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 63, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 203, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 331, in download
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 349, in _download2
OSError: [Errno 22] Invalid argument: '\\\\compu\\TV Shows\\vendettan-svtplay".m4a'
```

It should work to end the path with a backslash without svtplay-dl to crash. As long as i don't specify any file name it should download to the directory with or without the ending backslash. That is very common behavior in Windows.

**Comment by spaam** [comment]
can you try adding double back slashes to the path?  `\\\\server\\directory\\anotherone\\` ?

**Comment by Sopor** [comment]
Hmm, the file name will be .mp4 and i can't find the file :(

```
svtplay-dl.exe https://www.svtplay.se/video/32947142/vendettan/vendettan-sasong-1-avsnitt-5 -o "\\\\compu\TV Shows\\vendettan-svtplay\\test\\"
INFO: Outfile: .mp4
INFO: Selected to download dash, bitrate: 5743 format: h264-51
[717/717][================================================================================] ETA: 0:00:00
```

It is not in the output directory, not in the svtplay-dl.exe directory and not in the temp directory, but it seems to download.

**Comment by Sopor** [comment]
It should also be nice if svtplay-dl could create directories. Then i could do that directly when i download. As it is now i first have to create the directory before i can download to it.

**Comment by spaam** [comment]
creating directories with `-o` is a bit  meh.  how do we know if the last path of the argument to `-o`  should be a directory or a filename? 🤔

**Comment by Sopor** [comment]
> creating directories with `-o` is a bit meh. how do we know if the last path of the argument to `-o` should be a directory or a filename? 🤔

You end the path with a \ :)

**Comment by spaam** [comment]
but i think the last `/` and `\` will get removed when it do filename checks by the python internal things.

**Comment by spaam** [comment]
interesting it creates a directory in linux for some reason 🤔

**Comment by Sopor** [comment]
I wonder if it could have something to do with the UNC path?

**Comment by Sopor** [comment]
> It should also be nice if svtplay-dl could create directories. Then i could do that directly when i download. As it is now i first have to create the directory before i can download to it.

I don't know if this has something to do with the [above comment](https://github.com/spaam/svtplay-dl/issues/1433#issuecomment-955620997)?:
`--subfolder           Create a subfolder titled as the show, non-series gets in folder movies`

What i meant was that i could add the path where i wanted without creating the directories first.

So, if i download for example:
`svtplay-dl.exe https://www.svtplay.se/video/33003874/leif-och-billy/leif-och-billy-sasong-6-avsnitt-1`
i could specify the output with
`-o g:\tv-series\leif-och-billy\season06\`
and it should create all those directories that not exists already.
