### ISSUE TITLE
svtplay-dl crashed for some episodes on Discovery+

### ISSUE THREAD

**Issue by jonassam1** [spaam/svtplay-dl#1435]
When trying to download "Sommaren med släkten" from Discovery+ some episodes work fine, but some fails. I first tried with the **-A** switch. In order to isolate the issue, I generated the URLs with the **--get-only-episode-url** switch and used one of the failed ones as provided below. Pasting the generated URL into the browser plays the episode as it should.

### svtplay-dl versions:
svtplay-dl 4.9

### Operating system and Python version:
Microsoft Windows 11 Pro Version 10.0.22000 version 22000
Python Version 3.9.7

### What is the issue:
**Command (cookie value blanked out):**
svtplay-dl.exe --cookies "st=xxxxxxx" https://www.discoveryplus.se/videos/sommaren-med-slakten/kan-jens-ta-tillbaka-parkeringsplatsen --verbose

**Result:**
Error
```
DEBUG [1636289305.1415145] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.9
DEBUG [1636289305.1415145] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: discoveryplus
DEBUG [1636289305.1415145] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.discoveryplus.se/videos/sommaren-med-slakten/kan-jens-ta-tillbaka-parkeringsplatsen'
DEBUG [1636289305.17322] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.discoveryplus.se:443
DEBUG [1636289305.3928547] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.discoveryplus.se:443 "GET /videos/sommaren-med-slakten/kan-jens-ta-tillbaka-parkeringsplatsen HTTP/1.1" 200 None
DEBUG [1636289305.4084437] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/token?realm=dplayse&deviceId=709e80c88487a2411e1ee4dfb9f22a861492d20c4765150c0c794abd70f8147c&shortlived=true'
DEBUG [1636289305.4084437] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): disco-api.discoveryplus.se:443
DEBUG [1636289305.7108402] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /token?realm=dplayse&deviceId=709e80c88487a2411e1ee4dfb9f22a861492d20c4765150c0c794abd70f8147c&shortlived=true HTTP/1.1" 200 None
DEBUG [1636289305.7108402] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/users/me'
DEBUG [1636289305.7895048] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /users/me HTTP/1.1" 200 None
DEBUG [1636289305.7895048] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/content/videos/sommaren-med-slakten/kan-jens-ta-tillbaka-parkeringsplatsen'
DEBUG [1636289305.8608227] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /content/videos/sommaren-med-slakten/kan-jens-ta-tillbaka-parkeringsplatsen HTTP/1.1" 200 None
DEBUG [1636289305.8683403] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/playback/videoPlaybackInfo/173931?usePreAuth=true'
DEBUG [1636289305.9500787] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /playback/videoPlaybackInfo/173931?usePreAuth=true HTTP/1.1" 200 None
DEBUG [1636289305.9500787] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://dplaynordics-vod-97.akamaized.net/dplaydni/192080/0/hls/10014150004/playlist.m3u8?hdnts=st=1636289304~exp=1636375704~acl=/dplaydni/192080/0/hls/10014150004/*~hmac=515bdbada59c1511451e3326bba363ef775742ec2f7c2967e31eb2bdb61931d3'
DEBUG [1636289305.9783437] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): dplaynordics-vod-97.akamaized.net:443
DEBUG [1636289306.1977446] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://dplaynordics-vod-97.akamaized.net:443 "GET /dplaydni/192080/0/hls/10014150004/playlist.m3u8?hdnts=st=1636289304~exp=1636375704~acl=/dplaydni/192080/0/hls/10014150004/*~hmac=515bdbada59c1511451e3326bba363ef775742ec2f7c2967e31eb2bdb61931d3 HTTP/1.1" 200 None
DEBUG [1636289306.291794] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://dplaynordics-vod-97.akamaized.net/dplaydni/192080/0/hls/10014150004/exp=1636375704‾acl=%2f*‾data=hdntl‾hmac=5892e52bf1f3cf0976ce167a53cbd66ddc338979f8729ca75bd34061de2fc10b/1112635959-prog_index.m3u8?version_hash=911b93e1'
DEBUG [1636289306.307683] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://dplaynordics-vod-97.akamaized.net:443 "GET /dplaydni/192080/0/hls/10014150004/exp=1636375704%E2%80%BEacl=%2F*%E2%80%BEdata=hdntl%E2%80%BEhmac=5892e52bf1f3cf0976ce167a53cbd66ddc338979f8729ca75bd34061de2fc10b/1112635959-prog_index.m3u8?version_hash=911b93e1 HTTP/1.1" 403 581
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 63, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 112, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\dplay.py", line 104, in get
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 46, in hlsparse
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 174, in _hlsparse
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 359, in __init__
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 373, in parse_m3u
ValueError: Does not appear to be an 'EXTM3U' file.
```

**Comment by spaam** [comment]
you tried to download a video that you dont have access to?🤔

**Comment by jonassam1** [comment]
It works when I paste the link into the browser, so it is accessible through my account. And as some of the episodes download fine while others does even though they are part of the same season, I don't see any particular pattern to it...

**Comment by spaam** [comment]
now i get random crashes in windows. sometimes it works. sometimes not. wtf

**Comment by jonassam1** [comment]
Same error as I get? Very strange with the 403 from what I guess is the CDM as it works in the broswer....

**Comment by spaam** [comment]
yep  it works great in linux.  sometimes it works on windows and sometimes not.  
on windows i see a ip-only url where the video coming from and it works .  the ones that does not work is the akamai one. ..
 but the akamai one works in linux 🤔

**Comment by jonassam1** [comment]
I hope you get it to work on Windows as well. Otherwise I guess I need to learn Linux or Docker... :)

**Comment by spaam** [comment]
one another person on discord experience the same thing as me on macOS 🤔

**Comment by jonassam1** [comment]
That is does not work on MacOS neither? Well, then I'm sure you'll get it sorted out. Looking forward to it. And thanks for you effort!

**Comment by spaam** [comment]
the issue is that it get the file https://disco-api.discoveryplus.se/playback/v2/videoPlaybackInfo/173931?usePreAuth=true to get where to download the video. in that thing it depending on the request it will switch from one CDN to another one.  pretty round robin.

**Comment by spaam** [comment]
cant do anything more with this website. because of DRM 😞
