### ISSUE TITLE
Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) on Viafree

### ISSUE THREAD

**Issue by Usernamnet** [spaam/svtplay-dl#1437]
### svtplay-dl versions:
svtplay-dl --version
svtplay-dl 4.8

### Operating system and Python version:
WIN10
python --version
Python 3.9.2

### What is the issue:

Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) on Viafree

  svtplay-dl --verbose https://www.viafree.se/program/reality/pantbanken/sasong-3/avsnitt-5
DEBUG [1636534866.420792] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.8
DEBUG [1636534866.4244447] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: viafree
DEBUG [1636534866.4244447] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.viafree.se/program/reality/pantbanken/sasong-3/avsnitt-5'
DEBUG [1636534866.4264402] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.viafree.se:443
DEBUG [1636534866.5590937] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.viafree.se:443 "GET /program/reality/pantbanken/sasong-3/avsnitt-5 HTTP/1.1" 200 None
DEBUG [1636534866.564286] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://viafree.mtg-api.com/identity/viafree/auth/pwd/sessions'
DEBUG [1636534866.5658119] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): viafree.mtg-api.com:443
DEBUG [1636534867.0076509] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://viafree.mtg-api.com:443 "POST /identity/viafree/auth/pwd/sessions HTTP/1.1" 200 None
DEBUG [1636534867.0086484] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://playapi.viafree.tv/v3/videos/stream-links/1060937?device=web'
DEBUG [1636534867.009646] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): playapi.viafree.tv:443
DEBUG [1636534867.31304] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://playapi.viafree.tv:443 "GET /v3/videos/stream-links/1060937?device=web HTTP/1.1" 200 169
DEBUG [1636534867.313553] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting "https://b''b''?"
DEBUG [1636534867.3151226] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): b''b'':443
DEBUG [1636534867.3151226] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/'): Retry(total=4, connect=4, read=5, redirect=None, status=None)
WARNING [1636534867.315626] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002928C2AE5B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
DEBUG [1636534867.3161707] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (2): b''b'':443
DEBUG [1636534867.3161707] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/'): Retry(total=3, connect=3, read=5, redirect=None, status=None)
WARNING [1636534867.9245172] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002928C2AE760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
DEBUG [1636534867.9245172] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (3): b''b'':443
DEBUG [1636534867.9255152] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/'): Retry(total=2, connect=2, read=5, redirect=None, status=None)
WARNING [1636534869.1318185] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retrying (Retry(total=2, connect=2, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002928C2AE910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
DEBUG [1636534869.1358078] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (4): b''b'':443
DEBUG [1636534869.1358078] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/'): Retry(total=1, connect=1, read=5, redirect=None, status=None)
WARNING [1636534871.5494392] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retrying (Retry(total=1, connect=1, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002928C2AEAC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
DEBUG [1636534871.5494392] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (5): b''b'':443
DEBUG [1636534871.5504372] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/'): Retry(total=0, connect=0, read=5, redirect=None, status=None)
WARNING [1636534876.3559673] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retrying (Retry(total=0, connect=0, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002928C2AEC70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
DEBUG [1636534876.3559673] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (6): b''b'':443
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connection.py", line 358, in connect
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002928C2AEE20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\adapters.py", line 439, in send
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
  [Previous line repeated 2 more times]
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host="b''b''", port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002928C2AEE20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 63, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 112, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\viaplay.py", line 88, in get

  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py", line 42, in request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\sessions.py", line 542, in request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\sessions.py", line 655, in send
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host="b''b''", port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002928C2AEE20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by Usernamnet** [comment]
you can close this.
updated to 4.9 and then it works

**Comment by Usernamnet** [comment]
nevermind. have the same problem in 4.9

**Comment by spaam** [comment]
yeah its an issue and its an issue on their web page too..

**Comment by spaam** [comment]
i have pushed a new commit that will "fix" this and display that it cant find a video :)
