### ISSUE TITLE
Crash downloading from UR

### ISSUE THREAD

**Issue by erikatl** [spaam/svtplay-dl#1438]
### svtplay-dl versions:
svtplay-dl 4.9

### Operating system and Python version:
uname -a
Linux max 5.14.10-1-MANJARO #1 SMP PREEMPT Thu Oct 7 06:43:34 UTC 2021 x86_64 GNU/Linux

python --version 
Python 3.9.7

### What is the issue:
Running this command leads to a crash:
svtplay-dl --verbose https://urplay.se/program/221935-en-annan-sida-av-historien-hogkulturer
```
DEBUG [1636805726.770604] /usr/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 4.9
DEBUG [1636805726.7732127] /usr/lib/python3.9/site-packages/svtplay_dl/service/__init__.py/__init__: service: urplay
DEBUG [1636805726.7732766] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://urplay.se/program/221935-en-annan-sida-av-historien-hogkulturer'
DEBUG [1636805726.776234] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): urplay.se:443
DEBUG [1636805726.9556825] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://urplay.se:443 "GET /program/221935-en-annan-sida-av-historien-hogkulturer HTTP/1.1" 200 44637
DEBUG [1636805726.9746048] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming-loadbalancer.ur.se/loadbalancer.json'
DEBUG [1636805726.9815192] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): streaming-loadbalancer.ur.se:443
DEBUG [1636805727.0436306] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://streaming-loadbalancer.ur.se:443 "GET /loadbalancer.json HTTP/1.1" 200 None
DEBUG [1636805727.0491595] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming10.ur.se/urplay/_definst_/mp4:221000-221999/221935-9.mp4/playlist.m3u8'
DEBUG [1636805727.054514] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): streaming10.ur.se:443
DEBUG [1636805727.1061857] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://streaming10.ur.se:443 "GET /urplay/_definst_/mp4:221000-221999/221935-9.mp4/playlist.m3u8 HTTP/1.1" 200 None
DEBUG [1636805727.108361] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming10.ur.se/urplay/_definst_/mp4:221000-221999/221935-4.mp4/playlist.m3u8'
DEBUG [1636805727.1132462] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://streaming10.ur.se:443 "GET /urplay/_definst_/mp4:221000-221999/221935-4.mp4/playlist.m3u8 HTTP/1.1" 200 None
INFO [1636805727.1155663] /usr/lib/python3.9/site-packages/svtplay_dl/utils/output.py/find_dupes: Outfile: en.annan.sida.av.historien.s01e01.hogkulturer.srt
DEBUG [1636805727.1162024] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://undertexter.ur.se/221000-221999/221935-11.vtt'
DEBUG [1636805727.122927] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): undertexter.ur.se:443
DEBUG [1636805727.209693] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://undertexter.ur.se:443 "GET /221000-221999/221935-11.vtt HTTP/1.1" 200 6449
DEBUG [1636805727.2706296] /usr/lib/python3.9/site-packages/svtplay_dl/utils/stream.py/format_prio: Format priority: ['h264', 'h264-51']
DEBUG [1636805727.270763] /usr/lib/python3.9/site-packages/svtplay_dl/utils/stream.py/protocol_prio: Protocol priority scores (higher is better): {'dash': 3, 'hls': 2, 'http': 1}
DEBUG [1636805727.270997] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming10.ur.se/urplay/_definst_/mp4:221000-221999/221935-4.mp4/chunklist.m3u8'
DEBUG [1636805727.2748313] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): streaming10.ur.se:443
DEBUG [1636805727.3227215] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://streaming10.ur.se:443 "GET /urplay/_definst_/mp4:221000-221999/221935-4.mp4/chunklist.m3u8 HTTP/1.1" 200 None
INFO [1636805727.324775] /usr/lib/python3.9/site-packages/svtplay_dl/utils/output.py/find_dupes: Outfile: en.annan.sida.av.historien.s01e01.hogkulturer.ts
INFO [1636805727.3287404] /usr/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py/get_one_media: Selected to download hls, bitrate: 2897 format: h264
DEBUG [1636805727.3289409] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming10.ur.se/urplay/_definst_/mp4:221000-221999/221935-4.mp4/chunklist.m3u8'
DEBUG [1636805727.3360236] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): streaming10.ur.se:443
DEBUG [1636805727.3925595] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://streaming10.ur.se:443 "GET /urplay/_definst_/mp4:221000-221999/221935-4.mp4/chunklist.m3u8 HTTP/1.1" 200 None

[001/212][..........................................................................] ETA: 0:00:00DEBUG [1636805727.400228] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming10.ur.se/urplay/_definst_/mp4:221000-221999/221935-4.mp4/media_0.ts'
DEBUG [1636805727.4110458] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://streaming10.ur.se:443 "GET /urplay/_definst_/mp4:221000-221999/221935-4.mp4/media_0.ts HTTP/1.1" 200 1300396

[002/212][..........................................................................] ETA: 0:00:11DEBUG [1636805727.5056717] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming10.ur.se/urplay/_definst_/mp4:221000-221999/221935-4.mp4/media_1.ts'
DEBUG [1636805727.5152543] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://streaming10.ur.se:443 "GET /urplay/_definst_/mp4:221000-221999/221935-4.mp4/media_1.ts HTTP/1.1" 200 1068592

[003/212][=.........................................................................] ETA: 0:00:13DEBUG [1636805727.5984008] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming10.ur.se/urplay/_definst_/mp4:221000-221999/221935-4.mp4/media_2.ts'
DEBUG [1636805727.6079118] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://streaming10.ur.se:443 "GET /urplay/_definst_/mp4:221000-221999/221935-4.mp4/media_2.ts HTTP/1.1" 200 1189100

[004/212][=.........................................................................] ETA: 0:00:15DEBUG [1636805727.6993864] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming10.ur.se/urplay/_definst_/mp4:221000-221999/221935-4.mp4/media_3.ts'
DEBUG [1636805727.7089872] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://streaming10.ur.se:443 "GET /urplay/_definst_/mp4:221000-221999/221935-4.mp4/media_3.ts HTTP/1.1" 200 1612664

[005/212][=.........................................................................] ETA: 0:00:18DEBUG [1636805727.8401055] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming10.ur.se/urplay/_definst_/mp4:221000-221999/221935-4.mp4/media_4.ts'
DEBUG [1636805727.8500085] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://streaming10.ur.se:443 "GET /urplay/_definst_/mp4:221000-221999/221935-4.mp4/media_4.ts HTTP/1.1" 200 1070284

[006/212][==........................................................................] ETA: 0:00:18DEBUG [1636805727.9318495] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming10.ur.se/urplay/_definst_/mp4:221000-221999/221935-4.mp4/media_5.ts'
DEBUG [1636805727.9417977] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://streaming10.ur.se:443 "GET /urplay/_definst_/mp4:221000-221999/221935-4.mp4/media_5.ts HTTP/1.1" 200 805016


[212/212][==========================================================================] ETA: 0:00:00DEBUG [1636805747.6441598] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming10.ur.se/urplay/_definst_/mp4:221000-221999/221935-4.mp4/media_211.ts'
DEBUG [1636805747.6575954] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://streaming10.ur.se:443 "GET /urplay/_definst_/mp4:221000-221999/221935-4.mp4/media_211.ts HTTP/1.1" 200 64484

Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3.9/site-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "/usr/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 211, in get_one_media
    stream.get_thumbnail(stream.config)
  File "/usr/lib/python3.9/site-packages/svtplay_dl/service/__init__.py", line 128, in get_thumbnail
    download_thumbnails(self.output, options, [(False, url)])
  File "/usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py", line 53, in download_thumbnails
    data = Session().get(url).content
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/og-logo.png': No schema supplied. Perhaps you meant http:///og-logo.png?
```

**Comment by spaam** [comment]
it crashed getting the thumbnail and you dont have that in the argument you provided. you modified the code or you have it in a config? 🤔

**Comment by erikatl** [comment]
My .svtplay-dl.yaml:
```
  default:
#    path: ~/Hämtningar/svtplay
    subtitle: true
    merge_subtitle: true
#    all_episodes: true
#    subfolder: true
    filename: "{title}.s{season}e{episode}.{episodename}.{ext}" 
    thumbnail: true
```

**Comment by erikatl** [comment]
Changed thumbnail to false and now it works without a problem.

**Comment by spaam** [comment]
for some reason the thumbnail was broken. changed so it will take it from a different place instead and i pushed it to master and will be in the next release tomorrow.

**Comment by erikatl** [comment]
Quick response, thanks.
