### ISSUE TITLE
Minor: Crash at requesting --subtitle

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#1447]
svtplay-dl 4.9-7-gd9209f8
windows 8.1
python 3.8.10

For one specific item available at svtplay.se svtplay-dl crashes:

E: SSD..svtdl:svtplay-dl_exec --subtitle https://www.svtplay.se/video/33423770/nobel-2021-nobelkonserten/nobel-2021-nobelkonserten-8-dec-19-00
INFO: Outfile: nobel.2021.nobelkonserten.nobelkonserten-direkt-a032899-svtplay.srt
Traceback (most recent call last):
  File "c:\svtplaydll\svtplay-dl_sshot_20211124_215624py\__main__.py", line 15,in <module>
    svtplay_dl.main()
  File "c:\svtplaydll\svtplay-dl_sshot_20211124_215624py\svtplay_dl\__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "c:\svtplaydll\svtplay-dl_sshot_20211124_215624py\svtplay_dl\utils\getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "c:\svtplaydll\svtplay-dl_sshot_20211124_215624py\svtplay_dl\utils\getmedia.py", line 159, in get_one_media
    subtitle_decider(stream, subtitles)
  File "c:\svtplaydll\svtplay-dl_sshot_20211124_215624py\svtplay_dl\utils\stream.py", line 115, in subtitle_decider
    subtitles[0].download()
  File "c:\svtplaydll\svtplay-dl_sshot_20211124_215624py\svtplay_dl\subtitle\__init__.py", line 71, in download
    data = self.stpp(subdata)
  File "c:\svtplaydll\svtplay-dl_sshot_20211124_215624py\svtplay_dl\subtitle\__init__.py", line 357, in stpp
    _data = self._tt(res.content[start:].decode(), nr)
  File "c:\svtplaydll\svtplay-dl_sshot_20211124_215624py\svtplay_dl\subtitle\__init__.py", line 96, in _tt
    plist = list(xml.findall("p"))
AttributeError: 'NoneType' object has no attribute 'findall'

**However, svtplay-dl successfully downloads when the "--subtitle" parameter is absent.**

**Comment by pythonuser3856** [comment]
I just tested snap-shot 20211209_194250 and it works although with a peculiar waiting time of approx one minute until the tracking of the dash .m4a file is shown.
And it also leaves an empty .srt file as a result.
But it works and I'm fine.

**Comment by pythonuser3856** [comment]
I got a crash also with the snap-shop at testing link
https://www.svtplay.se/video/33430530/nobel-2021-nobelprisceremonin
No changes in run-time environment except for change of svtplay-dl version

The behavior after start of execution is silence until the trace comes. I've included time stamps just before start and right after stop.
The crash trace is:
time stamp at start 2021-12-10 18:15:38
py c:\svtplaydll\svtplay-dl_sshot_20211209_194250py\__main__.py  --subtitle https://www.svtplay.se/video/33430530/nobel-2021-nobelprisceremonin
INFO: Outfile: nobel.2021.nobelprisceremonin-ba0c5d7-svtplay.srt
Traceback (most recent call last):
  File "c:\svtplaydll\svtplay-dl_sshot_20211209_194250py\__main__.py", line 15,in <module>
    svtplay_dl.main()
  File "c:\svtplaydll\svtplay-dl_sshot_20211209_194250py\svtplay_dl\__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "c:\svtplaydll\svtplay-dl_sshot_20211209_194250py\svtplay_dl\utils\getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "c:\svtplaydll\svtplay-dl_sshot_20211209_194250py\svtplay_dl\utils\getmedia.py", line 159, in get_one_media
    subtitle_decider(stream, subtitles)
  File "c:\svtplaydll\svtplay-dl_sshot_20211209_194250py\svtplay_dl\utils\stream.py", line 115, in subtitle_decider
    subtitles[0].download()
  File "c:\svtplaydll\svtplay-dl_sshot_20211209_194250py\svtplay_dl\subtitle\__init__.py", line 71, in download
    data = self.stpp(subdata)
  File "c:\svtplaydll\svtplay-dl_sshot_20211209_194250py\svtplay_dl\subtitle\__init__.py", line 373, in stpp
    changed, entries = _resolv(entries)
  File "c:\svtplaydll\svtplay-dl_sshot_20211209_194250py\svtplay_dl\subtitle\__init__.py", line 397, in _resolv
    left_time = time_match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
time stamp at stop 18:16:50.38
**Also this time, if I run the command w/o parameter "--subtitle" I get a successful download.**

**Comment by spaam** [comment]
i cant reproduce this

**Comment by pythonuser3856** [comment]
Neither can I, it must have been a glitch
