### ISSUE TITLE
commit "parser: -M does not necessarily imply -S" making the script crash when only using -M

### ISSUE THREAD

**Issue by spaam** [spaam/svtplay-dl#1459]
after comrade @iwconfig contributions i totally forgot about people who only use `-M` 
```
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3.10/site-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3.10/site-packages/svtplay_dl/utils/getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "/usr/lib/python3.10/site-packages/svtplay_dl/utils/getmedia.py", line 222, in get_one_media
    post.merge()
  File "/usr/lib/python3.10/site-packages/svtplay_dl/postprocess/__init__.py", line 80, in merge
    langs = _sublanguage(self.stream, self.config, self.subfixes)
  File "/usr/lib/python3.10/site-packages/svtplay_dl/postprocess/__init__.py", line 216, in _sublanguage
    langs += [query(subfile)]
  File "/usr/lib/python3.10/site-packages/svtplay_dl/postprocess/__init__.py", line 176, in query
    _ = parse(self)
  File "/usr/lib/python3.10/site-packages/svtplay_dl/postprocess/__init__.py", line 172, in parse
    fd = open(self)
FileNotFoundError: [Errno 2] No such file or directory: 'disneydags.s01e31.avsnitt.31-764ef08-svtplay.srt'
``` 
i guess some people just want subs baked in to the .mp4/.mkv file instead of having it both baked in and separate file. 
Need to come up with some better way with this. 🤔 

1. add an additional argument for it? it feels bit meh
2. revert the revert?  4c90677089b5b454ffb33d20f041a935fbfb6111 
3. if both -S and -M is used it will bake it in and have it separate file? could be a solution. it will need some code internally for it. 
4. go crazy and remove subtitles completely?

**Comment by iwconfig** [comment]
lets do number 4!

The subtitle is never even downloaded, so how can this be an issue with `--merge-subtitle`?

```console
$ svtplay-dl --version
svtplay-dl 4.10+1.gf7b3d1b
```

```console
$ svtplay-dl --config "" -M "https://www.svtplay.se/video/34293496/disneydags/disneydags-sasong-1-avsnitt-31"
INFO: Outfile: disneydags.s01e31.avsnitt.31-764ef08-svtplay.srt
WARNING: Can't download subtitle file
$ svtplay-dl -S --force-subtitle "https://www.svtplay.se/video/34293496/disneydags/disneydags-sasong-1-avsnitt-31"
INFO: Outfile: svtplay-764ef08.srt
WARNING: Can't download subtitle file
$ svtplay-dl -M -S --force-subtitle "https://www.svtplay.se/video/34293496/disneydags/disneydags-sasong-1-avsnitt-31"
INFO: Outfile: svtplay-764ef08.srt
WARNING: Can't download subtitle file
```

```console
$ svtplay-dl --verbose -M -S --force-subtitle "https://www.svtplay.se/video/34293496/disneydags/disneydags-sasong-1-avsnitt-31"
DEBUG [1645995126.8272343] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/utils/getmedia.py/get_media: version: 4.10+1.gf7b3d1b
DEBUG [1645995126.8299882] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1645995126.8301563] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/34293496/disneydags/disneydags-sasong-1-avsnitt-31'
DEBUG [1645995126.8318696] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1645995126.903821] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/34293496/disneydags/disneydags-sasong-1-avsnitt-31 HTTP/1.1" 200 31311
DEBUG [1645995126.926071] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://api.svt.se/video/KA23ZdA'
DEBUG [1645995126.9293246] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): api.svt.se:443
DEBUG [1645995127.0012324] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://api.svt.se:443 "GET /video/KA23ZdA HTTP/1.1" 200 818
DEBUG [1645995127.0039048] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-secure-1c.akamaized.net/d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/hls-ts-avc.m3u8'
DEBUG [1645995127.007128] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-secure-1c.akamaized.net:443
DEBUG [1645995127.0808837] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-secure-1c.akamaized.net:443 "GET /d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/hls-ts-avc.m3u8 HTTP/1.1" 200 None
DEBUG [1645995127.0891511] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-secure-1c.akamaized.net/d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/text/text-0.m3u8?aka_me_session_id=AAAAAAAAAAD3NR1iAAAAABEKttwOgZFaQvb5TTbcfdXvpIM4PnAar232aBEOByRcXRxG9gVg3x8dm0Zgzh%2fwBcaLbQXokwPn&aka_media_format_type=hls'
DEBUG [1645995127.092594] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-secure-1c.akamaized.net:443
DEBUG [1645995127.1624563] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-secure-1c.akamaized.net:443 "GET /d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/text/text-0.m3u8?aka_me_session_id=AAAAAAAAAAD3NR1iAAAAABEKttwOgZFaQvb5TTbcfdXvpIM4PnAar232aBEOByRcXRxG9gVg3x8dm0Zgzh%2fwBcaLbQXokwPn&aka_media_format_type=hls HTTP/1.1" 200 551
DEBUG [1645995127.1659284] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-secure-1c.akamaized.net/d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/hls-ts-avc.m3u8'
DEBUG [1645995127.1838357] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-secure-1c.akamaized.net:443 "GET /d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/hls-ts-avc.m3u8 HTTP/1.1" 200 None
DEBUG [1645995127.1903415] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-secure-1c.akamaized.net/d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/text/text-0.m3u8?aka_me_session_id=AAAAAAAAAAD3NR1iAAAAAPbpTH77Zm0VfuIyzq+eK+sLSsgnyghPwBD9dTlLjzcNqmfNv7PAZrCFnwl8BjFlsoKPJmpSqTOV&aka_media_format_type=hls'
DEBUG [1645995127.1935492] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-secure-1c.akamaized.net:443
DEBUG [1645995127.2617943] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-secure-1c.akamaized.net:443 "GET /d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/text/text-0.m3u8?aka_me_session_id=AAAAAAAAAAD3NR1iAAAAAPbpTH77Zm0VfuIyzq+eK+sLSsgnyghPwBD9dTlLjzcNqmfNv7PAZrCFnwl8BjFlsoKPJmpSqTOV&aka_media_format_type=hls HTTP/1.1" 200 547
DEBUG [1645995127.2653863] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-secure-1c.akamaized.net/d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/hls-cmaf-lb-full.m3u8'
DEBUG [1645995127.2815812] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-secure-1c.akamaized.net:443 "GET /d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/hls-cmaf-lb-full.m3u8 HTTP/1.1" 200 None
DEBUG [1645995127.2915368] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-secure-1c.akamaized.net/d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/text/text-0.m3u8?aka_me_session_id=AAAAAAAAAAD3NR1iAAAAAEvZn9iV87nLl72wfwRGP%2fRmp+lvKxxVi1cVkRqLyG3wHRo4Js4DY6YbsFxWpTSCWkrHRWnUYQMM&aka_media_format_type=hls'
DEBUG [1645995127.2956266] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-secure-1c.akamaized.net:443
DEBUG [1645995127.3675478] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-secure-1c.akamaized.net:443 "GET /d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/text/text-0.m3u8?aka_me_session_id=AAAAAAAAAAD3NR1iAAAAAEvZn9iV87nLl72wfwRGP%2fRmp+lvKxxVi1cVkRqLyG3wHRo4Js4DY6YbsFxWpTSCWkrHRWnUYQMM&aka_media_format_type=hls HTTP/1.1" 200 551
DEBUG [1645995127.371045] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-secure-1c.akamaized.net/d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/hls-ts-lb-full.m3u8'
DEBUG [1645995127.3919997] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-secure-1c.akamaized.net:443 "GET /d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/hls-ts-lb-full.m3u8 HTTP/1.1" 200 None
DEBUG [1645995127.3984423] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-secure-1c.akamaized.net/d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/text/text-0.m3u8?aka_me_session_id=AAAAAAAAAAD3NR1iAAAAALuiALGJNkTqcLxcdR3RGOE5ysoMimqIEZ1i6qiLk+TrXPR3ZKGZj9OLot43Pnt95qBmcs0Wgd+G&aka_media_format_type=hls'
DEBUG [1645995127.4022276] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-secure-1c.akamaized.net:443
DEBUG [1645995127.4736183] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-secure-1c.akamaized.net:443 "GET /d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/text/text-0.m3u8?aka_me_session_id=AAAAAAAAAAD3NR1iAAAAALuiALGJNkTqcLxcdR3RGOE5ysoMimqIEZ1i6qiLk+TrXPR3ZKGZj9OLot43Pnt95qBmcs0Wgd+G&aka_media_format_type=hls HTTP/1.1" 200 547
DEBUG [1645995127.4772432] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-secure-1c.akamaized.net/d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/hls-ts-full.m3u8'
DEBUG [1645995127.493145] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-secure-1c.akamaized.net:443 "GET /d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/hls-ts-full.m3u8 HTTP/1.1" 200 None
DEBUG [1645995127.4996367] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-secure-1c.akamaized.net/d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/text/text-0.m3u8?aka_me_session_id=AAAAAAAAAAD3NR1iAAAAAPE5VnCKCZESdAy3sENFkLCCtPCvFlyuOUFyEyLP95msi8Rx%2fkyYzdUawG8GC9ZmESsEVbD9e8Jp&aka_media_format_type=hls'
DEBUG [1645995127.5029411] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-secure-1c.akamaized.net:443
DEBUG [1645995127.5874317] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-secure-1c.akamaized.net:443 "GET /d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/text/text-0.m3u8?aka_me_session_id=AAAAAAAAAAD3NR1iAAAAAPE5VnCKCZESdAy3sENFkLCCtPCvFlyuOUFyEyLP95msi8Rx%2fkyYzdUawG8GC9ZmESsEVbD9e8Jp&aka_media_format_type=hls HTTP/1.1" 200 551
DEBUG [1645995127.5908592] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-secure-1c.akamaized.net/d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/hls-cmaf-full.m3u8'
DEBUG [1645995127.616054] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-secure-1c.akamaized.net:443 "GET /d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/hls-cmaf-full.m3u8 HTTP/1.1" 200 None
DEBUG [1645995127.6322987] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-secure-1c.akamaized.net/d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/text/text-0.m3u8?aka_me_session_id=AAAAAAAAAAD3NR1iAAAAAM2QaqxISyDfj6rWUjWPltnOrIWAuBp5vemFdK8VbyPbUZKaS5LFv2YFjBMV20FBKObkIAdWXZff&aka_media_format_type=hls'
DEBUG [1645995127.635851] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-secure-1c.akamaized.net:443
DEBUG [1645995127.7045074] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-secure-1c.akamaized.net:443 "GET /d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/text/text-0.m3u8?aka_me_session_id=AAAAAAAAAAD3NR1iAAAAAM2QaqxISyDfj6rWUjWPltnOrIWAuBp5vemFdK8VbyPbUZKaS5LFv2YFjBMV20FBKObkIAdWXZff&aka_media_format_type=hls HTTP/1.1" 200 547
INFO [1645995127.7086706] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/utils/output.py/find_dupes: Outfile: svtplay-764ef08.srt
DEBUG [1645995127.7089121] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-secure-1c.akamaized.net/d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/text/text-0.vtt'
DEBUG [1645995127.7121549] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-secure-1c.akamaized.net:443
DEBUG [1645995127.7782817] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-secure-1c.akamaized.net:443 "GET /d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/text/text-0.vtt HTTP/1.1" 403 408
WARNING [1645995127.7787333] /usr/local/lib/python3.7/site-packages/svtplay_dl-4.10+1.gf7b3d1b-py3.7.egg/svtplay_dl/subtitle/__init__.py/download: Can't download subtitle file
```

Trying to download `subtitleReferences[0]['url']` in
```json
"subtitleReferences": [
  {
    "url": "https://svt-vod-secure-1c.akamaized.net/d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/text/text-0.vtt",
    "format": "webvtt"
  }
]
```
from https://api.svt.se/video/KA23ZdA only results in access denied error

but using the search parameters found in `text-0.m3u8` (`#EXTINF`)

```console
$ curl "https://svt-vod-secure-1c.akamaized.net/d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/text/text-0.m3u8?aka_me_session_id=AAAAAAAAAAD3NR1iAAAAABEKttwOgZFaQvb5TTbcfdXvpIM4PnAar232aBEOByRcXRxG9gVg3x8dm0Zgzh%2fwBcaLbQXokwPn&aka_media_format_type=hls"#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:3451
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="https://svt-vod-secure-1c.akamaized.net/d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/text/serve.key?aka_me_session_id=AAAAAAAAAAD3NR1iAAAAABEKttwOgZFaQvb5TTbcfdXvpIM4PnAar232aBEOByRcXRxG9gVg3x8dm0Zgzh%2fwBcaLbQXokwPn"
#EXTINF:3450.48,
text-0.vtt?aka_me_session_id=AAAAAAAAAAD3NR1iAAAAABEKttwOgZFaQvb5TTbcfdXvpIM4PnAar232aBEOByRcXRxG9gVg3x8dm0Zgzh%2fwBcaLbQXokwPn&aka_msn=0&aka_hls_version=3&aka_media_format_type=hls
#EXT-X-ENDLIST
```

you do get access, though to a binary blob, like so:

```console
$ head -1 < <(curl -s "https://svt-vod-secure-1c.akamaized.net/d0/secure/20220219/7070ed74-c89a-4d9f-a84d-bd88870278f1/text/text-0.vtt?aka_me_session_id=AAAAAAAAAAD3NR1iAAAAABEKttwOgZFaQvb5TTbcfdXvpIM4PnAar232aBEOByRcXRxG9gVg3x8dm0Zgzh%2fwBcaLbQXokwPn&aka_msn=0&aka_hls_version=3&aka_media_format_type=hls")
d��t�'���
           @��ʉ�4)�3�g�����Z%[��cs���5K�˂g(%���/l�S�B�3�'C��)�_�k�6.���Y�<s\�K�o��@^��l?B���j�眎S�"� ��h�0�Q�c	
                VS/�
```

I don't know what this means. I would think it is encrypted looking at `#EXT-X-KEY:METHOD=AES-128` in `text-0.m3u8` but I don't know how that works.

**Comment by spaam** [comment]
interesting error you got there 🤔

i get the crash when i try it as well. the crash above was from a user on discord. i guess the user did not provide with all info :( 

it worked great on a different video https://www.svtplay.se/video/34338228/allt-for-sverige/allt-for-sverige-avsnitt-7 when i tried it.  this issue is completely different now.  two things.
1) need to fix so we dont crash if we cant download a sub 
2) look on why we cant download that subtitle.
anyway, thanks for your comment @iwconfig <3

**Comment by iwconfig** [comment]
I stumbled on this today. Here's how to decrypt it the subtitle

```shell
#### Decrypting AES-128 encrypted text via HLS 
#### Video: https://www.svtplay.se/video/34576568/disneydags/disneydags-sasong-1-avsnitt-3-2?id=KyX2ELx
####     API: https://api.svt.se/video/KyX2ELx

hls_m3u8_url='https://svt-vod-secure-3b.akamaized.net/d0/secure/20220315/512e4a15-5f85-430a-8fe3-8d784e51f10e/hls-ts-full.m3u8'
base_url=${hls_m3u8_url%/*}
curl -s "$hls_m3u8_url" -o hls-ts-full.m3u8

text_m3u8_url=${base_url}/$(awk -F\" '/SUBTITLES,URI/{ print $2 }' hls-ts-full.m3u8)
curl -si "$text_m3u8_url" -o text-0.m3u8

text_vtt_url=${base_url}/text/$(awk '/text-0.vtt/' text-0.m3u8)
serve_key_url=$(awk -F\" '/AES/{ print $2 }' text-0.m3u8)
curl -s "$text_vtt_url" -o text.vtt
curl -s "$serve_key_url" -o serve.key

IV=$(awk -F[\":] '/ETag/{ print $3 }' text-0.m3u8)
KEY=$(hexdump -e '16/1 "%02x"' serve.key)

printf '%s\n\n' ${hls_m3u8_url@A} ${base_url@A} ${text_m3u8_url@A} ${text_vtt_url@A} ${serve_key_url@A} ${IV@A} ${KEY@A}

openssl enc -aes-128-cbc -nosalt -d -in text.vtt -out /dev/stdout -K $KEY -iv $IV
```

```console
$ bash ~/dev/hls-decrypt-subtitle-test.sh | head -n30
hls_m3u8_url='https://svt-vod-secure-3b.akamaized.net/d0/secure/20220315/512e4a15-5f85-430a-8fe3-8d784e51f10e/hls-ts-full.m3u8'

base_url='https://svt-vod-secure-3b.akamaized.net/d0/secure/20220315/512e4a15-5f85-430a-8fe3-8d784e51f10e'

text_m3u8_url='https://svt-vod-secure-3b.akamaized.net/d0/secure/20220315/512e4a15-5f85-430a-8fe3-8d784e51f10e/text/text-0.m3u8?aka_me_session_id=AAAAAAAAAABZBWdiAAAAAMmMNZEjFk3A%2fx4HnNo4VXs%2f2Z5WjgiBXZZOM%2fF1xWYBUmm+KZiK%2fD9XFh3pCfWwBjLHft3wS7Ff&aka_media_format_type=hls'

text_vtt_url='https://svt-vod-secure-3b.akamaized.net/d0/secure/20220315/512e4a15-5f85-430a-8fe3-8d784e51f10e/text/text-0.vtt?aka_me_session_id=AAAAAAAAAABZBWdiAAAAAMmMNZEjFk3A%2fx4HnNo4VXs%2f2Z5WjgiBXZZOM%2fF1xWYBUmm+KZiK%2fD9XFh3pCfWwBjLHft3wS7Ff&aka_msn=0&aka_hls_version=3&aka_media_format_type=hls'

serve_key_url='https://svt-vod-secure-3b.akamaized.net/d0/secure/20220315/512e4a15-5f85-430a-8fe3-8d784e51f10e/text/serve.key?aka_me_session_id=AAAAAAAAAABZBWdiAAAAAMmMNZEjFk3A%2fx4HnNo4VXs%2f2Z5WjgiBXZZOM%2fF1xWYBUmm+KZiK%2fD9XFh3pCfWwBjLHft3wS7Ff'

IV='04246f733afe905f12f8509a93ba8ade'

KEY='a8fe28594e9956445675e41e66e7dc04'

Sa-%n��U"�j�����.960 --> 00:00:29.120
<c.green>♫ För vinden har jag i mitt hår</c>
<c.green>♫ och en glöd inom mig</c>

00:00:29.280 --> 00:00:31.520
<c.green>♫ för allt det som ska börja</c>

00:00:31.680 --> 00:00:36.840
<c.green>♫ Jag har en gåta som gryr</c>
<c.green>♫ Jag ska följa dess spår</c>

00:00:37.000 --> 00:00:43.920
<c.green>♫ En böljande bris blåser hit,</c>
<c.green>♫ vill följa den ända till dit den går</c>

00:00:44.080 --> 00:00:47.120
```

Not sure why the first line is `Sa-%n��U"�j�����.960 --> 00:00:29.120`, but I assume it's due to some encoding issue. It's only the first line though... hmm. It might have something to do with `openssl` or something else entirely like a missing initial segment or whatever. Or maybe it's an error on their side, meaning the source file _is_ like this. I don't know. I'm too damn tired to mess with this now

The Initialization Vector (iv) is in the `ETag` response header of `$text_m3u8_url`.

**Comment by spaam** [comment]
encoding feels a bit strange.  its in the beginning of the file and the `åäö` and `♫` seems correct later in the file. i guess you get some "garbage" data first in the file  but that feels wrong too because of its using aes-cbc 🤔 
 
i have been thinking how to rewrite the whole fetcher class to be more generic-ish thing so we could use it for this subtitles too.  right now its a baaah way to do it and i hate it :)

**Comment by iwconfig** [comment]
Yeah, exactly

Doesn't seem to be that specific source either, based on only one test with another episode of Disneydags. The other one had the same issue.

Ah, that'd be nice. If I had the time and enough knowledge I'd give it a go

**Comment by iwconfig** [comment]
alright so I'm pretty sure something's missing with the IV. Wikipedia says

> Decrypting with the incorrect IV causes the first block of plaintext to be corrupt but subsequent plaintext blocks will be correct.[^1]

I cannot figure out how to get the correct IV though. The `ETag` response header reads
```
04246f733afe905f12f8509a93ba8ade:1647342827.581406
```
where the hex part delimited by the colon is the IV I used, but I have no clue what the float number is for.

I understand about _0.1^32%_ of this stuff, but if i may take a _wild uneducated guess_: they could also be using the CTS method[^2] because

> Its main drawbacks [of CBC] are that encryption is sequential (i.e., it cannot be parallelized), and that the message must be padded to a multiple of the cipher block size. One way to handle this last issue is through the method known as [ciphertext stealing](https://en.wikipedia.org/wiki/Ciphertext_stealing).[^1]

But idk 🤷🤷‍♂️🤷‍♀️

[^1]: https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Cipher_block_chaining_(CBC)
[^2]: https://en.wikipedia.org/wiki/Ciphertext_stealing
