### ISSUE TITLE
Proxy specified in config does not work

### ISSUE THREAD

**Issue by StaffanBetner** [spaam/svtplay-dl#1463]
### svtplay-dl versions:

svtplay-dl 4.11

### Operating system and Python version:

Ubuntu 20.04, Python 3.8.8

### What is the issue:

When I specify the proxy in the config file the download does not work. If the proxy is specified in command line it works.

Config file:
```
default:
    subtitle: true
    merge_subtitle: true
    subfolder: true
    output_format: mkv
    proxy: "socks5://127.0.0.1:25344"
```

Example:

```
svtplay-dl https://www.svtplay.se/video/30802018/mayarikets-dolda-varld --verbose
DEBUG [1648716973.5455663] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 4.11
DEBUG [1648716973.5504048] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1648716973.5505576] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/30802018/mayarikets-dolda-varld'
Traceback (most recent call last):
  File "/home/staffan/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/staffan/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 69, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 63, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 98, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/output.py", line 120, in filename
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py", line 66, in get_urldata
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py", line 42, in request
  File "/home/staffan/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 532, in request
    settings = self.merge_environment_settings(
  File "/home/staffan/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 710, in merge_environment_settings
    no_proxy = proxies.get('no_proxy') if proxies is not None else None
AttributeError: 'str' object has no attribute 'get'
```

**Comment by spaam** [comment]
interesting error. thanks for the bug report <3 . 
this should be in the next release. when it happen i dont know, until then it should be in the latest snapshot :)
