### ISSUE TITLE
Problem with media url for NRK TV

### ISSUE THREAD

**Issue by seb1234567** [spaam/svtplay-dl#1487]
### svtplay-dl versions:
4.13

Run `svtplay-dl --version`

### Operating system and Python version:
Windows 10, using cmd not python.

Name and version of the operating system and python version (run `python --version`)

### What is the issue:
Problem with media url for nrk tv. I cannot download from nrk tv in any form and when using verbose it states error for media url.

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

    svtplay-dl --verbose https://www.example.com

**Comment by joahallin** [comment]
I have the same issue:

PS C:\Users\Gemensam\Videos> .\svtplay-dl\svtplay-dl.exe https://tv.nrk.no/serie/dagsrevyen/202208/NNFA19080622/avspiller --verbose
DEBUG [1659855446.7187548] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.13-1-g487c7fe
DEBUG [1659855446.7207527] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: nrk
DEBUG [1659855446.7207527] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://tv.nrk.no/serie/dagsrevyen/202208/NNFA19080622/avspiller'
DEBUG [1659855446.7257493] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): tv.nrk.no:443
DEBUG [1659855446.8451502] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://tv.nrk.no:443 "GET /serie/dagsrevyen/202208/NNFA19080622/avspiller HTTP/1.1" 200 27290
DEBUG [1659855446.848149] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://psapi.nrk.no/mediaelement/NNFA19080622'
DEBUG [1659855446.8501446] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): psapi.nrk.no:443
DEBUG [1659855446.9562428] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://psapi.nrk.no:443 "GET /mediaelement/NNFA19080622 HTTP/1.1" 410 92
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 63, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 112, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\nrk.py", line 34, in get
KeyError: 'mediaUrl'
