### ISSUE TITLE
Cannot download from tv4play

### ISSUE THREAD

**Issue by enur001** [spaam/svtplay-dl#1490]
### svtplay-dl versions:

svtplay-dl 4.13

### Operating system and Python version:

Name and version of the operating system and python version (run `python --version`)
Mac OS 12.4. The command python --version is not found, but svtplay-dl has alwys worked before.

### What is the issue:

I cannot download from tv4play.se anymore. I only get some errors and according to them it seems to be some problem with the certificate. It has worked before, but yesterday and today it doesn't work. I have tried several different movies, for example 

svtplay-dl -S -M --output-format mkv --verbose https://www.tv4play.se/program/mord-och-inga-visor/del-20-s%C3%A4song-10/13279961

with the result:

DEBUG [1656855535.414504] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 4.13
DEBUG [1656855535.415107] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1656855535.415145] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/mord-och-inga-visor/del-20-s%C3%A4song-10/13279961'
DEBUG [1656855535.4206421] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1656855535.509435] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/mord-och-inga-visor/del-20-s%C3%A4song-10/13279961 HTTP/1.1" 200 None
DEBUG [1656855535.513803] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://playback-api.b17g.net/media/13279961?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome'
DEBUG [1656855535.514827] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback-api.b17g.net:443
DEBUG [1656855535.5681212] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/media/13279961?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome'): Retry(total=4, connect=5, read=5, redirect=None, status=None)
WARNING [1656855535.568247] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py/urlopen: Retrying (Retry(total=4, connect=5, read=5, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)'))': /media/13279961?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome
DEBUG [1656855535.568457] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (2): playback-api.b17g.net:443
DEBUG [1656855535.61447] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/media/13279961?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome'): Retry(total=3, connect=5, read=5, redirect=None, status=None)
WARNING [1656855536.2198882] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py/urlopen: Retrying (Retry(total=3, connect=5, read=5, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)'))': /media/13279961?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome
DEBUG [1656855536.221073] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (3): playback-api.b17g.net:443
DEBUG [1656855536.2900832] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/media/13279961?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome'): Retry(total=2, connect=5, read=5, redirect=None, status=None)
WARNING [1656855537.4955661] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py/urlopen: Retrying (Retry(total=2, connect=5, read=5, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)'))': /media/13279961?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome
DEBUG [1656855537.496377] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (4): playback-api.b17g.net:443
DEBUG [1656855537.549792] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/media/13279961?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome'): Retry(total=1, connect=5, read=5, redirect=None, status=None)
WARNING [1656855539.951149] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py/urlopen: Retrying (Retry(total=1, connect=5, read=5, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)'))': /media/13279961?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome
DEBUG [1656855539.953295] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (5): playback-api.b17g.net:443
DEBUG [1656855540.013432] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/media/13279961?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome'): Retry(total=0, connect=5, read=5, redirect=None, status=None)
WARNING [1656855544.818809] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py/urlopen: Retrying (Retry(total=0, connect=5, read=5, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)'))': /media/13279961?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome
DEBUG [1656855544.819777] /opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (6): playback-api.b17g.net:443
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='playback-api.b17g.net', port=443): Max retries exceeded with url: /media/13279961?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/svtplay_dl/utils/getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/svtplay_dl/utils/getmedia.py", line 112, in get_one_media
    for i in streams:
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/svtplay_dl/service/tv4play.py", line 71, in get
    res = self.http.request("get", url, cookies=self.cookies)
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/svtplay_dl/utils/http.py", line 42, in request
    res = Session.request(self, method, url, verify=self.verify, proxies=self.proxy, *args, **kwargs)
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/homebrew/Cellar/svtplay-dl/4.13/libexec/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='playback-api.b17g.net', port=443): Max retries exceeded with url: /media/13279961?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

**Comment by pythonuser3856** [comment]
It works for me; here's an example from right now:

h:dls -S -M --output-format mkv https://www.tv4play.se/program/smother/del-1-säsong-1/13343232
using svtplay-dl 4.13
INFO: Outfile: smother.s01e01.smother.del.1-13343232-tv4play.srt
INFO: Outfile: smother.s01e01.smother.del.1-13343232-tv4play.ts
INFO: Selected to download hls, bitrate: 3565 format: h264
[761/761][========================================] ETA: 0:00:00
[761/761][========================================] ETA: 0:00:00
INFO: Merge audio, video and subtitle into smother.s01e01.smother.del.1-13343232-tv4play.mkv
INFO: Determining the language of the subtitle(s).
INFO: Language code: swe
INFO: Merging done, removing old files.
h:

**Comment by enur001** [comment]
It still doesn't work for me. I now reinstalled both svtplay-dl and ffmpeg and then tried to download a movie again from tv4play. It is still the same result with some errors about that the certificate cannot be verified.

**Comment by pythonuser3856** [comment]
Below is the beginning of a trace when I apply the same command and get a succecssful download.
I'm using the python code svtplay v4.13 **w/o config-file and no username nor password towards TV4play**,
and it's running on Python 3.8 and Windows.

h:svtplay-dl_exec -S -M --output-format mkv --verbose https://www.tv4play.se/program/mord-och-inga-visor/del-20-s%C3%A4song-10/13279961
DEBUG [1656956715.429244] svtplay-dl_v4.13\svtplay_dl\utils\getmedia.py/get_media: version: 4.13
DEBUG [1656956715.4302447] svtplay-dl_v4.13\svtplay_dl\service\__init__.py/__init__: service: tv4play
DEBUG [1656956715.4312463] svtplay-dl_v4.13\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/program/mord-och-inga-visor/del-20-sA4song-10/13279961'
DEBUG [1656956715.4352493] c:\users\my_win_account\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1656956715.998612] c:\users\my_win_account\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/mord-och-inga-visor/del-20-sA4song-10/13279961 HTTP/1.1" 200 None
DEBUG [1656956715.998612] svtplay-dl_v4.13\svtplay_dl\utils\http.py/request: HTTP getting 'https://playback-api.b17g.net/media/13279961?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome'
DEBUG [1656956716.0142384] c:\users\my_win_account\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback-api.b17g.net:443
DEBUG [1656956716.2486315] c:\users\my_win_account\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/13279961?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome HTTP/1.1" 200 954
DEBUG [1656956716.2486315] svtplay-dl_v4.13\svtplay_dl\utils\http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/827e5/zhn5zp321yz(13279961_ISMUSP).ism/zhn5zp321yz(13279961_ISMUSP).m3u8?hls_no_audio_only=true'
DEBUG [1656956716.2486315] c:\users\my_win_account\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): lbs-usp-hls-vod.cmore.se:443
DEBUG [1656956716.3267632] c:\users\my_win_account\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/827e5/zhn5zp321yz(13279961_ISMUSP).ism/zhn5zp321yz(13279961_ISMUSP).m3u8?hls_no_audio_only=true HTTP/1.1" 200 2961
DEBUG [1656956716.3267632] svtplay-dl_v4.13\svtplay_dl\utils\http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/827e5/zhn5zp321yz(13279961_ISMUSP).ism/zhn5zp321yz(13279961_ISMUSP)-textstream_swe=3000.m3u8'
DEBUG [1656956716.3423896] c:\users\my_win_account\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/827e5/zhn5zp321yz(13279961_ISMUSP).ism/zhn5zp321yz(13279961_ISMUSP)-textstream_swe=3000.m3u8 HTTP/1.1" 200 53575
DEBUG [1656956716.358016] svtplay-dl_v4.13\svtplay_dl\utils\http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/827e5/zhn5zp321yz(13279961_ISMUSP).ism/zhn5zp321yz(13279961_ISMUSP).mpd?hls_no_audio_only=true'
DEBUG [1656956716.5611572] c:\users\my_win_account\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/827e5/zhn5zp321yz(13279961_ISMUSP).ism/zhn5zp321yz(13279961_ISMUSP).mpd?hls_no_audio_only=true HTTP/1.1" 200 23329
DEBUG [1656956716.7017927] svtplay-dl_v4.13\svtplay_dl\utils\http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/827e5/zhn5zp321yz(13279961_ISMUSP).ism/zhn5zp321yz(13279961_ISMUSP)-textstream_swe=3000-1.webvtt'
DEBUG [1656956716.7017927] c:\users\my_win_account\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): lbs-usp-hls-vod.cmore.se:443
DEBUG [1656956716.7642987] c:\users\my_win_account\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/827e5/zhn5zp321yz(13279961_ISMUSP).ism/zhn5zp321yz(13279961_ISMUSP)-textstream_swe=3000-1.webvtt HTTP/1.1" 200 109
DEBUG [1656956716.7642987] svtplay-dl_v4.13\svtplay_dl\utils\http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/827e5/zhn5zp321yz(13279961_ISMUSP).ism/zhn5zp321yz(13279961_ISMUSP)-textstream_swe=3000-1.webvtt'
DEBUG [1656956716.7799237] c:\users\my_win_account\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/827e5/zhn5zp321yz(13279961_ISMUSP).ism/zhn5zp321yz(13279961_ISMUSP)-textstream_swe=3000-1.webvtt HTTP/1.1" 200 109
DEBUG [1656956716.7799237] svtplay-dl_v4.13\svtplay_dl\utils\http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/827e5/zhn5zp321yz(13279961_ISMUSP).ism/zhn5zp321yz(13279961_ISMUSP)-textstream_swe=3000-2.webvtt'
--- snip ---

**Comment by spaam** [comment]
@enur001 this is not really an issue with svtplay-dl.  it works both on macOS 10.15 and 12.4 🤔. something seems a bit wrong with your computer.   what happens if you type `curl 'https://playback-api.b17g.net/media/13279961?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome'`? 🤔

**Comment by enur001** [comment]
svtplay-dl works fine when I download from svtplay and has earlier also worked fine with tv4play. I usually use it every weekend and it has worked fine until last weekend with tv4play.
When I try your command, the result is: {"message":"Route GET:/ not found","error":"Not Found","statusCode":404}%

**Comment by spaam** [comment]
@styrsven i tried `skilda världar´ and `Hidden` it seems to work. what videos did you try?

**Comment by styrsven** [comment]
Oops. I just assumed that if I couldn't play it due to DRM (no DRM support in browsers on FreeBSD) I couldn't download it. My mistake. That and that zsh needs quoting of the URL where bash doesn't.
Sorry for the noise.
