### ISSUE TITLE
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1495]
### svtplay-dl versions:

svtplay-dl 4.13-10-g48f376a

### Operating system and Python version:

Windows 10

ffmpeg 5.1

### What is the issue:

I got this in a middle of a download from PlutoTV
```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\response.py", line 700, in _update_chunk_length
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\response.py", line 441, in _error_catcher
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\response.py", line 767, in read_chunked
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\response.py", line 704, in _update_chunk_length
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\models.py", line 816, in generate
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\response.py", line 575, in stream
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\response.py", line 796, in read_chunked
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\contextlib.py", line 131, in __exit__
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\response.py", line 458, in _error_catcher
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 93, in get_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 201, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 223, in download
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 286, in _download
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py", line 42, in request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\sessions.py", line 587, in request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\sessions.py", line 745, in send
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\models.py", line 899, in content
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\models.py", line 818, in generate
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```

**Comment by Sopor** [comment]
I got a 500 error from github but for some reason the issue was created ...
