### ISSUE TITLE
PlutoTV - ValueError: invalid literal for int() with base 16: b''

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1497]
### svtplay-dl versions:

svtplay-dl 4.13-10-g48f376a

### Operating system and Python version:

Windows 10

ffmpeg 5.1

### What is the issue:

I got this in a middle of a download from PlutoTV:
```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\response.py", line 700, in _update_chunk_length
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\response.py", line 441, in _error_catcher
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\response.py", line 767, in read_chunked
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\response.py", line 704, in _update_chunk_length
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\models.py", line 816, in generate
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\response.py", line 575, in stream
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\response.py", line 796, in read_chunked
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\contextlib.py", line 131, in __exit__
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\response.py", line 458, in _error_catcher
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 93, in get_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 201, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 223, in download
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 286, in _download
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py", line 42, in request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\sessions.py", line 587, in request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\sessions.py", line 745, in send
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\models.py", line 899, in content
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\models.py", line 818, in generate
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```

**Comment by spaam** [comment]
what video? does it happen all the time?

**Comment by Sopor** [comment]
I was using `-A` when it happened but it seems to happen again around 300.
```
svtplay-dl.exe https://pluto.tv/en/on-demand/series/walker-texas-ranger-sv/season/2/episode/det-stora-bingobluffen-1995-2-11
```

**Comment by Sopor** [comment]
I did a test with another downloader and i got no errors. The file was downloaded to the end.

```
[PlutoTV] walker-texas-ranger-sv: Downloading JSON metadata
[PlutoTV] 62e775d89f6f47001499e33d: Downloading m3u8 information
[PlutoTV] 62e775d89f6f47001499e33d: Downloading m3u8 playlist
[PlutoTV] 62e775d89f6f47001499e33d: Downloading m3u8 playlist
[PlutoTV] 62e775d89f6f47001499e33d: Downloading m3u8 playlist
[PlutoTV] 62e775d89f6f47001499e33d: Downloading m3u8 playlist
[PlutoTV] 62e775d89f6f47001499e33d: Downloading m3u8 playlist
[PlutoTV] 62e775d89f6f47001499e33d: Downloading m3u8 information
[info] 62e775d89f6f47001499e33d: Downloading 1 format(s): hls-2540
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 566
[download] Destination: Season_2-11-Det_stora_bingobluffen.mp4
[download] 100% of 855.92MiB in 03:57
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Season_2-11-Det_stora_bingobluffen.mp4"
```

**Comment by spaam** [comment]
another plutotv issue. man this site is just one special site..

this seems to be an issue in lib that the script depend on.  svtplay-dl depend on requests that depen on urllib3..

i guess this other thing you use dunno what variant that is . it use the internal python stuff 🤔

**Comment by Sopor** [comment]
I got the same error on another file too
`https://pluto.tv/en/on-demand/series/walker-texas-ranger-sv/season/2/episode/cowboy-1995-2-14-ptv1`

**Comment by Sopor** [comment]
@spaam You can check it by yourself
`https://github.com/yt-dlp/yt-dlp`

**Comment by Sopor** [comment]
I do get errors with the other downloader, but it won't crash and i can always resume

`ERROR: unable to download video data: IncompleteRead(16 bytes read)`

**Comment by iszla** [comment]
I am getting the same error every now and then on Pluto. Retrying the episode with the issue 2-5 times usually solves it. But would it be possible to catch this error and exit with the normal error state?

I have some simple bash scripts that generate download queues and then removes the episode from the queue once it has downloaded, it will not remove it from the queue if svtplay-dl exists with a normal error, like for example "ERROR: No videos found. Can't find video info" but when the application crashes with this exception it doesn't work.

**Comment by spaam** [comment]
i have tried downloading some videos and never getting this error.
sounds like this site is pretty broken and making dependencies that i use to throw exceptions and i need to add workarounds to fix plutos broken stuff. adding more fuel to actually removing the site 🤔

**Comment by iszla** [comment]
For me it works well enough, catching the exception and exiting with an error code would just be an convenience thing for my usecase.

**Comment by R3C01L-SWE** [comment]
FWIW as much as I understand and have seen this is not a site problem. It's actually a network error. I'm not 100% sure about the details if it cause a corruption to the segment or just not being able to read the manifest for the link to the segment etc.

I have seen it happen with yt-dlp as well while downloading bigger files. But with that it just retries and continues it doesn't crash out.

Should be relatively easy to add some error handling to the code or maybe just switch to fetching via aria2c for example.

**Comment by spaam** [comment]
it could be a network error.  i guess i need to test this thing on an unstable connection somehow 🤔 

svtplay-dl do have retry code that it should retry the transfer. but i guess it wont work when its an expectation like this this.  which is a bit weird or it happen several times and we only got the last lines from our comrades @Sopor . @iszla  said the same. 

IIRC  yt-dlp using the builtin urllib to do all the http fetching stuff.  🤔 


sure aria2c is great. same as curl , wget ,  fetch and other similar applications. i dont want this to be a frontend to those commands.

**Comment by R3C01L-SWE** [comment]
> it could be a network error. i guess i need to test this thing on an unstable connection somehow 🤔
> 
> svtplay-dl do have retry code that it should retry the transfer. but i guess it wont work when its an expectation like this this. which is a bit weird or it happen several times and we only got the last lines from our comrades @Sopor . @iszla said the same.
> 
> IIRC yt-dlp using the builtin urllib to do all the http fetching stuff. 🤔
> 
> sure aria2c is great. same as curl , wget , fetch and other similar applications. i dont want this to be a frontend to those commands.

Well. It's all up to you what you do with your tool. 

I can only suggest enhancements to the tool and solutions to problems.

I only mentioned aria2c because it is faster at downloading videos due to its multi segmenting of the audio and video streams. And how it handles errors right there in the downloader. More than once has it saved my bacon.
