### ISSUE TITLE
Latest snapshot is missing zip-archives

### ISSUE THREAD

**Issue by Gurkan911** [spaam/svtplay-dl#1503]
Index of /download/snapshots/20220918_051107/ is missing zip-files.

Would be great if this can be fixed.

Thank you in advance!

Best Wishes, Gurkan911

**Comment by Sopor** [comment]
No important updates in that commit, so you can use `https://svtplay-dl.se/download/snapshots/20220709_125010`

Here is the reason:
```
Traceback (most recent call last):
  File "setup.py", line [7](https://github.com/spaam/svtplay-dl/actions/runs/3084455340/jobs/4986626345#step:9:8), in <module>
    from cx_Freeze import setup, Executable
  File "C:\hostedtoolcache\windows\Python\3.[8](https://github.com/spaam/svtplay-dl/actions/runs/3084455340/jobs/4986626345#step:9:9).[10](https://github.com/spaam/svtplay-dl/actions/runs/3084455340/jobs/4986626345#step:9:11)\x64\lib\site-packages\cx_Freeze\__init__.py", line 4, in <module>
    from .dist import bdist_rpm, build, build_exe, install, install_exe, setup
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\cx_Freeze\dist.py", line 18, in <module>
    from .windist import bdist_msi
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\cx_Freeze\windist.py", line 1, in <module>
    import distutils.command.bdist_msi
ModuleNotFoundError: No module named 'distutils.command.bdist_msi'
Error: Process completed with exit code 1.
```

**Comment by Gurkan911** [comment]
OK, thank you for a swift response!
I'm already using snapshots/20220709_125010 so I guess all is fine.
/Gurkan911

**Comment by spaam** [comment]
this is fixed :)
