### ISSUE TITLE
tv4play crash

### ISSUE THREAD

**Issue by SweDennis** [spaam/svtplay-dl#1505]
### svtplay-dl versions:

```
dennis@gentoo ~/temp $ svtplay-dl --version
svtplay-dl 4.13+17.g0935aed
dennis@gentoo ~/temp $ 

```

### Operating system and Python version:

```
dennis@gentoo ~/temp $ uname -a
Linux gentoo 5.19.16-gentoo #1 SMP Sat Oct 15 17:04:54 CEST 2022 x86_64 Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz GenuineIntel GNU/Linux
dennis@gentoo ~/temp $ python --version
Python 3.10.8
dennis@gentoo ~/temp $ 
```

### What is the issue:

tv4play crash.

```
dennis@gentoo ~/temp $ svtplay-dl https://www.tv4play.se/program/sveriges-m%C3%A4sterkock-vip/del-5-s%C3%A4song-2/13758216?offset=0 -v
DEBUG [1666608389.6041913] /usr/lib/python3.10/site-packages/svtplay_dl-4.13+21.g1c9dcfa-py3.10.egg/svtplay_dl/utils/getmedia.py/get_media: version: 4.13+17.g0935aed
DEBUG [1666608389.6057587] /usr/lib/python3.10/site-packages/svtplay_dl-4.13+21.g1c9dcfa-py3.10.egg/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1666608389.605836] /usr/lib/python3.10/site-packages/svtplay_dl-4.13+21.g1c9dcfa-py3.10.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/sveriges-m%C3%A4sterkock-vip/del-5-s%C3%A4song-2/13758216?offset=0'
DEBUG [1666608389.6073482] /usr/lib/python3.10/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1666608390.0520678] /usr/lib/python3.10/site-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/sveriges-m%C3%A4sterkock-vip/del-5-s%C3%A4song-2/13758216?offset=0 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==4.13+21.g1c9dcfa', 'svtplay-dl')
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1472, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.10/site-packages/svtplay_dl-4.13+21.g1c9dcfa-py3.10.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3.10/site-packages/svtplay_dl-4.13+21.g1c9dcfa-py3.10.egg/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3.10/site-packages/svtplay_dl-4.13+21.g1c9dcfa-py3.10.egg/svtplay_dl/utils/getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "/usr/lib/python3.10/site-packages/svtplay_dl-4.13+21.g1c9dcfa-py3.10.egg/svtplay_dl/utils/getmedia.py", line 112, in get_one_media
    for i in streams:
  File "/usr/lib/python3.10/site-packages/svtplay_dl-4.13+21.g1c9dcfa-py3.10.egg/svtplay_dl/service/tv4play.py", line 49, in get
    janson2 = jansson["props"]["pageProps"]["initialApolloState"]
KeyError: 'pageProps'
dennis@gentoo ~/temp $ 
```

**Comment by spaam** [comment]
this is fixed in master.  will release a new version tonight :)

**Comment by SweDennis** [comment]
Confirmed as working ... Great going, and incredibly swift response ... :-D
