### ISSUE TITLE
Unable to download from tv4play

### ISSUE THREAD

**Issue by derenback** [spaam/svtplay-dl#1506]
### What is the issue:

svtplay-dl --verbose https://www.tv4play.se/program/sveriges-m%C3%A4sterkock-vip/del-5-s%C3%A4song-2/13758216
DEBUG [1666632531.1753619] /home/david/.local/lib/python3.10/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 4.13
DEBUG [1666632531.1777782] /home/david/.local/lib/python3.10/site-packages/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1666632531.1779284] /home/david/.local/lib/python3.10/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/sveriges-m%C3%A4sterkock-vip/del-5-s%C3%A4song-2/13758216'
DEBUG [1666632531.1822045] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1666632531.5049005] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/sveriges-m%C3%A4sterkock-vip/del-5-s%C3%A4song-2/13758216 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/home/david/.local/lib/python3.10/site-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/home/david/.local/lib/python3.10/site-packages/svtplay_dl/utils/getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "/home/david/.local/lib/python3.10/site-packages/svtplay_dl/utils/getmedia.py", line 112, in get_one_media
    for i in streams:
  File "/home/david/.local/lib/python3.10/site-packages/svtplay_dl/service/tv4play.py", line 48, in get
    janson2 = jansson["props"]["pageProps"]["initialApolloState"]
KeyError: 'pageProps'

**Comment by spaam** [comment]
this is fixed in master . will be a new release later tonight. :)

**Comment by derenback** [comment]
Oh, great!
