### ISSUE TITLE
TV4play:  No decryptor found for encrypted hls steam.

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#1537]
Using
Python 3.8.10
Windows 64
svtplay-dl 4.20

I get a failure at trying to get media with link:
https://www.tv4play.se/program/miss-marple/del-2-hemligheten-på-chimneys-säsong-5/2412287

svtplay-dl --verbose https://www.tv4play.se/program/miss-marple/del-2-hemligheten-på-chimneys-säsong-5/2412287

DEBUG [1682918097.8902936] c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\utils\getmedia.py/get_media: version: 4.20
DEBUG [1682918097.905911] c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\service\__init__.py/__init__: service: tv4play
DEBUG [1682918097.905911] c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/program/miss-marple/del-2-hemligheten-på-chimneys-säsong-5/2412287'
DEBUG [1682918097.905911] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1682918098.3903005] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443"GET /program/miss-marple/del-2-hemligheten-p%C3%A5-chimneys-s%C3%A4song-5/2412287 HTTP/1.1" 200 None
DEBUG [1682918098.4215505] c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\utils\http.py/request: HTTP getting 'https://playback2.a2d.tv/play/2412287?service=tv4&device=browser&browser=GoogleChrome&protocol=hls%2Cdash&drm=widevine&capabilities=live-drm-adstitch-

2%2Cexpired_assets'
DEBUG [1682918098.4215505] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback2.a2d.tv:443
DEBUG [1682918098.8746748] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://playback2.a2d.tv:443 "GET /play/2412287?service=tv4&device=browser&browser=GoogleChrome&protocol=hls%2Cdash&drm=widevine&capabilities=live-

drm-adstitch-2%2Cexpired_assets HTTP/1.1" 200 5289
DEBUG [1682918098.8746748] c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\utils\http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/d04826f5-3fd0-4568-bc9f-d002df30b0cf/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052.ism/.m3u8'

DEBUG [1682918098.8746748] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): vod.streaming.a2d.tv:443
DEBUG [1682918099.0621676] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /d04826f5-3fd0-4568-bc9f-d002df30b0cf/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052.ism/.m3u8 HTTP/1.1" 200 

5293
DEBUG [1682918099.0621676] c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\utils\http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/d04826f5-3fd0-4568-bc9f-d002df30b0cf/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052.ism/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052-

textstream_swe=1000.m3u8'
DEBUG [1682918099.093425] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /d04826f5-3fd0-4568-bc9f-d002df30b0cf/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052.ism/9a6b58e0-5b49-11ed-

b8ee-c9478e048644_20324052-textstream_swe=1000.m3u8 HTTP/1.1" 200 143348
DEBUG [1682918099.1559086] c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\utils\http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/d04826f5-3fd0-4568-bc9f-d002df30b0cf/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052.ism/.mpd'
DEBUG [1682918099.1715329] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /d04826f5-3fd0-4568-bc9f-d002df30b0cf/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052.ism/.mpd HTTP/1.1" 200 

3309
DEBUG [1682918099.3121667] c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\utils\http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/d04826f5-3fd0-4568-bc9f-d002df30b0cf/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052.ism/.mpd'
DEBUG [1682918099.3277986] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /d04826f5-3fd0-4568-bc9f-d002df30b0cf/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052.ism/.mpd HTTP/1.1" 200 

3309
DEBUG [1682918099.3277986] c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\utils\http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/d04826f5-3fd0-4568-bc9f-d002df30b0cf/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052.ism/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052-

textstream_swe=1000.dash'
DEBUG [1682918099.3434227] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /d04826f5-3fd0-4568-bc9f-d002df30b0cf/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052.ism/9a6b58e0-5b49-11ed-

b8ee-c9478e048644_20324052-textstream_swe=1000.dash HTTP/1.1" 200 670
DEBUG [1682918099.3434227] c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\utils\stream.py/format_prio: Format priority: ['h264', 'h264-51']DEBUG [1682918099.3434227] c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\utils\stream.py/protocol_prio: Protocol priority 

scores (higher is better): {'dash': 3, 'hls': 2, 'http': 1}
DEBUG [1682918099.3434227] c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\utils\http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/d04826f5-3fd0-4568-bc9f-d002df30b0cf/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052.ism/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052-

video=6500000.m3u8'
DEBUG [1682918099.359042] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): vod.streaming.a2d.tv:443
DEBUG [1682918099.4215481] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /d04826f5-3fd0-4568-bc9f-d002df30b0cf/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052.ism/9a6b58e0-5b49-11ed-

b8ee-c9478e048644_20324052-video=6500000.m3u8 HTTP/1.1" 200 135307
INFO [1682918099.4527972] c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\utils\output.py/find_dupes: Outfile: miss-marple.s05e02.miss.marple.del.2-hemligheten.pa.chimneys-2412287-tv4play.ts
INFO [1682918099.4527972] c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\utils\getmedia.py/get_one_media: Selected to download hls, bitrate: 7027 format: h264
DEBUG [1682918099.4527972] c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\utils\http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/d04826f5-3fd0-4568-bc9f-d002df30b0cf/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052.ism/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052-

audio=128000.m3u8'
DEBUG [1682918099.4527972] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): vod.streaming.a2d.tv:443
DEBUG [1682918099.5152984] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /d04826f5-3fd0-4568-bc9f-d002df30b0cf/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052.ism/9a6b58e0-5b49-11ed-

b8ee-c9478e048644_20324052-audio=128000.m3u8 HTTP/1.1" 200 143423
[0001/1395][........................................] ETA: 0:00:00
DEBUG [1682918099.577787] c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\utils\http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/d04826f5-3fd0-4568-bc9f-d002df30b0cf/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052.ism/hls/9a6b58e0-5b49-11ed-b8ee-

c9478e048644_20324052-audio=128000.m4s'
DEBUG [1682918099.609048] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /d04826f5-3fd0-4568-bc9f-d002df30b0cf/9a6b58e0-5b49-11ed-b8ee-c9478e048644_20324052.ism/hls/9a6b58e0-5b49-

11ed-b8ee-c9478e048644_20324052-audio=128000.m4s HTTP/1.1" 200 1860
Traceback (most recent call last):
  File "c:\svtplaydll\svtplay-dl_v420_2023-04-19py\__main__.py", line 15, in <module>    svtplay_dl.main()
  File "c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\__init__.py", line 69, in main    get_media(urls[0], config, __version__)
  File "c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\utils\getmedia.py", line 63, in get_media    get_one_media(stream)
  File "c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\utils\getmedia.py", line 201, in get_one_media
    fstream.download()
  File "c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\fetcher\hls.py", line 198, in download
    self._download(self.audio, True)
  File "c:\svtplaydll\svtplay-dl_v420_2023-04-19py\svtplay_dl\fetcher\hls.py", line 281, in _download
    raise ValueError("No decryptor found for encrypted hls steam.")
ValueError: No decryptor found for encrypted hls steam.

**Comment by pythonuser3856** [comment]
It may be an error at TV4play, I cannot watch it via my browser either.
I've reported the issue to TV4play.
