### ISSUE TITLE
Crash! Tv4play crashing after recent update to svtplay-dl

### ISSUE THREAD

**Issue by SweDennis** [spaam/svtplay-dl#1541]
Using:
```
dennis@gentoo ~ $ svtplay-dl --version
svtplay-dl 4.21
dennis@gentoo ~ $ uname -a
Linux gentoo 6.2.16-gentoo #1 SMP PREEMPT_DYNAMIC Wed May 17 17:05:08 CEST 2023 x86_64 Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz GenuineIntel GNU/Linux
dennis@gentoo ~ $ python --version
Python 3.11.3
dennis@gentoo ~ $
```
Command:
```
svtplay-dl https://www.tv4play.se/program/sveriges-m%C3%A4sterkock-vip/del-8-s%C3%A4song-3/13805833?offset=0 -v
```
Output:
```
dennis@gentoo ~ $ svtplay-dl https://www.tv4play.se/program/sveriges-m%C3%A4sterkock-vip/del-8-s%C3%A4song-3/13805833?offset=0 -v
DEBUG [1685729437.9034224] /usr/lib/python3.11/site-packages/svtplay_dl-4.21-py3.11.egg/svtplay_dl/utils/getmedia.py/get_media: version: 4.21
DEBUG [1685729437.9045334] /usr/lib/python3.11/site-packages/svtplay_dl-4.21-py3.11.egg/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1685729437.904605] /usr/lib/python3.11/site-packages/svtplay_dl-4.21-py3.11.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/sveriges-m%C3%A4sterkock-vip/del-8-s%C3%A4song-3/13805833?offset=0'
DEBUG [1685729437.9064524] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1685729438.4545784] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/sveriges-m%C3%A4sterkock-vip/del-8-s%C3%A4song-3/13805833?offset=0 HTTP/1.1" 200 None
DEBUG [1685729438.4698873] /usr/lib/python3.11/site-packages/svtplay_dl-4.21-py3.11.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://playback2.a2d.tv/play/13805833?service=tv4&device=browser&browser=GoogleChrome&protocol=hls%2Cdash&drm=widevine&capabilities=live-drm-adstitch-2%2Cexpired_assets'
DEBUG [1685729438.4732106] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback2.a2d.tv:443
DEBUG [1685729438.8602614] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_make_request: https://playback2.a2d.tv:443 "GET /play/13805833?service=tv4&device=browser&browser=GoogleChrome&protocol=hls%2Cdash&drm=widevine&capabilities=live-drm-adstitch-2%2Cexpired_assets HTTP/1.1" 200 5164
DEBUG [1685729438.8612359] /usr/lib/python3.11/site-packages/svtplay_dl-4.21-py3.11.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/c4c51ea5-8d61-4c4f-bea1-e1a72141934d/9d132bf0-fb9d-11ed-bbbf-ed18d491feab_20365177.ism/.m3u8'
DEBUG [1685729438.863807] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): vod.streaming.a2d.tv:443
DEBUG [1685729438.9970677] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /c4c51ea5-8d61-4c4f-bea1-e1a72141934d/9d132bf0-fb9d-11ed-bbbf-ed18d491feab_20365177.ism/.m3u8 HTTP/1.1" 200 627
DEBUG [1685729439.0069485] /usr/lib/python3.11/site-packages/svtplay_dl-4.21-py3.11.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/c4c51ea5-8d61-4c4f-bea1-e1a72141934d/9d132bf0-fb9d-11ed-bbbf-ed18d491feab_20365177.ism/9d132bf0-fb9d-11ed-bbbf-ed18d491feab_20365177-textstream_swe=1000.m3u8'
DEBUG [1685729439.0473304] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /c4c51ea5-8d61-4c4f-bea1-e1a72141934d/9d132bf0-fb9d-11ed-bbbf-ed18d491feab_20365177.ism/9d132bf0-fb9d-11ed-bbbf-ed18d491feab_20365177-textstream_swe=1000.m3u8 HTTP/1.1" 200 2349
DEBUG [1685729439.1746683] /usr/lib/python3.11/site-packages/svtplay_dl-4.21-py3.11.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/c4c51ea5-8d61-4c4f-bea1-e1a72141934d/9d132bf0-fb9d-11ed-bbbf-ed18d491feab_20365177.ism/.mpd'
DEBUG [1685729439.2111673] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /c4c51ea5-8d61-4c4f-bea1-e1a72141934d/9d132bf0-fb9d-11ed-bbbf-ed18d491feab_20365177.ism/.mpd HTTP/1.1" 200 1462
DEBUG [1685729439.320341] /usr/lib/python3.11/site-packages/svtplay_dl-4.21-py3.11.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/c4c51ea5-8d61-4c4f-bea1-e1a72141934d/9d132bf0-fb9d-11ed-bbbf-ed18d491feab_20365177.ism/.mpd'
DEBUG [1685729439.355503] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /c4c51ea5-8d61-4c4f-bea1-e1a72141934d/9d132bf0-fb9d-11ed-bbbf-ed18d491feab_20365177.ism/.mpd HTTP/1.1" 200 1462
DEBUG [1685729439.3669336] /usr/lib/python3.11/site-packages/svtplay_dl-4.21-py3.11.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/c4c51ea5-8d61-4c4f-bea1-e1a72141934d/9d132bf0-fb9d-11ed-bbbf-ed18d491feab_20365177.ism/9d132bf0-fb9d-11ed-bbbf-ed18d491feab_20365177-textstream_swe=1000.dash'
DEBUG [1685729439.3988094] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /c4c51ea5-8d61-4c4f-bea1-e1a72141934d/9d132bf0-fb9d-11ed-bbbf-ed18d491feab_20365177.ism/9d132bf0-fb9d-11ed-bbbf-ed18d491feab_20365177-textstream_swe=1000.dash HTTP/1.1" 200 670
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==4.21', 'svtplay-dl')
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 720, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1559, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.11/site-packages/svtplay_dl-4.21-py3.11.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3.11/site-packages/svtplay_dl-4.21-py3.11.egg/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3.11/site-packages/svtplay_dl-4.21-py3.11.egg/svtplay_dl/utils/getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "/usr/lib/python3.11/site-packages/svtplay_dl-4.21-py3.11.egg/svtplay_dl/utils/getmedia.py", line 157, in get_one_media
    subtitle_decider(stream, subtitles)
  File "/usr/lib/python3.11/site-packages/svtplay_dl-4.21-py3.11.egg/svtplay_dl/utils/stream.py", line 100, in subtitle_decider
    if subtitles and (stream.config.get("merge_subtitle") or stream.config.get("subtitle") or stream.config("get_all_subtitles")):
                                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'Options' object is not callable
dennis@gentoo ~ $ 
```

**Comment by spaam** [comment]
bah. forgot to test without -M :D

**Comment by SweDennis** [comment]
That's why you have us around ...

**Comment by spaam** [comment]
try the latest snapshot. it should fix the issue. will release a new version after that :)

**Comment by SweDennis** [comment]
All well with:

```
dennis@gentoo ~ $ svtplay-dl --version
svtplay-dl 4.21+1.gd35796f
dennis@gentoo ~ $ 
```
No errors, all lights green, case closed.

**Comment by spaam** [comment]
woho 🥳
