### ISSUE TITLE
Error msgs Python initscrips, line 130 in run, line 16 in run

### ISSUE THREAD

**Issue by torbjornljung** [spaam/svtplay-dl#1545]
### svtplay-dl versions: 4.24

Run `svtplay-dl --version` 2023-06-18

### Operating system and Python version:

Name and version of the operating system Windows 11 and python version 2021-05-03 (run `python --version`)

### What is the issue:

Using this command file:
@ECHO OFF
SET /P _inputname= Please enter a URL:
@ECHO Du intastede "%_inputname%"
svtplay-dl -S -A -u xxxxxxx@gmail.com -p xxxxxxx "%_inputname%"
pause
@ECHO OFF

Here's the error result:
Please enter a URL:https://www.tv4play.se/video/0bfd7b6128a1af6ffe82/band-of-dads
Du intastede "https://www.tv4play.se/video/0bfd7b6128a1af6ffe82/band-of-dads"
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 130, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 79, in get_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\tv4play.py", line 137, in find_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\tv4play.py", line 198, in _graphql
KeyError: 'data'
Press any key to continue . . .

**Comment by spaam** [comment]
reading the language in your script i assume this happen because you trying to access videos from denmark but the script is failing because i forgot to check if the video is geoblocked.  :)

**Comment by torbjornljung** [comment]
Hi Johan, just tried the same with vpn enabled, but got the same result.
Torbjörn
tis 27 juni 2023 kl. 12:11 skrev Johan Andersson ***@***.***>:

**Comment by spaam** [comment]
tv4play likes to block vpn enpoints. its not their first time doing it.  but can you watch the video without any issue?

**Comment by torbjornljung** [comment]
Yes, I can watch it after logging in, but not when using VPN

Den tis 27 juni 2023 kl 12:18 skrev Johan Andersson <
***@***.***>:

**Comment by torbjornljung** [comment]
I didn't want to show my login data, that's why you read ***@***.***

**Comment by GreveTess** [comment]
I seem to be having the same issue. I'm not on VPN (as that was a question above)

C:\Users\Tess>svtplay-dl --version
svtplay-dl 4.24

C:\Users\Tess>svtplay-dl -A --verbose https://www.tv4play.se/program/e560a10921357483f685/a-million-little-things
DEBUG [1687899048.3374865] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.24
DEBUG [1687899048.340479] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: tv4play
DEBUG [1687899048.3414788] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/program/e560a10921357483f685/a-million-little-things'
DEBUG [1687899048.343478] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1687899048.7031767] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/e560a10921357483f685/a-million-little-things HTTP/1.1" 200 None
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 130, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 79, in get_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\tv4play.py", line 136, in find_all_episodes
KeyError: 'allSeasonLinks'

**Comment by spaam** [comment]
@GreveTess you have a different issue

**Comment by GreveTess** [comment]
> @GreveTess you have a different issue
I'll open a new issue

**Comment by spaam** [comment]
test 4.25  should fix this.
