### ISSUE TITLE
pluto.tv 

### ISSUE THREAD

**Issue by bartdedecker** [spaam/svtplay-dl#1556]
### svtplay-dl versions:

Run `svtplay-dl --version`
       svtplay-dl 4.19-4-g7882f6d

### Operating system and Python version:

Name and version of the operating system and python version (run `python --version`)
      Windows 10
      python 3.8.0

### What is the issue:

keyurl = get_full_url(i["EXT-X-KEY"]["URI"], self.url)
     KeyError: 'URI'

    svtplay-dl --verbose https://www.example.com

% svtplay-dl --verbose https://pluto.tv/en/on-demand/series/svenska-truckers-sv/season/8/episode/avsnitt-803-2019-8-3
DEBUG [1694537840.8167331] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.19-4-g7882f6d
DEBUG [1694537840.8167331] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: plutotv
DEBUG [1694537840.8167331] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://pluto.tv/en/on-demand/series/svenska-truckers-sv/season/8/episode/avsnitt-803-2019-8-3'
DEBUG [1694537840.8167331] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): pluto.tv:443
DEBUG [1694537841.5867786] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://pluto.tv:443 "GET /en/on-demand/series/svenska-truckers-sv/season/8/episode/avsnitt-803-2019-8-3 HTTP/1.1" 200 None
DEBUG [1694537841.6401138] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://boot.pluto.tv/v4/start'
DEBUG [1694537841.6401138] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): boot.pluto.tv:443
DEBUG [1694537842.0116963] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://boot.pluto.tv:443 "GET /v4/start?appName=web&appVersion=7.7.0-18f7ab32608969ea5bcbce8d0e23b9d0e1b24717&deviceVersion=100.0.0&deviceModel=web&deviceMake=firefox&deviceType=web&clientID=70995af2-518d-11ee-81d0-3ca9f48486f8&clientModelNumber=1.0.0&episodeSlugs=svenska-truckers-sv&serverSideAds=false&constraints=&drmCapabilities=widevine%253AL3&clientTime=2023-09-12T16%3A57%3A21Z HTTP/1.1" 200 None
DEBUG [1694537842.0759246] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://service-vod.clusters.pluto.tv/v4/vod/slugs/svenska-truckers-sv'
DEBUG [1694537842.0759246] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): service-vod.clusters.pluto.tv:443
DEBUG [1694537842.4188015] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://service-vod.clusters.pluto.tv:443 "GET /v4/vod/slugs/svenska-truckers-sv?appName=web&appVersion=7.7.0-18f7ab32608969ea5bcbce8d0e23b9d0e1b24717&deviceVersion=100.0.0&deviceModel=web&deviceMake=firefox&deviceType=web&clientID=70995af2-518d-11ee-81d0-3ca9f48486f8&clientModelNumber=1.0.0&episodeSlugs=svenska-truckers-sv&serverSideAds=false&constraints=&drmCapabilities=widevine%253AL3&clientTime=2023-09-12T16%3A57%3A21Z HTTP/1.1" 200 None
DEBUG [1694537842.4344265] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/stitch/hls/episode/64f5a50c6930bb0013030143/master.m3u8?advertisingId=&appName=web&appVersion=7.7.0-18f7ab32608969ea5bcbce8d0e23b9d0e1b24717&app_name=web&clientDeviceType=0&clientID=70995af2-518d-11ee-81d0-3ca9f48486f8&clientModelNumber=1.0.0&country=SE&deviceDNT=false&deviceId=70995af2-518d-11ee-81d0-3ca9f48486f8&deviceLat=59.3287&deviceLon=18.0717&deviceMake=firefox&deviceModel=web&deviceType=web&deviceVersion=100.0.0&marketingRegion=SE&serverSideAds=false&sessionID=7004065c-518d-11ee-bbb3-16212608c4e1&sid=7004065c-518d-11ee-bbb3-16212608c4e1&userId='
DEBUG [1694537842.4409344] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv:443
DEBUG [1694537844.0243394] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv:443 "GET /stitch/hls/episode/64f5a50c6930bb0013030143/master.m3u8?advertisingId=&appName=web&appVersion=7.7.0-18f7ab32608969ea5bcbce8d0e23b9d0e1b24717&app_name=web&clientDeviceType=0&clientID=70995af2-518d-11ee-81d0-3ca9f48486f8&clientModelNumber=1.0.0&country=SE&deviceDNT=false&deviceId=70995af2-518d-11ee-81d0-3ca9f48486f8&deviceLat=59.3287&deviceLon=18.0717&deviceMake=firefox&deviceModel=web&deviceType=web&deviceVersion=100.0.0&marketingRegion=SE&serverSideAds=false&sessionID=7004065c-518d-11ee-bbb3-16212608c4e1&sid=7004065c-518d-11ee-bbb3-16212608c4e1&userId= HTTP/1.1" 200 2328
DEBUG [1694537844.0243394] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/stitch/hls/episode/64f5a50c6930bb0013030143/master.m3u8?advertisingId=&appName=web&appVersion=7.7.0-18f7ab32608969ea5bcbce8d0e23b9d0e1b24717&app_name=web&clientDeviceType=0&clientID=70995af2-518d-11ee-81d0-3ca9f48486f8&clientModelNumber=1.0.0&country=SE&deviceDNT=false&deviceId=70995af2-518d-11ee-81d0-3ca9f48486f8&deviceLat=59.3287&deviceLon=18.0717&deviceMake=firefox&deviceModel=web&deviceType=web&deviceVersion=100.0.0&marketingRegion=SE&serverSideAds=false&sessionID=7004065c-518d-11ee-bbb3-16212608c4e1&sid=7004065c-518d-11ee-bbb3-16212608c4e1&userId='
DEBUG [1694537844.2079957] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv:443 "GET /stitch/hls/episode/64f5a50c6930bb0013030143/master.m3u8?advertisingId=&appName=web&appVersion=7.7.0-18f7ab32608969ea5bcbce8d0e23b9d0e1b24717&app_name=web&clientDeviceType=0&clientID=70995af2-518d-11ee-81d0-3ca9f48486f8&clientModelNumber=1.0.0&country=SE&deviceDNT=false&deviceId=70995af2-518d-11ee-81d0-3ca9f48486f8&deviceLat=59.3287&deviceLon=18.0717&deviceMake=firefox&deviceModel=web&deviceType=web&deviceVersion=100.0.0&marketingRegion=SE&serverSideAds=false&sessionID=7004065c-518d-11ee-bbb3-16212608c4e1&sid=7004065c-518d-11ee-bbb3-16212608c4e1&userId= HTTP/1.1" 200 2328
DEBUG [1694537844.2235856] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/stitch/hls/episode/64f5a50c6930bb0013030143/subtitle/sv/playlist.m3u8?terminate=false&sid=7004065c-518d-11ee-bbb3-16212608c4e1&deviceDNT=0&deviceLat=59.3287&deviceLon=18.0717&deviceModel=web&deviceVersion=100.0.0&appName=web&deviceId=70995af2-518d-11ee-81d0-3ca9f48486f8&appVersion=7.7.0-18f7ab32608969ea5bcbce8d0e23b9d0e1b24717&deviceType=web&deviceMake=firefox'
DEBUG [1694537844.2392094] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv:443
DEBUG [1694537844.6938522] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv:443 "GET /stitch/hls/episode/64f5a50c6930bb0013030143/subtitle/sv/playlist.m3u8?terminate=false&sid=7004065c-518d-11ee-bbb3-16212608c4e1&deviceDNT=0&deviceLat=59.3287&deviceLon=18.0717&deviceModel=web&deviceVersion=100.0.0&appName=web&deviceId=70995af2-518d-11ee-81d0-3ca9f48486f8&appVersion=7.7.0-18f7ab32608969ea5bcbce8d0e23b9d0e1b24717&deviceType=web&deviceMake=firefox HTTP/1.1" 200 95580
DEBUG [1694537844.7780864] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/stitch/hls/episode/64f5a50c6930bb0013030143/subtitle/sv/playlist.m3u8?terminate=false&sid=7004065c-518d-11ee-bbb3-16212608c4e1&deviceDNT=0&deviceLat=59.3287&deviceLon=18.0717&deviceModel=web&deviceVersion=100.0.0&appName=web&deviceId=70995af2-518d-11ee-81d0-3ca9f48486f8&appVersion=7.7.0-18f7ab32608969ea5bcbce8d0e23b9d0e1b24717&deviceType=web&deviceMake=firefox'
DEBUG [1694537844.7937355] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv:443
DEBUG [1694537845.1789308] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv:443 "GET /stitch/hls/episode/64f5a50c6930bb0013030143/subtitle/sv/playlist.m3u8?terminate=false&sid=7004065c-518d-11ee-bbb3-16212608c4e1&deviceDNT=0&deviceLat=59.3287&deviceLon=18.0717&deviceModel=web&deviceVersion=100.0.0&appName=web&deviceId=70995af2-518d-11ee-81d0-3ca9f48486f8&appVersion=7.7.0-18f7ab32608969ea5bcbce8d0e23b9d0e1b24717&deviceType=web&deviceMake=firefox HTTP/1.1" 200 95580
DEBUG [1694537845.6803684] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://siloh-sp.plutotv.net/593_pluto/clip/64f5a50b6930bb001303012a_Svenska_Truckers_SV_Avsnitt_803_S8E3/720pDRM/20230904_023611/hls/0-753760/sv-sub/00000.vtt'
DEBUG [1694537845.6803684] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): siloh-sp.plutotv.net:443
DEBUG [1694537845.927923] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://siloh-sp.plutotv.net:443 "GET /593_pluto/clip/64f5a50b6930bb001303012a_Svenska_Truckers_SV_Avsnitt_803_S8E3/720pDRM/20230904_023611/hls/0-753760/sv-sub/00000.vtt HTTP/1.1" 200 55
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 135, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 18, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 63, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 157, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\stream.py", line 107, in subtitle_decider
  File "C:\Program Files\Svtplay-dl\lib\svtplay_dl\subtitle\__init__.py", line 96, in download
    data = self.wrstsegment(subdata)
  File "C:\Program Files\Svtplay-dl\lib\svtplay_dl\subtitle\__init__.py", line 303, in wrstsegment
    keyurl = get_full_url(i["EXT-X-KEY"]["URI"], self.url)
KeyError: 'URI'

**Comment by bartdedecker** [comment]
The problem occurs when there are no subtitles while the configuration file has option subtitle set to true.

**Comment by bartdedecker** [comment]
Same problem when there are subtitles, e.g.
https://pluto.tv/en/on-demand/series/efterlyst-sv/season/62/episode/avsnitt-6203-1989-62-3

When I added a few print statements in subtitle.__init__()
then it seems that self.kwargs["m3u8"].encrypted) == True
and json object "i" is:

{
  "EXT-X-DISCONTINUITY": {},
  "EXT-X-PROGRAM-DATE-TIME": "2023-09-26T21:59:15.850Z",
  "EXT-X-KEY": {
    "METHOD": "NONE"
  },
  "EXTINF": {
    "duration": 5.0,
    "title": ""
  },
  "URI": "https://siloh-fs.plutotv.net/303_pluto/clip/651289e0a61c2a001b53d430_Efterlyst_SV_Avsnitt_6203_S62E3/720pDRM/20230926_003600/hls/0-943560/sv-cc/00000.vtt"
}

Field "EXT-X-KEY" contains only "METHOD": "NONE"; there simply is no "URI"
