### ISSUE TITLE
Can no longer use svtplay-dl after attempt to upgrade from 4.25 to 4.28.1

### ISSUE THREAD

**Issue by EmmW** [spaam/svtplay-dl#1572]
### svtplay-dl versions:

> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/bin/svtplay-dl/__main__.py", line 12, in <module>
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
>   File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 7, in <module>
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 896, in _find_spec
>   File "<frozen importlib._bootstrap_external>", line 1136, in find_spec
>   File "<frozen importlib._bootstrap_external>", line 1112, in _get_spec
>   File "<frozen importlib._bootstrap_external>", line 1093, in _legacy_get_spec
>   File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
>   File "<frozen importlib._bootstrap_external>", line 530, in spec_from_file_location
>   File "/usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py", line 182
>     url = f"http://www.tv4play.se/?video_id={match.group(1)}"
>                                                             ^
> SyntaxError: invalid syntax

### Operating system and Python version:

Mac OS 10.14.6
Python 2.7.17 (when I write "pip3 install requests" I get back "Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (2.13.0)")

### What is the issue:

My previous svtplay-dl version 4.25 was working fine with svtplay-dl in Terminal but not with kunskapskanalen.se, so I checked svtplay-dl.se and noticed that there was an update to 4.28.1 available. I first tried "brew upgrade svtplay-dl" but that didn't work, the "svtplay-dl --version" command still responded with the older version. I then tried "sudo curl -L https://svtplay-dl.se/download/latest/svtplay-dl -o /usr/local/bin/svtplay-dl" followed by "sudo chmod a+rx /usr/local/bin/svtplay-dl", and after that even the older svtplay-dl version stopped working, and now I get the above error message...

A solution would be highly appreciated, so please let me know if you need any further details from me — thanks in advance!

**Comment by spaam** [comment]
your system python3 (3.5) is pretty old. it does not support a bunch of things that i use in the script.
i recommend using brew to install svtplay-dl instead.  why didn't it work? any error message? maybe something with your macos version is a bit old?

**Comment by EmmW** [comment]
Thanks Johan for your feedback. For the moment I have it working on my MacBook Air M1 with Mac OS 12.7 (using svtplay-dl 4.28.1), but I would really like/need to have it working on my iMac i7 with Mac OS 10.14 as well — I will get back to you here with more details about the error messages the week after next. Thanks!

**Comment by Sopor** [comment]
@EmmW I don't know if [this](https://github.com/Homebrew/homebrew-core/issues/62911#issuecomment-713127246) can help you?
