### ISSUE TITLE
Failing to download content on dr.dk

### ISSUE THREAD

**Issue by jkiddo** [spaam/svtplay-dl#1574]
Using svtplay-dl 4.28.1 - fails on the following url from dr.dk:

```
jkiddo@badseed Desktop % svtplay-dl https://www.dr.dk/drtv/se/das-boot_-omringet_393853
INFO: suuubu
INFO: Outfile: das.boot.sson.3.omringet.se.online.her.drtv-dr.ts
INFO: Selected to download hls, bitrate: 5654 format: h264
[001/283][.........................................................................................................................................................................] ETA: 0:00:00Traceback (most recent call last):
  File "/opt/homebrew/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/opt/homebrew/Cellar/svtplay-dl/4.28.1_1/libexec/lib/python3.12/site-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/opt/homebrew/Cellar/svtplay-dl/4.28.1_1/libexec/lib/python3.12/site-packages/svtplay_dl/utils/getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "/opt/homebrew/Cellar/svtplay-dl/4.28.1_1/libexec/lib/python3.12/site-packages/svtplay_dl/utils/getmedia.py", line 201, in get_one_media
    fstream.download()
  File "/opt/homebrew/Cellar/svtplay-dl/4.28.1_1/libexec/lib/python3.12/site-packages/svtplay_dl/fetcher/hls.py", line 205, in download
    self._download(self.audio, True)
  File "/opt/homebrew/Cellar/svtplay-dl/4.28.1_1/libexec/lib/python3.12/site-packages/svtplay_dl/fetcher/hls.py", line 288, in _download
    raise ValueError("No decryptor found for encrypted hls steam.")
ValueError: No decryptor found for encrypted hls steam.
jkiddo@badseed Desktop %
```

**Comment by SweDennis** [comment]
Hello, late reply but can confirm.
When on a swedish IP I get a different message, but when "in Denmark" I get this message ...

Using:

```
dennis@gentoo ~ $ svtplay-dl --version
/usr/bin/svtplay-dl:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('svtplay-dl==4.28.1', 'svtplay-dl')
svtplay-dl 4.28.1
dennis@gentoo ~ $ python --version
Python 3.11.5
dennis@gentoo ~ $ uname -a
Linux gentoo 6.6.1-gentoo #1 SMP PREEMPT_DYNAMIC Wed Nov  8 16:54:27 CET 2023 x86_64 Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz GenuineIntel GNU/Linux
dennis@gentoo ~ $ 

```

**Comment by spaam** [comment]
It seems like a "bigger" issue than i thought it would be. the issue is related to parsing the playlist we getting for dr.dk. for some reason the needed crypto info getting removed for some reason and that is why you getting that error message.  🤔

**Comment by spaam** [comment]
bit late with the release. but this should work better now in 4.69 :)
