### ISSUE TITLE
pluto.tv - AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1594]
### svtplay-dl versions:

svtplay-dl 4.69

### Operating system and Python version:

Windows 10

### What is the issue:

```
svtplay-dl.exe -S https://pluto.tv/en/on-demand/series/6557380362063800133d019e/season/1/episode/6557380662063800133d0281
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 63, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 157, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\stream.py", line 123, in subtitle_decider
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\subtitle\__init__.py", line 97, in download
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\subtitle\__init__.py", line 316, in wrstsegment
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\subtitle\__init__.py", line 381, in _wrstsegments
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by spaam** [comment]
yeah.  there seems to be an issue yeah . but at the same time there is another issue also that the subtitles  starts from 00:00:00  after their ad thing.  sooo i dont know how to deal with that in a good way.. plus pluto that i cant watch pluto on my computers sooo.  maybe i should just disable subtitles for pluto and write a warning that subs is no longer suportet for the site? 🤔
