### ISSUE TITLE
Error downloading SVT Play

### ISSUE THREAD

**Issue by Link467** [spaam/svtplay-dl#1620]
PS C:\Apps\svtplay-dl> .\svtplay-dl.exe --subfolder -M https://www.svtplay.se/video/KrJY1bx/en-dag-kommer-allt-det-har-bli-ditt --verbose
DEBUG [1718357555.7906744] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.79
DEBUG [1718357555.7906744] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1718357555.7906744] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/KrJY1bx/en-dag-kommer-allt-det-har-bli-ditt'
DEBUG [1718357555.7906744] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1718357555.9468951] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/KrJY1bx/en-dag-kommer-allt-det-har-bli-ditt HTTP/1.1" 200 24259
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 138, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 17, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 63, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 112, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 87, in get
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 317, in outputfilename
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 338, in seasoninfo
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 350, in _find_season
KeyError: 'analyticsIdentifiers'

**Comment by sebbe34-svt** [comment]
får samma problem

**Comment by spaam** [comment]
vi har en issue grej för detta redan #1619  . så stänger denna så kolla på den issuen för uppdateringar :)
