### ISSUE TITLE
Nerladdning från svtplay fungerar inte: KeyError: 'analyticsIdentifiers'

### ISSUE THREAD

**Issue by MrScruffyish** [spaam/svtplay-dl#1622]
### svtplay-dl versions:
4.79

### Operating system and Python version:

Ubuntu 22.04 
python  3.10.12

### What is the issue:

Körde nerladdning från tv4 och det gick jättebra, men körde sedan direkt efter från svtplay och får då felet:

svtplay-dl -SMA --all-subtitles --verbose https://www.svtplay.se/video/ebYppwR/skruva-den-som-beckham 
DEBUG [1718396924.5257223] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 4.79
DEBUG [1718396924.5268245] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1718396924.5272746] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/ebYppwR/skruva-den-som-beckham'
DEBUG [1718396924.528371] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1718396924.7555978] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/ebYppwR/skruva-den-som-beckham HTTP/1.1" 200 24327
DEBUG [1718396924.7639894] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: svtplay
INFO [1718396924.7640681] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_all_episodes: Episode 1 of 1
INFO [1718396924.7641044] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_all_episodes: Url: http://www.svtplay.se/video/ebYppwR/skruva-den-som-beckham
DEBUG [1718396924.7641482] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://www.svtplay.se/video/ebYppwR/skruva-den-som-beckham'
DEBUG [1718396924.7647817] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): www.svtplay.se:80
DEBUG [1718396924.7985904] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://www.svtplay.se:80 "GET /video/ebYppwR/skruva-den-som-beckham HTTP/1.1" 301 0
DEBUG [1718396924.7994924] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1718396924.9257562] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/ebYppwR/skruva-den-som-beckham HTTP/1.1" 200 24327
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 69, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 61, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 93, in get_all_episodes
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 112, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 87, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 317, in outputfilename
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 338, in seasoninfo
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 350, in _find_season
KeyError: 'analyticsIdentifiers'

**Comment by spaam** [comment]
Om du tankar hem `4.83` som va släppt för ~20min sedan så kommer de funkar igen :)
