### ISSUE TITLE
TV4 Play  Error / CRASH

### ISSUE THREAD

**Issue by StreetCracker** [spaam/svtplay-dl#1623]
### svtplay-dl versions:

svtplay-dl 4.83

### Operating system and Python version:

Microsoft Windows [Version 10.0.19045.4239]

Name and version of the operating system and python version (run `python --version`)

### What is the issue:

Microsoft Windows [Version 10.0.19045.4239]
(c) Microsoft Corporation. Med ensamrätt.

C:\WINDOWS\system32>
C:\WINDOWS\system32>cd C:\svtplay-dl\svtplay-dl-amd64\svtplay-dl

C:\svtplay-dl\svtplay-dl-amd64\svtplay-dl>svtplay-dl.exe --token "*****" -u ***** -p ***** --no-postprocess  --format-preferred hevc-51,hevc,h264-51,h264  --resolution 1080,720  -o "D:\Video\svtplay-dl\DLs  -  TV4 Play" --nfo -t -S -A --include-clips https://www.tv4play.se/program/fb0e3a15f18dd02898fb/vit-sand
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 141, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 25, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 79, in get_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\tv4play.py", line 135, in find_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\tv4play.py", line 212, in _graphql
TypeError: unsupported operand type(s) for /: 'str' and 'int'

C:\svtplay-dl\svtplay-dl-amd64\svtplay-dl>

C:\svtplay-dl\svtplay-dl-amd64\svtplay-dl>
C:\svtplay-dl\svtplay-dl-amd64\svtplay-dl>cd C:\svtplay-dl\svtplay-dl-amd64\svtplay-dl

C:\svtplay-dl\svtplay-dl-amd64\svtplay-dl>svtplay-dl.exe --verbose --token "*****" -u ***** -p ***** --no-postprocess  --format-preferred hevc-51,hevc,h264-51,h264  --resolution 1080,720  -o "D:\Video\svtplay-dl\DLs  -  TV4 Play" --nfo -t -S -A --include-clips https://www.tv4play.se/program/fb0e3a15f18dd02898fb/vit-sand
DEBUG [1718755918.2525802] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.83
DEBUG [1718755918.2545366] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: tv4play
DEBUG [1718755918.2555356] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://avod-auth-alb.a2d.tv/oauth/refresh'
DEBUG [1718755918.2595346] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): avod-auth-alb.a2d.tv:443
DEBUG [1718755918.3886013] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://avod-auth-alb.a2d.tv:443 "POST /oauth/refresh HTTP/1.1" 200 624
DEBUG [1718755918.3905451] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/program/fb0e3a15f18dd02898fb/vit-sand'
DEBUG [1718755918.3925695] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1718755921.4616418] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/fb0e3a15f18dd02898fb/vit-sand HTTP/1.1" 200 None
DEBUG [1718755921.4696598] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://client-gateway.tv4.a2d.tv/graphql'
DEBUG [1718755921.471594] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): client-gateway.tv4.a2d.tv:443
DEBUG [1718755921.6394777] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://client-gateway.tv4.a2d.tv:443 "POST /graphql HTTP/1.1" 200 2367
DEBUG [1718755921.6404557] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://client-gateway.tv4.a2d.tv/graphql'
DEBUG [1718755921.718601] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://client-gateway.tv4.a2d.tv:443 "POST /graphql HTTP/1.1" 200 2703
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 141, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 25, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 79, in get_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\tv4play.py", line 135, in find_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\tv4play.py", line 212, in _graphql
TypeError: unsupported operand type(s) for /: 'str' and 'int'

**Comment by StreetCracker** [comment]
Oh Hey !
And Also ,

This particular one series is due to be **Taken Down**  by the end of  	_**Friday  21 june 2024**_
https://www.tv4play.se/program/fb0e3a15f18dd02898fb/vit-sand 

I would Much **Appreciate** if this is Resolved Before Then.

Thank You

**Comment by BacchusFLT** [comment]
I also have an issue with TV4 - wanted to download the full range of "Morden i Midsomer" but got this strange error:

c:\Download\Temp>svtplay-dl -S -A https://www.tv4play.se/program/09bbe1c047e296ac74fd/morden-i-midsomer
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 141, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 25, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 79, in get_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\tv4play.py", line 135, in find_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\tv4play.py", line 212, in _graphql
TypeError: unsupported operand type(s) for /: 'str' and 'int'

**Comment by spaam** [comment]
because i do this on my spare time and im not getting paid so messages like "plix fix this before X because of Y" will make things slower FYI.

**Comment by spaam** [comment]
this is fixed in `4.89`.  please no "plix fix this before X because of Y" in the future.
if you want things fixed fast, there is a donation page on the website :)
