### ISSUE TITLE
CRASH: New clean install, pretty much nothing works ...

### ISSUE THREAD

**Issue by SweDennis** [spaam/svtplay-dl#1635]
Hi,

just upgraded to 4.97.1 and I get the below error no matter what I try, even a svtplay-dl --version works ...
Wiped everything and cloned again, same result ...

Using:

```
dennis@gentoo ~/source/svtplay-dl $ svtplay-dl --version
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 33, in <module>
    sys.exit(load_entry_point('svtplay-dl==4.97.1', 'console_scripts', 'svtplay-dl')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/svtplay-dl", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^
StopIteration
dennis@gentoo ~/source/svtplay-dl $ python --version
Python 3.12.3
dennis@gentoo ~/source/svtplay-dl $ uname -a
Linux gentoo 6.9.12-gentoo #1 SMP PREEMPT_DYNAMIC Mon Jul 29 15:32:36 CEST 2024 x86_64 Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz GenuineIntel GNU/Linux
dennis@gentoo ~/source/svtplay-dl $ 
```

The error with --version pretty much says it all, that is what I get no matter what ...

Regards,
/Dennis

**Comment by spaam** [comment]
baah i hate python
https://github.com/spaam/svtplay-dl/commit/be2e1bcb3128c01470e4e1ef10e5d3f421c0640a this shit broke it.

**Comment by spaam** [comment]
what version of `python3-importlib-metadata`   do you have? it might be only called `importlib-metadata`? 
i know it works for me in ubuntu 22.04 with `python3-importlib-metadata             4.6.4-1`

**Comment by SweDennis** [comment]
I'm on 8.0.0 for that one. 8.2.0 appears to be the lastest ...

**Comment by spaam** [comment]
hmm weird . when i setup pyenv and 3.12  on my machine it works fine. 
how does the `svtplay-dl` file look like for you?

**Comment by SweDennis** [comment]
Like this :
```
#!/usr/lib/python-exec/python3.12/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'svtplay-dl==4.97.1','console_scripts','svtplay-dl'
import re
import sys

# for compatibility with easy_install; see #2198
__requires__ = 'svtplay-dl==4.97.1'

try:
    from importlib.metadata import distribution
except ImportError:
    try:
        from importlib_metadata import distribution
    except ImportError:
        from pkg_resources import load_entry_point


def importlib_load_entry_point(spec, group, name):
    dist_name, _, _ = spec.partition('==')
    matches = (
        entry_point
        for entry_point in distribution(dist_name).entry_points
        if entry_point.group == group and entry_point.name == name
    )
    return next(matches).load()


globals().setdefault('load_entry_point', importlib_load_entry_point)


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('svtplay-dl==4.97.1', 'console_scripts', 'svtplay-dl')())
  
 ```

**Comment by SweDennis** [comment]
Always happy to open the door and say welcome in, if it would help ...

**Comment by SweDennis** [comment]
Case is resolved, as of now, old versions need to be removed from "/usr/lib/python3.12/site-packages" in my case. Once done, 4.97.1 works. Can only vouch for how it works on Linux ... Was not an issue before, but is now, and can't say I've seen it as an issue for other packages. site-packages directory is usually something I have to clean out as maintenance, to save space, and to not be confused by, with old versions, but here and now it actually made a functional difference.
