### ISSUE TITLE
unable to download from svtplay

### ISSUE THREAD

**Issue by teepa922** [spaam/svtplay-dl#1648]
Hi,

cannot seem to download anything from STV Play.

### svtplay-dl versions:

svtplay-dl 4.79

### Operating system and Python version:
Windows 10 22H2
Python 3.11.9

### What is the issue:

svtplay-dl https://www.svtplay.se/video/eb1DDXm/greta-gris/doktor-hamsters-jattepresen --verbose
DEBUG [1729152220.4533627] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.79
DEBUG [1729152220.4543638] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1729152220.4543638] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/eb1DDXm/greta-gris/doktor-hamsters-jattepresen'
DEBUG [1729152220.4566474] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1729152220.879478] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/eb1DDXm/greta-gris/doktor-hamsters-jattepresen HTTP/1.1" 200 35833
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 138, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 17, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 63, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 112, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 87, in get
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 317, in outputfilename
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 338, in seasoninfo
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 350, in _find_season
KeyError: 'analyticsIdentifiers'

What seems to be the issue? I have also tried other URLs but get the same error every time.

**Comment by spaam** [comment]
The issue is that you are running an old version of svtplay-dl. Update to 4.97.1 and it should work better :)

**Comment by teepa922** [comment]
Of course, my scoop was out of date and no git installed. Now its working, thanks and sorry! :D
