### ISSUE TITLE
TV4 Play  not working

### ISSUE THREAD

**Issue by StreetCracker** [spaam/svtplay-dl#1649]
### Operating system and Python version:

Microsoft Windows [Version 10.0.19045.4842]

C:\svtplay-dl\svtplay-dl-amd64\svtplay-dl>svtplay-dl --version
svtplay-dl 4.97

### What is the issue:

Has TV4 Play  changed again ?

C:\svtplay-dl\svtplay-dl-amd64\svtplay-dl>svtplay-dl.exe --token "ey…" -u ***** -p ***** --no-postprocess  --format-preferred hevc-51,hevc,h264-51,h264  --resolution 1080,720  -o "D:\Video\svtplay-dl\DLs  -  TV4 Play" --nfo -t -S -A --include-clips  https://www.tv4play.se/program/f2811a3d5e1ec3c61956/mystery-road https://www.tv4play.se/program/e5bea08b41be07107cb8/mystery-road-origin
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 141, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 25, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 71, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 39, in get_multiple_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 79, in get_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\tv4play.py", line 143, in find_all_episodes
KeyError: 'data'

**Comment by cobolbear** [comment]
looks kind of simiar to what I experince in #1647 more programs are "DRM protected", basically they will not find the source for the video

**Comment by posktomten** [comment]
https://www.tv4play.se/program/f2811a3d5e1ec3c61956/mystery-road
"ERROR: No videos found. Use the video page not the series page."
Pleas use: 
"https://www.tv4play.se/video/fcd1e079d389031306a7/avsnitt-1-gone"
