### ISSUE TITLE
en viss token 'NoneType' förutsätts på svt..

### ISSUE THREAD

**Issue by sebbe34-svt** [spaam/svtplay-dl#1650]
svtplay-dl --list-quality https://www.svtplay.se/video/KGVkog5/svt-nyheter-direkt/presstraff-om-forsvarssatsningar?info=visa --verbose

DEBUG [1729455517.9193997] /media/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 4.97.1
DEBUG [1729455517.9220726] /media/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1729455517.922135] /media/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/KGVkog5/svt-nyheter-direkt/presstraff-om-forsvarssatsningar?info=visa'
DEBUG [1729455517.9237914] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1729455517.9962997] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/KGVkog5/svt-nyheter-direkt/presstraff-om-forsvarssatsningar?info=visa HTTP/1.1" 200 24574
DEBUG [1729455518.0068016] /media/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://api.svt.se/video/jgWzpka'
DEBUG [1729455518.0083284] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): api.svt.se:443
DEBUG [1729455518.0706878] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://api.svt.se:443 "GET /video/jgWzpka HTTP/1.1" 200 1264
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/media/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/__init__.py", line 69, in main
  File "/media/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 63, in get_media
  File "/media/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 112, in get_one_media
  File "/media/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 100, in get
  File "/media/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 119, in _get_video
TypeError: 'NoneType' object is not subscriptable

**Comment by spaam** [comment]
Interesting 🤔

**Comment by sebbe34-svt** [comment]
det verkar inte vara ett vanligt fel, men har inträffat på nån enstaka  "nyhets"-sida.

**Comment by quite** [comment]
is it the same that i get on `svtplay-dl --verbose https://www.svtplay.se/video/eXYgP1A/vinter`?

```Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3.12/site-packages/svtplay_dl/utils/getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "/usr/lib/python3.12/site-packages/svtplay_dl/utils/getmedia.py", line 112, in get_one_media
    for i in streams:
             ^^^^^^^
  File "/usr/lib/python3.12/site-packages/svtplay_dl/service/svtplay.py", line 100, in get
    yield from videos
  File "/usr/lib/python3.12/site-packages/svtplay_dl/service/svtplay.py", line 117, in _get_video
    drm = janson["rights"]["drmCopyProtection"]
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by spaam** [comment]
@quite what version are you using? You forgot that info. So I assume you are using an old version. Try 4.101 and see if it works better

**Comment by quite** [comment]
Sorry missed that, using latest 4.101 of course. But, my bad, the linked "vinter" URL is actually not being published until november 13th.

**Comment by spaam** [comment]
Aj see. I guess I forgot that check when I fixed something in the last version. 🤔 I can reproduce the issue here. Good. I will look into it tonight.
