### ISSUE TITLE
Failing version for me v4.101

### ISSUE THREAD

**Issue by Hipparcoss** [spaam/svtplay-dl#1659]
Hi

Before I used the second latest version of v4.83 and everything were ok.
And now a newer version was available v4.101.
I do the necessary changes as I usually do and the new version will not work at all.
I'll change back to the v4.83 version again and it works.

Where is the fault when changing to the new version?

 I have Windows 7 Professional 64-bit system and using ffmpeg version 2022-08-18-git-48be6616d0-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers for compling. The gears maybe be a litte bit old but it still runs well until now.

Now the new version v4.101 wount even start up.

When I enter svtplay-dl in the prompt I'll get the following error message.

"
C:\Users\privat>svtplay-dl
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\Lib\site-packages\cx_Freeze
\initscripts\__startup__.py", line 140, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\Lib\site-packages\cx_Freeze
\initscripts\console.py", line 25, in run
  File "bin\svtplay-dl", line 4, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 7, in <modu
le>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\cmore.py", line 6, in
<module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 15, in
<module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\subtitle\__init__.py", line 9,
 in <module>
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\cryptogra
phy\hazmat\primitives\ciphers\__init__.py", line 11, in <module>
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\cryptogra
phy\hazmat\primitives\ciphers\base.py", line 10, in <module>
ImportError: DLL load failed while importing _rust: Det går inte att hitta den a
ngivna proceduren.
"

What is the issue?
Thankfull for some help.

**Comment by spaam** [comment]
Yeah this is expected. The crypto library I use stopped supporting windows 7. It's an operating system Microsoft stopped supporting almost 5 years ago with security updates.
