### ISSUE TITLE
Support for Twitch seem to be broken

### ISSUE THREAD

**Issue by olof** [spaam/svtplay-dl#219]
$ svtplay-dl -v http://www.twitch.tv/clanmystik/c/6229670
    DEBUG [1425822254.86] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting 'http://www.twitch.tv/clanmystik/c/6229670'
    DEBUG [1425822255.66] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP got 21372 bytes from 'http://www.twitch.tv/clanmystik/c/6229670' in 0.79s (= 215966bps)
    Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/usr/bin/svtplay-dl/__main__.py", line 13, in <module>
      File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 234, in main
      File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 97, in get_media
      File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 120, in get_one_media
    TypeError: 'NoneType' object is not iterable

**Comment by spaam** [comment]
this is old.
