### ISSUE TITLE
Crash when using "\" at the end of the output folder

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#230]
When i end the output with a \ it seems to crash and it won't work. It would be nice if it worked even with a \ at the end :)
I don't know if UNC path have something to do with it?
```
python svtplay-dl -S http://www.kanal5play.se/program/3517812304/video/3496152288 -o "\\xbmcbuntu\TV Shows\test\"
INFO: Outfile: \\xbmcbuntu\TV Shows\test".srt
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "svtplay-dl\__main__.py", line 13, in <module>
  File "svtplay-dl\svtplay_dl\__init__.py", line 343, in main
  File "svtplay-dl\svtplay_dl\__init__.py", line 175, in get_media
  File "svtplay-dl\svtplay_dl\__init__.py", line 218, in get_one_media
  File "svtplay-dl\svtplay_dl\subtitle\__init__.py", line 35, in download
  File "svtplay-dl\svtplay_dl\output.py", line 140, in output
IOError: [Errno 22] invalid mode ('wb') or filename: '\\\\xbmcbuntu\\TV Shows\\test".srt'
```

**Comment by spaam** [comment]
the issue is not \ and the end. the problem is " around the output name.
