### ISSUE TITLE
-o can't handle international chars - åäö

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#233]
When i use an international character in the output path i get this message:
```
python svtplay-dl -S http://www.svtplay.se/video/2879014/vetenskapens-varld/vetenskapens-varld-avsnitt-14 -o "d:\image\smör gryta"
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "svtplay-dl\__main__.py", line 13, in <module>
  File "svtplay-dl\svtplay_dl\__init__.py", line 343, in main
  File "svtplay-dl\svtplay_dl\__init__.py", line 175, in get_media
  File "svtplay-dl\svtplay_dl\__init__.py", line 196, in get_one_media  File "C:\Python27\lib\ntpath.py", line 84, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 13: ordinal not in range(128)
```
It seems to work in file names but not folders.

I get different crash message if the folder is already exists or not. I can also see that the file name is gone. I believe you can find out more and if not you can always ask me.
```
python svtplay-dl -S http://www.svtplay.se/vid
eo/2879014/vetenskapens-varld/vetenskapens-varld-avsnitt-14 -o "d:\image\smör gryta\"
INFO: Outfile: d:/image/sm÷r gryta".srt
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "svtplay-dl\__main__.py", line 13, in <module>
  File "svtplay-dl\svtplay_dl\__init__.py", line 343, in main
  File "svtplay-dl\svtplay_dl\__init__.py", line 175, in get_media
  File "svtplay-dl\svtplay_dl\__init__.py", line 218, in get_one_media
  File "svtplay-dl\svtplay_dl\subtitle\__init__.py", line 35, in download
  File "svtplay-dl\svtplay_dl\output.py", line 140, in output
IOError: [Errno 22] invalid mode ('wb') or filename: 'd:/image/sm\xf6r gryta".srt'
```

**Comment by spaam** [comment]
python2 related bug. i get the same thing here but it works for python3

**Comment by Sopor-** [comment]
Now i get this:
```
python svtplay-dl -S http://www.svtplay.se/video/2879014/vetenskapens-varld/vetenskapens-varld-avsnitt-14 -o "d:\image\smör gryta\"
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "svtplay-dl\__main__.py", line 13, in <module>
  File "svtplay-dl\svtplay_dl\__init__.py", line 347, in main
  File "svtplay-dl\svtplay_dl\__init__.py", line 175, in get_media
  File "svtplay-dl\svtplay_dl\__init__.py", line 183, in get_one_media
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 11: invalid start byte
```

**Comment by Sopor-** [comment]
Now i need to first create the folder and if it exists it will use it and if it not exists it will name the file that name instead. Did it really worked that way before this? As you can see i end it with a \ to indicate it's a folder.
```
python svtplay-dl -S http://www.svtplay.se/video/2879014/vetenskapens-varld/vetenskapens-varld-avsnitt-14 -o "d:\image\smör gryta\"
INFO: Outfile: d:/image/smör gryta.srt
INFO: Selected to download hls, bitrate: 2794
INFO: Outfile: d:/image/smör gryta.ts
[070/353][========.....................................] ETA: 0:01:03
```

**Comment by spaam** [comment]
yes. we never create folders.

**Comment by Sopor-** [comment]
I understand...

But now i get this and i'm not sure where. Can you find it or do you need more info?
```
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 5, in <module>
    pkg_resources.run_script('svtplay-dl==0.10.2015.03.25', 'svtplay-dl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.10.2015.03.25-py2.7.egg/EGGINFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.10.2015.03.25-py2.7.egg/svtplay_dl/__init__.py", line 324, in main
    get_media(url, options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.10.2015.03.25-py2.7.egg/svtplay_dl/__init__.py", line 168, in get_media
    get_one_media(substream, copy.copy(options))
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.10.2015.03.25-py2.7.egg/svtplay_dl/__init__.py", line 199, in get_one_media
    subs[0].download()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.10.2015.03.25-py2.7.egg/svtplay_dl/subtitle/__init__.py", line 31, in download
    data = self.smi(subdata)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.10.2015.03.25-py2.7.egg/svtplay_dl/subtitle/__init__.py", line 121, in smi
    text = "%s\n" % TAG_RE.sub('', data.replace("<br>", "\n"))
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by Sopor-** [comment]
I was able to find it:
svtplay-dl -S -A --all-last=2 http://www.tv4play.se/program/gladiatorerna

**Comment by spaam** [comment]
that is some other issue

**Comment by Sopor-** [comment]
I get the same for this:
svtplay-dl -S -A --all-last=3 http://www.tv4play.se/program/sos-djur
Seems to have something to do with TV4 only...

**Comment by Sopor-** [comment]
Do you want me to create a new issue?

**Comment by Sopor-** [comment]
Do you think you manage to fix this so i can watch those programs tonight? :)

**Comment by spaam** [comment]
next time open a new ticket and its fixed

**Comment by Sopor-** [comment]
you want me to open a new issue, or what do you mean with "next time"?

**Comment by spaam** [comment]
it is fixed now.. next time it happen, open a new ticket.

**Comment by Sopor-** [comment]
I didn't know it was a new issue, sorry...
