### ISSUE TITLE
TV4Play - when i changed --all-last friom 2 to 3 i got this crash

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#234]
When i changed --all-last from 2 to 3 i got this crash:
```
svtplay-dl -S -A --all-last=3 http://www.tv4play.se/program/gladiatorerna
INFO: Episode 1 of 3
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 5, in <module>
    pkg_resources.run_script('svtplay-dl==0.10.2015.03.25', 'svtplay-dl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.10.2015.03.25-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.10.2015.03.25-py2.7.egg/svtplay_dl/__init__.py", line 324, in main
    get_media(url, options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.10.2015.03.25-py2.7.egg/svtplay_dl/__init__.py", line 168, in get_media
    get_one_media(substream, copy.copy(options))
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.10.2015.03.25-py2.7.egg/svtplay_dl/__init__.py", line 187, in get_one_media
    for i in streams:
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.10.2015.03.25-py2.7.egg/svtplay_dl/service/tv4play.py", line 119, in get
    error, data = get_http_data(url, cookiejar=self.cj)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.10.2015.03.25 py2.7.egg/svtplay_dl/utils/__init__.py", line 74, in get_http_data
    response = opener.open(request)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 104] Connection reset by peer

**Comment by Sopor-** [comment]
I got the same crash with this:
svtplay-dl -S -A --all-last=1 http://www.tv4play.se/program/familjen-annorlunda

**Comment by spaam** [comment]
i can't reproduce this right now. open a new ticket if it happen again
