### ISSUE TITLE
Re-add support for urplay.se

### ISSUE THREAD

**Issue by jmidgren** [spaam/svtplay-dl#252]
http://www.ur.se / http://urplay.se has a new design and svtplay-dl does not seem to work after the changes.

When trying to download an episode from the site I get the following output in the terminal:
```
$ svtplay-dl -o "Pinos födelsedag" http://www.ur.se/Produkter/167048-Pinos-dagbok-teckensprakstolkat-Pinos-fodelsedag

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 200, in main
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 86, in get_media
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 106, in get_one_media
  File "/usr/bin/svtplay-dl/svtplay_dl/service/urplay.py", line 29, in get
AttributeError: 'list' object has no attribute 'split'
```

**Comment by spaam** [comment]
I dont see this issue with the latest version of the script. try upgrade to the newest :)
