### ISSUE TITLE
Exclamation mark in URL causes TypeError: hlsparse() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by wthrbtn** [spaam/svtplay-dl#260]
svtplay-dl --version
0.10.2015.08.24
Ubuntu 14.04 Desktop LTS

Original URL:
http://urplay.se/Produkter/187396-Lana-for-livet!-Del-1

Escaping the exclamation mark in bash with backslash still causes problems:

svtplay-dl http://urplay.se/Produkter/187396-Lana-for-livet\!-Del-1
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 313, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 166, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 176, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/urplay.py", line 57, in get
TypeError: hlsparse() takes exactly 2 arguments (1 given)

I have tried encoding the "!" in different ways but it makes no difference. 
Other videos at urplay.se works fine. The only difference I can find is the exclamation mark.

Regards/Mvh
JH

**Comment by spaam** [comment]
awesome. thanks for playing around with master. :+1: 

tip and trix: you can put ' around the url if you dont want to escape !. :)
