### ISSUE TITLE
Is it possible to add www.dailymotion.com?

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#264]
Is it possible to add www.dailymotion.com ? If i try now i only get this:
```
python svtplay-dl http://www.dailymotion.com/video/x2ka1nn_violetta-season-1-episode-9_tv
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code exec code in run_globals
  File "svtplay-dl\__main__.py", line 13, in <module>
  File "svtplay-dl\svtplay_dl\__init__.py", line 313, in main
  File "svtplay-dl\svtplay_dl\__init__.py", line 133, in get_media
TypeError: __init__() takes exactly 2 arguments (1 given)
```

**Comment by olof** [comment]
I don't know how you got that stacktrace, i only get

    ERROR: That site is not supported. Make a ticket or send a message

(i.e excepted behavior, until this issue is fixed. I would suggest using youtube-dl until then.)

**Comment by Sopor-** [comment]
Maybe this was before you fixed that TV4 error? Many errors got fixed after that. I also now get "ERROR: That site is not supported. Make a ticket or send a message" when i run it.

**Comment by olof** [comment]
Ah, thanks for clarifying :)
