### ISSUE TITLE
URPlay: 'list' object has no attribute 'split'`

### ISSUE THREAD

**Issue by jelofsson** [spaam/svtplay-dl#269]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 200, in main
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 86, in get_media
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 106, in get_one_media
  File "/usr/bin/svtplay-dl/svtplay_dl/service/urplay.py", line 29, in get
AttributeError: 'list' object has no attribute 'split'

**Comment by spaam** [comment]
what version do you use? what video?

**Comment by jelofsson** [comment]
seems to work now when upgraded to latest version, this error was on the Ubuntu repo version.

**Comment by spaam** [comment]
okey. it will get a new version soon
