### ISSUE TITLE
URL parsing is off for dr.dk

### ISSUE THREAD

**Issue by moschler** [spaam/svtplay-dl#277]
(Note: works in version 0.10.2015.01.28)
When running svtplay-dl  (for example) 
./svtplay-dl --verbose https://www.dr.dk/tv/se/den-store-bagedyst/den-store-bagedyst-5-8-3

I get the following error message.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./svtplay-dl/__main__.py", line 13, in <module>
  File "./svtplay-dl/svtplay_dl/__init__.py", line 329, in main
  File "./svtplay-dl/svtplay_dl/__init__.py", line 170, in get_media
  File "./svtplay-dl/svtplay_dl/__init__.py", line 195, in get_one_media
requests.exceptions.InvalidSchema: No connection adapters were found for 'http:https://www.dr.dk/mu-online/api/1.3/bar/561598866187a909d005d581'

There is an error in the webaddress. An extra http: is added the the correct URL (which can be downloaded with wget.

**Comment by spaam** [comment]
thanks for the bug ticket. i will release a new version tonight with the fix.
