### ISSUE TITLE
can't download videos when using url from debuginformation

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#278]
In issue #201 you added support for downloading videos from the debuginformation you can get on every SVTPlay video. When i now try it i get this.
There should also be a fix for Windows?

```
$ svtplay-dl http://svtklipp2a-vh.akamaihd.net/z/fritt/open/20151012/K-20151012-152226-267/BARN-FREDAGSKVA-fb8491686f854dc4_,892,144,252,360,540,1584,2700,.mp4.csmil/manifest.f4m
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 5, in <module>pkg_resources.run_script('svtplay-dl==0.20.2015.09.13', 'svtplay-dl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_scriptself.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_scriptexecfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.20.2015.09.13-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module> svtplay_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.20.2015.09.13-py2.7.egg/svtplay_dl/__init__.py", line 341, in mainget_media(url, options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.20.2015.09.13-py2.7.egg/svtplay_dl/__init__.py", line 140, in get_mediaurl, stream = generic.get(sites)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.20.2015.09.13-py2.7.egg/svtplay_dl/service/__init__.py", line 150, in getreturn url, stream
UnboundLocalError: local variable 'url' referenced before assignment

```

**Comment by Sopor-** [comment]
i got a very funny file name when i download, "access.denied.flv"

**Comment by spaam** [comment]
that is expected because you didn't add anything after the manifest.f4m on the akamaihd.net domain. you can add "?hdcore=3.8.0" after it if you want. 
and no. this is not a script issue

**Comment by Sopor-** [comment]
Now i got a much appropriate name, thanks!
