### ISSUE TITLE
crash - list index out of range

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#287]
I don't know why i get this crash but i can read "list index out of range".
```
$ svtplay-dl -S -A --all-last=5 http://www.svtplay.se/kortfilm-i-svt
INFO: Episode 1 of 5
INFO: Outfile: kortfilm.i.svt.regn-2194365-svtplay.srt
ERROR: File already exists. Use --force-subtitle to overwrite
INFO: Selected to download hls, bitrate: 2792
INFO: Outfile: kortfilm.i.svt.regn-2194365-svtplay.ts
ERROR: File already exists. Use --force to overwrite
INFO: Episode 2 of 5
INFO: Outfile: kortfilm.i.svt.stormaktstiden-2994112-svtplay.srt
ERROR: File already exists. Use --force-subtitle to overwrite
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 5, in <module>
    pkg_resources.run_script('svtplay-dl==0.20.2015.10.08', 'svtplay-dl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.20.2015.10.08-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.20.2015.10.08-py2.7.egg/svtplay_dl/__init__.py", line 343, in main
    get_media(url, options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.20.2015.10.08-py2.7.egg/svtplay_dl/__init__.py", line 173, in get_media
    get_one_media(substream, copy.copy(options))
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.20.2015.10.08-py2.7.egg/svtplay_dl/__init__.py", line 218, in get_one_media
    log.error(error[0].args[0])
IndexError: list index out of range
```

**Comment by spaam** [comment]
i can't reproduce this

**Comment by Sopor-** [comment]
I do have over 300 files in the folder i download to. Can that be the reason for the crash?

**Comment by spaam** [comment]
i think  #290  fixed this issue
