### ISSUE TITLE
urplay not working

### ISSUE THREAD

**Issue by gituzer1** [spaam/svtplay-dl#297]
does not work sites:
http://www.ur.se
http://urplay.se/

exemple link to stream :
http://urplay.se/Produkter/190211-Makt-hos-mig-Segal-och-Mattias-Karlsson

get this output:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 200, in main
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 86, in get_media
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 106, in get_one_media
  File "/usr/bin/svtplay-dl/svtplay_dl/service/urplay.py", line 29, in get
AttributeError: 'list' object has no attribute 'split'
```

**Comment by spaam** [comment]
i dont get this error with latest release. try to upgrade to that one
