### ISSUE TITLE
dlplay.se

### ISSUE THREAD

**Issue by sigun004** [spaam/svtplay-dl#299]
Hello

I try to run svtplay-dl and dplay.se and i get message "Error: That site is not supported. Make a ticket or send a message." when i locket at svtplay-dl at github dplay.se is a supported services

i trying to use this url with svtplay-dl http://www.dplay.se/dessertmastarna/season-3-teknikstafett-och-citrusfrossa/

**Comment by spaam** [comment]
what version do you use? svtplay-dl --version

**Comment by ullgren** [comment]
Latest master gives "SSL3_GET_SERVER_CERTIFICATE:certificate verify failed" error when 

```
$ svtplay-dl --verbose http://www.dplay.se/dessertmastarna/season-3-teknikstafett-och-citrusfrossa/
DEBUG [1446622524.31] svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.dplay.se/dessertmastarna/season-3-teknikstafett-och-citrusfrossa/'
DEBUG [1446622524.4] svtplay_dl/utils/__init__.py/request: HTTP getting 'http://geo.dplay.se/geo.js'
DEBUG [1446622524.5] svtplay_dl/utils/__init__.py/request: HTTP getting u'https://secure.dplay.se/secure/api/v2/user/authorization/stream/137415?stream_type=hds'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "svtplay-dl/__main__.py", line 13, in <module>
  File "svtplay-dl/svtplay_dl/__init__.py", line 345, in main
  File "svtplay-dl/svtplay_dl/__init__.py", line 176, in get_media
  File "svtplay-dl/svtplay_dl/__init__.py", line 202, in get_one_media
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Comment by sigun004** [comment]
Version 0.10.2015.05.24

**Comment by olof** [comment]
dplay.se wans't introduced until 2015-10-04. To see the list of supported services in the packaged version you are using, see `man svtplay-dl`. The latest release build of svtplay-dl is available in the git repository if you like to use that one instead.
