### ISSUE TITLE
make it possible to download genre

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#312]
I wanted to download all "gor-om-mig" so i tried
```
python svtplay-dl -A http://www.svtplay.se/genre/gor-om-mig
```
but it didn't work. I then tried
```
python svtplay-dl http://www.svtplay.se/genre/gor-om-mig
```
but then the script told me to use --verbose and i did
```
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code exec code in run_globals
  File "svtplay-dl\__main__.py", line 13, in <module>
  File "svtplay-dl\svtplay_dl\__init__.py", line 345, in main
  File "svtplay-dl\svtplay_dl\__init__.py", line 176, in get_media
  File "svtplay-dl\svtplay_dl\__init__.py", line 202, in get_one_media
ValueError: No JSON object could be decoded
```
So it is quite obvious that this won't work but could you add support for it? You will find all the genres here http://www.svtplay.se/program?genrer=visa

**Comment by spaam** [comment]
you only want the clips or everything under there or what?

http://www.svtplay.se/genre/magasin have a lot of things in it.

**Comment by Sopor-** [comment]
Yes, you need to be very careful how you use it. 'Mode' for example only have 3 video http://www.svtplay.se/genre/mode so it would be nice if it could download everything. Maybe a warning if there are too many videos to download? Maybe even choose between clips and full episodes/movies?
"svtplay-dl --cliponly http://www.svtplay.se/genre/mode"
or
"svtplay-dl --videoonly http://www.svtplay.se/genre/mode"
Use your imagination :)
