### ISSUE TITLE
Downloading SVT Play, Öppet Arkiv videos results in `TypeError: 'dict' object is not callable` on __init__.py:202

### ISSUE THREAD

**Issue by mkjorling** [spaam/svtplay-dl#323]
I'm getting the same error with old and new version alike, including 424a74e (below dump is using 424a74e).

TV3 Play videos download fine.

    $ svtplay-dl -v http://www.svtplay.se/video/5701850/den-stora-nedslackningen/den-stora-nedslackningen-avsnitt-1
    DEBUG [1452345923.65] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/5701850/den-stora-nedslackningen/den-stora-nedslackningen-avsnitt-1'
    DEBUG [1452345924.15] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/5701850/den-stora-nedslackningen/den-stora-nedslackningen-avsnitt-1'
    Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
      File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 345, in main
        
      File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 176, in get_media
        
      File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 202, in get_one_media
        
    TypeError: 'dict' object is not callable
    $ echo $?
    1
    $

**Comment by Sopor-** [comment]
It works for me...
```
$ svtplay-dl http://www.svtplay.se/video/5701850/den-stora-nedslackningen/den-stora-nedslackningen-avsnitt-1
INFO: Selected to download hls, bitrate: 2793
INFO: Outfile: den.stora.nedslackningen-4f4bc27-svtplay.ts
[012/265][=====..............................................................................................................] ETA: 0:01:29
```

**Comment by spaam** [comment]
latest version dont have this error. upgrade to that :)
