### ISSUE TITLE
Error in autoname generation for episodes that contains " in the title on Windows 

### ISSUE THREAD

**Issue by qnorsten** [spaam/svtplay-dl#324]
Hello Tries to download some stuff from öppet arkiv before it gets deleted. Most of the episodes works great but there is some problems with episodes that contains " in the title. 

Using the latest code from this gitbug repositary

Example episodes: 
24 minuter Jason "Timbuktu" Diakité  - http://www.oppetarkiv.se/video/2112230/24-minuter
Aktuellt Ingrid Schrewelius om "Katja of Sweden" 1966  - http://www.oppetarkiv.se/video/1921800/aktuellt
Error output
```
INFO: Outfile: 24.minuter.jason."timbuktu".diakite-2112230-svtplay.ts
Traceback (most recent call last):
  File "P:\Programing\svtplay-dl\lib\svtplay_dl\__main__.py", line 13, in <modul
e>
    svtplay_dl.main()
  File "P:\Programing\svtplay-dl\lib\svtplay_dl\__init__.py", line 343, in main
    get_media(url, options)
  File "P:\Programing\svtplay-dl\lib\svtplay_dl\__init__.py", line 173, in get_m
edia
    get_one_media(substream, copy.copy(options))
  File "P:\Programing\svtplay-dl\lib\svtplay_dl\__init__.py", line 230, in get_o
ne_media
    stream.download()
  File "P:\Programing\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 88, in dow
nload
    file_d = output(self.options, "ts")
  File "P:\Programing\svtplay-dl\lib\svtplay_dl\output.py", line 171, in output
    file_d = open(options.output, mode)
OSError: [Errno 22] Invalid argument: '24.minuter.jason."timbuktu".diakite-21122
30-svtplay.ts'
```

**Comment by spaam** [comment]
interesting.

**Comment by spaam** [comment]
this works for me on both windows and *nix.  both master and the released version 0.20.2015.11.29

**Comment by spaam** [comment]
```
spaam:lib johan$ python -m svtplay_dl "http://www.oppetarkiv.se/video/2112230/24-minuter"
INFO: Selected to download hls, bitrate: 2793
INFO: Outfile: 24.minuter.jason.timbuktu.diakite-2112230-svtplay.ts
[005/150][=======......................................................................................................................................................................................................................] ETA: 0:00:50^C
spaam:lib johan$
```

**Comment by qnorsten** [comment]
Thank so much. This is embarrassing, was sure that I had fetched the latest updates before posting,  but seems something had went wrong during that.Re downloading the master branch, solved the problem. 
Thanks for quick support, and sorry for bothering you when the fault was mine.

**Comment by spaam** [comment]
good thing you found the issue :)
going to release a new version later today :)
