### ISSUE TITLE
TV4 - Unicode equal comparison failed to convert both arguments to Unicode

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#336]
When trying to download from TV4Play i got this message:
/usr/lib/python2.7/urllib.py:1288: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))
So i run it with --verbose and got this:
```
$ svtplay-dl -S -A --verbose http://www.tv4play.se/program/f%C3%A5ngarna-p%C3%A5-fortet
DEBUG [1453758794.87] /usr/local/lib/python2.7/dist-packages/svtplay_dl-0.20.2015.11.29-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://webapi.tv4play.se/play/video_assets?type=episode&is_live=false&platform=web&node_nids=f%C3%A5ngarna-p%C3%A5-fortet&per_page=99999'
INFO [1453758794.93] /usr/local/lib/python2.7/dist-packages/svtplay_dl-0.20.2015.11.29-py2.7.egg/svtplay_dl/__init__.py/get_media: Episode 1 of 7
DEBUG [1453758794.93] /usr/local/lib/python2.7/dist-packages/svtplay_dl-0.20.2015.11.29-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.tv4play.se/program/f\xe5ngarna-p\xe5-fortet?video_id=3229393'
DEBUG [1453758795.08] /usr/local/lib/python2.7/dist-packages/svtplay_dl-0.20.2015.11.29-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://premium.tv4play.se/api/web/asset/3229393/play'
/usr/lib/python2.7/urllib.py:1288: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 5, in <module>
    pkg_resources.run_script('svtplay-dl==0.20.2015.11.29', 'svtplay-dl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.20.2015.11.29-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.20.2015.11.29-py2.7.egg/svtplay_dl/__init__.py", line 355, in main
    get_media(url, options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.20.2015.11.29-py2.7.egg/svtplay_dl/__init__.py", line 176, in get_media
    get_one_media(substream, copy.copy(options))
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.20.2015.11.29-py2.7.egg/svtplay_dl/__init__.py", line 204, in get_one_media
    raise e
KeyError: u'\xe5'
```
If i download one episode without the -A it seems to work.

**Comment by spaam** [comment]
thanks! :)

**Comment by ullgren** [comment]
Commit ab3646e4e2b855f21e053266e6efc2ef524a04ba reverted the main part of this pull request and reintroduced this error.

**Comment by spaam** [comment]
oh

**Comment by spaam** [comment]
the wonderful unicode stuff in python2.  if i revert htat commit.. it works for "http://www.tv4play.se/program/f%C3%A5ngarna-p%C3%A5-fortet" but not for http://www.tv4play.se/program/fångarna-på-fortet
