### ISSUE TITLE
pkg_resources.UnknownExtra: requests 2.2.1 has no such extra feature 'security'

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#338]
I have always installed svtplay-dl on a second ubuntu computer with "sudo python setup.py install" but today i got this error message:
```
Installed /usr/local/lib/python2.7/dist-packages/svtplay_dl-0.30.2016.01.10-py2.7.egg
Processing dependencies for svtplay-dl==0.30.2016.01.10
Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    "Topic :: Utilities"]
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 96, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 381, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 597, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 648, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 694, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 633, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2299, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: requests 2.2.1 has no such extra feature 'security'
```

**Comment by spaam** [comment]
ubuntu again.. why do people run that dist? :S

**Comment by spaam** [comment]
this is new since 0.30.2016.01.10. when i tried to fix this ssl error. but i guess i need to do one more extra workaround for old dists

**Comment by spaam** [comment]
I'm going to fix a repo later today so you can use that with ubuntu

**Comment by Sopor-** [comment]
Thanks!

@spaam what dist do you prefer to use?

**Comment by Sopor-** [comment]
I still get the same error message
```
...
pkg_resources.UnknownExtra: requests 2.2.1 has no such extra feature 'security'
```

**Comment by spaam** [comment]
are you sure? i removed the security thing from the setup.py script

**Comment by Sopor-** [comment]
Here you have the complete text if that can help you?
```
$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to lib/svtplay_dl.egg-info/requires.txt
writing lib/svtplay_dl.egg-info/PKG-INFO
writing top-level names to lib/svtplay_dl.egg-info/top_level.txt
writing dependency_links to lib/svtplay_dl.egg-info/dependency_links.txt
reading manifest file 'lib/svtplay_dl.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'lib/svtplay_dl.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/svtplay_dl
copying lib/svtplay_dl/error.py -> build/lib.linux-x86_64-2.7/svtplay_dl
copying lib/svtplay_dl/log.py -> build/lib.linux-x86_64-2.7/svtplay_dl
copying lib/svtplay_dl/__main__.py -> build/lib.linux-x86_64-2.7/svtplay_dl
copying lib/svtplay_dl/output.py -> build/lib.linux-x86_64-2.7/svtplay_dl
copying lib/svtplay_dl/__init__.py -> build/lib.linux-x86_64-2.7/svtplay_dl
creating build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/mtvnn.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/bigbrother.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/viaplay.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/qbrick.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/picsearch.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/youplay.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/expressen.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/svtplay.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/kanal5.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/twitch.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/solidtango.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/hbo.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/bambuser.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/justin.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/facebook.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/dbtv.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/aftonbladet.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/radioplay.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/disney.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/efn.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/ruv.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/dplay.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/tv4play.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/raw.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/dr.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/nrk.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/lemonwhale.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/mtvservices.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/sr.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/oppetarkiv.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/urplay.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/__init__.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/vg.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
copying lib/svtplay_dl/service/vimeo.py -> build/lib.linux-x86_64-2.7/svtplay_dl/service
creating build/lib.linux-x86_64-2.7/svtplay_dl/fetcher
copying lib/svtplay_dl/fetcher/rtmp.py -> build/lib.linux-x86_64-2.7/svtplay_dl/fetcher
copying lib/svtplay_dl/fetcher/http.py -> build/lib.linux-x86_64-2.7/svtplay_dl/fetcher
copying lib/svtplay_dl/fetcher/hds.py -> build/lib.linux-x86_64-2.7/svtplay_dl/fetcher
copying lib/svtplay_dl/fetcher/hls.py -> build/lib.linux-x86_64-2.7/svtplay_dl/fetcher
copying lib/svtplay_dl/fetcher/__init__.py -> build/lib.linux-x86_64-2.7/svtplay_dl/fetcher
creating build/lib.linux-x86_64-2.7/svtplay_dl/utils
copying lib/svtplay_dl/utils/urllib.py -> build/lib.linux-x86_64-2.7/svtplay_dl/utils
copying lib/svtplay_dl/utils/terminal.py -> build/lib.linux-x86_64-2.7/svtplay_dl/utils
copying lib/svtplay_dl/utils/io.py -> build/lib.linux-x86_64-2.7/svtplay_dl/utils
copying lib/svtplay_dl/utils/__init__.py -> build/lib.linux-x86_64-2.7/svtplay_dl/utils
creating build/lib.linux-x86_64-2.7/svtplay_dl/subtitle
copying lib/svtplay_dl/subtitle/__init__.py -> build/lib.linux-x86_64-2.7/svtplay_dl/subtitle
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/svtplay_dl
copying build/lib.linux-x86_64-2.7/svtplay_dl/error.py -> build/bdist.linux-x86_64/egg/svtplay_dl
creating build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/mtvnn.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/bigbrother.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/viaplay.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/qbrick.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/picsearch.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/youplay.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/expressen.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/svtplay.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/kanal5.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/twitch.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/solidtango.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/hbo.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/bambuser.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/justin.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/facebook.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/dbtv.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/aftonbladet.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/radioplay.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/disney.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/efn.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/ruv.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/dplay.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/tv4play.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/raw.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/dr.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/nrk.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/lemonwhale.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/mtvservices.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/sr.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/oppetarkiv.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/urplay.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/__init__.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/vg.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
copying build/lib.linux-x86_64-2.7/svtplay_dl/service/vimeo.py -> build/bdist.linux-x86_64/egg/svtplay_dl/service
creating build/bdist.linux-x86_64/egg/svtplay_dl/fetcher
copying build/lib.linux-x86_64-2.7/svtplay_dl/fetcher/rtmp.py -> build/bdist.linux-x86_64/egg/svtplay_dl/fetcher
copying build/lib.linux-x86_64-2.7/svtplay_dl/fetcher/http.py -> build/bdist.linux-x86_64/egg/svtplay_dl/fetcher
copying build/lib.linux-x86_64-2.7/svtplay_dl/fetcher/hds.py -> build/bdist.linux-x86_64/egg/svtplay_dl/fetcher
copying build/lib.linux-x86_64-2.7/svtplay_dl/fetcher/hls.py -> build/bdist.linux-x86_64/egg/svtplay_dl/fetcher
copying build/lib.linux-x86_64-2.7/svtplay_dl/fetcher/__init__.py -> build/bdist.linux-x86_64/egg/svtplay_dl/fetcher
copying build/lib.linux-x86_64-2.7/svtplay_dl/log.py -> build/bdist.linux-x86_64/egg/svtplay_dl
copying build/lib.linux-x86_64-2.7/svtplay_dl/__main__.py -> build/bdist.linux-x86_64/egg/svtplay_dl
copying build/lib.linux-x86_64-2.7/svtplay_dl/output.py -> build/bdist.linux-x86_64/egg/svtplay_dl
creating build/bdist.linux-x86_64/egg/svtplay_dl/utils
copying build/lib.linux-x86_64-2.7/svtplay_dl/utils/urllib.py -> build/bdist.linux-x86_64/egg/svtplay_dl/utils
copying build/lib.linux-x86_64-2.7/svtplay_dl/utils/terminal.py -> build/bdist.linux-x86_64/egg/svtplay_dl/utils
copying build/lib.linux-x86_64-2.7/svtplay_dl/utils/io.py -> build/bdist.linux-x86_64/egg/svtplay_dl/utils
copying build/lib.linux-x86_64-2.7/svtplay_dl/utils/__init__.py -> build/bdist.linux-x86_64/egg/svtplay_dl/utils
creating build/bdist.linux-x86_64/egg/svtplay_dl/subtitle
copying build/lib.linux-x86_64-2.7/svtplay_dl/subtitle/__init__.py -> build/bdist.linux-x86_64/egg/svtplay_dl/subtitle
copying build/lib.linux-x86_64-2.7/svtplay_dl/__init__.py -> build/bdist.linux-x86_64/egg/svtplay_dl
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/error.py to error.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/mtvnn.py to mtvnn.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/bigbrother.py to bigbrother.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/viaplay.py to viaplay.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/qbrick.py to qbrick.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/picsearch.py to picsearch.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/youplay.py to youplay.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/expressen.py to expressen.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/svtplay.py to svtplay.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/kanal5.py to kanal5.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/twitch.py to twitch.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/solidtango.py to solidtango.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/hbo.py to hbo.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/bambuser.py to bambuser.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/justin.py to justin.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/facebook.py to facebook.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/dbtv.py to dbtv.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/aftonbladet.py to aftonbladet.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/radioplay.py to radioplay.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/disney.py to disney.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/efn.py to efn.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/ruv.py to ruv.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/dplay.py to dplay.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/tv4play.py to tv4play.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/raw.py to raw.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/dr.py to dr.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/nrk.py to nrk.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/lemonwhale.py to lemonwhale.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/mtvservices.py to mtvservices.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/sr.py to sr.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/oppetarkiv.py to oppetarkiv.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/urplay.py to urplay.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/vg.py to vg.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/service/vimeo.py to vimeo.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/fetcher/rtmp.py to rtmp.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/fetcher/http.py to http.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/fetcher/hds.py to hds.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/fetcher/hls.py to hls.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/fetcher/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/log.py to log.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/__main__.py to __main__.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/output.py to output.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/utils/urllib.py to urllib.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/utils/terminal.py to terminal.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/utils/io.py to io.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/utils/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/subtitle/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/svtplay_dl/__init__.py to __init__.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-2.7
copying and adjusting bin/svtplay-dl -> build/scripts-2.7
changing mode of build/scripts-2.7/svtplay-dl from 644 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/svtplay-dl -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/svtplay-dl to 755
copying lib/svtplay_dl.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lib/svtplay_dl.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lib/svtplay_dl.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lib/svtplay_dl.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lib/svtplay_dl.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
svtplay_dl.__main__: module references __file__
creating dist
creating 'dist/svtplay_dl-0.30.2016.01.10-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing svtplay_dl-0.30.2016.01.10-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.30.2016.01.10-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/svtplay_dl-0.30.2016.01.10-py2.7.egg
Extracting svtplay_dl-0.30.2016.01.10-py2.7.egg to /usr/local/lib/python2.7/dist-packages
svtplay-dl 0.30.2016.01.10 is already the active version in easy-install.pth
Installing svtplay-dl script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/svtplay_dl-0.30.2016.01.10-py2.7.egg
Processing dependencies for svtplay-dl==0.30.2016.01.10
Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    "Topic :: Utilities"]
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 96, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 381, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 597, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 648, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 694, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 633, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2299, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: requests 2.2.1 has no such extra feature 'security'
```

**Comment by spaam** [comment]
did you pull?

**Comment by spaam** [comment]
remove the old one and install again

**Comment by Sopor-** [comment]
Can i really have been that stupid? It seems that way because now it is working :)
I did this before i compiled
remote: Counting objects: 50, done.
remote: Total 50 (delta 32), reused 32 (delta 32), pack-reused 18
Unpacking objects: 100% (50/50), done.
From https://github.com/spaam/svtplay-dl
   3f04ae2..901ae80  master     -> origin/master
Updating 3f04ae2..901ae80
Fast-forward
 lib/svtplay_dl/fetcher/hds.py     |  4 ++--
 lib/svtplay_dl/fetcher/hls.py     |  4 ++--
 lib/svtplay_dl/service/dplay.py   |  2 +-
 lib/svtplay_dl/service/efn.py     |  2 --
 lib/svtplay_dl/service/twitch.py  |  1 -
 lib/svtplay_dl/service/urplay.py  |  1 -
 lib/svtplay_dl/service/vg.py      |  2 +-
 lib/svtplay_dl/service/viaplay.py | 10 +++++-----
 8 files changed, 11 insertions(+), 15 deletions(-)

but after you told me to do a new 'pull' i got even more

remote: Counting objects: 27, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 27 (delta 12), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (27/27), done.
From https://github.com/spaam/svtplay-dl
   901ae80..013b6d1  master     -> origin/master
Updating 901ae80..013b6d1
Fast-forward
 lib/svtplay_dl/service/dplay.py   | 31 +++++++++++++++++++++----------
 lib/svtplay_dl/service/svtplay.py |  7 +++++--
 setup.py                          |  5 ++++-
 3 files changed, 30 insertions(+), 13 deletions(-)

**Comment by spaam** [comment]
good :)
