### ISSUE TITLE
ElementTree.ParseError

### ISSUE THREAD

**Issue by silentboatman** [spaam/svtplay-dl#342]
This work:
svtplay-dl www.svtplay.se/video/2494881/peg-katt/avsnitt-22

But this do not work:
svtplay-dl www.svtplay.se/video/2325389/peg-katt/avsnitt-20
```
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3.5/site-packages/svtplay_dl/__init__.py", line 345, in main
    get_media(url, options)
  File "/usr/lib/python3.5/site-packages/svtplay_dl/__init__.py", line 176, in get_media
    get_one_media(stream, options)
  File "/usr/lib/python3.5/site-packages/svtplay_dl/__init__.py", line 202, in get_one_media
    raise e
  File "/usr/lib/python3.5/site-packages/svtplay_dl/__init__.py", line 189, in get_one_media
    for i in streams:
  File "/usr/lib/python3.5/site-packages/svtplay_dl/service/svtplay.py", line 88, in get
    streams = hdsparse(options, self.http.request("get", i["url"], params={"hdcore": "3.7.0"}), i["url"])
  File "/usr/lib/python3.5/site-packages/svtplay_dl/fetcher/hds.py", line 51, in hdsparse
    xml = ET.XML(res.text)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 4, column 2
```

svtplay-dl --version :
0.20.2015.11.29

**Comment by spaam** [comment]
i can't see the video in safari when it tries to watch it using HLS but it works in chrome using dash. and i dont have support for that right now

**Comment by silentboatman** [comment]
After updating to the latest code from git, I get the following message:
```
svtplay-dl --verbose http://www.svtplay.se/video/2494881/peg-katt/avsnitt-22

DEBUG [1454872066.4285622] /usr/lib/python3.5/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/2494881/peg-katt/avsnitt-22'
DEBUG [1454872066.6948123] /usr/lib/python3.5/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svt.se/videoplayer-api/video/1356153-022A'
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3.5/site-packages/svtplay_dl/__init__.py", line 352, in main
    get_media(url, options)
  File "/usr/lib/python3.5/site-packages/svtplay_dl/__init__.py", line 177, in get_media
    get_one_media(stream, options)
  File "/usr/lib/python3.5/site-packages/svtplay_dl/__init__.py", line 190, in get_one_media
    for i in streams:
  File "/usr/lib/python3.5/site-packages/svtplay_dl/service/svtplay.py", line 56, in get
    self.options.output = self.outputfilename(dataj, self.options.output, ensure_unicode(self.get_urldata()))
  File "/usr/lib/python3.5/site-packages/svtplay_dl/service/svtplay.py", line 153, in outputfilename
    id = hashlib.sha256(data["programVersionId"]).hexdigest()[:7]
TypeError: Unicode-objects must be encoded before hashing
```

That's the same error as #344. I'm also running Arch.

**Comment by spaam** [comment]
that problem is fixed now :)

**Comment by silentboatman** [comment]
Great, episode 22 works fine now! But for episode 20 there's a new error:
```
svtplay-dl --verbose http://www.svtplay.se/video/2325389/peg-katt/avsnitt-20

DEBUG [1454878243.4775455] /usr/lib/python3.5/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/2325389/peg-katt/avsnitt-20'
DEBUG [1454878243.6064005] /usr/lib/python3.5/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svt.se/videoplayer-api/video/1356153-020A'
DEBUG [1454878243.7155175] /usr/lib/python3.5/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://svtplay18n-f.akamaihd.net/z/se/open/20160201/1356153-020A/PG-1356153-020A-PEGCATPEG-02_,988,240,348,456,636,1680,2796,.mp4.csmil/manifest.f4m'
DEBUG [1454878245.2351058] /usr/lib/python3.5/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://svtplay18c-f.akamaihd.net/i/se/open/20160201/1356153-020A/PG-1356153-020A-PEGCATPEG-02_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8'
ERROR [1454878245.697656] /usr/lib/python3.5/site-packages/svtplay_dl/__init__.py/get_one_media: Can't read HDS playlist.
ERROR [1454878245.6979728] /usr/lib/python3.5/site-packages/svtplay_dl/__init__.py/get_one_media: Can't read HLS playlist.
```

But maybe that has to do with dash..

**Comment by spaam** [comment]
need to fix that.. look in for details #257
