### ISSUE TITLE
tv.nrksuper.no

### ISSUE THREAD

**Issue by spaam** [spaam/svtplay-dl#346]
request from IRC that we should add support for that site

**Comment by ehj** [comment]
Hello!

Hope it's OK if I ask right here.

I have problems with an urplay link:

ehj@hedgehog:~/Videos/dl/svtplay-dl$ ./svtplay-dl http://urplay.se/program/194168-ur-samtiden-psykisk-ohalsa-bland-barn-och-unga-2016-verktyg-i-motet-med-ensamkommande-barn
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./svtplay-dl/__main__.py", line 13, in <module>
  File "./svtplay-dl/svtplay_dl/__init__.py", line 341, in main
  File "./svtplay-dl/svtplay_dl/__init__.py", line 173, in get_media
  File "./svtplay-dl/svtplay_dl/__init__.py", line 204, in get_one_media
  File "./svtplay-dl/svtplay_dl/service/urplay.py", line 40, in get
KeyError: 'streamer'

Any hints?

//Erik

**Comment by spaam** [comment]
what version are you using? it looks like you got an old version of the script

**Comment by ehj** [comment]
I normally just do aptitude upgrade/update. Can I still wait for the new version of svtplay-dl to be included in the debian repositories?

**Comment by spaam** [comment]
what version of debian do you use? stable?

**Comment by ehj** [comment]
Debian GNU/Linux 8.3 (jessie)

**Comment by ehj** [comment]
Jonas packaged all the new great stuff! :-)

http://debian.jones.dk/pkg/multimedia-consume/svtplay-dl/jessie/bastian/

**Comment by spaam** [comment]
to bad that i didn't know about it before i made http://apt.svtplay-dl.se/  for 1.0 release :)

**Comment by ehj** [comment]
:-)
