### ISSUE TITLE
ImportError: No module named postprocess

### ISSUE THREAD

**Issue by DasKaktus** [spaam/svtplay-dl#360]
When I git cloned.
make
make install

and then run it I get the error message:

```
python /usr/local/bin/svtplay-dl 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 11, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 17, in <module>

ImportError: No module named postprocess
```

**Comment by spaam** [comment]
thank you for the bug report ! :)

**Comment by DasKaktus** [comment]
Nemas problemas.
