### ISSUE TITLE
Crash TV12 when using -A

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#386]
I got this crash trying to download all episodes for a show...
```
$ svtplay-dl -A http://www.tv4play.se/program/parkering-f%C3%B6rbjuden-b%C3%A4rgarna --verbose
DEBUG [1462237132.48] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.0-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://webapi.tv4play.se/play/video_assets?type=episode&is_live=false&platform=web&node_nids=parkering-f%C3%B6rbjuden-b%C3%A4rgarna&per_page=99999'
INFO [1462237132.54] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.0-py2.7.egg/svtplay_dl/__init__.py/get_all_episodes: Episode 1 of 22
DEBUG [1462237132.54] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.0-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.tv4play.se/program/parkering-f\xf6rbjuden-b\xe4rgarna?video_id=3195908'
DEBUG [1462237132.59] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.0-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://prima.tv4play.se/api/web/asset/3195908/play'
/usr/lib/python2.7/urllib.py:1288: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 5, in <module>
    pkg_resources.run_script('svtplay-dl==1.0', 'svtplay-dl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.0-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.0-py2.7.egg/svtplay_dl/__init__.py", line 370, in main
    get_media(url, options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.0-py2.7.egg/svtplay_dl/__init__.py", line 155, in get_media
    get_all_episodes(stream, options, url)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.0-py2.7.egg/svtplay_dl/__init__.py", line 183, in get_all_episodes
    get_one_media(substream, copy.copy(options))
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.0-py2.7.egg/svtplay_dl/__init__.py", line 196, in get_one_media
    for i in streams:
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.0-py2.7.egg/svtplay_dl/service/tv4play.py", line 73, in get
    basename = self._autoname(vid)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.0-py2.7.egg/svtplay_dl/service/tv4play.py", line 158, in _autoname
    jsondata = self._get_show_info()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.0-py2.7.egg/svtplay_dl/service/tv4play.py", line 121, in _get_show_info
    show = self._get_showname(self.url)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.0-py2.7.egg/svtplay_dl/service/tv4play.py", line 154, in _get_showname
    show = quote_plus(show)
  File "/usr/lib/python2.7/urllib.py", line 1295, in quote_plus
    return quote(s, safe)
  File "/usr/lib/python2.7/urllib.py", line 1288, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xf6'
```

**Comment by spaam** [comment]
i can't reproduce this with master.

**Comment by spaam** [comment]
this should be fixed in the commit 03a6307f381bcfe38efa394edae7b56fb7c7e462

**Comment by Sopor-** [comment]
Sorry, my bad... It is working now!

**Comment by spaam** [comment]
Najs :D
