### ISSUE TITLE
Error messages when -q range and -A in version 1.1

### ISSUE THREAD

**Issue by stdlogin** [spaam/svtplay-dl#392]
Microsoft Windows [Version 10.0.14342]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\myown\Desktop\svtplay-dl>svtplay-dl.exe -q 900-1500 -A http://www.tv3play.se/program/pluras-paradis/683196?autostart=true
INFO: Episode 1 of 6
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "svtplay_dl\__init__.py", line 399, in main
  File "svtplay_dl\__init__.py", line 163, in get_media
  File "svtplay_dl\__init__.py", line 191, in get_all_episodes
  File "svtplay_dl\__init__.py", line 258, in get_one_media
  File "svtplay_dl\utils\__init__.py", line 99, in select_quality
ValueError: invalid literal for int() with base 10: '900-1500'
svtplay-dl returned -1

**Comment by spaam** [comment]
What version is this?

-- 
Johan Andersson

**Comment by stdlogin** [comment]
version 1.1 of svtplay-dl for Windows
