### ISSUE TITLE
Download issues

### ISSUE THREAD

**Issue by jodenholm** [spaam/svtplay-dl#409]
Hi,
Using this on my mac with great success until today. Removed my old version and installed it with "brew install svtplay-dl"
$ svtplay-dl --version
0.9.2014.11.16
All my download-tries looks like this:
$ svtplay-dl http://www.svtplay.se/video/7371848/falsk-identitet/falsk-identitet-sasong-1-avsnitt-1
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 234, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 97, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 120, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 44, in get
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Any hints from anyone?

Thanks in advance

**Comment by spaam** [comment]
did you upgrade your brew repo?   brew update && brew upgrade ?    you should get version 1.1 from brew . 0.9.2014.11.16 is a bit old :)

**Comment by jodenholm** [comment]
Many thanks. I'll try that first. Only using brew for this and haven't had the need to upgrade so I'm a bit rusty.

**Comment by jodenholm** [comment]
Thanks. Some issues with updating brew but now it works again.

**Comment by spaam** [comment]
awesome :)
