### ISSUE TITLE
merging fails "typeError: population must be a sequence or set"

### ISSUE THREAD

**Issue by Christley** [spaam/svtplay-dl#444]
i have the latest ffmpeg build as of 2016-09-07 (ba7be8c), latest svtplay-dl (1.3). im running windows 10 x64 pro. my folder structure looks like this: http://i.imgur.com/Zy9rA0g.png

this is the command im running 
`svtplay-dl -S -M --remux --force http://www.svtplay.se/video/4410711/varldens-fakta-vithajens-hemliga-fullandning/varldens-fakta-vithajens-hemliga-fullandning-avsnitt-1`

this is the error im getting:
```
`svtplay-dl>svtplay-dl -S -M --remux --force http://www.svtplay.se/video/4410711/varldens-fakta-vithajens-hemliga-fullandning/varldens-fakta-vithajens-hemliga-fullandning-avsnitt-1
INFO: Outfile: naturfilm.varldens.fakta.vithajens.hemliga.fullandning-bc7e6ce-svtplay.srt
INFO: Selected to download hls, bitrate: 2793
INFO: Outfile: naturfilm.varldens.fakta.vithajens.hemliga.fullandning-bc7e6ce-svtplay.ts
[300/300][================================================================================] ETA: 0:00:00
INFO: Muxing naturfilm.varldens.fakta.vithajens.hemliga.fullandning-bc7e6ce-svtplay.ts and merging its subtitle into naturfilm.varldens.fakta.vithajens.hemliga.fullandning-bc7e6ce-svtplay.mp4
INFO: Determining the language of the subtitle.
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "site-packages\svtplay_dl-1.3-py3.5.egg\svtplay_dl\__init__.py", line 444, in main
  File "site-packages\svtplay_dl-1.3-py3.5.egg\svtplay_dl\__init__.py", line 178, in get_media
  File "site-packages\svtplay_dl-1.3-py3.5.egg\svtplay_dl\__init__.py", line 318, in get_one_media
  File "site-packages\svtplay_dl-1.3-py3.5.egg\svtplay_dl\postprocess\__init__.py", line 105, in remux
  File "site-packages\svtplay_dl-1.3-py3.5.egg\svtplay_dl\postprocess\__init__.py", line 75, in sublanguage
  File "site-packages\svtplay_dl-1.3-py3.5.egg\svtplay_dl\postprocess\__init__.py", line 36, in query
  File "random.py", line 311, in sample
TypeError: Population must be a sequence or set.  For dicts, use list(d).
svtplay-dl returned -1`
```
ive asked over on sweclockers about this issue and apperently it runs fine on Linux mint.
http://www.sweclockers.com/forum/trad/1442898-svtplay-dl-population-must-be-a-sequence

i have installed requests through pip, but couldnt with pycrypto since i have python 3.5.2 (not that i think it would matter?) and ive had rtmpdump 2.4 in the folder but it didnt make a difference so i just removed it

**Comment by spaam** [comment]
Interesting. thanks for the bug report with the awesome test case, because of that i could reproduce the same kind of error on my OSX machine with the same python version. 

I will take a look at this later today :)
