### ISSUE TITLE
Error in version 1.3 and tv4play.se

### ISSUE THREAD

**Issue by oveld** [spaam/svtplay-dl#446]
Försöker hämta hem från tv4play men får nedanstående fel: 
Fungerade i version 1.1 men vid uppgradering till 1.3 får jag fel oavsett länk jag klistrar in för tv4play.se
```
Last login: Fri Sep  9 17:45:18 on ttys001
iMac:~ Ove$ svtplay-dl -v http://www.tv4play.se/program/vad-blir-det-f%C3%B6r-mat?video_id=3431265
DEBUG [1473439649.68] /usr/local/Cellar/svtplay-dl/1.3/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.tv4play.se/program/vad-blir-det-f%C3%B6r-mat?video_id=3431265'
DEBUG [1473439650.54] /usr/local/Cellar/svtplay-dl/1.3/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://prima.tv4play.se/api/web/asset/3431265/play'
DEBUG [1473439651.2] /usr/local/Cellar/svtplay-dl/1.3/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://webapi.tv4play.se/play/video_assets?type=episode&is_live=false&platform=web&node_nids=vad-blir-det-f%C3%B6r-mat&per_page=99999'
DEBUG [1473439652.34] /usr/local/Cellar/svtplay-dl/1.3/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://tv4playhds-f.akamaihd.net/z/mp4root/2016-07-05/pid200015092(3431265_,T3MP445,T3MP435,T3MP425,T3MP415,T3MP48,T3MP43,T3MP4130,).mp4.csmil/manifest.f4m'
ERROR [1473439652.99] /usr/local/Cellar/svtplay-dl/1.3/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.3
Traceback (most recent call last):
  File "/usr/local/Cellar/svtplay-dl/1.3/libexec/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.3/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 444, in main
    get_media(url, options)
  File "/usr/local/Cellar/svtplay-dl/1.3/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 178, in get_media
    get_one_media(stream, options)
  File "/usr/local/Cellar/svtplay-dl/1.3/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 225, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/1.3/libexec/lib/python2.7/site-packages/svtplay_dl/service/tv4play.py", line 97, in get
    streams = hdsparse(self.options, self.http.request("get", i.find("url").text, params={"hdcore": "3.7.0"}), i.find("url").text)
  File "/usr/local/Cellar/svtplay-dl/1.3/libexec/lib/python2.7/site-packages/svtplay_dl/fetcher/hds.py", line 54, in hdsparse
    xml = ET.XML(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 7, column 2
iMac:~ Ove$ 
```

**Comment by spaam** [comment]
får du samma problem i 1.1? jag får samma fel i båda tyvärr :)

**Comment by oveld** [comment]
Hmm då har nog tv4 ändrat någonting då jag i förra veckan med version 1.1 hämtade hem avsnitt ett av ovan program i felbeskrivningen. Merde! :)

**Comment by jockeliten** [comment]
Jag märkte att det ändrades något nyligen. Nu måste man ha ett gratiskonto för att se även “gratis”material.

**Comment by oveld** [comment]
Gratiskontot har funnits i några veckor nu så det i sig har nog inte påverkat detta skulle jag tro då det fungerade för ett par dagar sedan.

**Comment by spaam** [comment]
verkar som dom har slutat med HDS som scriptet krashar på och nu kör dom bara med HLS

**Comment by spaam** [comment]
får bara HLS i firefox och chrome numera.

**Comment by spaam** [comment]
tack så mycket för buggrapporten. finns en fix i master just nu. :)

**Comment by jockeliten** [comment]
Hm, det fungerar att hämta hem själva videofilen men inte subtitle. Inte heller med -S --force-subtitle.

Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==1.4', 'svtplay-dl')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl-1.4-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl-1.4-py2.7.egg/svtplay_dl/__init__.py", line 444, in main
    get_media(url, options)
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl-1.4-py2.7.egg/svtplay_dl/__init__.py", line 178, in get_media
    get_one_media(stream, options)
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl-1.4-py2.7.egg/svtplay_dl/__init__.py", line 277, in get_one_media
    options_subs_dl(subfixes)
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl-1.4-py2.7.egg/svtplay_dl/__init__.py", line 272, in options_subs_dl
    subs[0].download()
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl-1.4-py2.7.egg/svtplay_dl/subtitle/__init__.py", line 23, in download
    subdata = self.http.request("get", self.url, cookies=self.options.cookies)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname ‘asset-subtitles.tv4play.se' doesn't match either of 'www.tv4play.se', 'secure.sfanytime.com', 'video-annotator.services.tv4play.se', 'img0.tv4cdn.se', 'atv-live.tv4play.se', 'www.sfanytime.se', 'progdwnl.tv4.se', 'atv.tv4play.se', 'secure.tv4play.se', 'img1.tv4cdn.se', 'android.tv4play.se', 'papi.tv4play.se', 'img2.tv4cdn.se', 'account.services.tv4play.se', 'ios.tv4play.se', 'secure.sfanytime.se', 'www.sfanytime.com', 'img-staging.koket.se', 'www.tv4.se', 'sslapi.tv4play.se', 'img3.tv4cdn.se', 'www.koket.se', 'img.koket.se', 'ios-conf.tv4play.se', 'staging.koket.se', 'secure.tv4.se'

Har de flyttat plats på undertexten eller dyl? Det har fungerat tidigare.

**Comment by spaam** [comment]
vad är det för video du testar med?

**Comment by jockeliten** [comment]
http://www.tv4play.se/program/doktorn-kan-komma?video_id=3499792

**Comment by Sopor-** [comment]
Jag har redan rapporterar till Retrospect att många av deras undertexter inte fungerar. Kan detta vara samma sak @spaam ?
https://bitbucket.org/basrieter/xbmc-online-tv/issues/745/tv4-no-subtitles-are-working

**Comment by spaam** [comment]
@Sopor- verkar va liknande. 
@jockeliten va kör du för python version?

för mig funkar bra, verkar som dom försöker ansluta till en https server som inte har asset-subtitles.tv4play.se i certifikatet. något trasigt hos tv4. kan inte gör så mycket åt problemet här..
med --dont-verify-ssl-cert kanske fixar problemet, ja rekommenderar _inte_ använda det.

**Comment by jockeliten** [comment]
@spaam Python 2.7.10.
Eg spelar inte undertexter någon roll - men jag tänkte att det vore kul att försöka få reda på varför de inte fungerar. Tack för att du kollade upp det :)

**Comment by Sopor-** [comment]
Jag vill gärna ha undertexter :)

**Comment by jockeliten** [comment]
Ja, helt ärligt så använder jag oftast undertexter av ren princip. Jag gillar att ha text fastän jag inte egentligen behöver det. Man kan titta på något annat för någon sekund och ändå hänga med i handlingen tack vare texten. Det känns tryggt. Hoppas det går att få bukt på.

**Comment by jockeliten** [comment]
Jag märkte att undertexten inte fungerade när jag använde min unlocator ifrån TV4. Men när jag inte använde den fungerade det fint att få hem undertexterna.

**Comment by spaam** [comment]
unlocator ? va e de?

**Comment by jockeliten** [comment]
unlocator.com , en tjänst som ska “avblockera”, som inte fungerar som en VPN eller dyl.
