### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by isakrubin** [spaam/svtplay-dl#457]
```
svtplay-dl -v --quality=2795 -Q 50 -A http://www.svtplay.se/morran-och-tobias
DEBUG [1474539723.36] /usr/lib64/python2.7/site-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/morran-och-tobias'
INFO [1474539723.65] /usr/lib64/python2.7/site-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/__init__.py/get_all_episodes: Episode 1 of 16
DEBUG [1474539723.65] /usr/lib64/python2.7/site-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.svtplay.se/video/2376309/morran-och-tobias'
DEBUG [1474539723.86] /usr/lib64/python2.7/site-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.svt.se/videoplayer-api/video/1365288-001A'
DEBUG [1474539724.11] /usr/lib64/python2.7/site-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay20r-f.akamaihd.net/d/world/open/delivery/20160608/1365288-001A/dash-ondemand/PG-1365288-001A-MONICAOCHTOBIA-01-becc0b97-8566-336d-79b4-7930c95e2152-ondemand.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1365288-001A.mpd'
DEBUG [1474539724.28] /usr/lib64/python2.7/site-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://switcher.cdn.svt.se/1365288-001A.mpd'
DEBUG [1474539724.56] /usr/lib64/python2.7/site-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://svtplay20k-f.akamaihd.net/d/world/open/delivery/20160608/1365288-001A/dash-live/PG-1365288-001A-MONICAOCHTOBIA-01-becc0b97-8566-336d-1498-1c6c8919aee1-live.mpd'
ERROR [1474539724.57] /usr/lib64/python2.7/site-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/__init__.py/get_one_media: version: 1.5
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==1.5', 'svtplay-dl')
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib64/python2.7/site-packages/svtplay_dl-1.5-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib64/python2.7/site-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/__init__.py", line 444, in main
    get_media(url, options)
  File "/usr/lib64/python2.7/site-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/__init__.py", line 176, in get_media
    get_all_episodes(stream, options, url)
  File "/usr/lib64/python2.7/site-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/__init__.py", line 204, in get_all_episodes
    get_one_media(substream, copy.copy(options))
  File "/usr/lib64/python2.7/site-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/__init__.py", line 225, in get_one_media
    for i in streams:
  File "/usr/lib64/python2.7/site-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/service/svtplay.py", line 119, in get
    streams = dashparse(self.options, self.http.request("get", alt.request.url), alt.request.url)
  File "/usr/lib64/python2.7/site-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/fetcher/dash.py", line 42, in dashparse
    audiourl = urljoin(baseurl, i.find("{urn:mpeg:dash:schema:mpd:2011}BaseURL").text)
AttributeError: 'NoneType' object has no attribute 'text'
```

Most other svtplay shows work just fine

**Comment by MR-2** [comment]
Use latest master.

**Comment by spaam** [comment]
master have a fix for this. going to release a new version later tonight

**Comment by spaam** [comment]
1.6 have fixes for this
