### ISSUE TITLE
syntax error near unexpected token `('

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#473]
I don't know if svtplay-dl should be able to download URL's, but if i try i only get an error message :(
```
$ svtplay-dl http://tv4play-i.akamaihd.net/i/mp4root/2013-04-18/88pid3585537(2334481_,T3MP445,T3MP435,T3MP425,T3MP415,T3MP48,T3MP43,T3MP4130,).mp4.csmil/index_0_av.m3u8
syntax error near unexpected token `('
```

**Comment by spaam** [comment]
try putting the url inside of '<url>'

**Comment by spaam** [comment]
that error is from your shell and not the script :)

**Comment by Sopor-** [comment]
```
$ svtplay-dl "http://tv4play-i.akamaihd.net/i/mp4root/2013-04-18/88pid3585537(2334481_,T3MP445,T3MP435,T3MP425,T3MP415,T3MP4,T3MP43,T3MP4130,).mp4.csmil/index_0_av.m3u8" --verbose
DEBUG [1476292950.69] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://tv4pay-i.akamaihd.net/i/mp4root/2013-04-18/88pid3585537(2334481_,T3MP445,T3MP435,T3MP425,T3MP415,T3MP48,T3MP43,T3MP4130,).mp4.csmil/index_0_av.m3u8'
DEBUG [1476292950.8] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://tv4ply-i.akamaihd.net/i/mp4root/2013-04-18/88pid3585537(2334481_,T3MP445,T3MP435,T3MP425,T3MP415,T3MP48,T3MP43,T3MP4130,).mp4.csmil/index_0_av.m3u8'
DEBUG [1476292950.86] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://tv4pay-i.akamaihd.net/i/mp4root/2013-04-18/88pid3585537(2334481_,T3MP445,T3MP435,T3MP425,T3MP415,T3MP48,T3MP43,T3MP4130,).mp4.csmil/index_0_av.m3u8'
ERROR [1476292950.89] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/__init__.py/get_one_media: version: 1.5
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 5, in <module>
    pkg_resources.run_script('svtplay-dl==1.5', u'svtplay-dl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.5-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/__init__.py", line 444, in main
    get_media(url, options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/__init__.py", line 178, in get_media
    get_one_media(stream, options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/__init__.py", line 225, in get_one_media
    for i in streams:
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/service/raw.py", line 34, in get
    streams = hlsparse(self.options, self.http.request("get", self.url), self.url)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/fetcher/hls.py", line 50, in hlsparse
    bitrate = float(i[1]["BANDWIDTH"])/1000
KeyError: 'BANDWIDTH'
``´

**Comment by spaam** [comment]
maybe you should give the m3u8 with the diffrerent playlists instead of the one with files.

**Comment by Sopor-** [comment]
I was almost sure this has been working before but i probably doing something wrong :(
Should it really crash?

**Comment by spaam** [comment]
it shouldn't crash..

**Comment by MR-2** [comment]
@Sopor- is there any particular reason why you need to use that particular url? 
http://tv4play-i.akamaihd.net/i/mp4root/2013-04-18/88pid3585537(2334481_,T3MP445,T3MP435,T3MP425,T3MP415,T3MP48,T3MP43,T3MP4130,).mp4.csmil/master.m3u8 Works if you use "" or escape the parentheses with \ before them. Like such: 
http://tv4play-i.akamaihd.net/i/mp4root/2013-04-18/88pid3585537\(2334481_,T3MP445,T3MP435,T3MP425,T3MP415,T3MP48,T3MP43,T3MP4130,\).mp4.csmil/master.m3u8

**Comment by Sopor-** [comment]
Yes, that seems to work. Couldn't svtplay-dl do the escaping so the user don't have to do it?

**Comment by spaam** [comment]
@Sopor- that error message is from your shell and that happens before svtplay-dl get it.
