### ISSUE TITLE
Can't download Bing episode from SVT-play

### ISSUE THREAD

**Issue by simoneddeland** [spaam/svtplay-dl#474]
I used the latest relase for windows, 1.6

The URL used: http://www.svtplay.se/video/3001367/bing/bing-sasong-1-avsnitt-1

Log:

D:\SVT-play>svtplay-dl.exe http://www.svtplay.se/video/3001367/bing/bing-sasong-1-avsnitt-1
ERROR: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues
ERROR: Include the URL used, the stack trace and the output of svtplay-dl --version in the issue

D:\SVT-play>svtplay-dl.exe --verbose http://www.svtplay.se/video/3001367/bing/bing-sasong-1-avsnitt-1
DEBUG [1476530668.635631] site-packages\svtplay_dl-1.6-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/3001367/bing/bing-sasong-1-avsnitt-1'
DEBUG [1476530668.7587397] site-packages\svtplay_dl-1.6-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svt.se/videoplayer-api/video/1189191-001A'
DEBUG [1476530668.786924] site-packages\svtplay_dl-1.6-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://svtplay12b-f.akamaihd.net/d/se/open/delivery/20161012/1189191-001A/dash-live/PG-1189191-001A-BINGBUNNYBIN-01-6f0049ca-a0cf-336d-d7b5-83794cbc6f53-live.mpd?alt=http://switcher.cdn.svt.se/1189191-001A.mpd'
DEBUG [1476530668.890168] site-packages\svtplay_dl-1.6-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://switcher.cdn.svt.se/1189191-001A.mpd'
ERROR [1476530668.9067006] site-packages\svtplay_dl-1.6-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.6
Traceback (most recent call last):
  File "site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
  File "site-packages\requests\packages\urllib3\util\connection.py", line 75, in create_connection
  File "socket.py", line 732, in getaddrinfo
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
  File "http\client.py", line 1106, in request
  File "http\client.py", line 1151, in _send_request
  File "http\client.py", line 1102, in endheaders
  File "http\client.py", line 934, in _send_output
  File "http\client.py", line 877, in send
  File "site-packages\requests\packages\urllib3\connection.py", line 167, in connect
  File "site-packages\requests\packages\urllib3\connection.py", line 151, in _new_conn
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x037D9690>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 423, in send
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 640, in urlopen
  File "site-packages\requests\packages\urllib3\util\retry.py", line 287, in increment
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='switcher.cdn.svt.se', port=80): Max retries exceeded with url: /1189191-001A.mpd (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x037D9690>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "site-packages\svtplay_dl-1.6-py3.5.egg\svtplay_dl\__init__.py", line 444, in main
  File "site-packages\svtplay_dl-1.6-py3.5.egg\svtplay_dl\__init__.py", line 178, in get_media
  File "site-packages\svtplay_dl-1.6-py3.5.egg\svtplay_dl\__init__.py", line 225, in get_one_media
  File "site-packages\svtplay_dl-1.6-py3.5.egg\svtplay_dl\service\svtplay.py", line 131, in get
  File "site-packages\requests\sessions.py", line 488, in get
  File "site-packages\svtplay_dl-1.6-py3.5.egg\svtplay_dl\utils\__init__.py", line 56, in request
  File "site-packages\requests\sessions.py", line 475, in request
  File "site-packages\requests\sessions.py", line 596, in send
  File "site-packages\requests\adapters.py", line 487, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='switcher.cdn.svt.se', port=80): Max retries exceeded with url: /1189191-001A.mpd (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x037D9690>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed',))
svtplay-dl returned -1

D:\SVT-play>

**Comment by spaam** [comment]
there is a fix in master for this and it will be available in the next release 1.7
