### ISSUE TITLE
Issues downloading s1e3 och The Staircase on svtplay

### ISSUE THREAD

**Issue by ScuttleSE** [spaam/svtplay-dl#475]
root@debian:/samba/video/Misc# svtplay-dl --verbose -S http://www.svtplay.se/video/1102208/the-staircase
DEBUG [1476637891.34] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/1102208/the-staircase'
DEBUG [1476637891.47] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.svt.se/videoplayer-api/video/1116319-003A'
ERROR [1476637891.52] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: version: 1.6
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 444, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 178, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 225, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 47, in get
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
root@debian:/samba/video/Misc#

**Comment by spaam** [comment]
will release a new version with the fix tomorrow.
