### ISSUE TITLE
crash after using CTRL+C

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#478]
I got this crash after using CTRL+C on SVTPlay
I'm trying to download only season 2 and it is the same issue i have on some of the other sites. When using -A it will download everything even if i use it in a folder with only season 5 episodes. I don't want to download 100+ episodes. But that wasn't the issue here.

At least it shouldn't crash when i use CTRL+C ...

```
$ svtplay-dl -S -A http://www.svtplay.se/tjockare-an-vatten?tab=sasong2
INFO: Episode 1 of 12
INFO: Outfile: tjockare.an.vatten.avsnitt.1-c2232fb-svtplay.srt
INFO: Selected to download dash, bitrate: 3061
INFO: Outfile: tjockare.an.vatten.avsnitt.1-c2232fb-svtplay.m4a
[103/436][=========================....................................................................................] ETA: 0:00:16^CTraceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 5, in <module>
    pkg_resources.run_script('svtplay-dl==1.6', u'svtplay-dl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.6-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.6-py2.7.egg/svtplay_dl/__init__.py", line 444, in main
    get_media(url, options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.6-py2.7.egg/svtplay_dl/__init__.py", line 176, in get_media
    get_all_episodes(stream, options, url)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.6-py2.7.egg/svtplay_dl/__init__.py", line 204, in get_all_episodes
    get_one_media(substream, copy.copy(options))
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.6-py2.7.egg/svtplay_dl/__init__.py", line 299, in get_one_media
    stream.download()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.6-py2.7.egg/svtplay_dl/fetcher/dash.py", line 122, in download
    self._download2(self.audio, audio=True)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.6-py2.7.egg/svtplay_dl/fetcher/dash.py", line 185, in _download2
    if data.status_code == 404:
AttributeError: 'NoneType' object has no attribute 'status_code'

```

**Comment by Sopor-** [comment]
When i use CTRL+C in Windows i get this error message. This is svtplay-dl 1.8
```
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 170, in _run_module_as_main "__main__", mod_spec)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 85, in_run_code exec(code, run_globals)
  File "..\svtplay-dl\__main__.py", line 13, in <module>
  File "..\svtplay-dl\svtplay_dl\__init__.py", line 444, in main
  File "..\svtplay-dl\svtplay_dl\__init__.py", line 176, in get_media
  File "..\svtplay-dl\svtplay_dl\__init__.py", line 204, in get_all_episodes
  File "..\svtplay-dl\svtplay_dl\__init__.py", line 299, in get_one_media
  File "..\svtplay-dl\svtplay_dl\fetcher\hls.py", line 106, in download
AttributeError: 'NoneType' object has no attribute 'status_code'
```

**Comment by Sopor-** [comment]
I still get this a crash when using CTRL+C.
```
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==1.9', 'svtplay-dl')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9-py2.7.egg/svtplay_dl/__init__.py", line 459, in main
    get_media(urls[0], options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9-py2.7.egg/svtplay_dl/__init__.py", line 190, in get_media
    get_all_episodes(stream, copy.copy(options), url)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9-py2.7.egg/svtplay_dl/__init__.py", line 218, in get_all_episodes
    get_one_media(substream, copy.copy(options))
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9-py2.7.egg/svtplay_dl/__init__.py", line 313, in get_one_media
    stream.download()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9-py2.7.egg/svtplay_dl/fetcher/dash.py", line 138, in download
    self._download2(self.audio, audio=True)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9-py2.7.egg/svtplay_dl/fetcher/dash.py", line 201, in _download2
    if data.status_code == 404:
AttributeError: 'NoneType' object has no attribute 'status_code'
```

**Comment by Sopor-** [comment]
This seems to be fixed so i'm closing it...
