### ISSUE TITLE
crash using ä in --exclude

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#479]
I get this crash if i try to use `--exclude=säsong` but i was not able to use `--exclude=säsong 1` because it didn't support space in --exclude.

```
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 5, in <module>
    pkg_resources.run_script('svtplay-dl==1.6', u'svtplay-dl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.6-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.6-py2.7.egg/svtplay_dl/__init__.py", line 424, in main
    options.exclude = options.exclude.split(",")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 15: ordinal not in range(128)

```

**Comment by spaam** [comment]
Is ä in the filename? if so we should remove it

**Comment by Sopor-** [comment]
No, ä was in the title. I was trying to exclude season 1 by adding "Säsong 1".
