### ISSUE TITLE
ERROR: svtplay-dl crashed

### ISSUE THREAD

**Issue by bos4711** [spaam/svtplay-dl#494]
~$ svtplay-dl --verbose --list-quality http://www.svtplay.se/video/10856841/allt-for-sverige/allt-for-sverige-sasong-6-avsnitt-2
DEBUG [1478286921.45] /home/bos/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/10856841/allt-for-sverige/allt-for-sverige-sasong-6-avsnitt-2'
DEBUG [1478286921.6] /home/bos/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://api.svt.se/videoplayer-api/video/1374517-002A'
ERROR [1478286921.64] /home/bos/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: version: 1.7-2-g4901d89
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/bos/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/home/bos/bin/svtplay-dl/svtplay_dl/__init__.py", line 444, in main
    
  File "/home/bos/bin/svtplay-dl/svtplay_dl/__init__.py", line 178, in get_media
    
  File "/home/bos/bin/svtplay-dl/svtplay_dl/__init__.py", line 225, in get_one_media
    
  File "/home/bos/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 47, in get
TypeError: 'dict' object is not callable

**Comment by MR-2** [comment]
@bos4711 works with Master version.

**Comment by bos4711** [comment]
Confirmed.

I just did a git pull and tried again, and it works now.
