### ISSUE TITLE
svtplay.se crash (AttributeError: 'NoneType' object has no attribute 'attrib')

### ISSUE THREAD

**Issue by dentarg** [spaam/svtplay-dl#499]
```
~/Downloads
$ svtplay-dl http://www.svtplay.se/video/11015221/aktuellt/aktuellt-9-nov-22-00
ERROR: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues
ERROR: Include the URL used, the stack trace and the output of svtplay-dl --version in the issue

~/Downloads 21s
$ svtplay-dl --verbose http://www.svtplay.se/video/11015221/aktuellt/aktuellt-9-nov-22-00
DEBUG [1478773865.89] /usr/local/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/11015221/aktuellt/aktuellt-9-nov-22-00'
DEBUG [1478773866.5] /usr/local/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://api.svt.se/videoplayer-api/video/1373856-001A'
DEBUG [1478773866.7] /usr/local/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'https://svt09-b.akamaized.net/u/svt09.mpd?start=1478724900&end=1478727000&pevi=1373856-001A'
ERROR [1478773867.22] /usr/local/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.7
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 444, in main
    get_media(url, options)
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 178, in get_media
    get_one_media(stream, options)
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 225, in get_one_media
    for i in streams:
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 127, in get
    streams = dashparse(self.options, self.http.request("get", i["url"]), i["url"])
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 61, in dashparse
    videofiles = parsesegments(video, url)
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 71, in parsesegments
    scheme = content[0].find("{urn:mpeg:dash:schema:mpd:2011}SegmentTemplate").attrib["media"]
AttributeError: 'NoneType' object has no attribute 'attrib'

~/Downloads
$ svtplay-dl --version
1.7

~/Downloads
$ python --version
Python 2.7.12
```

**Comment by spaam** [comment]
thanks for the bug report. this is fixed in master :)
