### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tooobe** [spaam/svtplay-dl#500]
I get an error on OSX from viafree.se

```
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==1.7', 'svtplay-dl')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl-1.7-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl-1.7-py2.7.egg/svtplay_dl/__init__.py", line 444, in main
    get_media(url, options)
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl-1.7-py2.7.egg/svtplay_dl/__init__.py", line 178, in get_media
    get_one_media(stream, options)
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl-1.7-py2.7.egg/svtplay_dl/__init__.py", line 277, in get_one_media
    options_subs_dl(subfixes)
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl-1.7-py2.7.egg/svtplay_dl/__init__.py", line 272, in options_subs_dl
    subs[0].download()
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl-1.7-py2.7.egg/svtplay_dl/subtitle/__init__.py", line 32, in download
    data = self.sami(subdata)
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl-1.7-py2.7.egg/svtplay_dl/subtitle/__init__.py", line 124, in sami
    tree = ET.fromstring(text)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
```

Is it because of my python version? 2.7.12_2
Tried uninstalling python and svtplay-dl from source and via homebrew with no success...

**Comment by spaam** [comment]
i just fixed this in master, i will release a new version in a few hours. :)

**Comment by tooobe** [comment]
You're amazing :)

**Comment by tooobe** [comment]
Same issue again?
```
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.8/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 444, in main
    get_media(url, options)
  File "/usr/local/Cellar/svtplay-dl/1.8/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 178, in get_media
    get_one_media(stream, options)
  File "/usr/local/Cellar/svtplay-dl/1.8/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 277, in get_one_media
    options_subs_dl(subfixes)
  File "/usr/local/Cellar/svtplay-dl/1.8/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 272, in options_subs_dl
    subs[0].download()
  File "/usr/local/Cellar/svtplay-dl/1.8/libexec/lib/python2.7/site-packages/svtplay_dl/subtitle/__init__.py", line 35, in download
    data = self.sami(subdata)
  File "/usr/local/Cellar/svtplay-dl/1.8/libexec/lib/python2.7/site-packages/svtplay_dl/subtitle/__init__.py", line 127, in sami
    tree = ET.fromstring(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1
```

**Comment by spaam** [comment]
do you get this everytime or what?  what video?

**Comment by spaam** [comment]
master have a fix for this now. it will be in the next version 1.9
