### ISSUE TITLE
viafree (tv3play) fel

### ISSUE THREAD

**Issue by wahboh** [spaam/svtplay-dl#507]
Följande fel uppträder på de flesta avsnitt ut tv3play/viafree Svartsjön:
http://www.viafree.se/program/drama/svartsjon/sasong-1/avsnitt-8
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py", line 444, in main
  File "site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py", line 178, in get_media
  File "site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py", line 277, in get_one_media
  File "site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py", line 272, in options_subs_dl
  File "site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\subtitle\__init__.py", line 35, in download
  File "site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\subtitle\__init__.py", line 127, in sami
  File "xml\etree\ElementTree.py", line 1333, in XML
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1
svtplay-dl returned -1

**Comment by Sopor-** [comment]
Försöker du att ta med undertexterna? Prova i så fall utan -S @wahboh

**Comment by wahboh** [comment]
Tack! Fungerar utan flaggan --subtitle
