### ISSUE TITLE
UR Play - Only SD and no subs

### ISSUE THREAD

**Issue by insurw** [spaam/svtplay-dl#508]
youtube-dl, which I think is based on same code is able to download in 720p.
I'm using the compiled Windows EXE, but I remember both 720p and subs working before.

**--list-quality**
INFO: Quality   Method
INFO: 6369      HLS
INFO: 2853      HLS

**-S**
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py", line 444, in main
  File "site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py", line 178, in get_media
  File "site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py", line 277, in get_one_media
  File "site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py", line 272, in options_subs_dl
  File "site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\subtitle\__init__.py", line 23, in download
  File "site-packages\requests\sessions.py", line 461, in request
  File "site-packages\requests\sessions.py", line 394, in prepare_request
  File "site-packages\requests\models.py", line 294, in prepare
  File "site-packages\requests\models.py", line 354, in prepare_url
requests.exceptions.MissingSchema: Invalid URL '//undertexter.ur.se/197000-197999/197084-18.vtt': No schema supplied. Perhaps you meant http:////undertexter.ur.se/197000-197999/197084-18.vtt?
svtplay-dl returned -1

**Comment by MR-2** [comment]
The subtitle issue should be fixed in master a couple of hours ago by @spaam. #504

**Comment by spaam** [comment]
what @MR-2 said.. i cant reproduce the quaility issue. can you share the url to the video?

**Comment by insurw** [comment]
Ah, sorry. I didn't know my list quality wouldn't say anything. I don't really know much about web ripping.
All of these can be played in HD in the browser and ripped in 720p by youtube-dl. E.g:
- Any videos from the "Vad är verkligt?" series, part 1: http://urplay.se/program/197084-var-manskliga-hjarna-vad-ar-verkligt
- Jakten på evigt liv: http://urplay.se/program/193163-jakten-pa-evigt-liv
- Godhet i generna: http://urplay.se/program/197592-godhet-i-generna

**Comment by spaam** [comment]
before we used the bitrate to define which one to use.   for some reason the sd one have a higher number compared to the hd one.

**Comment by MR-2** [comment]
"data-stream="PATH.mp4"" and "data-hdstream="PATH.mp4"". Might be two interesting classes to distinguish the quality of the streams.

**Comment by spaam** [comment]
yeah. maybe use that instead of the urPlayer.init one :)

**Comment by MR-2** [comment]
Maybe. But the current version works. If it ain't broke don't fix it.

**Comment by diskpart** [comment]
The issue with SD having higher bitrate used to be easily solved with --list-quality and then select the correct stream to download. However, recently ur play has made some changes which are visible in the urls and for some reason --list-quality and other parameters seems to have stopped working making it hard to know which bitrates are available.



c:\svtplay_exe>svtplay-dl http://urplay.se/program/198712-geografens-testamente-
europa-till-iberiska-halvon?v=1&utm_expid=138852357-7.hHGCyBdMR1CEFb8z-ShQ0w.1&u
tm_referrer=http%3A%2F%2Furplay.se%2Fprogram%2F198712-geografens-testamente-euro
pa-till-iberiska-halvon%3Fv%3D1 --list-quality
INFO: Selected to download hls, bitrate: 4082
INFO: Outfile: geografens.testamente-europa.till.iberiska.halvon-ur.play.ts
[179/179][========================================] ETA: 0:00:00
'utm_expid' is not recognized as an internal or external command,
operable program or batch file.
'utm_referrer' is not recognized as an internal or external command,
operable program or batch file.

**Comment by MR-2** [comment]
@diskpart try using: https://urplay.se/program/198712-geografens-testamente-europa-till-iberiska-halvon

**Comment by diskpart** [comment]
@MR-2 work like a charm! Thanks!

**Comment by selepo** [comment]
Should this be closed then ?

**Comment by diskpart** [comment]
@selepo I think so but I'm not the thread starter.
