### ISSUE TITLE
Crash when postprocessing

### ISSUE THREAD

**Issue by ecsfang** [spaam/svtplay-dl#517]
When downloading from SVT I get two files (m4a and mp4), and when merging these it crashes
I download using a scrip:

$ cat rip.sh 
  svtplay-dl -q 1677 -Q 10  -f -o TV/Fröken\ Frimans\ krig/ http://www.svtplay.se/video/11667382/froken-frimans-krig/froken-frimans-krig-sasong-3-avsnitt-1

$ ./rip.sh
  INFO: Selected to download dash, bitrate: 1677
  **INFO: Outfile: TV/Fröken Frimans krig/froken-frimans-krig.s03e01.avsnitt.1-34129da-svtplay.m4a**
  [354/354][========================================] ETA: 0:00:00
  **INFO: Outfile: TV/Fröken Frimans krig/froken-frimans-krig.s03e01.avsnitt.1-34129da-svtplay.mp4**
  [354/354][========================================] ETA: 0:00:00
  INFO: Merge audio and video into TV/Fröken Frimans krig/froken-frimans-krig.s03e01.avsnitt.1-34129da-svtplay.mp4
  Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 444, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 178, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 314, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/postprocess/__init__.py", line 153, in merge
  UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 5: ordinal not in range(128) 

But, if running exactly the same command directly at the prompt, it the just downloads a *.ts file instead with no problems ... !?
Any ideas of why?

$ svtplay-dl -q 1677 -Q 10  -f -o TV/Fröken\ Frimans\ krig/ http://www.svtplay.se/video/11667382/froken-frimans-krig/froken-frimans-krig-sasong-3-avsnitt-1
  INFO: Selected to download hls, bitrate: 1680
  **INFO: Outfile: TV/Fröken Frimans krig/froken-frimans-krig.s03e01.avsnitt.1-34129da-svtplay.ts**
  [352/352]  [==================================================================================================] ETA: 0:00:00

I'm using the latest version of svtplay-dl:

$ svtplay-dl --version
**1.8-11-g544f131**

**Comment by AnderScore** [comment]
Had the same problem.
But after installing ffmpeg with ```brew install ffmpeg``` it now works.

**Comment by ecsfang** [comment]
Thanks @AnderScore - I'll update ffmpeg and try again!

Cheers!

**Comment by spaam** [comment]
this sounds like an error with the directory name containing Ö in it.

**Comment by spaam** [comment]
master have a fix for this. please try it and see if it works :)

**Comment by ecsfang** [comment]
Thanks @spaam!
Updated - and this time it worked fine!

Cheers! :)
