### ISSUE TITLE
Picsearch crash - Konserthusetplay.se

### ISSUE THREAD

**Issue by MR-2** [spaam/svtplay-dl#527]
Working sample URL: http://konserthusetplay.se/?m=SWHy0qQwKhUWlNgiNkjo6g

None working sample URL: http://konserthusetplay.se/?m=QYBEuAhagByaRY3UkH7ShQ

Produced output:
`svtplay-dl http://konserthusetplay.se/?m=QYBEuAhagByaRY3UkH7ShQ --verbose
DEBUG [1485254971.46] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://konserthusetplay.se/?m=QYBEuAhagByaRY3UkH7ShQ'
DEBUG [1485254972.28] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://konserthusetplay.se/?m=QYBEuAhagByaRY3UkH7ShQ'
DEBUG [1485254973.06] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://csp.picsearch.com/rest?e=XhPxTe3dHxC1CsZKrpGHABwMDhNQ1tcIm8hlY_XU9oCCu5Kg39I934QyrTsX1hvpFRvm8M8WaNrO_GT1-oKAguAk5SkbsGUAwty0-niIq9TrBfLP_pbXLA&containerId=mediaplayer&i='
DEBUG [1485254973.5] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://csp.picsearch.com/rest?e=XhPxTe3dHxC1CsZKrpGHABwMDhNQ1tcIm8hlY_XU9oCCu5Kg39I934QyrTsX1hvpFRvm8M8WaNrO_GT1-oKAguAk5SkbsGUAwty0-niIq9TrBfLP_pbXLA&containerId=mediaplayer&i='
DEBUG [1485254973.88] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://csp.screen9.com/player?eventParam=1&ajaxauth=umFOAwliDZw54u7Nqo29Ul3jcXWNiPzMumoY0IbWGNTef421lKWTVg&method=embed&mediaid=v5cr7CrKjqbw-CY08KckBQ'
ERROR [1485254974.0] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: version: 1.9
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 459, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 192, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 239, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/picsearch.py", line 38, in get
KeyError: 'data'`

**Comment by spaam** [comment]
i think i have found a way to fix the issue. just need to check other sites that use this kind of streaming thing to see if its the same :) 

anyway thanks for the bug report <3

**Comment by MR-2** [comment]
Sounds great:)
