### ISSUE TITLE
Crash when using it with dplay.se running Linux Mint 18.1

### ISSUE THREAD

**Issue by b0bber** [spaam/svtplay-dl#529]
I'm getting crashes when trying to download some videos of dplay, most work just fine but a few give me this error, and I'm using the latest version, 1.9-1-gf38e840..
```
~ $ svtplay-dl -S --verbose http://www.dplay.se/arga-snickaren-vad-hande-sen/season-1-avsnitt-1/
DEBUG [1485433863.84] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.dplay.se/arga-snickaren-vad-hande-sen/season-1-avsnitt-1/'
DEBUG [1485433863.9] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.dplay.se/api/v2/ajax/videos?video_id=189155'
ERROR [1485433863.94] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: version: 1.9-1-gf38e840
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 459, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 192, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 239, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/dplay.py", line 57, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/dplay.py", line 109, in _autoname
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2013' in position 15: ordinal not in range(256)

```

**Comment by dentarg** [comment]
For another `UnicodeEncodeError` error (#430) it was possible to workaround it with `LANG=en_US.UTF-8`

**Comment by spaam** [comment]
it still crashes with LANG thing @dentarg  =/

**Comment by b0bber** [comment]
Is it an issue with my shell or with svtplay-dl?

**Comment by spaam** [comment]
svtplay-dl

**Comment by b0bber** [comment]
fix works :dancer:
