### ISSUE TITLE
Crash KeyError: 'titlePagePath'

### ISSUE THREAD

**Issue by EmptyStackExn** [spaam/svtplay-dl#530]
On a Ubuntu 16.04 and `svtplay-dl 1.9`, I am currently experiencing this error when I try to download [this link](http://www.svtplay.se/video/11396634/juicebaren/juicebaren-sasong-1-avsnitt-1):

```
$ svtplay-dl --version
1.9
$ svtplay-dl --verbose http://www.svtplay.se/video/11396634/juicebaren/juicebaren-sasong-1-avsnitt-1
DEBUG [1485439710.08] /home/psaxl/Paquets/.local/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/11396634/juicebaren/juicebaren-sasong-1-avsnitt-1'
ERROR [1485439710.18] /home/psaxl/Paquets/.local/svtplay-dl/svtplay_dl/__init__.py/get_one_media: version: 1.9
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/psaxl/Paquets/.local/svtplay-dl/__main__.py", line 13, in <module>
  File "/home/psaxl/Paquets/.local/svtplay-dl/svtplay_dl/__init__.py", line 459, in main
  File "/home/psaxl/Paquets/.local/svtplay-dl/svtplay_dl/__init__.py", line 192, in get_media
  File "/home/psaxl/Paquets/.local/svtplay-dl/svtplay_dl/__init__.py", line 239, in get_one_media
  File "/home/psaxl/Paquets/.local/svtplay-dl/svtplay_dl/service/svtplay.py", line 43, in get
  File "/home/psaxl/Paquets/.local/svtplay-dl/svtplay_dl/service/svtplay.py", line 178, in outputfilename
KeyError: 'titlePagePath'
```

**Comment by spaam** [comment]
thanks for the ticket :) i have already an ticket open for this #528.  i will close this ticket and write any updates in that ticket for this issue :)

**Comment by EmptyStackExn** [comment]
Thanks @spaam
