### ISSUE TITLE
crash when using svtplay.se

### ISSUE THREAD

**Issue by b0bber** [spaam/svtplay-dl#533]
ver. 1.9-1-gf38e840

```
svtplay-dl -S --verbose http://www.svtplay.se/video/12085610/antikrundan/antikrundan-sasong-28-avsnitt-3
DEBUG [1485458362.94] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/12085610/antikrundan/antikrundan-sasong-28-avsnitt-3'
ERROR [1485458363.09] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: version: 1.9-1-gf38e840
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 459, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 192, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 239, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 43, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 178, in outputfilename

    KeyError: 'titlePagePath'

```

**Comment by spaam** [comment]
i have just pushed a fix to master for this :D

**Comment by b0bber** [comment]
yeah, i saw that, tried to close this one, and it works now :)

**Comment by spaam** [comment]
awesome. thanks for testing the fix ❤️
