### ISSUE TITLE
SVTPlay crash

### ISSUE THREAD

**Issue by Starbane** [spaam/svtplay-dl#534]
Does not work to download any content from SVTPlay right now

svtplay-dl -M http://www.svtplay.se/video/11999570/illusionisten/illusionisten-avsnitt-1?tab=senast --verbose
DEBUG [1485460554.45] /usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/11999570/illusionisten/illusionisten-avsnitt-1?tab=senast'
ERROR [1485460554.7] /usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 459, in main
    get_media(urls[0], options)
  File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 192, in get_media
    get_one_media(stream, options)
  File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 239, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 43, in get
    self.options.output = self.outputfilename(janson, self.options.output)
  File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 178, in outputfilename
    name = data["video"]["titlePagePath"]
KeyError: 'titlePagePath'

**Comment by spaam** [comment]
@Starbane  thanks for the ticket. there is a fix in master right now. i will release a new version in a few hours with the fix :)

**Comment by Starbane** [comment]
Wow what a prompt answer! Thanks

Hope it will float downstream fast!
