### ISSUE TITLE
Crash! - KeyError: 'titlePagePath'

### ISSUE THREAD

**Issue by wirretheman** [spaam/svtplay-dl#538]
Seems to crash on all svt videos right now. :(           (Mac OS X - Version 1.9)

admin$ svtplay-dl --verbose http://www.svtplay.se/video/12051382/vanligen-lars-lerin/vanligen-lars-lerin-sasong-2-avsnitt-3
DEBUG [1485536210.06] /usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/12051382/vanligen-lars-lerin/vanligen-lars-lerin-sasong-2-avsnitt-3'
ERROR [1485536210.93] /usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 459, in main
    get_media(urls[0], options)
  File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 192, in get_media
    get_one_media(stream, options)
  File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 239, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 43, in get
    self.options.output = self.outputfilename(janson, self.options.output)
  File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 178, in outputfilename
    name = data["video"]["titlePagePath"]
KeyError: 'titlePagePath'

**Comment by spaam** [comment]
this is fixed in 1.9.1. i have made an pull request to brew to update that version. thank you for the bug report <3

**Comment by spaam** [comment]
brew havnt merged it yet.  hopefully later today :)

**Comment by iwconfig** [comment]
in the crash info, maybe people should be informed to search through the already open issues before opening a new one? no offence to those who have taken their time to come over here, thats great of course but in a case like this it might be a good thing to do first.

**Comment by Sopor-** [comment]
or create an `ISSUE_TEMPLATE.md` that will tell the user to search before creating new issues...

**Comment by spaam** [comment]
@iwconfig @Sopor-  yes. that sounds like a thing to do :)

**Comment by wirretheman** [comment]
Still get 1.9 through brew

**Comment by spaam** [comment]
@wirretheman i know my pull request is still open.

**Comment by wirretheman** [comment]
ok, patience then

**Comment by spaam** [comment]
they are usually pretty fast doing it.. this time they are little slow :)
