### ISSUE TITLE
SVTPlay doesn't work? 

### ISSUE THREAD

**Issue by Swedie** [spaam/svtplay-dl#539]
SVTPlay doesn't seem to work, get the same error for all videos I try.
Link: http://www.svtplay.se/video/12085658/pa-sparet/pa-sparet-sasong-27-avsnitt-8

C:\Users\Swedie\Downloads\Chrome\Program>svtplay-dl.exe --verbose http://www.svtplay.se/video/12085658/pa-sparet/pa-sparet-sasong-27-avsnitt-8
DEBUG [1485552478.350115] site-packages\svtplay_dl-1.9-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/12085658/pa-sparet/pa-sparet-sasong-27-avsnitt-8'
ERROR [1485552478.4666977] site-packages\svtplay_dl-1.9-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9-py3.5.egg\svtplay_dl\__init__.py", line 459, in main
  File "site-packages\svtplay_dl-1.9-py3.5.egg\svtplay_dl\__init__.py", line 192, in get_media
  File "site-packages\svtplay_dl-1.9-py3.5.egg\svtplay_dl\__init__.py", line 239, in get_one_media
  File "site-packages\svtplay_dl-1.9-py3.5.egg\svtplay_dl\service\svtplay.py", line 43, in get
  File "site-packages\svtplay_dl-1.9-py3.5.egg\svtplay_dl\service\svtplay.py", line 178, in outputfilename
KeyError: 'titlePagePath'
Failed to execute script svtplay-dl

**Comment by spaam** [comment]
I released a new version of the script 1.9.1 with a fix for this. download that one and it will work :)

**Comment by spaam** [comment]
thanks for the ticket <3

**Comment by Swedie** [comment]
Sorry, missed the fix. Thank you! :)
