### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Hans5004** [spaam/svtplay-dl#544]
Hi, well, svtplay-dl crashed, so here is my report:

hans@hans-System-Product-Name:~$ svtplay-dl --verbose http://www.svtplay.se/video/12087634/det-varas-for-solen/dokument-utifran-det-varas-for-solen-det-varas-for-solen
DEBUG [1485768786.53] /usr/lib/python2.7/dist-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/12087634/det-varas-for-solen/dokument-utifran-det-varas-for-solen-det-varas-for-solen'
ERROR [1485768786.83] /usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py", line 459, in main
    get_media(urls[0], options)
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py", line 192, in get_media
    get_one_media(stream, options)
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py", line 239, in get_one_media
    for i in streams:
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/service/svtplay.py", line 43, in get
    self.options.output = self.outputfilename(janson, self.options.output)
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/service/svtplay.py", line 178, in outputfilename
    name = data["video"]["titlePagePath"]
KeyError: 'titlePagePath'
hans@hans-System-Product-Name:~$ svtplay-dl --version
1.9

**Comment by spaam** [comment]
you can find a fix for this in 1.9.1

**Comment by spaam** [comment]
thank you for the bugreport

**Comment by Hans5004** [comment]
Slam, dunk! Thanks spaam!
