### ISSUE TITLE
Viafree -A key error 'program' in find_all_episodes

### ISSUE THREAD

**Issue by qnorsten** [spaam/svtplay-dl#547]
Trying to download all episodes of a series from viafree returns an key error. 

**Command: svtplay-dl.exe -A https://www.viafree.se/program/reality/ung-och-bortskamd -S --all-subtitles --raw-subtitles** 
**Version:** 1.9.1 (but should not be anything that affects this in master)
**Operating system:** Windows 7

I tried to do a quick look around on the json and website, to create a pullrequest rather then publish this issue, but could not pinpoint what has changed. 

**Error log:**
`DEBUG [1485941727.09386] site-packages\svtplay_dl-1.9.1-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.viafree.se/program/reality/ung-och-bortskamd'
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.1-py3.5.egg\svtplay_dl\__init__.py", line 459, in main
  File "site-packages\svtplay_dl-1.9.1-py3.5.egg\svtplay_dl\__init__.py", line 190, in get_media
  File "site-packages\svtplay_dl-1.9.1-py3.5.egg\svtplay_dl\__init__.py", line 206, in get_all_episodes
  File "site-packages\svtplay_dl-1.9.1-py3.5.egg\svtplay_dl\service\viaplay.py", line 195, in find_all_episodes
KeyError: 'program'
Failed to execute script svtplay-dl
`

**Comment by spaam** [comment]
the issue here was that they had a clip for season two but not an episode/"program".

thank you for you bugreport <3

**Comment by qnorsten** [comment]
Thanks for the quick fix @spaam :) That explains why I did not find any change when I looked in the source code:)
