### ISSUE TITLE
Crash on www.svtplay.se

### ISSUE THREAD

**Issue by lthuresson** [spaam/svtplay-dl#551]
svtplay-dl -v http://www.svtplay.se/video/11950466/homeland/homeland-sasong-6-avsnitt-1
DEBUG [1486150889.84] /usr/local/Cellar/svtplay-dl/1.8/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/11950466/homeland/homeland-sasong-6-avsnitt-1'
ERROR [1486150890.28] /usr/local/Cellar/svtplay-dl/1.8/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.8
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.8/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 444, in main
    get_media(url, options)
  File "/usr/local/Cellar/svtplay-dl/1.8/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 178, in get_media
    get_one_media(stream, options)
  File "/usr/local/Cellar/svtplay-dl/1.8/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 225, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/1.8/libexec/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 43, in get
    self.options.output = self.outputfilename(janson, self.options.output)
  File "/usr/local/Cellar/svtplay-dl/1.8/libexec/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 178, in outputfilename
    name = data["video"]["titlePagePath"]
KeyError: 'titlePagePath'

Platform: OS/x EL Captain
svtplay-dl built with http://brew.sh/

**Comment by spaam** [comment]
This is fixed in 1.9.1. Update brew and you will get the new release 

-- 
Johan Andersson
