### ISSUE TITLE
Can't download Melodifestivalen on Ubuntu

### ISSUE THREAD

**Issue by dataviruset** [spaam/svtplay-dl#557]
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

$ sudo dpkg -l | grep svtplay
ii  svtplay-dl                                                  0.30.2016.01.10-1~ubuntu14.04.1                     all          program to download videos from video on demand sites

$ svtplay-dl --verbose http://www.svtplay.se/video/12293898/melodifestivalen/melodifestivalen-2017-deltavling-2-11-feb-20-00-1
DEBUG [1486867256.74] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/12293898/melodifestivalen/melodifestivalen-2017-deltavling-2-11-feb-20-00-1'
DEBUG [1486867259.45] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.svt.se/videoplayer-api/video/1373985-002A'
DEBUG [1486867261.23] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'https://svt07-a.akamaized.net/u/svt07.m3u8?start=1486839600&end=1486844940&pevi=1373985-002A'
INFO [1486867261.92] /usr/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: Selected to download hls, bitrate: 2795
DEBUG [1486867261.93] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'https://svt07-a.akamaized.net/u/956_6.m3u8?pevi=1373985-002A&start=1486839600&end=1486844940?start=1486839600&end=1486844940&pevi=1373985-002A'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 352, in main
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 177, in get_media
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 235, in get_one_media
  File "/usr/bin/svtplay-dl/svtplay_dl/fetcher/hls.py", line 69, in download
  File "/usr/bin/svtplay-dl/svtplay_dl/fetcher/hls.py", line 143, in parsem3u
ValueError: need more than 1 value to unpack

**Comment by dataviruset** [comment]
Thanks for the quick fix!
