### ISSUE TITLE
Can't download Melodifestivalen on CentOS 6

### ISSUE THREAD

**Issue by dataviruset** [spaam/svtplay-dl#558]
$ cat /etc/redhat-release 
CentOS release 6.8 (Final)

Used pip to install:
svtplay-dl (1.9.1)
Tried to upgrade to latest version using pip install --upgrade svtplay-dl, but still doesn't work.

$ svtplay-dl --verbose http://www.svtplay.se/video/12293898/melodifestivalen/melodifestivalen-2017-deltavling-2-11-feb-20-00-1
/usr/lib64/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
DEBUG [1486867242.48] /usr/lib/python2.6/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/12293898/melodifestivalen/melodifestivalen-2017-deltavling-2-11-feb-20-00-1'
ERROR [1486867243.93] /usr/lib/python2.6/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9.1
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python2.6/site-packages/svtplay_dl/__init__.py", line 459, in main
    get_media(urls[0], options)
  File "/usr/lib/python2.6/site-packages/svtplay_dl/__init__.py", line 192, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/lib/python2.6/site-packages/svtplay_dl/__init__.py", line 239, in get_one_media
    for i in streams:
  File "/usr/lib/python2.6/site-packages/svtplay_dl/service/svtplay.py", line 53, in get
    res = self.http.get("http://api.svt.se/videoplayer-api/video/{}".format(vid))
ValueError: zero length field name in format

**Comment by dataviruset** [comment]
Thanks for the quick fix!
