### ISSUE TITLE
TV4 Play does not work

### ISSUE THREAD

**Issue by Kihltech** [spaam/svtplay-dl#561]
TV4 play has worked nice for a long time for me but now it has some issue:

```
$ svtplay-dl --verbose http://www.tv4play.se/program/farmen?video_id=3775652
DEBUG [1487006134.05] /usr/lib/python2.7/dist-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.tv4play.se/program/farmen?video_id=3775652'
DEBUG [1487006134.08] /usr/lib/python2.7/dist-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://prima.tv4play.se/api/web/asset/3775652/play'
DEBUG [1487006134.24] /usr/lib/python2.7/dist-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://webapi.tv4play.se/play/video_assets?type=episode&is_live=false&platform=web&node_nids=farmen&per_page=99999'
DEBUG [1487006134.27] /usr/lib/python2.7/dist-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://tv4playhds-f.akamaihd.net/z/mp4root/2017-02-04/pid200023696(3775652_,T3MP445,T3MP435,T3MP425,T3MP415,T3MP48,T3MP43,T3MP4130,).mp4.csmil/manifest.f4m'
DEBUG [1487006134.32] /usr/lib/python2.7/dist-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://prima.tv4play.se/api/web/asset/3775652/play?protocol=hls3'
ERROR [1487006134.35] /usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9.2
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py", line 461, in main
    get_media(urls[0], options)
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py", line 192, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py", line 239, in get_one_media
    for i in streams:
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/service/tv4play.py", line 105, in get
    data = self.http.request("get", url, cookies=self.cookies).content
AttributeError: 'NoneType' object has no attribute 'content'
```

Hope there is a solution to this great tool!

**Comment by b0bber** [comment]
Same here, with the lastest from github, 1.9.2
```

DEBUG [1487010985.81] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.tv4play.se/program/farmen?video_id=3774832'
DEBUG [1487010985.89] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://prima.tv4play.se/api/web/asset/3774832/play'
DEBUG [1487010986.1] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://webapi.tv4play.se/play/video_assets?type=episode&is_live=false&platform=web&node_nids=farmen&per_page=99999'
DEBUG [1487010986.17] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://tv4playhds-f.akamaihd.net/z/mp4root/2017-02-03/pid200016682(3774832_,T3MP445,T3MP435,T3MP425,T3MP415,T3MP48,T3MP43,T3MP4130,).mp4.csmil/manifest.f4m'
DEBUG [1487010986.25] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://prima.tv4play.se/api/web/asset/3774832/play?protocol=hls3'
ERROR [1487010986.33] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: version: 1.9.2
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 461, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 192, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 239, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/tv4play.py", line 105, in get
AttributeError: 'NoneType' object has no attribute 'content'
```

**Comment by spaam** [comment]
workaround for this is to add --dont-verify-ssl-cert  until i can find a better fix for this.

**Comment by b0bber** [comment]
Worked like a charm, thanx :)

**Comment by spaam** [comment]
the issue here is that tv4play changed a certificate at prima.tv4play.se server, because of that python can verify if its the right certificate or not.

**Comment by Kihltech** [comment]
**b0bber**, good that you reminded me, I forgot the version. I'm running 1.9.2 as well.

Thanks for the workaroudn **spaam**, works great!

**Comment by spaam** [comment]
Good guy tv4play have fixed the issue on their end. you can stop using the workaround now. :)
thanks for the bug report <3
