### ISSUE TITLE
Crash when downloading latest Melodifestivalen with python 2.6

### ISSUE THREAD

**Issue by dataviruset** [spaam/svtplay-dl#563]
CentOS 6, svtplay-dl 1.9.2.

```
> $ svtplay-dl --verbose http://www.svtplay.se/video/12366498/melodifestivalen/melodifestivalen-2017-deltavling-3-18-feb-20-00-1
> /usr/lib64/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
>   DeprecationWarning
> DEBUG [1487481712.42] /usr/lib/python2.6/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/12366498/melodifestivalen/melodifestivalen-2017-deltavling-3-18-feb-20-00-1'
> DEBUG [1487481714.29] /usr/lib/python2.6/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1373985-003A'
> DEBUG [1487481715.26] /usr/lib/python2.6/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay13j-f.akamaihd.net/z/world/open/20170219/1373985-003A/PG-1373985-003A-MELODIFESTIVALEN-02_,988,240,348,456,636,1680,2796,.mp4.csmil/manifest.f4m'
> DEBUG [1487481716.63] /usr/lib/python2.6/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay13h-f.akamaihd.net/d/world/open/delivery/20170219/1373985-003A/dash-live/PG-1373985-003A-MELODIFESTIVALEN-02-f291e670-dba9-41dc-8d37-deab0a9c5c53-6f0049ca-62ee-336d-36fe-4c5c75fc1837-live.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1373985-003A.mpd'
> ERROR [1487481716.86] /usr/lib/python2.6/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9.2
> Traceback (most recent call last):
>   File "/usr/bin/svtplay-dl", line 7, in <module>
>     svtplay_dl.main()
>   File "/usr/lib/python2.6/site-packages/svtplay_dl/__init__.py", line 461, in main
>     get_media(urls[0], options)
>   File "/usr/lib/python2.6/site-packages/svtplay_dl/__init__.py", line 192, in get_media
>     get_one_media(stream, copy.copy(options))
>   File "/usr/lib/python2.6/site-packages/svtplay_dl/__init__.py", line 239, in get_one_media
>     for i in streams:
>   File "/usr/lib/python2.6/site-packages/svtplay_dl/service/svtplay.py", line 96, in get
>     streams = dashparse(self.options, self.http.request("get", i["url"]), i["url"])
>   File "/usr/lib/python2.6/site-packages/svtplay_dl/fetcher/dash.py", line 55, in dashparse
>     video = xml.findall(".//{urn:mpeg:dash:schema:mpd:2011}AdaptationSet[@contentType='video']")
>   File "/usr/lib64/python2.6/xml/etree/ElementTree.py", line 355, in findall
>     return ElementPath.findall(self, path)
>   File "/usr/lib64/python2.6/xml/etree/ElementPath.py", line 198, in findall
>     return _compile(path).findall(element)
>   File "/usr/lib64/python2.6/xml/etree/ElementPath.py", line 176, in _compile
>     p = Path(path)
>   File "/usr/lib64/python2.6/xml/etree/ElementPath.py", line 93, in __init__
>     "expected path separator (%s)" % (op or tag)
> SyntaxError: expected path separator ([)

```

**Comment by qnorsten** [comment]
I think this is an error that is most easily fixed by updating your python version to at least 2.7 (even though I would recommend python 3 as svtplay-dl v 2.0 will drop python2 support)
