### ISSUE TITLE
Crash downloading news segment from SVT Play

### ISSUE THREAD

**Issue by tobiasger** [spaam/svtplay-dl#573]
I'm trying to download the following link:
[http://www.svtplay.se/klipp/11720382/nya-ord-pa-svenska-och-jamska?](url)

But I get the following error message:

`DEBUG [1487673938.61] /usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/klipp/11720382/'
ERROR [1487673939.52] /usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9.1
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 459, in main
    get_media(urls[0], options)
  File "/usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 192, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 239, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 43, in get
    self.options.output = self.outputfilename(janson, self.options.output)
  File "/usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 185, in outputfilename
    name = filenamify(data["video"]["programTitle"])
  File "/usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py", line 204, in filenamify
    title = unicodedata.normalize('NFD', title)
TypeError: must be unicode, not None`

Videos with `http://www.svtplay.se/video` seems to work fine, but `http://www.svtplay.se/klipp` crashes.

**Comment by spaam** [comment]
try upgrade your brew version to the latest one and see of you still get the error.

**Comment by spaam** [comment]
`brew update` and `brew upgrade`

**Comment by tobiasger** [comment]
@spaam That did it! Thanks!
