### ISSUE TITLE
Cant download from öppet arkiv

### ISSUE THREAD

**Issue by Skankhunter42** [spaam/svtplay-dl#574]
Hello.

I came across this issue while downloading episode 3 from Percy Tårar. I used --verbose and I got this message:

```
svtplay-dl --verbose https://www.oppetarkiv.se/video/2818855/percy-tarar-avsnitt-3-av-6
DEBUG [1487760596.57] /usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.oppetarkiv.se/video/2818855/percy-tarar-avsnitt-3-av-6'
DEBUG [1487760599.64] /usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://api.svt.se/videoplayer-api/video/1369346-003OA'
DEBUG [1487760599.84] /usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtarchive5b-f.akamaihd.net/z/se/open/20150407/1369346-003OA_OARKIV/EPISOD-1369346-003OA-1dbbf743593b6872_,892,144,252,360,540,1584,2700,.mp4.csmil/manifest.f4m'
DEBUG [1487760599.89] /usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtarchive5b-f.akamaihd.net/i/se/open/20150407/1369346-003OA_OARKIV/EPISOD-1369346-003OA-1dbbf743593b6872_,892,144,252,360,540,1584,2700,.mp4.csmil/master.m3u8'
DEBUG [1487760599.91] /usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtdash-vh.akamaihd.net/d/anders/1369346-003OA/PG-1369346-003OA-PERCYTARAR-01_dash.mpd'
DEBUG [1487760599.94] /usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtdash-vh.akamaihd.net/d/anders/1369346-003OA/PG-1369346-003OA-PERCYTARAR-01_hbbtv.mpd'
ERROR [1487760599.96] /usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9.1
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 459, in main
    get_media(urls[0], options)
  File "/usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 192, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 239, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/service/oppetarkiv.py", line 87, in get
    streams = dashparse(self.options, self.http.request("get", i["url"]), i["url"])
  File "/usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 61, in dashparse
    videofiles = parsesegments(video, url)
  File "/usr/local/Cellar/svtplay-dl/1.9.1/libexec/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 94, in parsesegments
    init = i.find("{urn:mpeg:dash:schema:mpd:2011}SegmentTemplate").attrib["initialization"]
AttributeError: 'NoneType' object has no attribute 'attrib'
```
Is it a problem at my end?

Thanks.

**Comment by spaam** [comment]
its not a problem on our end :)

**Comment by Skankhunter42** [comment]
Ok. 

Then I try again in a few days. 

Thanks.

**Comment by Sopor-** [comment]
@spaam but should it really crash?

**Comment by spaam** [comment]
@Sopor- no. in this case we try to access an element with the name `SegmentTemplate` and then the attribute `initialization` .. but we didnt find the `SegmentTemplate` and that is why it crashes.

**Comment by spaam** [comment]
in a more technical  thing where this crash happen is beacuse it the dash have the profile `isoff-live`  and i thought all files was split into several small segments, but this dash thing looks like `isoff-on-demand`.   on-demand using one big file that you download ranges from. i need to find a better way to detect those two types  and not using the profile one.
