### ISSUE TITLE
crashes with dplay (1.9.3)

### ISSUE THREAD

**Issue by b0bber** [spaam/svtplay-dl#575]
```
b0b@deathstar ~ $ svtplay-dl -S --verbose http://www.dplay.se/superstars/season-1-hinderbana-och-curling-star-pa-schemat/

DEBUG [1488315886.7] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.dplay.se/superstars/season-1-hinderbana-och-curling-star-pa-schemat/'
DEBUG [1488315886.78] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.dplay.se/api/v2/ajax/videos?video_id=192519'
DEBUG [1488315886.82] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://geo.dplay.se/geo.js'
DEBUG [1488315886.91] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'https://secure.dplay.se/secure/api/v2/user/authorization/stream/192519?stream_type=hds'
ERROR [1488315887.97] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: version: 1.9.3
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 463, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 194, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 241, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/dplay.py", line 89, in get
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

b0b@deathstar ~ $ svtplay-dl --version
1.9.3
```
plox halp1

**Comment by spaam** [comment]
have you tried watching the video on their site? for me i cant do it. so i gussing its something wrong on their end.  but yes. the script should not crash because of it

**Comment by b0bber** [comment]
oh, you're smarter than me... not i feel ashamed, just figured that dplay updated something and you haven't had the chance to update the software yet :/

**Comment by spaam** [comment]
they haven't updated anything. it works with other videos on their site. but for some reason that specific video does not work.   the script expecting that we get some proper respond back.. but we didnt. that is why it crash :)

**Comment by takanes** [comment]
It seems the site updated this video just now and it can be correctly download. Thanks!
