### ISSUE TITLE
ERROR: svtplay-dl crashed trying to download Halv åtta hos mig, ep 1

### ISSUE THREAD

**Issue by Gurkan911** [spaam/svtplay-dl#590]
Svtplay-dl crashes when trying to download "Halv åtta hos mig" episode 1. Eps 2 & 3 works.

svtplay-dl  http://www.tv4play.se/program/halv-%C3%A5tta-hos-mig?video_id=3753533 --verbose
DEBUG [1490218534.28] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.tv4play.se/program/halv-%C3%A5tta-hos-mig?video_id=3753533'
DEBUG [1490218534.33] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://prima.tv4play.se/api/web/asset/3753533/play'
DEBUG [1490218534.54] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://webapi.tv4play.se/play/video_assets?type=episode&is_live=false&platform=web&node_nids=halv-%C3%A5tta-hos-mig&per_page=99999'
ERROR [1490218535.82] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: version: 1.9.3-2-ga310ceb
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 463, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 194, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 241, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/tv4play.py", line 73, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/tv4play.py", line 182, in _autoname
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/tv4play.py", line 171, in _seasoninfo
KeyError: 'episode'

**Comment by Gurkan911** [comment]
if I use --output=filename it works.

**Comment by spaam** [comment]
latest master have a fix for this and it will be in the next version today
