### ISSUE TITLE
Crash: dl from oppetarkiv.se

### ISSUE THREAD

**Issue by ahkoila** [spaam/svtplay-dl#593]
True for 20+ DLs from oppetarkiv today. And by the way - thanks for a really good little tools :)

example:

**archibald@alexandra:/alexandria/svt2$ svtplay-dl https://www.oppetarkiv.se/video/3808263/pa-sparet-avsnitt-1-av-6 --verbose**
DEBUG [1490475635.31] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.oppetarkiv.se/video/3808263/pa-sparet-avsnitt-1-av-6'
DEBUG [1490475636.3] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.svt.se/videoplayer-api/video/1355559-001OA'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 352, in main
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 177, in get_media
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 190, in get_one_media
  File "/usr/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 56, in get
  File "/usr/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 148, in outputfilename
KeyError: 'programTitle'

**archibald@alexandra:/alexandria/svt2$ svtplay-dl --version**
0.30.2016.02.08-debian1

**Comment by iwconfig** [comment]
This is a known issue and a PR is available at #591, but there is some complications with it. So.. well, stay tuned. :)

**Comment by qnorsten** [comment]
For now a temporary fix is to set an output filename manually with -o or --output
