### ISSUE TITLE
TV4Play crash @ Rebecca Martinsson

### ISSUE THREAD

**Issue by wahboh** [spaam/svtplay-dl#599]
https://www.tv4play.se/program/rebecka-martinsson?video_id=3862894

DEBUG [1491517372.7760074] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.tv4play.se/session/new?https='
DEBUG [1491517372.9389236] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://account.services.tv4play.se/session/authenticate'
ERROR [1491517372.9389236] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.3
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 463, in main
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 194, in get_media
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 241, in get_one_media
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\tv4play.py", line 33, in get
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\tv4play.py", line 236, in _login
AttributeError: 'NoneType' object has no attribute 'json'
Failed to execute script svtplay-dl

Thanks for your dedicated work!

**Comment by MR-2** [comment]
@wahboh this isn't premium material hence it doesn't require you to put in your account information.
` svtplay-dl https://www.tv4play.se/program/rebecka-martinsson?video_id=3862894` is sufficient.

**Comment by spaam** [comment]
i guess something with the login thing here is the wrong  and what @MR-2 say : )

**Comment by MR-2** [comment]
@wahboh would be interesting if you could specify what your input string looked like which produced this output. Please don't post your account information

**Comment by wahboh** [comment]
@MR-2 
Thanks for valuable help! Removing login info helped and file downloaded without problems!
