### ISSUE TITLE
dplay.se - TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#602]
I get this error when trying to download Ullared but Sofias Anglar work. It work if i exclude -A. I'm running latest master.

```
$ svtplay-dl -A -S -P hls -v http://www.dplay.se/ullared
DEBUG [1491943406.58] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.dplay.se/ullared'
DEBUG [1491943407.03] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.dplay.se/api/v2/ajax/shows/843/seasons/?items=9999999&sort=episode_number_desc&page=0'
DEBUG [1491943409.6] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.dplay.se/api/v2/ajax/shows/843/seasons/?items=9999999&sort=episode_number_desc&page=1'
DEBUG [1491943410.26] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.dplay.se/api/v2/ajax/shows/843/seasons/?items=9999999&sort=episode_number_desc&page=2'
DEBUG [1491943410.72] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.dplay.se/api/v2/ajax/shows/843/seasons/?items=9999999&sort=episode_number_desc&page=3'
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==1.9.3', 'svtplay-dl')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 743, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1498, in run_script
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/__init__.py", line 463, in main
    get_media(urls[0], options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/__init__.py", line 192, in get_media
    get_all_episodes(stream, copy.copy(options), url)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/__init__.py", line 208, in get_all_episodes
    episodes = stream.find_all_episodes(options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/service/dplay.py", line 176, in find_all_episodes
    for i in dataj["data"]:
TypeError: 'NoneType' object is not iterable
```

**Comment by qnorsten** [comment]
It seems to works fine for me, with latest master. @Sopor can you check if it was some temporary error?

**svtplay-dl -S -A --force-subtitle http://www.dplay.se/ullared** 

INFO: Episode 1 of 72
INFO: Url: http://www.dplay.se/ullared/season-8-provjobb-pa-damavdelningen/
INFO: Outfile: ullared.s08e11.provjobb.pa.damavdelningen-194409-dplay.srt
INFO: Episode 2 of 72
INFO: Url: http://www.dplay.se/ullared/season-8-morgan-ola-conny-komponerar-varsin-matratt/
INFO: Outfile: ullared.s08e10.morgan.ola-conny.komponerar.varsin.matratt-198292-dplay.srt
INFO: Episode 3 of 72
INFO: Url: http://www.dplay.se/ullared/season-8-ullaredsfantaster/
INFO: Outfile: ullared.s08e09.ullaredsfantaster-197274-dplay.srt
 and so on....

**Comment by Sopor-** [comment]
This could be the old requests version i was running and when i try now it works so i'm closing this...
