### ISSUE TITLE
Öppet arkiv "KeyError: 'programTitle'"

### ISSUE THREAD

**Issue by wahboh** [spaam/svtplay-dl#605]
Hej vänner!

Får plötsligt "KeyError: 'programTitle'" på allt på "Öppet arkiv":

svtplay-dl.exe --verbose https://www.oppetarkiv.se/video/9800990/den-vite-riddaren-sasong-1-avsnitt-1-av-4

https://www.oppetarkiv.se/video/9800990/den-vite-riddaren-sasong-1-avsnitt-1-av-4
DEBUG [1492279444.956084] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.oppetarkiv.se/video/9800990/den-vite-riddaren-sasong-1-avsnitt-1-av-4'
DEBUG [1492279445.2720847] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1141057-001OA'
ERROR [1492279445.5192986] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.3
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 463, in main
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 194, in get_media
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 241, in get_one_media
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\oppetarkiv.py", line 40, in get
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\oppetarkiv.py", line 155, in outputfilename
KeyError: 'programTitle'
Failed to execute script svtplay-dl

**Comment by MR-2** [comment]
Dupe #596

**Comment by spaam** [comment]
what @MR-2  said
