### ISSUE TITLE
New error, svtplay.se

### ISSUE THREAD

**Issue by ijbh** [spaam/svtplay-dl#606]
I've been trying to download this link: https://www.svtplay.se/video/13213043/agenda/agenda-special-9-apr-20-00?start=auto

I'm using brew on MAC OS. I get the following error message after downloading for a while:

> INFO: Selected to download dash, bitrate: 3388
> INFO: Outfile: agenda.son.9.apr.20.00-381c55d-svtplay.m4a
> [1039/1039][========================================] ETA: 0:00:00
> INFO: Outfile: agenda.son.9.apr.20.00-381c55d-svtplay.mp4
> [0890/1042][==================================......] ETA: 0:04:48Traceback (most recent call last):
>   File "/usr/local/bin/svtplay-dl", line 7, in <module>
>     svtplay_dl.main()
>   File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 463, in main
>     get_media(urls[0], options)
>   File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 194, in get_media
>     get_one_media(stream, copy.copy(options))
>   File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 315, in get_one_media
>     stream.download()
>   File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 140, in download
>     self._download2(self.files)
>   File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 202, in _download2
>     if data.status_code == 404:
> AttributeError: 'NoneType' object has no attribute 'status_code'

I've tried downloading the file several times. This error message has appeared at different stages of the download. That makes me think that the problem is on my side. Could it for example be issues with my internet connection?

**Comment by qnorsten** [comment]
That is the same error you get if you cancel the running svtplay-dl program. So I think it is probably based in problem with your internet connection. But I am not sure.

**Comment by spaam** [comment]
hmm i guess we should try to download the part again if it failed when its not an KeyboardInterrupt expection.

**Comment by stdlogin** [comment]
I tried to download this movie from svtplay.se, and it works OK for me!
https://www.svtplay.se/video/13213043/agenda/agenda-special-9-apr-20-00?start=auto

 
================================================= BEGIN PROCESS ================================================= 
 
 
 
SVTPlayDL_Single 
1.00 (17/04/01) 

SVTPlay-DL Version installed 
1.9.3


----------------------------------------------------------------------
# Details 
----------------------------------------------------------------------

SourceURL 
https://www.svtplay.se/video/13213043/agenda/agenda-special-9-apr-20-00?start=auto 

Quality range (MIN-MAX)  
100 -1000  

Parameters 
-P HLS --force 
 
Location  
C:\Users\myown\Documents\SVTPlayDL\Movies 
 
INFO: Selected to download hls, bitrate: 988
INFO: Outfile: agenda.son.9.apr.20.00-381c55d-svtplay.ts

**Comment by ijbh** [comment]
Yes, I've tried again and again and it's very likely that it is an issue with my internet connection. That being said, what are the odds that you will update the program so that it allows downloads to be resumed after broken Internet connection? :)
