### ISSUE TITLE
Oppetarkiv.se - outputfilename KeyError: 'programTitle' Failed to execute script svtplay-dl

### ISSUE THREAD

**Issue by stdlogin** [spaam/svtplay-dl#608]
Hi,
I can´t download movies from oppetarkiv.se anymore with the lastest svtplay-dl for windows

**I tried to download this movie, but I get this messages**
https://www.oppetarkiv.se/video/13158007/fyra-nyanser-av-brunt-avsnitt-1-av-4

**Messages:**
outputfilename
KeyError: 'programTitle'
Failed to execute script svtplay-dl

**DEBUG:**
DEBUG [1492450773.0060005] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.oppetarkiv.se/video/13158007/fyra-nyanser-av-brunt-avsnitt-1-av-4'
DEBUG [1492450773.4501255] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1119767-001OA'
ERROR [1492450773.6727808] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.3
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 463, in main
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 194, in get_media
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 241, in get_one_media
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\oppetarkiv.py", line 40, in get
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\oppetarkiv.py", line 155, in outputfilename
KeyError: 'programTitle'
Failed to execute script svtplay-dl

**Comment by MR-2** [comment]
Dupe #596

**Comment by spaam** [comment]
what @MR-2 . closing this. no need to have several issues open

**Comment by spaam** [comment]
for the same thing and thanks for the issue :D
