### ISSUE TITLE
TV4Play - does not work - ERROR: svtplay-dl crashed  - 1.9.3

### ISSUE THREAD

**Issue by snix47** [spaam/svtplay-dl#612]
svt>svtplay-dl.exe -u dittlogin -p dittpasswd -S --verbose --remux https://www.tv4play.se/program/sveriges-mästerkock?video_id=3815893

DEBUG [1492697680.0186782] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.tv4play.se/program/sveriges-mästerkock?video_id=3815893'
DEBUG [1492697680.2778757] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.tv4play.se/session/new?https='
DEBUG [1492697680.4093769] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://account.services.tv4play.se/session/authenticate'
ERROR [1492697680.4176152] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.3
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 463, in main
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 194, in get_media
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 241, in get_one_media
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\tv4play.py", line 33, in get
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\tv4play.py", line 236, in _login
AttributeError: 'NoneType' object has no attribute 'json'
Failed to execute script svtplay-dl

**Comment by qnorsten** [comment]
They have changed some login stuff. Try it without the password and username, it was only ever needed for premium content and that has moved to cmore already.

**Comment by snix47** [comment]
Hi qnorsten
I did, and *tada* success! 
Thank you
