### ISSUE TITLE
ÖppetArkiv crash

### ISSUE THREAD

**Issue by martinsnygg** [spaam/svtplay-dl#615]
svtplay-dl --verbose https://www.oppetarkiv.se/video/1091339/den-vita-stenen-avsnitt-1-av-13
DEBUG [1493046346.66] /usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.oppetarkiv.se/video/1091339/den-vita-stenen-avsnitt-1-av-13'
DEBUG [1493046346.87] /usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://api.svt.se/videoplayer-api/video/1120198-001OA'
ERROR [1493046347.13] /usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9.3
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 463, in main
    get_media(urls[0], options)
  File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 194, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 241, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/service/oppetarkiv.py", line 40, in get
    self.options.output = self.outputfilename(data, self.options.output, ensure_unicode(self.get_urldata()))
  File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/service/oppetarkiv.py", line 155, in outputfilename
    name = data["programTitle"]
KeyError: 'programTitle'

**Comment by qnorsten** [comment]
That is fixed by https://github.com/spaam/svtplay-dl/commit/72eddeb4706325a690997b8e8347f575921f396a in latest master. But no new version have been released but if you install from source it should work.

**Comment by spaam** [comment]
i have released a new verison. it will hit brew tomorrow or the day after tomorrow.  thanks for the bugreport
