### ISSUE TITLE
Öppet arkiv crash

### ISSUE THREAD

**Issue by ingenvet** [spaam/svtplay-dl#617]
svtplay-dl https://www.oppetarkiv.se/video/1311985 --verbose
DEBUG [1493393709.4455442] /usr/lib/python3.6/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.oppetarkiv.se/video/1311985'
DEBUG [1493393709.528299] /usr/lib/python3.6/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1356965-001OA'
ERROR [1493393709.564596] /usr/lib/python3.6/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9.3
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3.6/site-packages/svtplay_dl/__init__.py", line 463, in main
    get_media(urls[0], options)
  File "/usr/lib/python3.6/site-packages/svtplay_dl/__init__.py", line 194, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/lib/python3.6/site-packages/svtplay_dl/__init__.py", line 241, in get_one_media
    for i in streams:
  File "/usr/lib/python3.6/site-packages/svtplay_dl/service/oppetarkiv.py", line 40, in get
    self.options.output = self.outputfilename(data, self.options.output, ensure_unicode(self.get_urldata()))
  File "/usr/lib/python3.6/site-packages/svtplay_dl/service/oppetarkiv.py", line 155, in outputfilename
    name = data["programTitle"]
KeyError: 'programTitle'

**Comment by b0bber** [comment]
It works with 1.9.3-15-g72eddeb (latest version as I type)

**Comment by Sopor-** [comment]
I'm at 1.9.3-17-gad6180e and it work here too

**Comment by spaam** [comment]
latest version 1.9.4 have a fix for this.
