### ISSUE TITLE
TV4Play crash

### ISSUE THREAD

**Issue by b0bber** [spaam/svtplay-dl#618]
**b0b@deathstar ~/Lagring/outgoing $** svtplay-dl --verbose https://www.tv4play.se/program/biggest-loser?video_id=3798773
DEBUG [1493668338.86] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.tv4play.se/program/biggest-loser?video_id=3798773'
DEBUG [1493668339.02] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://prima.tv4play.se/api/web/asset/3798773/play'
DEBUG [1493668339.25] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://webapi.tv4play.se/play/video_assets?type=episode&is_live=false&platform=web&node_nids=biggest-loser&per_page=99999'
ERROR [1493668339.47] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: version: 1.9.3-15-g72eddeb
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 464, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 194, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 242, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/tv4play.py", line 73, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/tv4play.py", line 182, in _autoname
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/tv4play.py", line 171, in _seasoninfo
KeyError: 'episode'
**b0b@deathstar ~/Lagring/outgoing $** svtplay-dl --version
1.9.3-15-g72eddeb
**b0b@deathstar ~/Lagring/outgoing $** 

Plox help, gf is mad coz she can't watch her precious Biggest Looser :|

**Comment by qnorsten** [comment]
Seem to be an issue with the autonaming. As long as you are only downloading one video at a time (not using -a or --all-episodes) you can just fix it by supplying your own file name with either -o filename or --output filename

**Comment by b0bber** [comment]
Sweet, it worked!
Thanks alot @qnorsten

**Comment by spaam** [comment]
latest master have a fix for this

**Comment by Sopor-** [comment]
Is it you or TV4 that have changed the file name?
Last week:
`biggest.loser.s01e03.del.6-revanschen-3798774-tv4play.ts`
Today after the fix:
`biggest.loser.s01.del.7-revanschen-3798773-tv4play.ts`

**Comment by spaam** [comment]
@Sopor-  tv4 changed it on their end. there is no episode info on revanschen part.  but the `del 7` that is not revanschen have episode info..
