### ISSUE TITLE
Issue svtplay

### ISSUE THREAD

**Issue by Skankhunter42** [spaam/svtplay-dl#619]
Hello.

I tried to download episode 2 of the new season of skam with -M to get the subtitles.

This is my output.

svtplay-dl -M https://www.svtplay.se/video/13356584/skam/skam-sasong-4-avsnitt-2?start=auto
INFO: Outfile: skam.s04e02.avsnitt.2-eb0a706-svtplay.srt
INFO: Selected to download dash, bitrate: 3285
INFO: Outfile: skam.s04e02.avsnitt.2-eb0a706-svtplay.m4a
[184/184][========================================] ETA: 0:00:00
INFO: Outfile: skam.s04e02.avsnitt.2-eb0a706-svtplay.mp4
[185/185][========================================] ETA: 0:00:00
INFO: Merge audio, video and subtitle into skam.s04e02.avsnitt.2-eb0a706-svtplay.mp4
INFO: Determining the language of the subtitle.
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 463, in main
    get_media(urls[0], options)
  File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 194, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 330, in get_one_media
    post.merge()
  File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/postprocess/__init__.py", line 166, in merge
    langs = self.sublanguage()
  File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/postprocess/__init__.py", line 84, in sublanguage
    langs += [query(subfile)]
  File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/postprocess/__init__.py", line 42, in query
    random_sentences = ' '.join(sample(parse(self), 8)).replace('\r\n', '')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 323, in sample
    raise ValueError("sample larger than population")
ValueError: sample larger than population

It is a problem at my end?

**Comment by Skankhunter42** [comment]
Hello.

I closed that ticket because I didn't see the problem anymore when I stopped using -m when downloading the episodes. That's why I closed the ticket. 

But the problem is still there it seems.
