### ISSUE TITLE
https://www.svtplay.se/ stopped working, worked fine before! :/

### ISSUE THREAD

**Issue by MaistroX** [spaam/svtplay-dl#623]
C:\svtplay-dl>svtplay-dl.exe -o I:\svtplay-dl -S -M --remux -f https://www.svtplay.se/video/13393728/gift-vid-forsta-ogonkastet/gift-vid-forsta-ogonkastet-sasong-3-avsnitt-7 --verbose
DEBUG [1494091304.0679605] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.svtplay.se/video/13393728/gift-vid-forsta-ogonkastet/gift-vid-forsta-ogonkastet-sasong-3-avsnitt-7'
ERROR [1494091304.5875676] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.3
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 463, in main
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 194, in get_media
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 241, in get_one_media
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\svtplay.py", line 41, in get
KeyError: 'videoTitlePage'
Failed to execute script svtplay-dl

**Comment by ForHelvete** [comment]
This issue has been brought up quite a few times.
https://github.com/spaam/svtplay-dl/issues/622
https://github.com/spaam/svtplay-dl/issues/621
https://github.com/spaam/svtplay-dl/issues/617

It's fixed but they haven't uploaded the latest version, so the solution is to "just" compile your own with the available source code, which is not entirely straight forward as some would believe, unless you're familiar with programming.

**Comment by MaistroX** [comment]
Thx, that solved that, should have looked around Before I posted! ;)
