### ISSUE TITLE
Can´t download from viafree.se - SVTPlay-DL Crash

### ISSUE THREAD

**Issue by stdlogin** [spaam/svtplay-dl#626]
Hi, I can´t download from viafree.se anymore.

**I got this messages**

DEBUG [1494141140.9778156] C:\Python35-32\lib\site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.viafree.se/program/underhallning/jocke-och-jonna-moter/sasong-1/836586'
DEBUG [1494141141.1381145] C:\Python35-32\lib\site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://playapi.mtgx.tv/v3/videos/836586'
ERROR [1494141141.227859] C:\Python35-32\lib\site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.3
Traceback (most recent call last):
  File "P:\Programing\svtplay-dl spamm\svtplay-dl\bin\svtplay-dl", line 7, in <module>
  File "C:\Python35-32\lib\site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 464, in main
  File "C:\Python35-32\lib\site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 194, in get_media
  File "C:\Python35-32\lib\site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 242, in get_one_media
  File "C:\Python35-32\lib\site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\viaplay.py", line 126, in get
  File "C:\Python35-32\lib\site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\viaplay.py", line 237, in outputfilename
  File "C:\Python35-32\lib\site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\viaplay.py", line 280, in _autoname
ValueError: invalid literal for int() with base 10: 'Mikaela Laurén'
Failed to execute script svtplay-dl

**Comment by MR-2** [comment]
Encoding issue with the auto-naming, specify it yourself with the -o command until there's a fix.
