### ISSUE TITLE
vk.se crash

### ISSUE THREAD

**Issue by emillundh** [spaam/svtplay-dl#638]
www.vk.se/play has worked before. From their current site I can't download anything without the following crash: 
```
$ bin/svtplay-dl http://www.vk.se/play?video=0a62cf61-7148-4615-8c3c-d5e8eaa5f5cf -v
DEBUG [1495440355.95] /usr/lib/python2.7/dist-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.vk.se/play?video=0a62cf61-7148-4615-8c3c-d5e8eaa5f5cf'
DEBUG [1495440356.08] /usr/lib/python2.7/dist-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ljsp.lwcdn.com/web/public/item.json?type=video&pi=f49d49d5-85a3-4674-82e3-a471e17b0322'
ERROR [1495440356.13] /usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9.4
Traceback (most recent call last):
  File "bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py", line 466, in main
    get_media(urls[0], options)
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py", line 196, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py", line 244, in get_one_media
    for i in streams:
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/service/lemonwhale.py", line 44, in get
    videos = jdata["videos"][0]["media"]["streams"]
KeyError: 'videos'
```
```
$ bin/svtplay-dl --version
1.9.4
```
(same error with version 1.8)

**Comment by MR-2** [comment]
@emillundh this URL should work fine:

http://www.vk.se/2006201/tv-jattefisken-forsokte-ata-upp-fangsten

**Comment by emillundh** [comment]
Thanks, that url did work! :)
