### ISSUE TITLE
tv4play download: AttributeError: 'NoneType' object has no attribute 'content'

### ISSUE THREAD

**Issue by Mirarkitty** [spaam/svtplay-dl#641]
I fail to download:

```
% svtplay-dl --verbose 'https://www.tv4play.se/program/%C3%A4ntligen-hemma?video_id=3820232' 
DEBUG [1496624582.2] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.tv4play.se/program/%C3%A4ntligen-hemma?video_id=3820232'
DEBUG [1496624582.4] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://prima.tv4play.se/api/web/asset/3820232/play'
DEBUG [1496624582.54] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://webapi.tv4play.se/play/video_assets?type=episode&is_live=false&platform=web&node_nids=%C3%A4ntligen-hemma&per_page=99999'
DEBUG [1496624583.64] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://tv4playhds-f.akamaihd.net/z/mp4root/2017-03-03/pid200017622(3820232_,T3MP445,T3MP435,T3MP425,T3MP415,T3MP48,T3MP43,T3MP4130,).mp4.csmil/manifest.f4m'
DEBUG [1496624583.68] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://prima.tv4play.se/api/web/asset/3820232/play?protocol=hls3'
ERROR [1496624583.69] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: version: 1.9.4-1-ge2bb0dd
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 466, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 196, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 244, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/tv4play.py", line 105, in get
AttributeError: 'NoneType' object has no attribute 'content'
```

Not sure if tv4 is still supposed to work?

**Comment by spaam** [comment]
it works now.. for some reason getting the info for some files didnt work.

**Comment by Mirarkitty** [comment]
I'm still getting the same errors on those streams. Anything more I can debug?

**Comment by spaam** [comment]
what do you get when you type `curl -v -o /dev/null https://prima.tv4play.se/api/web/asset/3820232/play?protocol=hls3` ?

**Comment by Mirarkitty** [comment]
```
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 54.230.128.4...
* Connected to prima.tv4play.se (54.230.128.4) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: CN=prima.tv4play.se
*        start date: 2017-04-27 00:00:00 GMT
*        expire date: 2018-05-27 12:00:00 GMT
*        subjectAltName: prima.tv4play.se matched
*        issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*        SSL certificate verify ok.
> GET /api/web/asset/3820232/play?protocol=hls3 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: prima.tv4play.se
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/xml;charset=UTF-8
< Content-Length: 2810
< Connection: keep-alive
* Server Apache-Coyote/1.1 is not blacklisted
< Server: Apache-Coyote/1.1
< Cache-Control: must-revalidate, max-age=0, private
< ETag: 9DE842258F691AF668FF304A7F4FDFAA
< Date: Tue, 04 Jul 2017 13:56:58 GMT
< x-backend: restapi7
< X-Cache: Miss from cloudfront
< Via: 1.1 1f0b42f241167f63f522e5c1d8579e22.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: RXrYjj-U45uxcCsfb7svALv7zT9o8GnSZtJKKOQNw0-hHe8KV76MMg==
< 
{ [data not shown]
100  2810  100  2810    0     0  10940      0 --:--:-- --:--:-- --:--:-- 10976
* Connection #0 to host prima.tv4play.se left intact

```

**Comment by Sopor-** [comment]
It works here:
```
svtplay-dl https://www.tv4play.se/program/%C3%A4ntligen-hemma?video_id=3820232
INFO: Selected to download hls, bitrate: 4496
INFO: Outfile: antligen.hemma.s41e02.del.2-3820232-tv4play.ts
[013/294][===...................................................................] ETA: 0:01:53
```

**Comment by selepo** [comment]
@Mirarkitty: Should this be closed then ?

**Comment by dentarg** [comment]
Yeah, seems like it was a temporary problem.

**Comment by Mirarkitty** [comment]
It's weird, but it seems a problem with a library not behaving like expected. The solution should probably be a better error message.
