### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by tooobe** [spaam/svtplay-dl#657]
I'm getting the following error. If I retry the download it will usually work eventually. Is it on the server side or script error?

Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 466, in main
    get_media(urls[0], options)
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 196, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 318, in get_one_media
    stream.download()
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/fetcher/hls.py", line 110, in download
    if data.status_code == 404:
AttributeError: 'NoneType' object has no attribute 'status_code'

**Comment by spaam** [comment]
Did you press ctrl+c when you got this? 

-- 
Johan Andersson

**Comment by tooobe** [comment]
Not to my knowledge. And I'm on macOS also ☺️

**Comment by dentarg** [comment]
Hard to reproduce this without any URL to try to download. New versions of svtplay-dl has been released since, please try them. If there's still an issue here, we can re-open.
