### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by ondope** [spaam/svtplay-dl#658]
```
svtplay-dl -A https://www.dr.dk/tv/se/boern/ultra/klassen-tv/klassen-6/klassen-det-store-klasseshow-116
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3.6/site-packages/svtplay_dl/__init__.py", line 466, in main
    get_media(urls[0], options)
  File "/usr/lib/python3.6/site-packages/svtplay_dl/__init__.py", line 194, in get_media
    get_all_episodes(stream, copy.copy(options), url)
  File "/usr/lib/python3.6/site-packages/svtplay_dl/__init__.py", line 210, in get_all_episodes
    episodes = stream.find_all_episodes(options)
  File "/usr/lib/python3.6/site-packages/svtplay_dl/service/dr.py", line 86, in find_all_episodes
    if '/view/' in path:
TypeError: a bytes-like object is required, not 'str'

```
Arch Linux, python 3.6, svtplay-dl 1.9.4

**Comment by spaam** [comment]
this will be in the next 1.9.5 release.
