### ISSUE TITLE
Can't download subtitles for URPlay

### ISSUE THREAD

**Issue by g3blv** [spaam/svtplay-dl#661]
Trying to download video with subtitles on URPlay gives me the following error.
```
svtplay-dl -S http://urplay.se/program/195243-berlin-tokyo-med-bil-asian-highway
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 352, in main
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 177, in get_media
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 217, in get_one_media
  File "/usr/bin/svtplay-dl/svtplay_dl/subtitle/__init__.py", line 22, in download
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 353, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//undertexter.ur.se/195000-195999/195243-18.vtt': No schema supplied. Perhaps you meant http:////undertexter.ur.se/195000-195999/195243-18.vtt?
```

I'm running on Ubuntu 16.04.2. Please let me know if any further information or investigation is needed.

**Comment by selepo** [comment]
What version of svtplay-dl are you using ?

`svtplay-dl --version`

**Comment by g3blv** [comment]
Upgrade from 
0.30.2016.02.08-debian1
to
1.9.4
I'm not getting the error message now.
Thanks for helping out.
