### ISSUE TITLE
Option -A for viafree

### ISSUE THREAD

**Issue by agent666** [spaam/svtplay-dl#663]
The option to get all episodes on viafree not working  ..

**Comment by spaam** [comment]
nice. i will fix this tomorrow. rewriting the mpd parser for #567 right now

**Comment by spaam** [comment]
what kind of error did you get? some  similar to 
``` 
File "/Users/johan/dev/svtplay-dl-dev/lib/svtplay_dl/service/viaplay.py", line 201, in find_all_episodes
    if "program" in janson["format"]["videos"][str(i)]:
KeyError: '2'
```
?

**Comment by Sopor-** [comment]
I get this crash when using -A but i can download if i do it without -A

$ svtplay-dl -A -S -P hls https://www.viafree.se/program/livsstil/skonhetsfallan-sverige

Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==1.9.4', u'svtplay-dl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1438, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.4-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.4-py2.7.egg/svtplay_dl/__init__.py", line 466, in main
    get_media(urls[0], options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.4-py2.7.egg/svtplay_dl/__init__.py", line 194, in get_media
    get_all_episodes(stream, copy.copy(options), url)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.4-py2.7.egg/svtplay_dl/__init__.py", line 210, in get_all_episodes
    episodes = stream.find_all_episodes(options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.4-py2.7.egg/svtplay_dl/service/viaplay.py", line 201, in find_all_episodes
    if "program" in janson["format"]["videos"][str(i)]:
KeyError: '1'
