### ISSUE TITLE
Option -A for svtplay

### ISSUE THREAD

**Issue by agent666** [spaam/svtplay-dl#676]
C:\>python svtplay-dl -v -A https://www.svtplay.se/video/956586/en-pilgrims
-dod/del-1-346?start=auto
DEBUG [1505372282.48] svtplay-dl\svtplay_dl\utils\__init__.py/request: HTTP gett
ing 'https://www.svtplay.se/video/956586/en-pilgrims-dod/del-1-346?start=auto'
Traceback (most recent call last):
  File "C:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "svtplay-dl\__main__.py", line 13, in <module>
  File "svtplay-dl\svtplay_dl\__init__.py", line 467, in main
  File "svtplay-dl\svtplay_dl\__init__.py", line 195, in get_media
  File "svtplay-dl\svtplay_dl\__init__.py", line 211, in get_all_episodes
  File "svtplay-dl\svtplay_dl\service\svtplay.py", line 220, in find_all_episode
s
KeyError: 'relatedVideosTabs'

Fler med detta problem? Har en uppdaterad version.

**Comment by MaistroX** [comment]
C:\svtplay-dl>svtplay-dl.exe -o I:\svtplay-dl -S -M --remux -f https://www.svtplay.se/video/956586/en-pilgrims-dod/del-1-346?info=visa&start=auto
INFO: Outfile: I:\svtplay-dl\en.pilgrims.dod.s01e01.avsnitt.1-e38b114-svtplay.srt
INFO: Selected to download dash, bitrate: 3140
INFO: Outfile: I:\svtplay-dl\en.pilgrims.dod.s01e01.avsnitt.1-e38b114-svtplay.m4a
[584/584][=====================================================================================================================================================================================================] ETA: 0:00:00
INFO: Outfile: I:\svtplay-dl\en.pilgrims.dod.s01e01.avsnitt.1-e38b114-svtplay.mp4
[142/585][===============================================......................................................................................................................................................] ETA: 0:02:45

Fungerar hur bra som helst! :)

Kör "Latest" versionen från https://svtplay-dl.se/archive/

**Comment by agent666** [comment]
Jo men om du kör med -A också du kör ej med den va jag kan se

**Comment by MaistroX** [comment]
Sorry, my Bad!

Får samma som du -> 

C:\svtplay-dl>svtplay-dl.exe -o I:\svtplay-dl -S -M --remux -A -f --all-subtitles https://www.svtplay.se/video/998829/en-pilgrims-dod/
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.4-py3.5.egg\svtplay_dl\__init__.py", line 466, in main
  File "site-packages\svtplay_dl-1.9.4-py3.5.egg\svtplay_dl\__init__.py", line 194, in get_media
  File "site-packages\svtplay_dl-1.9.4-py3.5.egg\svtplay_dl\__init__.py", line 210, in get_all_episodes
  File "site-packages\svtplay_dl-1.9.4-py3.5.egg\svtplay_dl\service\svtplay.py", line 220, in find_all_episodes
KeyError: 'relatedVideosTabs'
Failed to execute script svtplay-dl

:(

**Comment by spaam** [comment]
fixat i master. kommer i release idag.
