### ISSUE TITLE
--all-episodes broken

### ISSUE THREAD

**Issue by hacker112** [spaam/svtplay-dl#678]
Probably due to changes in HTML-structure on svtplay.se

Example and traceback:
$ svtplay-dl  --all-episodes 'https://www.svtplay.se/video/15047372/rederiet/rederiet-sasong-1-farlig-kryssning'
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 466, in main
    get_media(urls[0], options)
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 194, in get_media
    get_all_episodes(stream, copy.copy(options), url)
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 210, in get_all_episodes
    episodes = stream.find_all_episodes(options)
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 220, in find_all_episodes
    items = dataj["relatedVideoContent"]["relatedVideosTabs"]

**Comment by spaam** [comment]
yes this is fixed in #676 .. i will release 1.9.5  in a few hours.
