### ISSUE TITLE
Crash: svtplay-dl --verbose -A -S 'https://www.oppetarkiv.se/video/1311985/som-man-ropar-avsnitt-1-av-3'

### ISSUE THREAD

**Issue by henriksten65** [spaam/svtplay-dl#679]
Host: Xubuntu 17.04.

DEBUG [1505673808.37] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.oppetarkiv.se/video/1311985/som-man-ropar-avsnitt-1-av-3'
DEBUG [1505673808.64] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.oppetarkiv.se/etikett/titel/Som_man_ropar/?sida=1&sort=tid_stigande&embed=true'
DEBUG [1505673808.9] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.oppetarkiv.se/etikett/titel/Som_man_ropar/?sida=2&sort=tid_stigande&embed=true'
INFO [1505673809.08] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/__init__.py/get_all_episodes: Episode 1 of 3
DEBUG [1505673809.08] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.oppetarkiv.se/video/1311985/som-man-ropar-avsnitt-1-av-3'
DEBUG [1505673809.31] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://api.svt.se/videoplayer-api/video/1356965-001OA'
ERROR [1505673809.64] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/__init__.py/get_one_media: version: 1.9.3
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==1.9.3', 'svtplay-dl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/__init__.py", line 463, in main
    get_media(urls[0], options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/__init__.py", line 192, in get_media
    get_all_episodes(stream, copy.copy(options), url)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/__init__.py", line 220, in get_all_episodes
    get_one_media(substream, copy.copy(options))
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/__init__.py", line 241, in get_one_media
    for i in streams:
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/service/oppetarkiv.py", line 40, in get
    self.options.output = self.outputfilename(data, self.options.output, ensure_unicode(self.get_urldata()))
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/service/oppetarkiv.py", line 155, in outputfilename
    name = data["programTitle"]
KeyError: 'programTitle'

**Comment by spaam** [comment]
this was fixed in 1.9.4 and you are using 1.9.3.  upgrade and it will work better. thanks for the bug report :)

**Comment by henriksten65** [comment]
Oh, how embarrassing.  Thanks!  I only followed the instructions on https://apt.svtplay-dl.se/ and 1.9.3 was what I got.

**Comment by spaam** [comment]
it seems like you have some other version svtplay-dl installed too.   installed it with setup.py or pip?  if so. does it show up in: `pip list`?  if so `pip uninstall svtplay-dl`
