### ISSUE TITLE
TypeError: __str__ returned non-string (type Error)

### ISSUE THREAD

**Issue by forthrin** [spaam/svtplay-dl#689]
```
$ svtplay-dl --http-header "X-FORWARDED-FOR=176.11.19.180" http://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-1/episode-1
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 477, in main
    get_media(urls[0], options)
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 199, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 231, in get_one_media
    if not filename(stream):
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/output.py", line 128, in filename
    data = ensure_unicode(stream.get_urldata())
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/service/__init__.py", line 31, in get_urldata
    self._urldata = self.http.request("get", self.url).text
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py", line 56, in request
    res = Session.request(self, method, url, verify=self.verify, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 471, in request
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 602, in send
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 176, in resolve_redirects
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 581, in send
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 417, in send
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 355, in _make_request
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 325, in _raise_timeout
TypeError: __str__ returned non-string (type Error)

~$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

$ uname -a
Darwin *.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

$ svtplay-dl --version
1.9.6
```

**Comment by dentarg** [comment]
@forthrin what shell are you using? `echo $SHELL`

**Comment by forthrin** [comment]
I found the cause of the error. By doing `unset PYTHONPATH` the error disappeared. The question now is whether this is a bug in `svtplay-dl` or if my `PYTHONPATH` is incorrectly set or something.

    PYTHONPATH=/usr/local/lib/python2.7/site-packages
