### ISSUE TITLE
Crashes on debian 9

### ISSUE THREAD

**Issue by JimmyElephant** [spaam/svtplay-dl#700]
i get 

> svtplay-dl --verbose --stream-priority=dash,hls https://www.svtplay.se/video/15403417/stephans-klassiker/stephans-klassiker-sasong-1-avsnitt-11
DEBUG [1507138417.04] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/video/15403417/stephans-klassiker/stephans-klassiker-sasong-1-avsnitt-11'
ERROR [1507138417.36] /usr/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: version: 1.9.1
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 459, in main
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 192, in get_media
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 239, in get_one_media
  File "/usr/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 36, in get
KeyError: 'videoTitlePage'

>
it workd to download 2 days ago. not the same url but, maybe im just stupid  :P
i did run the same line on windows and that worked.

**Comment by spaam** [comment]
it works fine with 1.9.6 :)
