### ISSUE TITLE
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

### ISSUE THREAD

**Issue by AliensInc** [spaam/svtplay-dl#701]
ERROR [1507151392.536455] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.6
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 477, in main
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 199, in get_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 247, in get_one_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\svtplay.py", line 76, in get
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\svtplay.py", line 122, in _get_video
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\fetcher\dash.py", line 119, in dashparse
  File "xml\etree\ElementTree.py", line 1334, in XML
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

**Comment by spaam** [comment]
what url did you get this from?

**Comment by AliensInc** [comment]
Oh sorry, missed that:

svtplay-dl.exe -P hls https://www.svtplay.se/video/9809682/varldens-basta-veterinar/varldens-basta-veterinar-special-avsnitt-1 --verbose

**Comment by spaam** [comment]
thanks for the bug report. i will release a new version with this fix on sunday.

**Comment by AliensInc** [comment]
ok, no worries :)
