### ISSUE TITLE
KeyError: '"countryCode"'

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#715]
I get this when i try to download with svtplay-dl 1.9.6-21-g59d2513
```
$ svtplay-dl -A -S -P hls --verbose http://www.dplay.se/trafikpoliserna/
DEBUG [1507677618.86] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.dplay.se/trafikpoliserna/'
DEBUG [1507677618.9] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.dplay.se/api/v2/ajax/shows/16918/seasons/?items=9999999&sort=episode_number_desc&page=0'
INFO [1507677618.97] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_all_episodes: Episode 1 of 1
INFO [1507677618.97] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_all_episodes: Url: http://www.dplay.se/trafikpoliserna/season-1-berusad-man-forsoker-kora-ifran-trafikpoliserna/
DEBUG [1507677618.97] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.dplay.se/trafikpoliserna/season-1-berusad-man-forsoker-kora-ifran-trafikpoliserna/'
DEBUG [1507677619.01] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.dplay.se/api/v2/ajax/videos?video_id=212019'
DEBUG [1507677619.04] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://geo.dplay.se/geo.js'
ERROR [1507677619.07] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: version: 1.9.6-21-g59d2513
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 479, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 199, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 228, in get_all_episodes
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 249, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/dplay.py", line 80, in get
KeyError: '"countryCode"'
```

**Comment by spaam** [comment]
this is from 804b869644cc87a0b759e63bb49b64b03fea1f4d

**Comment by Sopor-** [comment]
What do you mean @spaam? I'm running 1.9.6-22-g328ad0c but i still get the same error :(
