### ISSUE TITLE
ValueError: unmatched '{' in format

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#718]
```
svtplay-dl -A -S -P hls http://www.dplay.se/tunnelbanan
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 479, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 199, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 215, in get_all_episodes
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/dplay.py", line 174, in find_all_episodes
ValueError: unmatched '{' in format
```
svtplay-dl 1.9.6-23-gad94873

**Comment by granbom** [comment]
Line 174 had a closing bracket instead of a curly-brace in the string format. This line will do the trick.
`data = self.http.request("get", "{0}{1}".format(url, n)).text`
