### ISSUE TITLE
ValueError: Input strings must be a multiple of 16 in length

### ISSUE THREAD

**Issue by b0bber** [spaam/svtplay-dl#726]
svtplay-dl crashes when trying to download from viafree.se

```
svtplay-dl -S https://www.viafree.se/program/reality/ensam-mamma-soker/sasong-9/avsnitt-1
INFO: Outfile: ensam-mamma-soker.s09e01-884162-viafree.srt
INFO: Selected to download hls, bitrate: 2482
INFO: Outfile: ensam-mamma-soker.s09e01-884162-viafree.ts
[007/266][=.......................................] ETA: 0:04:13Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 479, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 201, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 323, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/hls.py", line 118, in download
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length
```

Version: 1.9.6-27-g2c2446b

**Comment by spaam** [comment]
this is fixed 2c2446b30b581b..  sorry for no update.  this will be in the next release.
