### ISSUE TITLE
svtplay-dl crashes when trying to download from svtplay.se

### ISSUE THREAD

**Issue by inghal** [spaam/svtplay-dl#727]
$ svtplay-dl -o doctor-foster-2-5.mp4 https://www.svtplay.se/video/15611036/doctor-foster/doctor-foster-sasong-2-avsnitt-5
ERROR: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues
ERROR: Include the URL used, the stack trace and the output of svtplay-dl --version in the issue

$ svtplay-dl --version
0.30.2016.02.08-debian1

$ svtplay-dl -o doctor-foster-2-5.mp4 -v https://www.svtplay.se/video/15611036/doctor-foster/doctor-foster-sasong-2-avsnitt-5
DEBUG [1508841004.46] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/video/15611036/doctor-foster/doctor-foster-sasong-2-avsnitt-5'
DEBUG [1508841004.63] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.svt.se/videoplayer-api/video/1377836-005A'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 352, in main
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 177, in get_media
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 190, in get_one_media
  File "/usr/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 40, in get
  File "/usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py", line 50, in request
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 195, in resolve_redirects
    **adapter_kwargs
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.svt.se', port=443): Max retries exceeded with url: /videoplayer-api/video/1377836-005A (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7feae7279250>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

**Comment by spaam** [comment]
Have you tried using 1.9.6 ? 0.30.2016.02.08 is a bit old :)

**Comment by inghal** [comment]
Have upgraded to 1.9.6. Downloding OK but no sound.

**Comment by spaam** [comment]
did it use dash? if so, did you see a message about `Cant find ffmpeg/avconv. audio and video is in seperate files. if you dont want this use -P hls or hds` ?  if so.  you should install ffmpeg or avconv

**Comment by inghal** [comment]
Have installed ffmpeg. I'm using the following command:
svtplay-dl  -P  hls  -S  -o outfile.mp4  https://link

**Comment by spaam** [comment]
ahh you need to add `--remux` when downloading HLS and saving to a .mp4 file or you can write this by hand on the already downloaded file: ffmpeg -i input.mp4 -map 0:v -map 0:a -c copy -copyts -f mp4 -bsf:a aac_adtstoasc -y output.mp4

**Comment by spaam** [comment]
that command will convert the file from .ts to .mp4 and give it the right audio bitstream that .mp4 need to have.  `--remux` will do it automagic.

**Comment by inghal** [comment]
--remux solved the problem! Thank you very much.
