### ISSUE TITLE
Urskola.se

### ISSUE THREAD

**Issue by TV4Profilen** [spaam/svtplay-dl#731]
Ser att denna site inte är listad men det borde va hyfsat lika urplay

Ser ut som att den laddar ner hög kvalité men den nerladdade filen håller bara runt 1000
och 640*360 i upplösning

Gör jag fel eller är det begränsningar på urskola.se?

svtplay-dl.exe --list-quality https://urskola.se/Produkter/185990-Brev-till-allmanheten
INFO: Quality   Method
INFO: 7268      HLS
INFO: 2985      HLS

d:\down>svtplay-dl.exe -S -q 7268 https://urskola.se/Produkter/185990-Brev-till-allmanheten
INFO: Outfile: brev.till.allmanheten-ur.skola.srt
INFO: Selected to download hls, bitrate: 7268
INFO: Outfile: brev.till.allmanheten-ur.skola.ts
[382/382][================================================================================] ETA: 0:00:00

**Comment by MR-2** [comment]
In this case 7268 is:
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3.1
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 3 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 58 min 36 s
Bit rate                                 : 841 kb/s
Width                                    : 640 pixels
Height                                   : 360 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 25.000 FPS
Minimum frame rate                       : 12.500 FPS
Maximum frame rate                       : 90 000.000 FPS
Standard                                 : PAL
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.146
Stream size                              : 353 MiB (86%)
Color range                              : Limited
and 2985 is: 
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3.1
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 3 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 58 min 36 s
Bit rate mode                            : Variable
Bit rate                                 : 2 201 kb/s
Maximum bit rate                         : 2 499 kb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 25.000 FPS
Minimum frame rate                       : 12.500 FPS
Maximum frame rate                       : 90 000.000 FPS
Standard                                 : PAL
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.096
Stream size                              : 923 MiB (94%)
Color range                              : Limited

**This is a bug that's caused by that the manifest created by UR are specifying the wrong bandwidth however the resolution is correctly specified.**

**Comment by Sopor-** [comment]
svtplay-dl crash when i try to run it

**Comment by Sopor-** [comment]
svtplay-dl crash when i run it:

**Comment by Sopor-** [comment]
svtplay-dl crash when i run it:
```
$ svtplay-dl --list-quality https://urskola.se/Produkter/185990-Brev-till-allmanheten --verbose
DEBUG [1511744897.63] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://urskola.se/Produkter/185990-Brev-till-allmanheten'
DEBUG [1511744897.82] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'//streaming-loadbalancer.ur.se/loadbalancer.json'
ERROR [1511744897.82] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: version: 1.9.6-28-g403f375
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 479, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 201, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 249, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/urplay.py", line 49, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py", line 68, in request
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 443, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 374, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 304, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 358, in prepare_url
    "Perhaps you meant http://{0}?".format(url))
requests.exceptions.MissingSchema: Invalid URL u'//streaming-loadbalancer.ur.se/loadbalancer.json': No schema supplied. Perhaps you meant http:////streaming-loadbalancer.ur.se/loadbalancer.json?
```

**Comment by Sopor-** [comment]
I can download it but it will only be the lower bitrate:
```
$ svtplay-dl -S -P hls https://www.dr.dk/tv/se/oernen-tv/oernen-dk-13-24/oernen-24-24
INFO: Outfile: rnen.iii.88.tv.dr.srt
INFO: Selected to download hls, bitrate: 2381
INFO: Outfile: rnen.iii.88.tv.dr.ts
[024/356][=======.......................................................................................................] ETA: 0:01:50
```
