### ISSUE TITLE
Can't download from Öppet arkiv

### ISSUE THREAD

**Issue by thommym** [spaam/svtplay-dl#736]
Trying to fetch a program from Öppet arkiv at SVT and get this error:

$ svtplay-dl --verbose https://www.oppetarkiv.se/video/2803300/g-som-i-hemlig
DEBUG [1510211832.71] /usr/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.oppetarkiv.se/video/2803300/g-som-i-hemlig'
DEBUG [1510211832.81] /usr/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.svt.se/videoplayer-api/video/1370437-001OA'
Traceback (most recent call last):
  File "/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 352, in main
    get_media(url, options)
  File "/usr/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 177, in get_media
    get_one_media(stream, options)
  File "/usr/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 190, in get_one_media
    for i in streams:
  File "/usr/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 56, in get
    self.options.output = self.outputfilename(dataj, self.options.output, ensure_unicode(self.get_urldata()))
  File "/usr/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 148, in outputfilename
    name = data["programTitle"]
KeyError: 'programTitle'

**Comment by MR-2** [comment]
Which version of svtplay-dl are you using? Seems to be an outdated version.

**Comment by thommym** [comment]
$ svtplay-dl --version
0.30.2016.02.08
The latest for Fedora 26.
I'll try to compile from source.

**Comment by MR-2** [comment]
This ticket can be closed.

**Comment by thommym** [comment]
Yes, by all means.
