### ISSUE TITLE
Can't load the new christmascalander  

### ISSUE THREAD

**Issue by bjornbergdal** [spaam/svtplay-dl#743]
./svtplay-dl --verbose https://www.svtplay.se/video/16017263/julkalendern-jakten-pa-tidskristallen/julkalendern-jakten-pa-tidskristallen-sasong-1-avsnitt-1?tab=sasong1
DEBUG [1512141700.85] ./svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/video/16017263/julkalendern-jakten-pa-tidskristallen/julkalendern-jakten-pa-tidskristallen-sasong-1-avsnitt-1?tab=sasong1'
DEBUG [1512141700.97] ./svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/video/16017263/julkalendern-jakten-pa-tidskristallen/julkalendern-jakten-pa-tidskristallen-sasong-1-avsnitt-1?tab=sasong1'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./svtplay-dl/__main__.py", line 13, in <module>
  File "./svtplay-dl/svtplay_dl/__init__.py", line 345, in main
  File "./svtplay-dl/svtplay_dl/__init__.py", line 176, in get_media
  File "./svtplay-dl/svtplay_dl/__init__.py", line 202, in get_one_media
ValueError: No JSON object could be decoded

**Comment by Sopor-** [comment]
I can download it with -A
```
$ svtplay-dl -A -S -P hls https://www.svtplay.se/julkalendern-jakten-pa-tidskristallen
INFO: Episode 1 of 1
INFO: Url: https://www.svtplay.se/video/16017263/julkalendern-jakten-pa-tidskristallen/julkalendern-jakten-pa-tidskristallen-sasong-1-avsnitt-1
INFO: Outfile: julkalendern.jakten.pa.tidskristallen.s01e01.avsnitt.1-5a117c5-svtplay.srt
INFO: Selected to download hls, bitrate: 2793
INFO: Outfile: julkalendern.jakten.pa.tidskristallen.s01e01.avsnitt.1-5a117c5-svtplay.ts
[11/83][==============................................................................................................] ETA: 0:00:26
```
And i can download a single episode too
```
$ svtplay-dl -S -P hls https://www.svtplay.se/video/16017263/julkalendern-jakten-pa-tidskristallen/julkalendern-jakten-pa-tidskristallen-sasong-1-avsnitt-1
INFO: Outfile: julkalendern.jakten.pa.tidskristallen.s01e01.avsnitt.1-5a117c5-svtplay.srt
INFO: Selected to download hls, bitrate: 2796
INFO: Outfile: julkalendern.jakten.pa.tidskristallen.s01e01.avsnitt.1-5a117c5-svtplay.ts
[08/83][==========....................................................................................................] ETA: 0:00:24
```

**Comment by Sopor-** [comment]
If you use `tab=sasong1` you need to add `-A`, but remember you will have to use the `--exclude` switch to exclude `teckentolkat` and `syntolkat`.

**Comment by bjornbergdal** [comment]
Already tested -A among other:
./svtplay-dl --verbose -A -S -P hls https://www.svtplay.se/julkalendern-jakten-pa-tidskristallen
DEBUG [1512213601.02] ./svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/julkalendern-jakten-pa-tidskristallen'
DEBUG [1512213601.15] ./svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'https://www.svtplay.se/julkalendern-jakten-pa-tidskristallen/rss.xml'
INFO [1512213601.17] ./svtplay-dl/svtplay_dl/__init__.py/get_media: Episode 1 of 2
DEBUG [1512213601.17] ./svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/video/16017263/julkalendern-jakten-pa-tidskristallen/julkalendern-jakten-pa-tidskristallen-sasong-1-avsnitt-1'
DEBUG [1512213601.31] ./svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/video/16017263/julkalendern-jakten-pa-tidskristallen/julkalendern-jakten-pa-tidskristallen-sasong-1-avsnitt-1'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./svtplay-dl/__main__.py", line 13, in <module>
  File "./svtplay-dl/svtplay_dl/__init__.py", line 345, in main
  File "./svtplay-dl/svtplay_dl/__init__.py", line 174, in get_media
  File "./svtplay-dl/svtplay_dl/__init__.py", line 202, in get_one_media
ValueError: No JSON object could be decoded

Single episode:
./svtplay-dl --verbose -S -P hls https://www.svtplay.se/video/16017263/julkalendern-jakten-pa-tidskristallen/julkalendern-jakten-pa-tidskristallen-sasong-1-avsnitt-1
DEBUG [1512213757.62] ./svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/video/16017263/julkalendern-jakten-pa-tidskristallen/julkalendern-jakten-pa-tidskristallen-sasong-1-avsnitt-1'
DEBUG [1512213757.73] ./svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/video/16017263/julkalendern-jakten-pa-tidskristallen/julkalendern-jakten-pa-tidskristallen-sasong-1-avsnitt-1'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./svtplay-dl/__main__.py", line 13, in <module>
  File "./svtplay-dl/svtplay_dl/__init__.py", line 345, in main
  File "./svtplay-dl/svtplay_dl/__init__.py", line 176, in get_media
  File "./svtplay-dl/svtplay_dl/__init__.py", line 202, in get_one_media
ValueError: No JSON object could be decoded

**Comment by Sopor-** [comment]
And you are running latest version or latest master?
```
$ svtplay-dl --version
1.9.6-35-gc26bb3c
```

**Comment by bjornbergdal** [comment]
I thaught I did. I folloved instructions at https://apt.svtplay-dl.se/ ... But just checked no. Have tried to update but nothing have so far worked. Thank you, should have checked version to start with...
