### ISSUE TITLE
Cmore doesn't work

### ISSUE THREAD

**Issue by max204** [spaam/svtplay-dl#744]
This is the error I get:

svtplay-dl --verbose -S -P hls --username= --password= https://www.cmore.se/serie/95194-det-var-en-gang/

DEBUG [1512077225.18] /usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/utils/init.py/request: HTTP getting 'https://www.cmore.se/serie/95194-det-var-en-gang/'
DEBUG [1512077226.27] /usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/utils/init.py/request: HTTP getting 'https://www.cmore.se/login'
DEBUG [1512077226.28] /usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/utils/init.py/request: HTTP getting 'https://account.cmore.se/session?client=web'
DEBUG [1512077226.5] /usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/utils/init.py/request: HTTP getting 'https://www.cmore.se/serie/95194-det-var-en-gang/'
DEBUG [1512077226.96] /usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/utils/init.py/request: HTTP getting 'https://restapi.cmore.se/api/tve_web/asset/3917467/play.json?protocol=VUDASH'
DEBUG [1512077227.21] /usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/utils/init.py/request: HTTP getting 'https://restapi.cmore.se/api/tve_web/asset/3917467.json?expand=metadata'
ERROR [1512077227.32] /usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/init.py/get_one_media: version: 1.9.6
Traceback (most recent call last):
File "/usr/local/bin/svtplay-dl", line 7, in 
svtplay_dl.main()
File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/init.py", line 477, in main
get_media(urls[0], options)
File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/init.py", line 199, in get_media
get_one_media(stream, copy.copy(options))
File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/init.py", line 247, in get_one_media
for i in streams:
File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/service/cmore.py", line 37, in get
basename = self._autoname(match.group(1))
File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/service/cmore.py", line 87, in _autoname
name = "{0}.S{1}E{2:02d}".format(name, season, int(janson["episode"]["$"]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 12: ordinal not in range(128)

**Comment by max204** [comment]
With the new version of svt-play I get the message that it's DRM protected.
That's why it never downloaded.
