### ISSUE TITLE
Crash on viafree.se

### ISSUE THREAD

**Issue by SweDennis** [spaam/svtplay-dl#748]
From one day to the next, without any intermediate windows updates, I'm getting this: 
(Episodes up and untill 18 worked just fine)

C:\Users\Dennis\Desktop\Unsafe>svtplay-dl.exe --verbose --list-quality https://w
ww.viafree.se/program/livsstil/masterchef-usa/sasong-8/avsnitt-19
DEBUG [1513254261.570541] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\ut
ils\__init__.py/request: HTTP getting 'https://www.viafree.se/program/livsstil/m
asterchef-usa/sasong-8/avsnitt-19'
ERROR [1513254263.0837438] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\_
_init__.py/get_one_media: version: 1.9.6
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 4
77, in main
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 1
99, in get_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 2
47, in get_one_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\viaplay.py",
 line 107, in get
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\viaplay.py",
 line 87, in _get_video_id
  File "json\__init__.py", line 319, in loads
  File "json\decoder.py", line 342, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 51322 (char 51321)
Failed to execute script svtplay-dl

In contrast, svtplay.se still works just fine:

C:\Users\Dennis\Desktop\Unsafe>svtplay-dl.exe --list-quality https://www.svtplay
.se/video/16225254/min-sanning/min-sanning-anders-ygeman-sasong-10
INFO: Quality   Method
INFO: 3247      DASH
INFO: 2796      HLS
INFO: 2794      HLS
INFO: 2794      HDS
INFO: 2794      DASH
INFO: 2048      DASH
INFO: 1680      HLS
INFO: 1678      HLS
INFO: 1678      HDS
INFO: 1678      DASH
INFO: 1198      DASH
INFO: 988       HLS
INFO: 986       HLS
INFO: 986       HDS
INFO: 986       DASH
INFO: 715       DASH
INFO: 636       HLS
INFO: 634       HLS
INFO: 634       HDS
INFO: 634       DASH
INFO: 502       DASH
INFO: 456       HLS
INFO: 454       HLS
INFO: 454       HDS
INFO: 454       DASH
INFO: 380       DASH
INFO: 348       HLS
INFO: 346       HLS
INFO: 346       HDS
INFO: 346       DASH
INFO: 261       DASH
INFO: 240       HLS
INFO: 238       HLS
INFO: 238       HDS
INFO: 238       DASH

C:\Users\Dennis\Desktop\Unsafe>

**Comment by bpmildh** [comment]
I get similar error on a basic request:
svtplay-dl --verbose https://www.viafree.se/program/drama/lethal-weapon/sasong-2/avsnitt-9
DEBUG [1513418488.47] /usr/lib/python2.7/dist-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.viafree.se/program/drama/lethal-weapon/sasong-2/avsnitt-9'
ERROR [1513418488.55] /usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9.6
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py", line 477, in main
    get_media(urls[0], options)
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py", line 199, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py", line 247, in get_one_media
    for i in streams:
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/service/viaplay.py", line 107, in get
    vid = self._get_video_id()
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/service/viaplay.py", line 87, in _get_video_id
    janson = json.loads(match.group(1))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 17129 - line 1 column 633413 (char 17128 - 633412)

viafree.se stopped work in youtube-dl too

**Comment by logabug** [comment]
Viafree doesn't work for me either (worked OK less than a week ago thought). I'm running Windows 10.
I tried a lot of different files/pages, e g:

DEBUG [1513515690.603169] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.viafree.se/program/drama/doc-martin/sasong-5/avsnitt-1'
ERROR [1513515691.6604524] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.6
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 477, in main
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 199, in get_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 247, in get_one_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\viaplay.py", line 107, in get
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\viaplay.py", line 87, in _get_video_id
  File "json\__init__.py", line 319, in loads
  File "json\decoder.py", line 342, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 27389 (char 27388)
Failed to execute script svtplay-dl

**Comment by logabug** [comment]
Btw, same error on viafree.dk

**Comment by SweDennis** [comment]
Yeah, seems pretty conclusive that something was changed on the viafree-side. Thanks all for confirming, so far.

**Comment by hamkg** [comment]
Seems as if UWTD suffered from the same problem but managed to offer a solution on Sunday last. So there's hope, and no doubt there will be a new svtplay-dl version coming shortly fixing this issue as soon as spaam can find the time.
