### ISSUE TITLE
https://www.viafree.se nedladdnings problem! :/

### ISSUE THREAD

**Issue by MaistroX** [spaam/svtplay-dl#754]
C:\svtplay-dl>svtplay-dl.exe --verbose -o I:\svtplay-dl -S -M --remux -f https://www.viafree.se/program/reality/unga-mammor/sasong-2/avsnitt-30
DEBUG [1513877395.9115417] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.viafree.se/program/reality/unga-mammor/sasong-2/avsnitt-30
ERROR [1513877396.5365775] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.6
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 477, in main
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 199, in get_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 247, in get_one_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\viaplay.py", line 107, in get
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\viaplay.py", line 87, in _get_video_id
  File "json\__init__.py", line 319, in loads
  File "json\decoder.py", line 342, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 555423 (char 555422)
Failed to execute script svtplay-dl

**Comment by hamkg** [comment]
Already filed as #748

**Comment by spaam** [comment]
good guy @magic75 fixed it in #753 . this will be in 1.9.7 later this week. thanks for the bug report :)
