### ISSUE TITLE
`ERROR: svtplay-dl crashed`

### ISSUE THREAD

**Issue by dakl** [spaam/svtplay-dl#756]
I'm attempting `svtplay-dl "https://www.svtplay.se/video/13423404/octonauterna/octonauterna-sasong-1-avsnitt-11"`  which fails:

```
ERROR: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues
ERROR: Include the URL used, the stack trace and the output of svtplay-dl --version in the issue
```

Adding `--verbose` yields this:

```
DEBUG [1514615193.88] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/video/13423404/octonauterna/octonauterna-sasong-1-avsnitt-11?start=auto'
DEBUG [1514615193.93] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1374573-011A'
DEBUG [1514615193.94] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay3l-f.akamaihd.net/i/se/open/20171214/1374573-011A/PG-1374573-011A-THEOCTONAUTS-01_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1374573-011A_ab612113.m3u8&defaultSubLang=sv'
DEBUG [1514615193.95] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay3l-f.akamaihd.net/i/se/open/20171214/1374573-011A/PG-1374573-011A-THEOCTONAUTS-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_0_av.m3u8?null=0'
DEBUG [1514615193.96] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay3l-f.akamaihd.net/i/se/open/20171214/1374573-011A/PG-1374573-011A-THEOCTONAUTS-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_1_av.m3u8?null=0'
DEBUG [1514615193.97] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay3l-f.akamaihd.net/i/se/open/20171214/1374573-011A/PG-1374573-011A-THEOCTONAUTS-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_2_av.m3u8?null=0'
DEBUG [1514615193.98] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay3l-f.akamaihd.net/i/se/open/20171214/1374573-011A/PG-1374573-011A-THEOCTONAUTS-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_3_av.m3u8?null=0'
DEBUG [1514615193.98] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay3l-f.akamaihd.net/i/se/open/20171214/1374573-011A/PG-1374573-011A-THEOCTONAUTS-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_4_av.m3u8?null=0'
DEBUG [1514615193.99] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay3l-f.akamaihd.net/i/se/open/20171214/1374573-011A/PG-1374573-011A-THEOCTONAUTS-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_5_av.m3u8?null=0'
DEBUG [1514615194.0] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay3l-f.akamaihd.net/i/se/open/20171214/1374573-011A/PG-1374573-011A-THEOCTONAUTS-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_6_av.m3u8?null=0'
DEBUG [1514615194.01] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://switcher.cdn.svt.se/1374573-011A_ab612113.m3u8'
DEBUG [1514615194.03] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://ed6.cdn.svt.se/vod/_definst_/amlst:20171214/1374573-011A/504f18a5-f434-42bc-b69c-f399edc9dcdf/PG-1374573-011A-THEOCTONAUTS-01/playlist.m3u8'
DEBUG [1514615194.04] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed6.cdn.svt.se/vod/_definst_/amlst:20171214/1374573-011A/504f18a5-f434-42bc-b69c-f399edc9dcdf/PG-1374573-011A-THEOCTONAUTS-01/chunklist_b988000_slsv.m3u8'
DEBUG [1514615194.04] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed6.cdn.svt.se/vod/_definst_/amlst:20171214/1374573-011A/504f18a5-f434-42bc-b69c-f399edc9dcdf/PG-1374573-011A-THEOCTONAUTS-01/chunklist_b240000_slsv.m3u8'
DEBUG [1514615194.05] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed6.cdn.svt.se/vod/_definst_/amlst:20171214/1374573-011A/504f18a5-f434-42bc-b69c-f399edc9dcdf/PG-1374573-011A-THEOCTONAUTS-01/chunklist_b348000_slsv.m3u8'
DEBUG [1514615194.05] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed6.cdn.svt.se/vod/_definst_/amlst:20171214/1374573-011A/504f18a5-f434-42bc-b69c-f399edc9dcdf/PG-1374573-011A-THEOCTONAUTS-01/chunklist_b456000_slsv.m3u8'
DEBUG [1514615194.06] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed6.cdn.svt.se/vod/_definst_/amlst:20171214/1374573-011A/504f18a5-f434-42bc-b69c-f399edc9dcdf/PG-1374573-011A-THEOCTONAUTS-01/chunklist_b636000_slsv.m3u8'
DEBUG [1514615194.06] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed6.cdn.svt.se/vod/_definst_/amlst:20171214/1374573-011A/504f18a5-f434-42bc-b69c-f399edc9dcdf/PG-1374573-011A-THEOCTONAUTS-01/chunklist_b1680000_slsv.m3u8'
DEBUG [1514615194.07] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed6.cdn.svt.se/vod/_definst_/amlst:20171214/1374573-011A/504f18a5-f434-42bc-b69c-f399edc9dcdf/PG-1374573-011A-THEOCTONAUTS-01/chunklist_b2796000_slsv.m3u8'
DEBUG [1514615194.07] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay3q-f.akamaihd.net/d/se/open/delivery/20171214/1374573-011A/dash-live/PG-1374573-011A-THEOCTONAUTS-01-799f799b-07ab-4893-af2a-ff1e999115c2-1a894f3d-e7aa-336d-472e-56993a27cd04-live.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1374573-011A_ab612113.mpd'
DEBUG [1514615194.1] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://switcher.cdn.svt.se/1374573-011A_ab612113.mpd'
DEBUG [1514615194.12] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://ed6.cdn.svt.se/vod/_definst_/amlst:20171214/1374573-011A/504f18a5-f434-42bc-b69c-f399edc9dcdf/PG-1374573-011A-THEOCTONAUTS-01/manifest.mpd'
ERROR [1514615194.13] /Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9.4
Traceback (most recent call last):
  File "/Users/danielk/miniconda2/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 466, in main
    get_media(urls[0], options)
  File "/Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 196, in get_media
    get_one_media(stream, copy.copy(options))
  File "/Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 244, in get_one_media
    for i in streams:
  File "/Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 76, in get
    for i in videos:
  File "/Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 130, in _get_video
    streams = dashparse(self.options, self.http.request("get", alt.request.url), alt.request.url)
  File "/Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 61, in dashparse
    videofiles = parsesegments(video, url)
  File "/Users/danielk/miniconda2/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 121, in parsesegments
    for n in time:
TypeError: 'bool' object is not iterable
```

**Comment by dakl** [comment]
I'm  closing this as it was apparently an error on my end. `pip install -U svtplay-dl` helped which is strange since I was already running 1.9.4 but ¯\_(ツ)_/¯ 

```
  Found existing installation: svtplay-dl 1.9.4
    Uninstalling svtplay-dl-1.9.4:
      Successfully uninstalled svtplay-dl-1.9.4
```
