### ISSUE TITLE
svtplay-dl crash on svt play

### ISSUE THREAD

**Issue by thaofus** [spaam/svtplay-dl#757]
Trying this url to download:
svtplay-dl https://www.svtplay.se/video/11831246/det-hemliga-rom/det-hemliga-rom-avsnitt-1

Error: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
with the verbose argument this:

svtplay-dl --verbose https://www.svtplay.se/video/11831246/det-hemliga-rom/det-hemliga-rom-avsnitt-1
DEBUG [1514618524.86] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/video/11831246/det-hemliga-rom/det-hemliga-rom-avsnitt-1'
DEBUG [1514618525.1] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1370904-001A'
DEBUG [1514618525.3] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay12m-f.akamaihd.net/i/se/open/20171227/1370904-001A/PG-1370904-001A-ROMESINVISIBLE-01_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1370904-001A_28780570.m3u8'
DEBUG [1514618525.5] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay12m-f.akamaihd.net/i/se/open/20171227/1370904-001A/PG-1370904-001A-ROMESINVISIBLE-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_0_av.m3u8?null=0'
DEBUG [1514618525.64] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay12m-f.akamaihd.net/i/se/open/20171227/1370904-001A/PG-1370904-001A-ROMESINVISIBLE-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_1_av.m3u8?null=0'
DEBUG [1514618525.76] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay12m-f.akamaihd.net/i/se/open/20171227/1370904-001A/PG-1370904-001A-ROMESINVISIBLE-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_2_av.m3u8?null=0'
DEBUG [1514618525.93] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay12m-f.akamaihd.net/i/se/open/20171227/1370904-001A/PG-1370904-001A-ROMESINVISIBLE-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_3_av.m3u8?null=0'
DEBUG [1514618526.18] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay12m-f.akamaihd.net/i/se/open/20171227/1370904-001A/PG-1370904-001A-ROMESINVISIBLE-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_4_av.m3u8?null=0'
DEBUG [1514618526.3] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay12m-f.akamaihd.net/i/se/open/20171227/1370904-001A/PG-1370904-001A-ROMESINVISIBLE-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_5_av.m3u8?null=0'
DEBUG [1514618526.41] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay12m-f.akamaihd.net/i/se/open/20171227/1370904-001A/PG-1370904-001A-ROMESINVISIBLE-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_6_av.m3u8?null=0'
DEBUG [1514618526.54] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://switcher.cdn.svt.se/1370904-001A_28780570.m3u8'
DEBUG [1514618526.76] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://ed0.cdn.svt.se/vod/_definst_/amlst:20171227/1370904-001A/e7253a38-5da6-4b96-af01-e27ec8e247cf/PG-1370904-001A-ROMESINVISIBLE-01/playlist.m3u8'
DEBUG [1514618526.79] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed0.cdn.svt.se/vod/_definst_/amlst:20171227/1370904-001A/e7253a38-5da6-4b96-af01-e27ec8e247cf/PG-1370904-001A-ROMESINVISIBLE-01/chunklist_b988000_slsv.m3u8'
DEBUG [1514618526.82] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed0.cdn.svt.se/vod/_definst_/amlst:20171227/1370904-001A/e7253a38-5da6-4b96-af01-e27ec8e247cf/PG-1370904-001A-ROMESINVISIBLE-01/chunklist_b240000_slsv.m3u8'
DEBUG [1514618526.84] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed0.cdn.svt.se/vod/_definst_/amlst:20171227/1370904-001A/e7253a38-5da6-4b96-af01-e27ec8e247cf/PG-1370904-001A-ROMESINVISIBLE-01/chunklist_b348000_slsv.m3u8'
DEBUG [1514618526.87] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed0.cdn.svt.se/vod/_definst_/amlst:20171227/1370904-001A/e7253a38-5da6-4b96-af01-e27ec8e247cf/PG-1370904-001A-ROMESINVISIBLE-01/chunklist_b456000_slsv.m3u8'
DEBUG [1514618526.89] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed0.cdn.svt.se/vod/_definst_/amlst:20171227/1370904-001A/e7253a38-5da6-4b96-af01-e27ec8e247cf/PG-1370904-001A-ROMESINVISIBLE-01/chunklist_b636000_slsv.m3u8'
DEBUG [1514618526.91] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed0.cdn.svt.se/vod/_definst_/amlst:20171227/1370904-001A/e7253a38-5da6-4b96-af01-e27ec8e247cf/PG-1370904-001A-ROMESINVISIBLE-01/chunklist_b1680000_slsv.m3u8'
DEBUG [1514618526.93] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed0.cdn.svt.se/vod/_definst_/amlst:20171227/1370904-001A/e7253a38-5da6-4b96-af01-e27ec8e247cf/PG-1370904-001A-ROMESINVISIBLE-01/chunklist_b2796000_slsv.m3u8'
DEBUG [1514618526.95] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay12g-f.akamaihd.net/d/se/open/delivery/20171227/1370904-001A/dash-live/PG-1370904-001A-ROMESINVISIBLE-01-4e6646cc-0ae6-420c-9e5e-fe603dbe3b0f-6f0049ca-a0cf-336d-d7b5-83794cbc6f53-live.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1370904-001A_28780570.mpd'
DEBUG [1514618527.16] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://switcher.cdn.svt.se/1370904-001A_28780570.mpd'
DEBUG [1514618527.23] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://ed0.cdn.svt.se/vod/_definst_/amlst:20171227/1370904-001A/e7253a38-5da6-4b96-af01-e27ec8e247cf/PG-1370904-001A-ROMESINVISIBLE-01/manifest.mpd'
ERROR [1514618527.25] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9.4
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 466, in main
    get_media(urls[0], options)
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 196, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 244, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 76, in get
    for i in videos:
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 130, in _get_video
    streams = dashparse(self.options, self.http.request("get", alt.request.url), alt.request.url)
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 61, in dashparse
    videofiles = parsesegments(video, url)
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 121, in parsesegments
    for n in time:
TypeError: 'bool' object is not iterable

**Comment by spaam** [comment]
@thaofus , your version ( 1.9.4 ) is a bit old. try updating your brew with  `brew update && brew upgrade ` to install 1.9.6. maybe it should fix your issue

**Comment by sjoqvist** [comment]
I have a similar problem, but I've installed the latest package for Ubuntu 17.10. (It works for me on Arch so it's not a huge problem, but I think it's better if the official packages are working.)
```
Package: svtplay-dl
Version: 1.9.4-1
Priority: optional
Section: universe/utils
Origin: Ubuntu
Maintainer: Ubuntu Developers <nospam>
Original-Maintainer: Olof Johansson <nospam>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 94.2 kB
Depends: rtmpdump (>= 2.4), python, python-crypto, python-requests, ffmpeg | libavtools
Homepage: https://github.com/spaam/svtplay-dl
Download-Size: 74.7 kB
APT-Manual-Installed: yes
APT-Sources: http://se.archive.ubuntu.com/ubuntu artful/universe amd64 Packages
Description: program to download videos from video on demand sites
 svtplay-dl is a command line application for downloading videos
 from various video on demand sites (sometimes called "play"
 services). Currently supports some 15+ service, including
 SVTPlay, HBO, twitch.tv, vimeo and many more.
```

**Comment by thaofus** [comment]
Thank´s Johan it worked out fine!

*Vänliga Hälsningar*

*Ulf Brettstam*








2018-01-05 6:36 GMT+01:00 Anders Sjöqvist <notifications@github.com>:

**Comment by saxmark** [comment]
Have tested with MacOSX, Ubuntu, Kali and now finally CentOS, No luck at all..  Cant figure out what i am doing wrong.. 

DEBUG [1518467276.7] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_media: version: 1.9.7
DEBUG [1518467276.73] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/video/16908794/bron/bron-sasong-4-avsnitt-7'
DEBUG [1518467277.05] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://api.svt.se/videoplayer-api/video/1375792-007A'
DEBUG [1518467277.13] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay11r-f.akamaihd.net/z/se/open/20180208/1375792-007A/PG-1375792-007A-BRON4-01_,988,240,348,456,636,1680,2796,.mp4.csmil/manifest.f4m'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 497, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 209, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 257, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 91, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 121, in _get_video
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/hds.py", line 58, in hdsparse
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    return parser.close()
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
[calle@localhost ~]$ svtplay-dl https://www.svtplay.se/video/16908794/bron/bron-sasong-4-avsnitt-7 --verbose --version
1.9.7

**Comment by evildemons** [comment]
@saxmark 

```
svtplay-dl.exe https://www.svtplay.se/video/16908794/bron/bron-sasong-4-avsnitt-7 --remux -S
```
Now I do not know if you run this but if you do it remove it.
"--all-episodes"

It works for me both on Windows and Linux.

**Comment by saxmark** [comment]
Mmm.. Nope.. Didn´t do any difference.. Have tried with -A and tested with --all-episodes now.. Did a Clean run to only get one episode when i posted the first time. But thanks for the effort of sending me an answer though.. Which version are you running @evildeamons ?

**Comment by evildemons** [comment]
@saxmark 

1.9.7

Try driving with. ````sudo```
