### ISSUE TITLE
Failure downloading from SVTplay

### ISSUE THREAD

**Issue by hjoel** [spaam/svtplay-dl#758]
Sorry to bother.

Tried (using version 1.9.6) both with the parameters I normally use
F:\##dl>svtplay-dl -q 1677 -P dash --force https://www.svtplay.se/video/16456670/nyarskonsert-fran-wien/nyarskonsert-fran-wien-1-jan-11-15-1
and got this message:
ERROR: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues
ERROR: Include the URL used, the stack trace and the output of svtplay-dl --version in the issue

I then tried simply with special parameters
F:\##dl>svtplay-dl https://www.svtplay.se/video/16456670/nyarskonsert-fran-wien/nyarskonsert-fran-wien-1-jan-11-15-1
with the same result.

Then adding at your advice
F:\##dl>svtplay-dl --verbose https://www.svtplay.se/video/16456670/nyarskonsert-fran-wien/nyarskonsert-fran-wien-1-jan-11-15-1
which gave:
DEBUG [1514822101.6095831] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.svtplay.se/video/16456670/nyarskonsert-fran-wien/nyarskonsert-fran-wien-1-jan-11-15-1'
DEBUG [1514822102.2386634] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1383179-001A'
DEBUG [1514822102.4761963] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://svt-event-21-b.akamaized.net/se/1383179-001A/manifest.mpd'
ERROR [1514822102.6732178] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.6
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 477, in main
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 199, in get_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 247, in get_one_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\svtplay.py", line 76, in get
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\svtplay.py", line 122, in _get_video
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\fetcher\dash.py", line 122, in dashparse
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\fetcher\dash.py", line 100, in adaptionset
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\fetcher\dash.py", line 38, in templateelemt
AttributeError: 'NoneType' object has no attribute 'findall'
Failed to execute script svtplay-dl

Advice?

Thank you for being there!
/Håkan
hjmercator@gmail.com

**Comment by Sopor-** [comment]
I don't know if this is the same kind of crash but i get this when trying to download Bron:
`svtplay-dl -A -S -P hls https://www.svtplay.se/bron?tab=sasong3`
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 489, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 189, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py", line 115, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py", line 68, in request
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 227, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

```

**Comment by spaam** [comment]
@Sopor- that is a different issue. it looks something in your dists version of python module urllib3

**Comment by Sopor-** [comment]
@spaam I will create a new issie for it
