### ISSUE TITLE
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#759]
svtplay-dl -A -S -P hls https://www.svtplay.se/bron?tab=sasong3
and i get the same if i use
https://www.svtplay.se/bron?tab=sasong4#section-sasong4
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 489, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 189, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py", line 115, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py", line 68, in request
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 227, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
```

**Comment by spaam** [comment]
this is not an issue with svtplay-dl. its looks something in your dists version of python module urllib3 that is a broken.. try upgrading it.

**Comment by Sopor-** [comment]
Why will it fail now? I haven't changed anything and i'm using the same version of svtplay-dl :(

**Comment by Sopor-** [comment]
But you were right. It seems to work now, but i'm still curious why is suddenly fails...

**Comment by Sopor-** [comment]
Now i got this back again..
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 491, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 191, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py", line 115, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py", line 68, in request
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 227, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
```

**Comment by Sopor-** [comment]
I have updated everything and i still get this on svtplay
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 499, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 182, in get_multiple_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 195, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py", line 115, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py", line 68, in request
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 227, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
```
