### ISSUE TITLE
viafree.no downloading not working no more?

### ISSUE THREAD

**Issue by Cissamannen** [spaam/svtplay-dl#761]
Hi,
Trying to download files from viafree.no but I get this error on all media. I tried some from svtplay.se etc and they work flawless. So I added the debug here so you can see. I didnt have this problem in November. But after a reinstall of windows and waiting till now to try again this issue occured. Ive installed svtplay-dl correctly from repository and such since it downloads fine from other sources than viafree.no :/

svtplay-dl --verbose https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-6/episode-1
DEBUG [1514971899.5149765] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-6/episode-1'
ERROR [1514971900.7128012] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.6
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 477, in main
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 199, in get_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 247, in get_one_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\viaplay.py", line 107, in get
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\viaplay.py", line 87, in _get_video_id
  File "json\__init__.py", line 319, in loads
  File "json\decoder.py", line 342, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 154983 (char 154982)
Failed to execute script svtplay-dl

**Comment by crapmaster** [comment]
Most likely the same problem reported in #748.

**Comment by spaam** [comment]
good guy @magic75 fixed it in #753 . this will be in 1.9.7 later this week.  thanks for the bug report
