### ISSUE TITLE
viafree.se error windows 1.9.6

### ISSUE THREAD

**Issue by evildemons** [spaam/svtplay-dl#762]
`N:\>svtplay-dl.exe https://www.viafree.se/program/dokumentar/banged-up-abroad/sa
song-7/avsnitt-10 --remux -S --verbose
DEBUG [1515055568.2421072] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\u
tils\__init__.py/request: HTTP getting 'https://www.viafree.se/program/dokumenta
r/banged-up-abroad/sasong-7/avsnitt-10'
ERROR [1515055568.6551306] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\_
_init__.py/get_one_media: version: 1.9.6
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 4
77, in main
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 1
99, in get_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 2
47, in get_one_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\viaplay.py",
 line 107, in get
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\viaplay.py",
 line 87, in _get_video_id
  File "json\__init__.py", line 319, in loads
  File "json\decoder.py", line 342, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 30017 (char 30016)
Failed to execute script svtplay-dl`

**Comment by spaam** [comment]
this is fixed in master. it will be included 1.9.7 later this week. thanks for the bug report :)

**Comment by evildemons** [comment]
@spaam Will it come out within 14 days?

Want to download them before they remove it.

**Comment by spaam** [comment]
@evildemons most likely on saturday (5/1) or sunday (6/1) this week.

**Comment by evildemons** [comment]
@spaam  Thanks so much.

**Comment by evildemons** [comment]
@spaam What Saturday or Sunday would the new version come out?

**Comment by spaam** [comment]
1.9.7 is out. so this should be fixed now
