### ISSUE TITLE
Viafree.se issue - Cant download sjukhuset from viafree.se

### ISSUE THREAD

**Issue by myowncloudservice** [spaam/svtplay-dl#765]
.\svtplay-dl.exe -v -q 100 -Q 1000 https://www.viafree.se/program/reality/sjukhuset/sasong-6/avsnitt-1
DEBUG [1515380796.6030922] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.viafree.se/program/reality/sjukhuset/sasong-6/avsnitt-1'
ERROR [1515380797.1413913] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.6
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 477, in main
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 199, in get_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 247, in get_one_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\viaplay.py", line 107, in get
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\viaplay.py", line 87, in _get_video_id
  File "json\__init__.py", line 319, in loads
  File "json\decoder.py", line 342, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 60435 (char 60434)
Failed to execute script svtplay-dl

**Comment by evildemons** [comment]
@myowncloudservice https://github.com/spaam/svtplay-dl/issues/762

**Comment by spaam** [comment]
this is fixed in 1.9.7. thanks for the report.
