### ISSUE TITLE
Hjälp med Win 10 och svtplay-dl!!!

### ISSUE THREAD

**Issue by MaistroX** [spaam/svtplay-dl#807]
Haft svtplay-dl på min Windows 7 lääänge och funkat som en klocka, men efter byte till nya komponenter så slutade det med Windows 10 x64 som ett måste tyvärr! :(
Försökt att "installera" svtplay-dl här och få det att funka, men helt OMÖJLIGT....
Finns det någon som kan göra en steg för steg guide för oss på Windows 10 så svtplay-dl kan få fungera även hos "oss"?
Tacksam för all hjälp!

P.S https://svtplay-dl.se/install/ hjälper inte till det funkar och det är otroligt rörigt! :/

**Comment by evildemons** [comment]
@MaistroX 

Kör du den via CMD eller i en bat fil?
Ta gärna en bild så blir det lättare och se hur du har gjort det?

**Comment by MaistroX** [comment]
Kör cmd, samma rad som jag körde i Windows 7 testade jag nu EXAKT på samma sätt i Windows 10 och det funkar inte! 😔

**Comment by MaistroX** [comment]
Ex:
C:\svtplay-dl>svtplay-dl.exe -o I:\svtplay-dl -S -M --remux -f https://www.tv4play.se/program/min-f%C3%B6rst%C3%B6rda-kropp/3663512
Traceback (most recent call last):
  File "P:\Programing\svtplay-dl spamm\svtplay-dl\bin\svtplay-dl", line 7, in <module>
  File "C:\Python35-32\lib\site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 464, in main
  File "C:\Python35-32\lib\site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 194, in get_media
  File "C:\Python35-32\lib\site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 226, in get_one_media
  File "C:\Python35-32\lib\site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\output.py", line 128, in filename
  File "C:\Python35-32\lib\site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\__init__.py", line 31, in get_urldata
AttributeError: 'NoneType' object has no attribute 'text'
Failed to execute script svtplay-dl

**Comment by spaam** [comment]
Du använder 1.9.3.  Kan du testa med 1.9.7 och se om du får samma problem? :)

-- 
Johan Andersson

**Comment by evildemons** [comment]
@MaistroX 

Den som du försöker ladda ner måste man ha ett konto på TV4play.

**Comment by MaistroX** [comment]
Funkade som en klocka att bara uppdatera till 1.9.7! :)

C:\svtplay-dl>svtplay-dl.exe -o I:\svtplay-dl -S -M --remux -f https://www.tv4play.se/program/love-at-first-kiss-sverige/3955072
INFO: Outfile: I:\svtplay-dl\love.at.first.kiss-sverige.s01e21.del.7-3955072-tv4play.srt
INFO: Selected to download hls, bitrate: 4505
INFO: Outfile: I:\svtplay-dl\love.at.first.kiss-sverige.s01e21.del.7-3955072-tv4play.ts
[73/73][====================================================================================================================================================================================================================================================================] ETA: 0:00:00
INFO: Muxing I:\svtplay-dl\love.at.first.kiss-sverige.s01e21.del.7-3955072-tv4play.ts and merging its subtitle into I:\svtplay-dl\love.at.first.kiss-sverige.s01e21.del.7-3955072-tv4play.mp4
INFO: Determining the language of the subtitle.
INFO: Language code: swe
INFO: Muxing done, removing the old file.


Men en förenklad Step By Step med bilder vore kanske på sin plats för de(n) oinvigde att ha på hemsidan iaf.! :)
