### ISSUE TITLE
Dplay crash when we try to download a video from the program url.

### ISSUE THREAD

**Issue by SweDennis** [spaam/svtplay-dl#824]
Hi, 
just tried to download the below, first try since I got the 1.9.9 version, attaching the verbose.
```
C:\Users\Dennis\Desktop\Unsafe>svtplay-dl.exe --list-quality https://www.dplay.se/program/he-lied-about-everything -v
DEBUG [1519632073.537129] site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__
init__.py/get_media: version: 1.9.9
DEBUG [1519632073.5391293] site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\u
tils\__init__.py/request: HTTP getting 'https://www.dplay.se/program/he-lied-abo
ut-everything'
DEBUG [1519632075.1362205] site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\u
tils\__init__.py/request: HTTP getting 'https://disco-api.dplay.se/token?realm=d
playse&deviceId=3e84c247e11701fb5451865acb6262c8495d47c5f397a772a7bc01c9ce9f5b12
&shortlived=true'
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 5
14, in main
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 2
19, in get_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 2
67, in get_one_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\service\dplay.py", l
ine 42, in get
AttributeError: 'NoneType' object has no attribute 'group'
[6744] Failed to execute script svtplay-dl

C:\Users\Dennis\Desktop\Unsafe>
```

**Comment by spaam** [comment]
you need to do this on the actual video and not the program url. `https://www.dplay.se/videos/he-lied-about-everything/he-lied-about-everything`

**Comment by SweDennis** [comment]
D'Oh, Sort of knew that, or Did know, works fine when done right. Close and forget this case. :-D

**Comment by spaam** [comment]
nah its a good case. we should not crash like we did when we try to access something that is not an video and thanks for the bug report :)
