### ISSUE TITLE
Dplay.se - UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 25: ordinal not in range(128)

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#832]
```
$ svtplay-dl -A --exclude=s01,s02,s03,s04,s05,s06,s07,s08 https://www.dplay.se/program/ullared --verbose
DEBUG [1519769652.02] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_media: version: 1.9.9-1-gf1befe0
DEBUG [1519769652.03] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/token?realm=dplayse&deviceId=68e1e435db6ab43fd38ae5df6c6a03b50a5c9c6290f4691e1b670a786c0ebe12&shortlived=true'
DEBUG [1519769652.34] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/content/shows/ullared'
DEBUG [1519769652.41] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/content/videos?include=primaryChannel,show&filter[videoType]=EPISODE&filter[show.id]=278&filter[seasonNumber]=1&page[size]=100&sort=seasonNumber,episodeNumber,-earliestPlayableStart'
DEBUG [1519769652.51] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/content/videos?include=primaryChannel,show&filter[videoType]=EPISODE&filter[show.id]=278&filter[seasonNumber]=2&page[size]=100&sort=seasonNumber,episodeNumber,-earliestPlayableStart'
DEBUG [1519769652.61] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/content/videos?include=primaryChannel,show&filter[videoType]=EPISODE&filter[show.id]=278&filter[seasonNumber]=3&page[size]=100&sort=seasonNumber,episodeNumber,-earliestPlayableStart'
DEBUG [1519769652.71] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/content/videos?include=primaryChannel,show&filter[videoType]=EPISODE&filter[show.id]=278&filter[seasonNumber]=4&page[size]=100&sort=seasonNumber,episodeNumber,-earliestPlayableStart'
DEBUG [1519769652.81] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/content/videos?include=primaryChannel,show&filter[videoType]=EPISODE&filter[show.id]=278&filter[seasonNumber]=5&page[size]=100&sort=seasonNumber,episodeNumber,-earliestPlayableStart'
DEBUG [1519769652.88] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/content/videos?include=primaryChannel,show&filter[videoType]=EPISODE&filter[show.id]=278&filter[seasonNumber]=6&page[size]=100&sort=seasonNumber,episodeNumber,-earliestPlayableStart'
DEBUG [1519769652.96] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/content/videos?include=primaryChannel,show&filter[videoType]=EPISODE&filter[show.id]=278&filter[seasonNumber]=7&page[size]=100&sort=seasonNumber,episodeNumber,-earliestPlayableStart'
DEBUG [1519769653.03] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/content/videos?include=primaryChannel,show&filter[videoType]=EPISODE&filter[show.id]=278&filter[seasonNumber]=8&page[size]=100&sort=seasonNumber,episodeNumber,-earliestPlayableStart'
DEBUG [1519769653.11] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/content/videos?include=primaryChannel,show&filter[videoType]=EPISODE&filter[show.id]=278&filter[seasonNumber]=9&page[size]=100&sort=seasonNumber,episodeNumber,-earliestPlayableStart'
INFO [1519769653.19] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_all_episodes: Episode 1 of 77
INFO [1519769653.19] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_all_episodes: Url: https://www.dplay.se/videos/ullared/ullared-101
DEBUG [1519769653.19] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.dplay.se/videos/ullared/ullared-101'
DEBUG [1519769654.04] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/token?realm=dplayse&deviceId=d6723fa996ced47773f2dea29cce9b11f951e6dafe321a84ac7d32791c3b4660&shortlived=true'
DEBUG [1519769654.32] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/content/videos/ullared/ullared-101'
ERROR [1519769654.39] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: No videos found.
ERROR [1519769654.39] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: Excluding video
INFO [1519769654.4] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_all_episodes: Episode 2 of 77
INFO [1519769654.41] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_all_episodes: Url: https://www.dplay.se/videos/ullared/ullared-102
DEBUG [1519769654.41] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.dplay.se/videos/ullared/ullared-102'
DEBUG [1519769655.21] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/token?realm=dplayse&deviceId=c62510afc57db491f9f993387b76dd9a7d08f09c01326953904b6586c19c4b8a&shortlived=true'
DEBUG [1519769655.5] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/content/videos/ullared/ullared-102'
ERROR [1519769655.57] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: No videos found.
ERROR [1519769655.57] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: Excluding video
INFO [1519769655.58] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_all_episodes: Episode 3 of 77
INFO [1519769655.59] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_all_episodes: Url: https://www.dplay.se/videos/ullared/ullared-103
DEBUG [1519769655.59] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.dplay.se/videos/ullared/ullared-103'
DEBUG [1519769656.39] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/token?realm=dplayse&deviceId=15a26c6fa5151c712acc7ee45a1fd525ab85b801f096847c7d5fdf49efeabb4d&shortlived=true'
DEBUG [1519769656.66] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/content/videos/ullared/ullared-103'
ERROR [1519769656.73] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: No videos found.
ERROR [1519769656.73] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: Excluding video
INFO [1519769656.74] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_all_episodes: Episode 4 of 77
INFO [1519769656.74] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_all_episodes: Url: https://www.dplay.se/videos/ullared/ullared-104
DEBUG [1519769656.74] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.dplay.se/videos/ullared/ullared-104'
DEBUG [1519769657.55] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/token?realm=dplayse&deviceId=23c5910b8b10cfa86e40099cf01e5c2b36f4dd0a903f0c60e5517ea177f4d390&shortlived=true'
DEBUG [1519769657.89] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/content/videos/ullared/ullared-104'
ERROR [1519769657.98] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: No videos found.
ERROR [1519769657.98] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: Excluding video
INFO [1519769658.0] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_all_episodes: Episode 5 of 77
INFO [1519769658.0] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_all_episodes: Url: https://www.dplay.se/videos/ullared/ullared-105
DEBUG [1519769658.0] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.dplay.se/videos/ullared/ullared-105'
DEBUG [1519769658.87] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/token?realm=dplayse&deviceId=12bdc9eedc0abc0dc0f5a4c36836d8bac9a5b78de2e10a4747859a305f6d4535&shortlived=true'
DEBUG [1519769659.18] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://disco-api.dplay.se/content/videos/ullared/ullared-105'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 514, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 217, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 246, in get_all_episodes
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 267, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/dplay.py", line 55, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/dplay.py", line 90, in _autoname
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 25: ordinal not in range(128)
```
svtplay-dl 1.9.9-1-gf1befe0

**Comment by spaam** [comment]
we have a ticket for this  #826

**Comment by spaam** [comment]
closing this . no need for two tickets :)

**Comment by Sopor-** [comment]
I was sure i seen it somewhere but i couldn't find it when i was searching...

**Comment by spaam** [comment]
yes the ticket title is bad  :)
