### ISSUE TITLE
Streams not available to download, both on svtplay and tv4play

### ISSUE THREAD

**Issue by SweDennis** [spaam/svtplay-dl#833]
Hello, beginning to think I have something strange going on with my installation.
I just recently posted a "General usage question" regarding dplay. The answer provided to that one I had already tried, and now I get this, same issue on tv4play and svtplay, and an error message I haven't seen before.

A --list-quality works just fine, but whether I give the below command with a flexible quality, or a specific one, I get the same answer, and I've tried it, as said, both on svtplay, and another program on tv4play. Getting confused. Apologies if I'm just chasing after something local here, and not general issues at all.
```
C:\Users\Dennis\Desktop\Unsafe>svtplay-dl.exe -q 1600 -Q 100 -P HDS https://www.
svtplay.se/video/17119614/kulturfragan-kontrapunkt/kulturfragan-kontrapunkt-saso
ng-2-avsnitt-2 -v

DEBUG [1519883269.8415833] site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\_
_init__.py/get_media: version: 1.9.9
DEBUG [1519883269.8445833] site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\u
tils\__init__.py/request: HTTP getting 'https://www.svtplay.se/video/17119614/ku
lturfragan-kontrapunkt/kulturfragan-kontrapunkt-sasong-2-avsnitt-2'
DEBUG [1519883270.9796484] site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\u
tils\__init__.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/
1379511-002A'
DEBUG [1519883271.0336514] site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\u
tils\__init__.py/request: HTTP getting 'http://svtplay4a-f.akamaihd.net/z/se/ope
n/20180227/1379511-002A/PG-1379511-002A-KULTURFRAGANKON-01_,988,240,348,456,636,
1680,2796,.mp4.csmil/manifest.f4m'
DEBUG [1519883271.1446576] site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\u
tils\__init__.py/request: HTTP getting 'http://switcher.cdn.svt.se/1379511-002A_
329f13e6.mpd'
DEBUG [1519883271.2676647] site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\u
tils\__init__.py/request: HTTP getting 'http://svtplay4m-f.akamaihd.net/d/se/ope
n/delivery/20180227/1379511-002A/dash-live/PG-1379511-002A-KULTURFRAGANKON-01-77
8e1b10-8122-4e11-abd8-d8b3e1261cd5-1a894f3d-36c0-336d-cc4c-b2d8c0006d6a-live.mpd
?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1379511-002A_329f13e6.mpd'
DEBUG [1519883271.8566985] site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\u
tils\__init__.py/request: HTTP getting 'http://ed5.cdn.svt.se/vod/_definst_/amls
t:20180227/1379511-002A/90504f7d-f99a-47f5-870b-52a924cc8538/PG-1379511-002A-KUL
TURFRAGANKON-01/manifest.mpd'
DEBUG [1519883272.0517097] site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\u
tils\__init__.py/request: HTTP getting 'http://switcher.cdn.svt.se/1379511-002A_
329f13e6.m3u8'
DEBUG [1519883272.112713] site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\ut
ils\__init__.py/request: HTTP getting 'http://svtplay4h-f.akamaihd.net/i/se/open
/20180227/1379511-002A/PG-1379511-002A-KULTURFRAGANKON-01_,988,240,348,456,636,1
680,2796,.mp4.csmil/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1379511-0
02A_329f13e6.m3u8&defaultSubLang=sv'
DEBUG [1519883272.1757166] site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\u
tils\__init__.py/request: HTTP getting 'http://ed5.cdn.svt.se/vod/_definst_/amls
t:20180227/1379511-002A/90504f7d-f99a-47f5-870b-52a924cc8538/PG-1379511-002A-KUL
TURFRAGANKON-01/playlist.m3u8'
DEBUG [1519883272.2007182] site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\u
tils\__init__.py/request: HTTP getting 'http://switcher.cdn.svt.se/1379511-002A_
329f13e6.m3u8'
DEBUG [1519883272.2627218] site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\u
tils\__init__.py/protocol_prio: Protocol priority scores (higher is better): {'r
tmp': 1, 'dash': 5, 'hls': 4, 'http': 2, 'hds': 3}
DEBUG [1519883272.2647219] site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\u
tils\__init__.py/request: HTTP getting 'http://svtplay4a-f.akamaihd.net/z/se/ope
n/20180227/1379511-002A/PG-1379511-002A-KULTURFRAGANKON-01_,988,240,348,456,636,
1680,2796,.mp4.csmil/manifest.f4m'
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 5
14, in main
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 2
19, in get_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 3
43, in get_one_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 3
34, in get_one_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\utils\__init__.py",
line 189, in select_quality
svtplay_dl.error.UIException: Streams not available to download.
[7256] Failed to execute script svtplay-dl
```

**Comment by SweDennis** [comment]
Just to add, just tried something on svtplay, and it Works, with no options, but otherwise no. I must be completely blind and doing something wrong...

C:\Users\Dennis\Desktop\Unsafe>svtplay-dl.exe https://www.svtplay.se/video/17119
602/uppdrag-granskning/uppdrag-granskning-avsnitt-13-3
INFO: Selected to download dash, bitrate: 3337
INFO: Outfile: uppdrag.granskning.fallet.christer.pettersson.del.5.palmegruppens
.hemligheter-91a8682-svtplay.m4a
[020/308][==......................................] ETA: 0:00:12

C:\Users\Dennis\Desktop\Unsafe>svtplay-dl.exe https://www.svtplay.se/video/17119
602/uppdrag-granskning/uppdrag-granskning-avsnitt-13-3 -P hds -q 1600 -Q 100
ERROR: Streams not available to download.

C:\Users\Dennis\Desktop\Unsafe>svtplay-dl.exe https://www.svtplay.se/video/17119
602/uppdrag-granskning/uppdrag-granskning-avsnitt-13-3 --list-quality
INFO: Quality   Method
INFO: 3337      DASH
INFO: 2796      HLS
INFO: 2794      DASH
INFO: 2793      HLS
INFO: 2793      HDS
INFO: 1959      DASH
INFO: 1680      HLS
INFO: 1678      DASH
INFO: 1677      HLS
INFO: 1677      HDS
INFO: 1148      DASH
INFO: 988       HLS
INFO: 986       DASH
INFO: 985       HLS
INFO: 985       HDS
INFO: 739       DASH
INFO: 636       HLS
INFO: 634       DASH
INFO: 633       HLS
INFO: 633       HDS
INFO: 525       DASH
INFO: 456       HLS
INFO: 454       DASH
INFO: 453       HLS
INFO: 453       HDS
INFO: 397       DASH
INFO: 348       HLS
INFO: 346       DASH
INFO: 345       HLS
INFO: 345       HDS
INFO: 270       DASH
INFO: 240       HLS
INFO: 238       DASH
INFO: 237       HLS
INFO: 237       HDS

C:\Users\Dennis\Desktop\Unsafe>

**Comment by SweDennis** [comment]
Now it's getting somewhat interesting... adding -P hds is the fail... perhaps it's not me after all...

C:\Users\Dennis\Desktop\Unsafe>svtplay-dl.exe --list-quality https://www.oppetar
kiv.se/video/2896326/kanal-22-avsnitt-1-av-6 -q 985
INFO: Quality   Method
INFO: 2794      HLS
INFO: 2794      HDS
INFO: 1678      HLS
INFO: 1678      HDS
INFO: 985       HLS
INFO: 985       HDS
INFO: 634       HLS
INFO: 634       HDS
INFO: 454       HLS
INFO: 454       HDS
INFO: 346       HLS
INFO: 346       HDS
INFO: 238       HLS
INFO: 238       HDS

C:\Users\Dennis\Desktop\Unsafe>svtplay-dl.exe  https://www.oppetarkiv.se/video/2
896326/kanal-22-avsnitt-1-av-6 -q 985
INFO: Selected to download hls, bitrate: 985
INFO: Outfile: kanal.22.e01-aa6a5cf-svtplay.ts
ERROR: File (kanal.22.e01-aa6a5cf-svtplay.ts) already exists. Use --force to ove
rwrite
WARNING: Cant find ffmpeg/avconv. File may be unplayable.

C:\Users\Dennis\Desktop\Unsafe>svtplay-dl.exe  https://www.oppetarkiv.se/video/2
896326/kanal-22-avsnitt-1-av-6 -q 985 -f
INFO: Selected to download hls, bitrate: 985
INFO: Outfile: kanal.22.e01-aa6a5cf-svtplay.ts
[003/165][........................................] ETA: 0:01:11

C:\Users\Dennis\Desktop\Unsafe>svtplay-dl.exe  https://www.oppetarkiv.se/video/2
896326/kanal-22-avsnitt-1-av-6 -q 985 -f -P hds
ERROR: Streams not available to download.

C:\Users\Dennis\Desktop\Unsafe>
