### ISSUE TITLE
[7908] Failed to execute script svtplay-dl

### ISSUE THREAD

**Issue by david8704** [spaam/svtplay-dl#835]
recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 514, in main
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 217, in get_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 246, in get_all_episodes
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 340, in get_one_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\fetcher\hls.py", line 113, in download
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\fetcher\hls.py", line 175, in _download
  File "site-packages\Crypto\Cipher\blockalgo.py", line 295, in decrypt
ValueError: Input strings must be a multiple of 16 in length
[7908] Failed to execute script svtplay-dl

**Comment by spaam** [comment]
for what url did you get this? :)

**Comment by david8704** [comment]
File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 514, in main
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 217, in get_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 246, in get_all_episodes
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 340, in get_one_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\fetcher\hls.py", line 113, in download
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\fetcher\hls.py", line 175, in _download
  File "site-packages\Crypto\Cipher\blockalgo.py", line 295, in decrypt
ValueError: Input strings must be a multiple of 16 in length
[7908] Failed to execute script svtplay-dl

C:\Users\Fujitsu Siemens>svtplay-dl -A --force -q 1200 -Q 500 https://www.dplay.se/program/vagens-hjaltar

URL is in this case: https://www.dplay.se/program/vagens-hjaltar

**Comment by david8704** [comment]
Thanks for a great app!

**Comment by spaam** [comment]
what file of those 28 did it fail on?  thanks :)

**Comment by david8704** [comment]
In this case, the second one...

**Comment by david8704** [comment]
But different times, it hangs on different files...

**Comment by david8704** [comment]
INFO: Outfile: vagens-hjaltar.s01e02.en.bil.star.i.lagor-2934-dplay.m4a
[253/253][================================================================================] ETA: 0:00:00
INFO: Outfile: vagens-hjaltar.s01e02.en.bil.star.i.lagor-2934-dplay.mp4
[033/253][==========......................................................................] ETA: 0:00:35Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 514, in main
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 217, in get_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 246, in get_all_episodes
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 340, in get_one_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\fetcher\hls.py", line 113, in download
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\fetcher\hls.py", line 175, in _download
  File "site-packages\Crypto\Cipher\blockalgo.py", line 295, in decrypt
ValueError: Input strings must be a multiple of 16 in length
[7908] Failed to execute script svtplay-dl

**Comment by david8704** [comment]
Now it worked. Sorry for taking your time. Tried many times before I wrote.

**Comment by spaam** [comment]
really strange it failes random at different times :)
