### ISSUE TITLE
1.9.9 seems not to like UNC paths - error in path

### ISSUE THREAD

**Issue by BoneheadFraggle** [spaam/svtplay-dl#836]
In version 1.9.6 and several previous versions I have always used this syntax:

svtplay-dl.exe -P hls -o "\\NAS01\Media\TV-Serier\<name of show>\S01E01" url.

For example:
svtplay-dl.exe -P hls -o "\\NAS01\Media\TV-Serier\Gåsmamman\S01E01" https://www.dplay.se/videos/gasmamman/gasmamman-101

In version 1.9.9 the script seems to add double backslashes in the UNC path and fails:

C:\Temp>svtplay-dl.exe -P hls -o "\\NAS01\Media\TV-Serier\Gåsmamman\S01E01" https://www.dplay.se/videos/gasmamman/gasmamman-101
<RequestsCookieJar[]>
INFO: Selected to download hls, bitrate: 6533
INFO: Outfile: \\NAS01\Media\TV-Serier\Gåsmamman\S01E01.m4a
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 514, in main
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 219, in get_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 340, in get_one_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\fetcher\hls.py", line 112, in download
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\fetcher\hls.py", line 131, in _download
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\output.py", line 167, in output
FileNotFoundError: [Errno 2] No such file or directory: **'\\\\NAS01\\Media\\TV-Serier\\Gåsmamman\\S01E01.m4a**'
**[2064] Failed to execute script svtplay-dl**

If I store the file locally, it works fine:

svtplay-dl.exe -S -P hls -o "C:\TEMP\S01E01" https://www.dplay.se/videos/gasmamman/gasmamman-101 --force
<RequestsCookieJar[]>
INFO: Outfile: C:\TEMP\S01E01.srt
ERROR: File (C:\TEMP\S01E01.srt) already exists. Use --force-subtitle to overwrite
INFO: Selected to download hls, bitrate: 6533
INFO: Outfile: C:\TEMP\S01E01.m4a
[266/266][====================================================================================================] ETA: 0:00:00
INFO: Outfile: C:\TEMP\S01E01.mp4
[266/266][====================================================================================================] ETA: 0:00:00
**INFO: Merge audio and video into C:\TEMP\S01E01.mp4
INFO: Merging done, removing old files.**

**Comment by Sopor-** [comment]
UNC paths you need to start with `\\server\drive\folder`. It works perfect for me with svtplay-dl.exe

**Comment by BoneheadFraggle** [comment]
It seems as the formatting gets crippled when the post is saved. I'll try again:

C:\Temp>svtplay-dl.exe -P hls -o "\\NAS01\Media\TV-Serier\Gåsmamman\S01E01" https://www.dplay.se/videos/gasmamman/gasmamman-101
<RequestsCookieJar[]>
INFO: Selected to download hls, bitrate: 6533
INFO: Outfile: \\NAS01\Media\TV-Serier\Gåsmamman\S01E01.m4a
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 514, in main
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 219, in get_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 340, in get_one_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\fetcher\hls.py", line 112, in download
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\fetcher\hls.py", line 131, in _download
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\output.py", line 167, in output
FileNotFoundError: [Errno 2] No such file or directory: '\\\\NAS01\\Media\\TV-Serier\\Gåsmamman\\S01E01.m4a'
[2064] Failed to execute script svtplay-dl

**Comment by BoneheadFraggle** [comment]
hmm.. i'll post a picture instead:
![screenshot](https://user-images.githubusercontent.com/2287810/36911691-976326ce-1e44-11e8-85d1-a28ed273e854.png)

**Comment by Sopor-** [comment]
Ohh, one of the backslashes disappear when you not using ` around the path.

**Comment by Sopor-** [comment]
Could it be the Swedish char `å`?

**Comment by BoneheadFraggle** [comment]
Nope, it works with å if I save it locally (first post).

**Comment by spaam** [comment]
In The picture its four \ and not two.   Might be a issue. 

-- 
Johan Andersson

**Comment by Sopor-** [comment]
Yes, but your NAS is not using Windows, right?

**Comment by Sopor-** [comment]
Now i got it. The last S01E01 is a folder that not exists or some of the other folder is not there. You need to verify that that path exists.

**Comment by Sopor-** [comment]
This works perfect:
```
svtplay-dl -P hls -o "\\osmc\Movies\Gasmamman\S01E01" https://www.dplay.se/videos/gasmamman/gasmamman-101
<RequestsCookieJar[]>
INFO: Selected to download hls, bitrate: 6533
INFO: Outfile: \\osmc\Movies\Gasmamman\S01E01.m4a
[049/266][============..........................................................] ETA: 0:00:18
```
But if i delete the folder `Gasmamman` and i run it again i get this:
```
svtplay-dl -P hls -o "\\osmc\Movies\Gasmamman\S01E01" https://www.dplay.se/videos/gasmamman/gasmamman-101
<RequestsCookieJar[]>
INFO: Selected to download hls, bitrate: 6533
INFO: Outfile: \\osmc\Movies\Gasmamman\S01E01.m4a
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 514, in main
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 219, in get_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 340, in get_one_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\fetcher\hls.py", line 112, in download
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\fetcher\hls.py", line 131, in _download
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\output.py", line 167, in output
FileNotFoundError: [Errno 2] No such file or directory: '\\\\osmc\\Movies\\Gasmamman\\S01E01.m4a'
[2052] Failed to execute script svtplay-dl
```

**Comment by BoneheadFraggle** [comment]
No, it's not that. S01E01 is the filename (usually I use S01E01.mp4, but since this file is in two parts and gets muxed together after download it fails if I enter .mp4 (both parts is then downloaded to s01e01.mp4..) Again, when I use the exact same syntax locally, it works.

**But you were right - it is the Swedish character.**
I have used åäö previously, that's why I was so certain.

UNC works fine without Å
C:\Temp>svtplay-dl.exe -S -P hls -o "\\NAS01\Media\TEMP\S01E01" https://www.dplay.se/videos/gasmamman/gasmamman-101 --force
<RequestsCookieJar[]>
INFO: Outfile: \\NAS01\Media\TEMP\S01E01.srt
INFO: Selected to download hls, bitrate: 6533
INFO: Outfile: \\NAS01\Media\TEMP\S01E01.m4a
[266/266][====================================================================================================] ETA: 0:00:00
INFO: Outfile: \\NAS01\Media\TEMP\S01E01.mp4
[266/266][====================================================================================================] ETA: 0:00:00
INFO: Merge audio and video into \\NAS01\Media\TEMP\S01E01.mp4
INFO: Merging done, removing old files.

C:\Temp>

And C: doesn't work with Å:
C:\Temp>svtplay-dl.exe -S -P hls -o "C:\TEMP\Gåsmamman\S01E01" https://www.dplay.se/videos/gasmamman/gasmamman-101 --force
<RequestsCookieJar[]>
INFO: Outfile: C:\TEMP\Gåsmamman\S01E01.srt
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 514, in main
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 219, in get_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 318, in get_one_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 313, in options_subs_dl
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\subtitle\__init__.py", line 58, in download
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\subtitle\__init__.py", line 62, in save_file
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\output.py", line 167, in output
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\TEMP\\Gåsmamman\\S01E01.srt'
[13248] Failed to execute script svtplay-dl

C:\Temp>

**Comment by BoneheadFraggle** [comment]
Closing issue - maybe another will be opened regarding "Download to folder containing Swedish character doesn't work".

**Comment by Sopor-** [comment]
But do you have created a folder called `Gåsmamman` @BoneheadFraggle ? If i don't do that i get the above crash.

**Comment by BoneheadFraggle** [comment]
Yep. But it crashes anyway. But if I rename it to Gasmamman it works fine.

**Comment by Sopor-** [comment]
Those international chars are not the same in Windows and Linux, so i avoid using them as much as i can, same as space.

**Comment by spaam** [comment]
i cant reproduce this on windows 10 with the directory `gåsmannen` local and on a unc path.

**Comment by Sopor-** [comment]
If you use a path that doesn't exists you will get that crash. Did you save the video file on Linux @spaam? I believe you can't use Windows to try to save the file on a NAS that run Linux OS (or similar).
If you want i can try with Gåsmamman?

**Comment by Sopor-** [comment]
It worked, but try to use a name that wont exists.. I tried to save to a nonexisting folder (i misspelled Gåsmamman as you can see) and now i get the crash.
```
svtplay-dl -P hls -o "\\osmc\Movies\Gåsmaman\S01E01" https://www.dplay.se/videos/gasmamman/gasmamman-101
<RequestsCookieJar[]>
INFO: Selected to download hls, bitrate: 6533
INFO: Outfile: \\osmc\Movies\Gåsmaman\S01E01.m4a
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 514, in main
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 219, in get_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\__init__.py", line 340, in get_one_media
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\fetcher\hls.py", line 112, in download
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\fetcher\hls.py", line 131, in _download
  File "site-packages\svtplay_dl-1.9.9-py3.5.egg\svtplay_dl\output.py", line 167, in output
FileNotFoundError: [Errno 2] No such file or directory: '\\\\osmc\\Movies\\Gåsmaman\\S01E01.m4a'
[15272] Failed to execute script svtplay-dl
```

**Comment by spaam** [comment]
i get the same issue here when `gåsmamman` does not exists.  🤔

**Comment by spaam** [comment]
i see the issue.  we only create the dir if you use `-A` .  without it we will use it as a filename.
