### ISSUE TITLE
ValueError: Input strings must be a multiple of 16 in length

### ISSUE THREAD

**Issue by b0bber** [spaam/svtplay-dl#848]
Hey.. Got some issues with the latest ver.

`svtplay-dl -S https://www.dplay.se/videos/far-vi-folja-med/far-vi-folja-med-107
INFO: Outfile: far-vi-folja-med.s01e07.midsommar.i.eslov-643-dplay.srt
INFO: Selected to download hls, bitrate: 6554
INFO: Outfile: far-vi-folja-med.s01e07.midsommar.i.eslov-643-dplay.m4a
[264/264][========================================] ETA: 0:00:00
INFO: Outfile: far-vi-folja-med.s01e07.midsommar.i.eslov-643-dplay.mp4
[051/264][=======.................................] ETA: 0:02:26
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 512, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 217, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 338, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/hls.py", line 115, in download
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/hls.py", line 179, in _download
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in `length`

`svtplay-dl --version
1.9.9-9-g8b3a5da

python --version
Python 2.7.12
`

I tried using Python 3.6 but then it wanted pycrypto for downloading hls-streams, and it  from what I can google its not compatible with 3.6?

**Comment by spaam** [comment]
great i can reproduce the issue :)

**Comment by spaam** [comment]
bah. it worked one time, maybe this pycrypto is buggy and we need to replace it with something better

**Comment by MR-2** [comment]
@spaam [pycryptodome](https://github.com/Legrandin/pycryptodome)?

**Comment by spaam** [comment]
@MR-2 yes. make a ticket about that #850
