### ISSUE TITLE
is this crash new or already reported?

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#851]
svtplay-dl 1.9.9-15-g735ba01
```
INFO: Url: https://www.dplay.se/videos/vagens-hjaltar/vagens-hjaltar-401
INFO: Outfile: vagens-hjaltar.s04e01.en.bil.har.lagt.av.mitt.i.fredagsrusningen-42327-dplay.srt
ERROR: File (vagens-hjaltar.s04e01.en.bil.har.lagt.av.mitt.i.fredagsrusningen-42327-dplay.srt) already exists. Use --force-subtitle to overwrite
INFO: Selected to download hls, bitrate: 6533
INFO: Outfile: vagens-hjaltar.s04e01.en.bil.har.lagt.av.mitt.i.fredagsrusningen-42327-dplay.audio.ts
[253/253][==============================================================================================================] ETA: 0:00:00
INFO: Outfile: vagens-hjaltar.s04e01.en.bil.har.lagt.av.mitt.i.fredagsrusningen-42327-dplay.ts
ERROR: File (vagens-hjaltar.s04e01.en.bil.har.lagt.av.mitt.i.fredagsrusningen-42327-dplay.ts) already exists. Use --force to overwrite
INFO: Merge audio and video into vagens-hjaltar.s04e01.en.bil.har.lagt.av.mitt.i.fredagsrusningen-42327-dplay.ts
ERROR: Something went wrong: ffmpeg version 3.2.10-1~deb9u1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
vagens-hjaltar.s04e01.en.bil.har.lagt.av.mitt.i.fredagsrusningen-42327-dplay.ts: No such file or directory
INFO: Merging done, removing old files.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 511, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 215, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 244, in get_all_episodes
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 354, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/postprocess/__init__.py", line 201, in merge
OSError: [Errno 2] No such file or directory: 'vagens-hjaltar.s04e01.en.bil.har.lagt.av.mitt.i.fredagsrusningen-42327-dplay.ts'
```

**Comment by Sopor-** [comment]
it was a dupe of #849 ...
