### ISSUE TITLE
KeyError: 'cookies'

### ISSUE THREAD

**Issue by Ragvald** [spaam/svtplay-dl#858]
When I download from http://sverigesradio.se/p4live I get  this error on version 1.9.10:

svtplay-dl http://sverigesradio.se/sida/avsnitt/1027854
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3.6/site-packages/svtplay_dl/__init__.py", line 511, in main
    get_media(urls[0], options)
  File "/usr/lib/python3.6/site-packages/svtplay_dl/__init__.py", line 217, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/lib/python3.6/site-packages/svtplay_dl/__init__.py", line 332, in get_one_media
    stream = select_quality(options, videos)
  File "/usr/lib/python3.6/site-packages/svtplay_dl/utils/__init__.py", line 186, in select_quality
    res = http.get(stream_hash[w].url, cookies=stream_hash[w].kwargs["cookies"])
KeyError: 'cookies'

It works on version 1.9.7. I've tried 1.9.8 and 1.9.9 and they also fails with the same error.

**Comment by spaam** [comment]
thanks for the bug report. this will be included in the next release :)
