### ISSUE TITLE
Crash in dashparse because we parse the date wrong in some cases.

### ISSUE THREAD

**Issue by MickeMannen** [spaam/svtplay-dl#872]
Hi!

--Version-- 1.9.11

Trying to download rapport from svtplay... here is the output with --verbose
Url: https://www.svtplay.se/video/17322070/rapport/rapport-16-mar-19-30-3

MacBookMicke:Downloads mikael$ ./svtplay-dl --verbose https://www.svtplay.se/video/17322070/rapport/rapport-16-mar-19-30-3
DEBUG [1521253212.16] ./svtplay-dl/svtplay_dl/__init__.py/get_media: version: 1.9.11
DEBUG [1521253212.17] ./svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/video/17322070/rapport/rapport-16-mar-19-30-3'
DEBUG [1521253215.55] ./svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://api.svt.se/videoplayer-api/video/1382988-065A'
DEBUG [1521253216.46] ./svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'https://svt-event-78-a.akamaized.net/world/1382988-065A/manifest.mpd?defaultSubLang=1'
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./svtplay-dl/__main__.py", line 13, in <module>
  File "./svtplay-dl/svtplay_dl/__init__.py", line 511, in main
  File "./svtplay-dl/svtplay_dl/__init__.py", line 217, in get_media
  File "./svtplay-dl/svtplay_dl/__init__.py", line 265, in get_one_media
  File "./svtplay-dl/svtplay_dl/service/svtplay.py", line 92, in get
  File "./svtplay-dl/svtplay_dl/service/svtplay.py", line 129, in _get_video
  File "./svtplay-dl/svtplay_dl/fetcher/dash.py", line 162, in dashparse
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data 'PT25M4S' does not match format 'PT%HH%MM%S.%fS'

Not sure what goes wrong! Same issue for Aktuellt from yesterday too

**Comment by MickeMannen** [comment]
Added a check in dashparse as a workaround.... don't know if there are any side affects to this change.

        if "mediaPresentationDuration" in xml.attrib:
            mediaPresentationDuration = xml.attrib["mediaPresentationDuration"]
            **if re.search("PT[0-9]+H[0-9]+M[0-9]+S.[0-9]+S]",mediaPresentationDuration) is not None:**
                dt = datetime.strptime(mediaPresentationDuration, 'PT%HH%MM%S.%fS')
                duration_sec = (dt - datetime(1900, 1, 1)).total_seconds()
