### ISSUE TITLE
ValueError: time data 'PT44M3.2S' does not match format 'PT%HH%MM%S.%fS'

### ISSUE THREAD

**Issue by AliensInc** [spaam/svtplay-dl#885]
C:\Programs\svtplay-dl>svtplay-dl.exe --verbose -P hls https://www.svtplay.se/video/17725239/agenda/agenda-29-apr-21-15-1?start=auto
DEBUG [1525034043.0267882] site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\__init__.py/get_media: version: 1.9.11
DEBUG [1525034043.0297887] site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.svtplay.se/video/17725239/agenda/agenda-29-apr-21-15-1?start=auto'
DEBUG [1525034043.96095] site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1382948-015A'
DEBUG [1525034044.0099597] site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://svt-event-45-a.akamaized.net/world/1382948-015A/manifest.mpd?defaultSubLang=1'
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\__init__.py", line 511, in main
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\__init__.py", line 217, in get_media
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\__init__.py", line 265, in get_one_media
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\service\svtplay.py", line 92, in get
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\service\svtplay.py", line 129, in _get_video
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\fetcher\dash.py", line 162, in dashparse
  File "_strptime.py", line 510, in _strptime_datetime
  File "_strptime.py", line 343, in _strptime
ValueError: time data 'PT44M3.2S' does not match format 'PT%HH%MM%S.%fS'
[5516] Failed to execute script svtplay-dl

I also that got that 'virus'-warning when DLing the latest version since 'my' version hade the same error as shown above.

**Comment by dalgr** [comment]
Same as #872

**Comment by AliensInc** [comment]
So no fix for it?
Right now I use the windows version so I can't add the fix of #872

**Comment by AliensInc** [comment]
OK, I'll get it on Linux then :)
thx
