### ISSUE TITLE
Downloading from cmore.fi does not work

### ISSUE THREAD

**Issue by teepean** [spaam/svtplay-dl#886]
Note: I am using version 1.9.11-7-g346b40d

I noticed that svtplay-dl had cmore.fi in supported domains and decided to test it. Downloading doesn't work but produces the following output. Any ideas? There is an option to choose an operator but I have no idea what to use as an argument.

~$ svtplay-dl --verbose  -u xxx@xxx -p xxxxx -S https://www.cmore.fi/ohjelma/33200062/seinfeld/892980/1-pilotti
DEBUG [1525187855.98] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_media: version: 1.9.11-7-g346b40d
DEBUG [1525187855.98] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.cmore.fi/ohjelma/33200062/seinfeld/892980/1-pilotti'
DEBUG [1525187856.3] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'https://www.cmore.fi/login'
DEBUG [1525187856.71] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'https://account.cmore.fi/session?client=cmore-web-prod'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 511, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 217, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 265, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/cmore.py", line 24, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/cmore.py", line 143, in _login
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py", line 68, in request
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='account.cmore.fi', port=443): Max retries exceeded with url: /session?client=cmore-web-prod (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f92dbbd9610>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by anddilolz** [comment]
svtplay-dl --verbose -u **@l** -p **** -S https://www.cmore.fi/ohjelma/44002111/mr-mercedes
```
DEBUG [1527089564.8109057] site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\__init__.py/get_media: version: 1.9.11
DEBUG [1527089564.8119063] site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.cmore.fi/ohjelma/44002111/mr-mercedes'
DEBUG [1527089565.279756] site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.cmore.fi/login'
DEBUG [1527089565.6136508] site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://account.cmore.fi/session?client=cmore-web-prod'
Traceback (most recent call last):
  File "site-packages\urllib3\connection.py", line 141, in _new_conn
  File "site-packages\urllib3\util\connection.py", line 60, in create_connection
  File "socket.py", line 732, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 346, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
  File "site-packages\urllib3\connection.py", line 284, in connect
  File "site-packages\urllib3\connection.py", line 150, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x03AD7110>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 440, in send
  File "site-packages\urllib3\connectionpool.py", line 668, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 668, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 668, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 668, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 668, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 639, in urlopen
  File "site-packages\urllib3\util\retry.py", line 388, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='account.cmore.fi', port=443): Max retries exceeded with url: /session?client=cmore-web-prod (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03AD7110>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\__init__.py", line 511, in main
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\__init__.py", line 217, in get_media
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\__init__.py", line 265, in get_one_media
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\service\cmore.py", line 24, in get
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\service\cmore.py", line 143, in _login
  File "site-packages\requests\sessions.py", line 555, in post
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\utils\__init__.py", line 68, in request
  File "site-packages\requests\sessions.py", line 508, in request
  File "site-packages\requests\sessions.py", line 618, in send
  File "site-packages\requests\adapters.py", line 508, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='account.cmore.fi', port=443): Max retries exceeded with url: /session?client=cmore-web-prod (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03AD7110>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
[5900] Failed to execute script svtplay-dl
```

I'm getting the following aswell when trying to download from cmore.fi

**Comment by qnorsten** [comment]
Cmore.fi do not seem to use the same api as the other cmore site. So a rewrite is needed to make it work. 
In the meantime it is probably good to remove cmore.fi from the supported site list.

**Comment by anddilolz** [comment]
> Cmore.fi do not seem to use the same api as the other cmore site. So a rewrite is needed to make it work.
> In the meantime it is probably good to remove cmore.fi from the supported site list.

Thanks for the reply! Too bad they don't share the same api. Could svtplay-dl somehow decrypt the files from cmore.fi if I could download them manually?
