### ISSUE TITLE
weird

### ISSUE THREAD

**Issue by junologue** [spaam/svtplay-dl#889]
Whenever I try to use svtplay-dl this happens.
Have tried to uninstall svtplay, home-brew, and python completely and reinstall.
maybe I have missed to delete something

Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 511, in main
    get_media(urls[0], options)
  File "/usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 217, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 249, in get_one_media
    if not filename(stream):
  File "/usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/svtplay_dl/output.py", line 127, in filename
    data = ensure_unicode(stream.get_urldata())
  File "/usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/svtplay_dl/service/__init__.py", line 32, in get_urldata
    self._urldata = self.http.request("get", self.url).text
  File "/usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py", line 68, in request
    res = Session.request(self, method, url, verify=self.verify, proxies=self.proxy, *args, **kwargs)
  File "/usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.tv4play.se', port=443): Max retries exceeded with url: /program/robinson/3962618 (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))

**Comment by dalgr** [comment]
Have you tried to run:
```
sudo -H pip install -U pip
sudo -H pip uninstall svtplay-dl
sudo -H pip install svtplay-dl
```

Then run, and post the output:
```
which svtplay-dl
svtplay-dl "https://www.svtplay.se/video/17725059/han-designade-den-amerikanska-drommen" -fv
```
