### ISSUE TITLE
URplay.se   no longer works

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#897]
Symptoms
- SVTplay-dl crashes, a verbose log shows an SSL-error "SSL: CERTIFICATE_VERIFY_FAILED"
- The error is both for new items and for item that previously could be fetched
- The same streams can be viewed via Firefox
- an example link with failure: https://urplay.se/program/204765-udda-platser-i-varlden-fagelbo-till-middag
I'm using version 1.9.11

**Comment by MR-2** [comment]
Could bypass by using the flag " --dont-verify-ssl-cert" i.e

**Comment by pythonuser3856** [comment]
Sorry, I missed that option. The workaround is functional.
Thanks !

**Comment by spaam** [comment]
big chance this might be because you are using an old version of python. older than 2.7.9

**Comment by pythonuser3856** [comment]
As far as I can see I'm running Python 3.5.3

**Comment by noob403** [comment]
Can someone help a noob:
I trying to download this but all I get is the following what is I am missing?  

svtplay-dl -S -M -v https://urplay.se/program/206678-iran-inifran-hundar-forbjudna

DEBUG [1544049959.356322] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1544049959.3580658] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/__init__.py/__init__: service: urplay
DEBUG [1544049959.358159] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://urplay.se/program/206678-iran-inifran-hundar-forbjudna'
DEBUG [1544049959.36914] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): urplay.se:443
DEBUG [1544049959.520318] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://urplay.se:443 "GET /program/206678-iran-inifran-hundar-forbjudna HTTP/1.1" 200 17894
DEBUG [1544049959.526109] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming-loadbalancer.ur.se/loadbalancer.json'
DEBUG [1544049959.528803] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): streaming-loadbalancer.ur.se:443
DEBUG [1544049959.66236] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://streaming-loadbalancer.ur.se:443 "GET /loadbalancer.json HTTP/1.1" 200 None
DEBUG [1544049959.6641212] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming4.ur.se/urplay/_definst_/mp4:se/206000-206999/206678-11.mp4/playlist.m3u8'
DEBUG [1544049959.667653] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): streaming4.ur.se:443
DEBUG [1544049959.8729239] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://streaming4.ur.se:443 "GET /urplay/_definst_/mp4:se/206000-206999/206678-11.mp4/playlist.m3u8 HTTP/1.1" 200 235
DEBUG [1544049959.87625] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming4.ur.se/urplay/_definst_/mp4:se/206000-206999/206678-4.mp4/playlist.m3u8'
DEBUG [1544049959.949319] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://streaming4.ur.se:443 "GET /urplay/_definst_/mp4:se/206000-206999/206678-4.mp4/playlist.m3u8 HTTP/1.1" 200 235
DEBUG [1544049959.9515378] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://undertexter.ur.se/206000-206999/206678-16.vtt'
DEBUG [1544049959.955057] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): undertexter.ur.se:443
DEBUG [1544049960.100322] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://undertexter.ur.se:443 "GET /206000-206999/206678-16.vtt HTTP/1.1" 200 16719
INFO [1544049960.130612] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/output.py/output: Outfile: iran.inifran.hundar.forbjudna-ur.play-urplay.srt
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 58, in get_media
    get_one_media(stream)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 176, in get_one_media
    options_subs_dl(subfixes)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 171, in options_subs_dl
    subs[0].download()
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/subtitle/__init__.py", line 73, in download
    self.save_file(data, "srt")
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/subtitle/__init__.py", line 79, in save_file
    file_d = output(self.output, self.config, subtype, mode="wt")
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/output.py", line 199, in output
    if findexpisode(output, os.path.dirname(os.path.realpath(name)), os.path.basename(name)):
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/output.py", line 225, in findexpisode
    name.find(output["id"]) > 0 and lsname.find(output["id"]) > 0 and \
TypeError: must be str, not NoneType

**Comment by Sopor-** [comment]
@noob403 Try latest [master](https://ci.appveyor.com/api/buildjobs/hnxs008g16owwhll/artifacts/svtplay-dl.zip) and it will work.

**Comment by noob403** [comment]
I am on MAC OS 10.9 I dont how to use the file though, but thanks anyway

**Comment by Sopor** [comment]
I have used MAC OS for about 10 minutes in my whole life. Today i installed MAC OS in Vmware on my Windows 10. After installing MAC OS i was thinking of installing svtplay-dl to see how hard or easy it is and i have to say it was very easy. In Windows i never manage to compile it and in Linux I was forced to struggle a bit but in MAC OS it was so easy so a 10 years old kid should be able to do it.

So to all MAC OS user, if you don't want to wait for a release of svtplay-dl try to compile it by yourself. You only need to follow these steps [here](https://svtplay-dl.se/install/source/)
