### ISSUE TITLE
TV4Play - AttributeError: 'Tv4play' object has no attribute 'options'

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#899]
```
$ svtplay-dl -A -S https://www.tv4play.se/program/gws-mord --verbose
version: 1.9.11-95-g72af4ff
DEBUG [1526859293.482028] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 1.9.11-95-g72af4ff
DEBUG [1526859293.4898448] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1526859293.4924307] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://webapi.tv4play.se/play/video_assets?type=episode&is_live=false&platform=web&node_nids=gws-mord&per_page=99999'
DEBUG [1526859293.5020308] /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): webapi.tv4play.se
DEBUG [1526859293.534637] /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py/_make_request: http://webapi.tv4play.se:80 "GET /play/video_assets?type=episode&is_live=false&platform=web&node_nids=gws-mord&per_page=99999 HTTP/1.1" 200 3002
DEBUG [1526859293.5435019] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: tv4play
Episode 1 of 5
INFO [1526859293.544101] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_all_episodes: Episode 1 of 5
Url: http://www.tv4play.se/program/gws-mord?video_id=3960703
INFO [1526859293.544773] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_all_episodes: Url: http://www.tv4play.se/program/gws-mord?video_id=3960703
DEBUG [1526859293.5455263] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://www.tv4play.se/program/gws-mord?video_id=3960703'
DEBUG [1526859293.5512395] /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): www.tv4play.se
DEBUG [1526859293.5799344] /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py/_make_request: http://www.tv4play.se:80 "GET /program/gws-mord?video_id=3960703 HTTP/1.1" 301 20
DEBUG [1526859293.5876863] /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se
DEBUG [1526859293.6917582] /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/gws-mord?video_id=3960703 HTTP/1.1" 301 None
DEBUG [1526859293.7035728] /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py/_get_conn: Resetting dropped connection: www.tv4play.se
DEBUG [1526859293.8173556] /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/gws-mord/3960703 HTTP/1.1" 200 9755
DEBUG [1526859293.8259797] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://prima.tv4play.se/api/web/asset/3960703/play'
DEBUG [1526859293.83147] /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): prima.tv4play.se
DEBUG [1526859293.9499214] /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py/_make_request: http://prima.tv4play.se:80 "GET /api/web/asset/3960703/play HTTP/1.1" 200 3606
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 61, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 52, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 83, in get_all_episodes
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 104, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/tv4play.py", line 75, in get
AttributeError: 'Tv4play' object has no attribute 'options'
```

**Comment by Sopor-** [comment]
On Dplay i get `AttributeError: 'Options' object has no attribute 'all_last'`

**Comment by dalgr** [comment]
Do you get the same problem with python 2.7?

**Comment by spaam** [comment]
@dalgr this errors are from python3 rewrite that is in master now. 

@Sopor- i cant reproduce the Dplay thing.   tv4 is fixed

**Comment by Sopor-** [comment]
Now i get
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 61, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 52, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 83, in get_all_episodes
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 178, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/hls.py", line 119, in download
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/hls.py", line 136, in _download
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/output.py", line 180, in output
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/output.py", line 210, in findexpisode
TypeError: Can't convert 'NoneType' object to str implicitly
```

**Comment by Sopor-** [comment]
Sorry @spaam, it was viafree and not Dplay:
```
$ svtplay-dl -A -S https://www.viafree.se/program/drama/advokaten
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 61, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 52, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 70, in get_all_episodes
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/viaplay.py", line 199, in find_all_episodes
AttributeError: 'Options' object has no attribute 'all_last'
```

**Comment by spaam** [comment]
@Sopor-  what tv4 video have that issue?   viaplay thing. please open a new ticket for that kind of things  next time. this title of this issue say "tv4play..."

**Comment by Sopor-** [comment]
Viafree issue moved here #900

**Comment by Sopor-** [comment]
Yes, i get `TypeError: Can't convert 'NoneType' object to str implicitly` on TV4 after your fix.

**Comment by spaam** [comment]
this is fixed in master
