### ISSUE TITLE
Viafree - AttributeError: 'Options' object has no attribute 'all_last'

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#900]
```
$ svtplay-dl -A -S https://www.viafree.se/program/drama/advokaten
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 61, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 52, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 70, in get_all_episodes
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/viaplay.py", line 199, in find_all_episodes
AttributeError: 'Options' object has no attribute 'all_last'
````
svtplay-dl 1.9.11-101-g81e327e

**Comment by spaam** [comment]
this is fixed in master
