### ISSUE TITLE
ImportError: No module named parse (master)

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#906]
Instead of a crash it would be nice if it could tell the user they should use python 3 when trying to install:
```
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    import svtplay_dl
  File "/home/osmc/svtplay-dl/lib/svtplay_dl/__init__.py", line 10, in <module>
    from svtplay_dl.utils.getmedia import get_media, get_multiple_media
  File "/home/osmc/svtplay-dl/lib/svtplay_dl/utils/getmedia.py", line 7, in <module>
    from svtplay_dl.service import service_handler, Generic
  File "/home/osmc/svtplay-dl/lib/svtplay_dl/service/__init__.py", line 7, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse
```

**Comment by spaam** [comment]
it looks like you used python(2) to install and not python3.

**Comment by Sopor-** [comment]
@spaam Yes i know, but to prevent new issues you should add some kind of message that they need to use python 3 and not python 2.

**Comment by spaam** [comment]
this is fixed in master and it will crash.
