### ISSUE TITLE
Problem with TV4Play

### ISSUE THREAD

**Issue by drzenon** [spaam/svtplay-dl#916]
svtplay-dl.1.9.11.exe --all-subtitles --raw-subtitles --verbose https://www.tv4play.se/program/sj%C3%B6lyckan/3960590
DEBUG [1528997835.6591475] site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\__init__.py/get_media: version: 1.9.11
DEBUG [1528997835.6601474] site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.tv4play.se/program/sj%C3%B6lyckan/3960590'
DEBUG [1528997836.0561702] site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://prima.tv4play.se/api/web/asset/3960590/play'
Traceback (most recent call last):
  File "site-packages\urllib3\connection.py", line 141, in _new_conn
  File "site-packages\urllib3\util\connection.py", line 60, in create_connection
  File "socket.py", line 732, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 357, in _make_request
  File "http\client.py", line 1106, in request
  File "http\client.py", line 1151, in _send_request
  File "http\client.py", line 1102, in endheaders
  File "http\client.py", line 934, in _send_output
  File "http\client.py", line 877, in send
  File "site-packages\urllib3\connection.py", line 166, in connect
  File "site-packages\urllib3\connection.py", line 150, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x029F1370>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 440, in send
  File "site-packages\urllib3\connectionpool.py", line 668, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 668, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 668, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 668, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 668, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 639, in urlopen
  File "site-packages\urllib3\util\retry.py", line 388, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='prima.tv4play.se', port=80): Max retries exceeded with url: /api/web/asset/3960590/play (Caused by NewConnectionError('<u
rllib3.connection.HTTPConnection object at 0x029F1370>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\__init__.py", line 511, in main
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\__init__.py", line 217, in get_media
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\__init__.py", line 265, in get_one_media
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\service\tv4play.py", line 52, in get
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\utils\__init__.py", line 68, in request
  File "site-packages\requests\sessions.py", line 508, in request
  File "site-packages\requests\sessions.py", line 618, in send
  File "site-packages\requests\adapters.py", line 508, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='prima.tv4play.se', port=80): Max retries exceeded with url: /api/web/asset/3960590/play (Caused by NewConnectionError(
'<urllib3.connection.HTTPConnection object at 0x029F1370>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))
[4896] Failed to execute script svtplay-dl

svtplay-dl.1.9.11.exe --version
1.9.11

**Comment by drejjmit** [comment]
@spaam Are you going to update windows .exe (currently 1.9.11)?

**Comment by JohnnyJorgensen** [comment]
@spaam - I agree with drejjmit. If the Tv4Play problem is solved, a new Windows exe would be really nice! :-D
BTW Thanks a lot for all the good work you're doing with svtplay-dl!

**Comment by spaam** [comment]
this is fixed in master and it will be part of the 2.0 release. 

@drejjmit need to do some testing and after that i will release 2.0. hopefully tomorrow or friday.
