### ISSUE TITLE
can not fetch from tv4play

### ISSUE THREAD

**Issue by snix47** [spaam/svtplay-dl#918]
Windows version 1.9.11 does not fetch from tv4play, they must have changed code 14 days ago or so.

svtplay-dl.exe --version
1.9.11

svtplay-dl.exe -S --remux --verbose https://www.tv4play.se/program/sveriges-yngsta-mästerkock/3970984
DEBUG [1529427856.9114347] site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\__init__.py/get_media: version: 1.9.11
DEBUG [1529427856.9134333] site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.tv4play.se/program/sveriges-yngsta-mästerkock/3970984'
DEBUG [1529427857.17627] site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://prima.tv4play.se/api/web/asset/3970984/play'
Traceback (most recent call last):
  File "site-packages\urllib3\connection.py", line 141, in _new_conn
  File "site-packages\urllib3\util\connection.py", line 60, in create_connection
  File "socket.py", line 732, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 357, in _make_request
  File "http\client.py", line 1106, in request
  File "http\client.py", line 1151, in _send_request
  File "http\client.py", line 1102, in endheaders
  File "http\client.py", line 934, in _send_output
  File "http\client.py", line 877, in send
  File "site-packages\urllib3\connection.py", line 166, in connect
  File "site-packages\urllib3\connection.py", line 150, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x041409F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 440, in send
  File "site-packages\urllib3\connectionpool.py", line 668, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 668, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 668, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 668, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 668, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 639, in urlopen
  File "site-packages\urllib3\util\retry.py", line 388, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='prima.tv4play.se', port=80): Max retries exceeded with url: /api/web/asset/3970984/play (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x041409F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\__init__.py", line 511, in main
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\__init__.py", line 217, in get_media
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\__init__.py", line 265, in get_one_media
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\service\tv4play.py", line 52, in get
  File "site-packages\svtplay_dl-1.9.11-py3.5.egg\svtplay_dl\utils\__init__.py", line 68, in request
  File "site-packages\requests\sessions.py", line 508, in request
  File "site-packages\requests\sessions.py", line 618, in send
  File "site-packages\requests\adapters.py", line 508, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='prima.tv4play.se', port=80): Max retries exceeded with url: /api/web/asset/3970984/play (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x041409F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
[22612] Failed to execute script svtplay-dl

**Comment by drejjmit** [comment]
youtube-dl can still do tv4play. Hope svtplay-dl finds a way to fix it.
