### ISSUE TITLE
bambuser no longer working

### ISSUE THREAD

**Issue by theseal** [spaam/svtplay-dl#924]
Seems like the bambuser service changed something to the backend which broke `svtplay-dl`.
The old api host can no longer be resolved:
```
$ host player-c.api.bambuser.com
Host player-c.api.bambuser.com not found: 3(NXDOMAIN)
```

Output when running `svtplay-dl` against bambuser.com:
```
$ svtplay-dl https://bambuser.com/v/6931506 --verbose
DEBUG [1530722448.5] /usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_media: version: 1.9.11
DEBUG [1530722448.5] /usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://bambuser.com/v/6931506'
DEBUG [1530722449.5] /usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://player-c.api.bambuser.com/getVideo.json?api_key=005f64509e19a868399060af746a00aa&vid=6931506'
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 511, in main
    get_media(urls[0], options)
  File "/usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 217, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 265, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/svtplay_dl/service/bambuser.py", line 28, in get
    data = self.http.request("get", json_url).text
  File "/usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py", line 68, in request
    res = Session.request(self, method, url, verify=self.verify, proxies=self.proxy, *args, **kwargs)
  File "/usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/svtplay-dl/1.9.11/libexec/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='player-c.api.bambuser.com', port=80): Max retries exceeded with url: /getVideo.json?api_key=005f64509e19a868399060af746a00aa&vid=6931506 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f618790>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
```

Let me know if there is any more information I can provide to help this issue.
```
$ svtplay-dl --version
1.9.11
```

**Comment by spaam** [comment]
i thought bambuser shutdown some time ago? i cant find any videos on their site now =/

**Comment by theseal** [comment]
I didn't know, but you are right!
Here is the announcement: https://go.bambuser.com/shutdown-announcement
The service should have been shutdown 31/05/2018 but seems to kinda working even now. But I can see that there is no point try to fix so that `svtplay-dl`still works.

Should we close this issue or use it to remove the legacy code?
