### ISSUE TITLE
No subtitles in tv4play.se

### ISSUE THREAD

**Issue by epikuren** [spaam/svtplay-dl#930]
I have succeeded installing svtplay-dl 2.0. in Ubuntu bash on Windows 10. It works well with tv4play.se, but I cannot download any subtitles. Is it possible to fix this?

**Comment by spaam** [comment]
what happens when you download it? does it crash? nothing happen? do you have an url? :)

**Comment by epikuren** [comment]
Är svenska ok?
Om jag försöker ladda ner med:
 svtplay-dl -S https://www.tv4play.se/program/sweetbitter/10315175

får jag följande resultat:

INFO: Starting new HTTPS connection (1): www.tv4play.se
INFO: Starting new HTTPS connection (1): playback-api.b17g.net
INFO: Starting new HTTPS connection (1): lbs-usp-hls-vod.cmore.se
INFO: Starting new HTTPS connection (1): cmoreseusphlsvod63.akamaized.net
INFO: Starting new HTTPS connection (1): cmoreseusphlsvod15.akamaized.net
INFO: Starting new HTTPS connection (1): lbs-usp-hls-vod.cmore.se
INFO: Starting new HTTPS connection (1): cmoreseusphlsvod18.akamaized.net
...
INFO: Starting new HTTPS connection (1): cmoreseusphlsvod55.akamaized.net
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 63, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 56, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 157, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 152, in options_subs_dl
  File "/usr/local/bin/svtplay-dl/svtplay_dl/subtitle/__init__.py", line 58, in download
  File "/usr/local/bin/svtplay-dl/svtplay_dl/subtitle/__init__.py", line 277, in wrstsegment
IndexError: list index out of range

Det går bra att ladda ner utan undertexter, men jag behöver dem..
Uppskattar annars möjligheten att ladda ner TV4-program, eftersom jag avskyr tv-reklam...

**Comment by Sopor-** [comment]
Undertextproblemet är väl redan nämt i #925 så detta är inget nytt problem med 2.0.

**Comment by JohnnyJorgensen** [comment]
I have the same problem. Also get the index out of range error. None of the subtitle switches seem to work with TV4Play.

**Comment by ottob** [comment]
I ran into the same issue today:
```shell
$ ./svtplay-dl -S https://www.tv4play.se/program/the-young-pope/3970075
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./svtplay-dl/__main__.py", line 13, in <module>
  File "./svtplay-dl/svtplay_dl/__init__.py", line 63, in main
  File "./svtplay-dl/svtplay_dl/utils/getmedia.py", line 56, in get_media
  File "./svtplay-dl/svtplay_dl/utils/getmedia.py", line 157, in get_one_media
  File "./svtplay-dl/svtplay_dl/utils/getmedia.py", line 152, in options_subs_dl
  File "./svtplay-dl/svtplay_dl/subtitle/__init__.py", line 58, in download
  File "./svtplay-dl/svtplay_dl/subtitle/__init__.py", line 277, in wrstsegment
IndexError: list index out of range
```

**Comment by Sopor-** [comment]
@spaam Could [this](https://github.com/glut23/webvtt-py) be useful for the TV4 subtitle issue?

**Comment by Sopor-** [comment]
How it is possible that svtplay-dl now suddenly can download webvtt from TV4?
`https://lbs-usp-hls-vod.cmore.se/vod/4d529/mbd2a3emm33(3971715_ISMUSP).ism/mbd2a3emm33(3971715_ISMUSP)-textstream_swe=3000-1.webvtt`
So when i downloaded [Parlamentet](https://www.tv4play.se/program/parlamentet-valspecial-2018/3971715) i got an SRT subtitle file.

**Comment by JohnnyJorgensen** [comment]
Really interesting. Parlamentet worked for me too, but I tried downloading JUST the subtitle, and it took a REALLY long time before anything happened. But I got the SRT file.

**Comment by Sopor-** [comment]
Add `-verbose` and you will see how it is downloading small part of the subtitle. Yes, it will take about 25 seconds to download only the subtitle but that is much better than no subtitle at all.

**Comment by Sopor-** [comment]
@JohnnyJorgensen did you noticed any quality issues in `Parlamentet`? For me i get lag in the video. I will do some more testing.

**Comment by JohnnyJorgensen** [comment]
@Sopor- Now that you mention it. It's not a lot, but the video doesn't seem to play 100% smoothly.
For some time now, I've had problems with VLC, it doesn't play correctly and once in a while it crashes all together. Haven't had time to investigate that problem, though. But in this case I even tested with Windows Media Player, and that one didn't play smoothly either... :-(
If it has any impact on the problem, I'm using the ffmpeg version that Bengt-H mentioned in thread #925.

**Comment by epikuren** [comment]
I still don't get any subtitles. And I don't understand how to download by using "webvtt ". For the moment I pay for Cmore with TV4 programs, so the problem for me is solved - but for a price...
But if someone could be kind enough to tell me what exact command to write if I, for example, want to download "https://www.tv4play.se/program/parlamentet/3209953" WITH subtitles (or only the subtitle), I would be very grateful.

**Comment by Sopor-** [comment]
@epikuren To download the subtitle you need to use latest [master](https://ci.appveyor.com/api/buildjobs/dk9j9hs9pd3nke6m/artifacts/svtplay-dl.zip)
If you want to download both the video and the subtitle
`svtplay-dl -S https://www.tv4play.se/program/parlamentet/3209953`
If you only want to download the subtitle
`svtplay-dl -S --force-subtitle https://www.tv4play.se/program/parlamentet/3209953`
It will take up to 60 seconds to get the subtitle (it converts the webvtt to srt) so don't abort it if you think is has got stuck.

**Comment by epikuren** [comment]
Yes, it seems to work sometimes, sometimes not.  I got the same error when downloading that particular show, even if I tried to download subs separately. But with antoher show
- svtplay-dl -S https://www.tv4play.se/program/younger/10026711 - it worked fine.
Would be interesting if someone had a theory about why it just works sometimes.
If you cannot be sure getting subtitles - and you need them -  the application is not so useful.

**Comment by JohnnyJorgensen** [comment]
> If you cannot be sure getting subtitles - and you need them - the application is not so useful.

You could try look at it from the perspective that *nothing* is fool proof and be grateful for what you DO get?

Remember that the good developers of this application are doing this for free and on their own time...

**Comment by OldSchool297** [comment]
I know how to get subtitles from Hem till gården past summer because they changed from webvtt to streaming subtitles. I have all subtitles from 2015 to 2017 autumn. I also have the most from 2013-2014. I miss from autumn 2017 to spring 2018. If anyone has them we can make a trade? Sadly i can't download them with the swedish program uwtd. Is there any other program that can download the new streaming subtitles?

**Comment by Sopor-** [comment]
@OldSchool297 You can use svtplay-dl but you need latest master. Note: It looks like nothing happens when it downloads the subtitle but that it because there is no progress indicator.

**Comment by OldSchool297** [comment]
I get a message about: The program can't start because api-ms-win-crt-stdio-l1-1-0.dll is missing from your computer. 

hpsu: Do you follow Hem till gården everyday? Because i miss some subtitles, i have some if you may miss some.

**Comment by OldSchool297** [comment]
Do i need to install Svtplay-dl in Windows 7? I have the folder but i only get the error message as i wrote earlier. https://svtplay-dl.se/install/source/

**Comment by Sopor-** [comment]
@OldSchool297 To solve the missing dll file you should be able to fix that with [Microsoft Visual C++ 2015 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=52685) and if you can't get svtplay-dl 2.1 to work you can always download latest master. Follow this [video](https://ufile.io/kq3q2) on how to download an already compiled version for Windows. To compile svtplay-dl in Windows from source is not so easy.

**Comment by OldSchool297** [comment]
I have now installed http://m.majorgeeks.com/content/page/install_all_the_microsoft_c_runtimes_at_once_with_visual_c_runtime_installer.html but i get the same error message. I have these Visual c++ http://www.imagebam.com/image/3643f11104401014 I run an antique computer with an old 1,9ghz processor that can't install Win 8 even so maybe it's to old to run Svtplay-dl?

**Comment by OldSchool297** [comment]
You had right it was the 2015 runtime, it never got fully installed, i had to remove the 2017 first to install 2015, Svtplay-dl now open and loads some texts and then close quit. Does it work by Command prompt like Youtube-dl?

**Comment by OldSchool297** [comment]
Has got Svtplay-dl to work and it should be able to download from Tv4. C: svtplay-dl svtplay-dl.exe -o I: svtplay-dl -S -M --remux -f https://www.tv4play.se/program/ home-t ... 5rden / 11832356 gets up: Merge susbtitle needs ffmpeg. Where to install it? In svtplay folder?

Have downloaded the latest ffmpeg and run setx /M PATH "C:\svtplay-dl\ffmpeg\bin;%PATH%" but get the same message about ffmpeg.

https://www.wdiaz.org/how-to-install-ffmpeg-on-windows/

In system it looks like this: C:\svtplay-dl\ffmpeg\bin;C:\Windows\system32;C:\Windows;C:\Wi ndows\System32\Wbem;C:\Windows\System32\WindowsPow erShell\v1.0" 

It looks like this under System in Win 7: http://www.imagebam.com/image/c977af1106423894

**Comment by Sopor-** [comment]
Yes, that is already reported #1038

**Comment by OldSchool297** [comment]
Thank you, can anyone download subtitle from? https://www.tv4play.se/program/hem-till-g%C3%A5rden/11832356

**Comment by OldSchool297** [comment]
Any other program that can download subtitle from Tv4? The program m3u8_dl can download but it can't work on my computer.
