### ISSUE TITLE
Problem downloading from svtplay

### ISSUE THREAD

**Issue by KGBGit** [spaam/svtplay-dl#939]
hello, got this message when I tried to download Poldark.

KGBMacPro:~ ketil$ svtplay-dl https://www.svtplay.se/video/18744498/poldark/poldark-sasong-3-avsnitt-5?start=auto
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 11, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 7, in <module>
ImportError: No module named 'yaml'

What have I done wrong?

**Comment by KGBGit** [comment]
Found out that my version of svtplay-dl is 1.9.11, how can I install 2.0??

**Comment by MR-2** [comment]
@KGBGit "ImportError: No module named 'yaml'"
This issue can also be closed

**Comment by spaam** [comment]
you need to install pyyaml

**Comment by KGBGit** [comment]
Done, works perfect.

Thank you.

K
