### ISSUE TITLE
viafree crash ValueError: invalid literal for int() with base 10:

### ISSUE THREAD

**Issue by spaam** [spaam/svtplay-dl#941]
```
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3/dist-packages/svtplay_dl/__init__.py", line 63, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 56, in get_media
    get_one_media(stream)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 105, in get_one_media
    for i in streams:
  File "/usr/lib/python3/dist-packages/svtplay_dl/service/viaplay.py", line 144, in get
    self._autoname(dataj)
  File "/usr/lib/python3/dist-packages/svtplay_dl/service/viaplay.py", line 276, in _autoname
    episode = int(episode)
ValueError: invalid literal for int() with base 10: 'Time-Police 2'
```
https://www.viafree.se/program/humor/superjail/sasong-1/961240
svtplay-dl 2.0

**Comment by Sopor-** [comment]
Same here: https://www.viafree.se/program/dokumentar/tv3-dokumentar/sasong-1/972387
