### ISSUE TITLE
viafree.se = Works .... tv4play.se = Does Not! Why, help!

### ISSUE THREAD

**Issue by MaistroX** [spaam/svtplay-dl#945]
C:\svtplay-dl-2>svtplay-dl.exe -o F:\svtplay-dl -S -M --remux -f https://www.viafree.se/program/reality/geordie-shore/sasong-17/avsnitt-11
INFO: Outfile: F:\svtplay-dl\geordie-shore.s17e11-963995-viaplay.srt
INFO: Selected to download hls, bitrate: 2516
INFO: Outfile: F:\svtplay-dl\geordie-shore.s17e11-963995-viaplay.ts
[264/264][========================================================================================================================================================================================================] ETA: 0:00:00
Muxing F:\svtplay-dl\geordie-shore.s17e11-963995-viaplay.ts and merging its subtitle into F:\svtplay-dl\geordie-shore.s17e11-963995-viaplay.mp4
INFO: Muxing F:\svtplay-dl\geordie-shore.s17e11-963995-viaplay.ts and merging its subtitle into F:\svtplay-dl\geordie-shore.s17e11-963995-viaplay.mp4
Determining the language of the subtitle.
INFO: Determining the language of the subtitle.
Language code: swe
INFO: Language code: swe
Muxing done, removing the old file.
INFO: Muxing done, removing the old file.

Perfect sync and with subtitles from viafree…..

C:\svtplay-dl-2>svtplay-dl.exe -o F:\svtplay-dl -S -M --remux -f https://www.tv4play.se/program/love-island-uk/3972191
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 63, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 56, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 157, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 152, in options_subs_dl
  File "c:\projects\svtplay-dl\lib\svtplay_dl\subtitle\__init__.py", line 58, in download
  File "c:\projects\svtplay-dl\lib\svtplay_dl\subtitle\__init__.py", line 277, in wrstsegment
IndexError: list index out of range

And this is what I get with with tv4play.se, HELP!

**Comment by JohnnyJorgensen** [comment]
It is discussed in thread #925 and #930. So far no solution in sight...
