### ISSUE TITLE
Issue:  --cmore-operatorlist doesn´t work (version svtplay-dl v2.0 windows)

### ISSUE THREAD

**Issue by myowncloudservice** [spaam/svtplay-dl#955]
Hi,

This command doesn´t work correctly in the latest version of svtplay-dl for windows (version 2.0)
`--cmore-operatorlist`

**Debug/Traceback:**
`svtplay-dl.exe --verbose --cmore-operatorlist https://www.cmore.se/serie/117457-maria-lang/sasong-1/episod-2/10001026-kung-liljekonvalje-av-dungen`
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 45, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py", line 27, in __init__
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py", line 29, in __init__
AttributeError: 'Namespace' object has no attribute 'get'

**Comment by spaam** [comment]
this is fixed in master. thanks for the bug report <3

**Comment by myowncloudservice** [comment]
Ok, thanks for a greate job with svtplay-dl @spaam
