### ISSUE TITLE
Key error: 'episodeTitle' - only on foreign movies  

### ISSUE THREAD

**Issue by jobal62** [spaam/svtplay-dl#958]
I tried to use svtplay-dl on a couple of movies but it just continue to crash. It works fine on national produced clips but not on movies:

DUMP:
svtplay-dl --verbose https://www.svtplay.se/video/18873434/the-queen

DEBUG [1535737222.09] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/video/18873434/the-queen'
DEBUG [1535737222.38] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.svt.se/videoplayer-api/video/1136932-001A'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 352, in main
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 177, in get_media
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 190, in get_one_media
  File "/usr/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 56, in get
  File "/usr/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 152, in outputfilename
KeyError: 'episodeTitle'

**Comment by jobal62** [comment]
I just downloaded it. svtplay-dl --version reports:
0.30.2016.02.08-debian1
Sopor, do you have anything to contribute with in this issue?

**Comment by jobal62** [comment]
Again, the movie "[En man som heter Ove](https://www.svtplay.se/video/16393154/en-man-som-heter-ove)" crashes, while "[Kulturmagasinet Sverige!](https://www.svtplay.se/video/19129951/sverige/sverige-sasong-21-avsnitt-2)" works just fine.
