### ISSUE TITLE
Can't download from svtplay.se

### ISSUE THREAD

**Issue by pulsatorius** [spaam/svtplay-dl#969]
$ svtplay-dl https://www.svtplay.se/video/19282459/the-split/the-split-sasong-1-avsnitt-2?start=auto
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==2.0+21.gfd0171d', 'svtplay-dl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+21.gfd0171d-py3.5.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+21.gfd0171d-py3.5.egg/svtplay_dl/__init__.py", line 63, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+21.gfd0171d-py3.5.egg/svtplay_dl/utils/getmedia.py", line 58, in get_media
    get_one_media(stream)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+21.gfd0171d-py3.5.egg/svtplay_dl/utils/getmedia.py", line 130, in get_one_media
    after_date = datetime.fromisoformat(stream.config.get("after_date"))
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
$ svtplay-dl --version
svtplay-dl 2.0+21.gfd0171d
$

**Comment by myowncloudservice** [comment]
Works fine for me!

I use svtplay-dl version 2.0 for Windows

I tried to download the link you have, and it works correctly for me!

`https://www.svtplay.se/video/19282459/the-split/the-split-sasong-1-avsnitt-2?start=auto`

**Comment by ml-1** [comment]
I get the same error with Python 3.5, fromisoformat seems to be added in 3.7.
Time to upgrade requirements?

**Comment by granbom** [comment]
I think it might be better to just do something like:
`after_date = datetime.strptime(stream.config.get("after_date"), "%Y-%m-%d")`
instead of the current
`after_date = datetime.fromisoformat(stream.config.get("after_date"))`

Demanding 3.7 just to parse a date from config once I feel will create more issues than benefits.
Default Ubuntu 18.04 using 3.6 for instance.

**Comment by spaam** [comment]
@granbom you are right. there is a https://pypi.org/project/backports-datetime-fromisoformat/ .. but it feels like its better to revert the fd0171d257 commit if i cant find a better way to do it.

**Comment by granbom** [comment]
@spaam change to `after_date = datetime.strptime(stream.config.get("after_date"), "%Y-%m-%d")` should work I think. Only line 130 in getmedia.py needs to be changed then as far as I can tell.
