### ISSUE TITLE
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#974]
I'm now running `svtplay-dl 2.0+21.gfd0171d` but this version will not download. It will only give my the same error message whatever i do:
`AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'`

```
$ svtplay-dl https://www.viafree.se/program/dokumentar/tv3-dokumentar/sasong-1/975365
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==2.0+21.gfd0171d', 'svtplay-dl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+21.gfd0171d-py3.5.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+21.gfd0171d-py3.5.egg/svtplay_dl/__init__.py", line 63, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+21.gfd0171d-py3.5.egg/svtplay_dl/utils/getmedia.py", line 58, in get_media
    get_one_media(stream)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+21.gfd0171d-py3.5.egg/svtplay_dl/utils/getmedia.py", line 130, in get_one_media
    after_date = datetime.fromisoformat(stream.config.get("after_date"))
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

**Comment by Sopor-** [comment]
If i go back to `svtplay-dl 2.0+12.g57e51c8` it is working as it should.

**Comment by granbom** [comment]
It's the line 130 in lib/svtplay-dl/utils/getmedia.py that should be changed to something like:
`after_date = datetime.strptime(stream.config.get("after_date"), "%Y-%m-%d")`
then it will not be dependent on "fromisoformat" that is a new function in python 3.7. Hence, 3.7 is required if that function is used.

**Comment by Sopor-** [comment]
@spaam will i be able to use latest master now after your latest commits?
