### ISSUE TITLE
tv4play - KeyError: 'playbackItem'

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#981]
It seems that Brottsjournalen crashed when trying to download a single episode. It seems to be broadcast LIVE in about 40 minutes, but it shouldn't crash.

```
$ svtplay-dl -S -P hls https://www.tv4play.se/program/brottsjournalen/11792034 --verbose
version: 2.0+12.g57e51c8
DEBUG [1538504103.0287256] /usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+12.g57e51c8-py3.5.egg/svtplay_dl/utils/getmedia.py/get_media: version: 2.0+12.g57e51c8
DEBUG [1538504103.0434177] /usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+12.g57e51c8-py3.5.egg/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1538504103.0439236] /usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+12.g57e51c8-py3.5.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/brottsjournalen/11792034'
DEBUG [1538504103.0538983] /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se
DEBUG [1538504103.1801424] /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/brottsjournalen/11792034 HTTP/1.1" 200 7504
DEBUG [1538504103.192944] /usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+12.g57e51c8-py3.5.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://playback-api.b17g.net/media/11792034?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'
DEBUG [1538504103.1988053] /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback-api.b17g.net
DEBUG [1538504103.9644454] /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/11792034?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 404 113
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==2.0+12.g57e51c8', 'svtplay-dl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+12.g57e51c8-py3.5.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+12.g57e51c8-py3.5.egg/svtplay_dl/__init__.py", line 63, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+12.g57e51c8-py3.5.egg/svtplay_dl/utils/getmedia.py", line 56, in get_media
    get_one_media(stream)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+12.g57e51c8-py3.5.egg/svtplay_dl/utils/getmedia.py", line 105, in get_one_media
    for i in streams:
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+12.g57e51c8-py3.5.egg/svtplay_dl/service/tv4play.py", line 76, in get
    if res.json()["playbackItem"]["type"] == "hls":
KeyError: 'playbackItem'
```

**Comment by alphaleonis** [comment]
I think this is because it wasn't available yet. I encountered the same problem, just assumed it was because there was no video actually present there yet. But I agree, it would be nice if it didn't crash.

**Comment by alphaleonis** [comment]
Of course now that it's running live I get: 
`requests.exceptions.InvalidSchema: No connection adapters were found for 'skd://fairplay-license.drm.technology/license/live'` :/
Perhaps it will work better when it is not live anymore.

**Comment by alphaleonis** [comment]
Now that it is not live anymore everything works as expected.

**Comment by Sopor-** [comment]
Yes, but `-A` doesn't seems to work as i have reported in #980
