### ISSUE TITLE
UR Play - Another subtitle problem

### ISSUE THREAD

**Issue by JohnnyJorgensen** [spaam/svtplay-dl#984]
Getting subtitle works fine on Språknyheterna, episode 1:
https://urplay.se/program/206988-spraknyheterna-sprakprat-med-anders-svensson-och-kallprat-med-niklas-kallner

But NOT on episode 2:
https://urplay.se/program/206989-spraknyheterna-niklas-stromstedt-the-rockin-pots-och-roboten-furhat

Error:
C:\Users\jojo\Downloads\SVTPlay-DL\_new - special ffmpeg>svtplay-dl -S --force-subtitle https://urplay.se/program/206989-spraknyheterna-niklas-stromstedt-the-rockin-pots-och-roboten-furhat
INFO: Outfile: spraknyheterna.niklas.stromstedt.the.rockin.pots.och.roboten.furhat-ur.play-urplay.srt
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 63, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 56, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 157, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 152, in options_subs_dl
  File "c:\projects\svtplay-dl\lib\svtplay_dl\subtitle\__init__.py", line 73, in download
  File "c:\projects\svtplay-dl\lib\svtplay_dl\subtitle\__init__.py", line 77, in save_file
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\output.py", line 183, in output
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\output.py", line 209, in findexpisode
TypeError: Can't convert 'NoneType' object to str implicitly

**Comment by jswetzen** [comment]
The same issue happens for this programme: https://urplay.se/program/209023

**Comment by bhwsandip** [comment]
I had the same issue. You just have to move the output files after you download them to another folder.  Then, you can start another download with subtitles.

**Comment by jswetzen** [comment]
Aha, tried again and what didn’t work was `--all-subtitles`. Just `-S` works.
