### ISSUE TITLE
viafree.se - ValueError: invalid literal for int() with base 10: '107a'

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#987]
I got this crash when downloading:
`$ svtplay-dl -A -S -P hls svtplay-dl -A https://www.viafree.se/program/reality/unga-mammor/sasong-4`

svtplay-dl 2.0+45.g7ac0b5f

```
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==2.0+45.g7ac0b5f', 'svtplay-dl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+45.g7ac0b5f-py3.5.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+45.g7ac0b5f-py3.5.egg/svtplay_dl/__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+45.g7ac0b5f-py3.5.egg/svtplay_dl/utils/getmedia.py", line 56, in get_media
    get_all_episodes(stream, url)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+45.g7ac0b5f-py3.5.egg/svtplay_dl/utils/getmedia.py", line 87, in get_all_episodes
    get_one_media(substream)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+45.g7ac0b5f-py3.5.egg/svtplay_dl/utils/getmedia.py", line 176, in get_one_media
    options_subs_dl(subfixes)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+45.g7ac0b5f-py3.5.egg/svtplay_dl/utils/getmedia.py", line 171, in options_subs_dl
    subs[0].download()
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+45.g7ac0b5f-py3.5.egg/svtplay_dl/subtitle/__init__.py", line 47, in download
    data = self.sami(subdata)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl-2.0+45.g7ac0b5f-py3.5.egg/svtplay_dl/subtitle/__init__.py", line 149, in sami
    if int(n) > 0 and i.text:
ValueError: invalid literal for int() with base 10: '107a'
```

**Comment by Sopor-** [comment]
It seems to be episode 19 that make it crash
`https://www.viafree.se/program/reality/unga-mammor/sasong-4/avsnitt-19`
