### ISSUE TITLE
Tv4play can't download with -S

### ISSUE THREAD

**Issue by KGBGit** [spaam/svtplay-dl#988]
Only one time svtplay-dl -S did work, all the other times this happens:
svtplay-dl -S https://www.tv4play.se/program/gr%C3%A5zon/3970497
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 63, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 56, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 157, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 152, in options_subs_dl
  File "/usr/local/bin/svtplay-dl/svtplay_dl/subtitle/__init__.py", line 58, in download
  File "/usr/local/bin/svtplay-dl/svtplay_dl/subtitle/__init__.py", line 277, in wrstsegment
IndexError: list index out of range

What is wrong?

**Comment by KGBGit** [comment]
---and the version:
svtplay-dl --version
svtplay-dl 2.0-1-g8297d66

**Comment by Sopor-** [comment]
If you use latest master it will work...

**Comment by KGBGit** [comment]
Latest master????

Mvh Ketil

**Comment by Sopor-** [comment]
Follow the instructions and you can download a newer svtplay-dl that probably work :)

**Comment by Sopor-** [comment]
@KGBGit you are still running the same version. Download [this](https://ci.appveyor.com/api/buildjobs/21uk7oispa0x6wx0/artifacts/svtplay-dl.zip) version and see if it works.

**Comment by KGBGit** [comment]
Hello,
I didn’t metion... that was a Win pgm, I have Mac os

Mvh Ketil

**Comment by Sopor-** [comment]
I have no idea how to compile svtplay-dl from source on a Mac. The only Mac i have is a MAC address :)

**Comment by KGBGit** [comment]
Thanks any way.
What version of svtplay-dl should I be using instead of 2.0??

Mvh Ketil

**Comment by Sopor-** [comment]
I'm running `svtplay-dl 2.0+51.g647d119` and if you don't want to wait for 2.1 you have to compile your own svtplay-dl. It can't be that hard? Maybe someone can guide you @KGBGit so you don't have to wait for a release?

**Comment by dentarg** [comment]
`svtplay-dl -S https://www.tv4play.se/program/gr%C3%A5zon/3970497` works for me on macOS 10.14 and svtplay-dl 2.1

**Comment by KGBGit** [comment]
The problem is that I don’t know how to get 2.1, I only have 2.0????

Mvh Ketil
