### ISSUE TITLE
Cant download from viafree

### ISSUE THREAD

**Issue by yabbah** [spaam/svtplay-dl#994]
Using v 2.1 on ubuntu 16.04.

I got this:
`root:/path/to/serie/Tjafs/$ svtplay-dl https://www.viafree.se/program/samhalle/tjafs/sasong-1/avsnitt-2
INFO: Starting new HTTPS connection (1): www.viafree.se
INFO: Starting new HTTP connection (1): playapi.mtgx.tv
INFO: Starting new HTTPS connection (1): mtgxse01-vh.akamaihd.net
INFO: Starting new HTTPS connection (1): mtgxse01-vh.akamaihd.net
INFO: Selected to download hls, bitrate: 2792
INFO: Starting new HTTPS connection (1): mtgxse01-vh.akamaihd.net
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3/dist-packages/svtplay_dl/__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 58, in get_media
    get_one_media(stream)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 201, in get_one_media
    fstream.download()
  File "/usr/lib/python3/dist-packages/svtplay_dl/fetcher/hls.py", line 121, in download
    self._download(self.url, file_name=(self.output, "ts"))
  File "/usr/lib/python3/dist-packages/svtplay_dl/fetcher/hls.py", line 130, in _download
    from Crypto.Cipher import AES
ImportError: No module named 'Crypto'`

Seems like there is a missing Crypto-module, and I have no idea how to fix it. Anyone?

**Comment by yabbah** [comment]
I have try on a clear VM with ubuntu 16.04 now, same issue. :/

**Comment by granbom** [comment]
Install the pycryptodome package with:
`pip3 install pycryptodome`

**Comment by yabbah** [comment]
> Install the pycryptodome package with:
> `pip3 install pycryptodome`

Thank you! :)
